- README.md
- build.xml
- circle.yml
- main/test/ca/uwaterloo/flix/TestAll.scala
This small PR adds support for continuous integration with circle ci.
The plan is to run travis ci and circle ci simultaneously to
(1) Help us uncover bugs in Flix, esp. related to testing. 
(2) Find out which one we prefer to use.
> Add support for CircleCI

- examples/analysis/SUopt.flix
- main/src/ca/uwaterloo/flix/api/WrappedModel.scala
- main/src/ca/uwaterloo/flix/language/ast/ExecutableAst.scala
- main/src/ca/uwaterloo/flix/language/phase/CreateExecutableAst.scala
- main/src/ca/uwaterloo/flix/runtime/Model.scala
- main/src/ca/uwaterloo/flix/runtime/Solver.scala
- main/src/ca/uwaterloo/flix/runtime/datastore/IndexedLattice.scala
- main/src/ca/uwaterloo/flix/runtime/debugger/RestServer.scala
- main/src/ca/uwaterloo/flix/util/PrettyPrint.scala
- main/test/ca/uwaterloo/flix/runtime/TestSolver.scala
In the previous versions of Flix, a predicate was of the form P(k1, ..., kn, l1, ..., ln) where k1...kn are keys and l1...ln are lattice elements. In current versions, we only allow P(k1, ..., kn, l). This PR implements that change for IndexedLattice. The benefit is slightly cleaner code, and fewer array allocations.
> Refactor IndexedLattice

- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/ca/uwaterloo/flix/runtime/TestBackend.scala
> Replace `in` operator by semicolon.

- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Unification.scala
Adds a text field to `Type.Var` to track the type parameter name assigned by the user.
> Add Textual Field to Type.Var

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/runtime/Value.scala
- main/src/tutorials/interpreter.flix
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
This PR adds syntactic sugar for `list/append`. Namely:
```
def f: List[Int] = 1 :: Nil @@ 1 :: 2 :: Nil
```
> Add syntax for list/append

- main/src/library/List.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestSet.flix
- Addressed https://github.com/flix/flix/issues/379
Note:  The addition of `reduce` functions to `Map` in another PR uses `List.reduceOpt` which has been renamed here.  So I will update this PR once the Map PR is merged.
> Name Fixes

- main/src/ca/uwaterloo/flix/language/phase/Codegen.scala
- main/test/ca/uwaterloo/flix/language/feature/FeatureSuite.scala
- main/test/ca/uwaterloo/flix/language/feature/TestNativeCall.flix
Apart from discussions in https://github.com/flix/flix/issues/410 there are couple of other issues:
1. I'm not quite sure why `def f: Bool = unsafe native field java.lang.Boolean.TRUE` fails at invoking in `Linker.scala`
2. Is there a way to call void functions like the following:
`def f: Bool =
let x = unsafe native new java.util.BitSet();
unsafe native method java.util.BitSet.set(x, 1);
true`
I also tried `let y = unsafe native method java.util.BitSet.set(x, 1);` but this tries to pop an object off the stack so this fails.
3. Every field with `_` in it fails at parsing stage
4. There is no way currently to fetch fields of an object. Looking at NativeField, no object is provided so only static field codes can be emitted.
> Adding Support for native calls in flix.

- main/src/ca/uwaterloo/flix/language/phase/Codegen.scala
- main/test/ca/uwaterloo/flix/language/feature/TestNativeCall.flix
If LHS of a comparison is a unit, this directly checks the equality to the second object based on the type of the second object instead of callibg `equals` method on LHS. 
This is for issue https://github.com/flix/flix/issues/427
> Unit Direct Comparison

- main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala
- main/src/library/List.flix
- main/src/library/Map.flix
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
- main/test/ca/uwaterloo/flix/language/phase/TestPatExhaustiveness.scala
- Made the check recursive on expressions (oops)
- Use Int instead of Integer
- Don't use getClass
- Reorder type constructor
- Added a few more tests for nested cases
> Minor cleanup of Pattern Match Exhaustiveness (Fixes #468)

- main/src/ca/uwaterloo/flix/language/phase/EnumGen.scala
In order to invoke an interface method, in addition to passing in `INVOKEINTERFACE` as an argument `true` has to be passed inside `visitMethodInsn` as the last argument.
> Fix the #458

- main/src/ca/uwaterloo/flix/language/phase/jvm/AsmOps.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenClosureClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenFunctionClasses.scala
Refactoring AsmOps + adding sanity check for closures.
@magnus-madsen: Can we add a flag so we can turn this sanity check off at times? I'm concerned about it's performance when we have a lot of closure calls (because it will do the sanity check each time a closure is called).
> Refactoring + Sanity check

- main/src/ca/uwaterloo/flix/runtime/interpreter/Channel.java
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.SelectChannel.flix
This bug occurs when a Select expression unsuccessfully attempts to read from a Channel after it was initially waiting. The lock will then be prematurely released, causing an error the next time the Select expression runs.
> Fixed a bug where a lock was released too early in a Select expression

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/tools/Packager.scala
- main/test/ca/uwaterloo/flix/tools/TestPackager.scala
This adds another command to the build system "check" which only type checks the program. Similar to the other build system commands, you simply run `flix check` to type check the program.
It's inspired by the "cargo check" command from the [cargo](https://doc.rust-lang.org/cargo/commands/cargo-check.html) (Rust) build system.
> Add check command to the build system

- build.xml
Adding this line allowed me to build with `ant build-all`, and failed without it. (tried with scala 2.12.8)
> Add reflection library to dependencies.

- main/src/flix/runtime/fixpoint/Solver.java
- main/src/flix/runtime/fixpoint/symbol/LatSym.java
- main/src/flix/runtime/fixpoint/symbol/RelSym.java
In the presence of first-class constraints where a predicate symbol may have multiple meanings it is unsound to do so.
> Remove Caching of Predicate Symbols

- main/src/flix/runtime/library/InterimReadShow.java
- main/src/library/BigInt.flix
- main/src/library/Float32.flix
- main/src/library/Float64.flix
- main/src/library/Int16.flix
- main/src/library/Int32.flix
- main/src/library/Int64.flix
- main/src/library/Int8.flix
- main/test/ca/uwaterloo/flix/library/TestBigInt.flix
- main/test/ca/uwaterloo/flix/library/TestFloat32.flix
- main/test/ca/uwaterloo/flix/library/TestFloat64.flix
- main/test/ca/uwaterloo/flix/library/TestInt16.flix
- main/test/ca/uwaterloo/flix/library/TestInt32.flix
- main/test/ca/uwaterloo/flix/library/TestInt64.flix
- main/test/ca/uwaterloo/flix/library/TestInt8.flix
Hi Magnus - here's a pull request for `toString` / `fromString` on the numeric types.
I've decided to follow an "allow leading or trailing whitespace" principle for the `fromString` functions. In Java the float and double "parse" functions allow leading and trailing whitespace but the integer parse functions don't. This inconsistency doesn't feel like the best choice. 
Choosing "allow leading or trailing whitespace" has meant I have to manually trim the input first for the integer parsers which makes them slower than they could be if you know their input doesn't have whitespace, but it seems a bit of a shame to make the float and double parses less flexible by testing if their input has whitespace and returning Err(_) if it does.
I'm certainly happy to change to "disallow all whitespace" …
> Interim toString / fromString for the numeric types

- main/src/library/Char.flix
- main/test/ca/uwaterloo/flix/library/LibrarySuite.scala
- main/test/ca/uwaterloo/flix/library/TestChar.flix
See issue #1036 - Missing tests for Char.flix and error in Char.isHexDigit 
This PR adds a test suite for Char.flix and changes Char.flix itself.
Changes to Char.flix
Added functions `isAsciiDigit` , `toInt32` and `fromInt32`.
Changed `isAscii` to be implemented in Flix - `isAscii` now tests if the character is in the range 0..127.
Changed `isDigit`, `isOctDigit` and `isHexDigit` to be implemented in fix. Theses test the character code is in the respective range or ranges.
> Add test suite for Char.flix and some changes to Char.flix including fix for isHexDigit

- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestMap.flix
- main/test/ca/uwaterloo/flix/library/TestSet.flix
Pull request for issue #1052 - Add `sortWith` to List / Add unfolds to List, Map and Set
Adds the following functions:
~~~
List.flix - sortWith
List.flix - unfold
List.flix - unfoldWithIter
Map.flix - unfold
Map.flix - unfoldWithIter
Set.flix - unfold
Set.flix - unfoldWithIter
~~~
The `sortWith` is a Flix implementation of `sortBy` from Haskell's Data.List - the Haskell code has been refined at least three times for performance.
> Add sortWith to List / Add unfolds to List, Map and Set

- .gitignore
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
The behaviour for the jar build target in gradle was not defined. This
has now been done so a jar can be build by running the gradle wrapper,
and giving jar as an argument (on linux "./gradlew jar"). This will
create build/lib/flix.jar.
This makes it possible to create a Flix jar with all neccesary dependencies, without using IntelliJ.
This will only work correctly after running gradle build. My understanding of gradle is not great enough to fix this.
> Fix gradle "jar" build target

- build.gradle
The way i tested for if the standard library was present in the last PR, turned out to be wrong. In this jar target, the Flix standard library is added as expected.
> Include flix std library in jar

- main/src/library/String.flix
- main/test/ca/uwaterloo/flix/library/TestString.flix
Hi Magnus - here are "in Flix" versions of `indent` and `stripIndent` so the String module can compile with Java 11.
> String indent "in Flix"

- main/src/ca/uwaterloo/flix/language/ast/Kind.scala
- main/src/ca/uwaterloo/flix/language/ast/Scheme.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala
- main/src/ca/uwaterloo/flix/language/debug/FormatType.scala
- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
- main/src/ca/uwaterloo/flix/language/phase/Finalize.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Synthesize.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
The first of several incremental changes to introduce well-kinded types.
`Type.Record` and `Type.Schema` are replaced by applications of new `TypeConstructor.Record` and `TypeConstructor.Schema`.
Unit tests pass and no to-dos remain. This should be fine to merge if approved.
> Well-Kinded Types Part I: Refactor record and schema kinds

- build.gradle
Fixing a deprecation warning that will become a hard error in Gradle 7.0. There's to my knowledge no functional difference born from the changes
> Fix gradle deprecation warning

- main/src/library/List.flix
This addresses issue #1119
java.lang.StackOverflowError in List.sortWith around 2^12 elements 
The helper functions have been changed to be in the continuation passing style, except `sortMergeAll` which was already tail recursive and didn't need a CPS transform.
I've run @esbenbjerre 's script with 4096000 (and adding console output of the numbers) and it has run to completion.
> Changed sortWith helper functions to be in continuation-passing style

- main/test/ca/uwaterloo/flix/library/TestFloat32.flix
- main/test/ca/uwaterloo/flix/library/TestFloat64.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestMap.flix
- main/test/ca/uwaterloo/flix/library/TestOption.flix
- main/test/ca/uwaterloo/flix/library/TestPrelude.flix
- main/test/ca/uwaterloo/flix/library/TestResult.flix
- main/test/ca/uwaterloo/flix/library/TestSet.flix
See issue...
Remove assert!, assertEq!, and assertNot! From Prelude #1136
This PR removes the assert functions from the standard library tests.
> Removed assert, assertEq and asssertNot from library tests.

- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
Related: #1198 
Unconditionally recursion is now only detected where the number of formal parameters in an application exactly equals the number of formal parameters in the def.
> simplify unconditional recursion check

- main/src/library/List.flix
- main/src/library/Option.flix
- main/src/library/Result.flix
- main/test/ca/uwaterloo/flix/library/TestResult.flix
Hi Magnus - here's the PR to fix `List.length` and add `Result.traverse` & `Result.sequence` .
Changes:
* List.length - made tail recursive with an accumulator
* List.repeat & List.range - re-implemented in continuation passing style
* Option.traverse & Option.sequence - re-implemented in continuation passing style
* Result.traverse & Result.sequence - new additions, implemented in CPS. Added tests to TestResult.
Adding `traverse` and `sequence` to Result matches Option.
Reimplementing the Option and List functions means they should work with long lists. `List.length` was noted as not being tail recursive in issue #1226. I also noticed `List.range` and `List.repeat` weren't tail recursive / in CPS when trying to use them to generate long lists for test cases.
> Add Result.traverse and Result.sequence plus List and Option tailrec / CPS changes

- main/src/library/List.flix
- main/src/library/Option.flix
- main/src/library/Result.flix
- main/src/library/Validation.flix
- main/test/ca/uwaterloo/flix/library/TestOption.flix
- main/test/ca/uwaterloo/flix/library/TestResult.flix
- main/test/ca/uwaterloo/flix/library/TestValidation.flix
Hi Magnus 
This adds `traverseX` to Option, Result and Validation.
It also changes `Validation.sequence` , `Validation.traverse` and `List.map` so they are in CPS / tail recursive and shouldn't burst the stack.
> Added traverseX to Option, Result and Validation. Plus tailrec / CPS changes 

- main/src/ca/uwaterloo/flix/language/ast/Kind.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/errors/NameError.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/debug/TestFormatType.scala
- main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala
This will assign the appropriate kinds to type parameters, allowing kind checking for the rest of the function.
Only currently operates on functions without explicit type parameters.
> Kind-check function signature

- main/src/library/List.flix
- main/src/library/Option.flix
- main/src/library/Result.flix
- main/test/ca/uwaterloo/flix/library/TestOption.flix
- main/test/ca/uwaterloo/flix/library/TestResult.flix
Hi Magnus - this PR adds "short-circuiting" list folds to Option and Result.
It also re-implements `List.foldRight` in CPS so it shouldn't blow the stack. 
See Issue #1263 - Names for short-circuiting Result and Option folds?
> Add short-circuiting list folds to Option and Result

- examples/polymorphic-record-extension-and-restriction.flix
- examples/the-ast-typing-problem-with-polymorphic-records.flix
- examples/type-safe-builders-with-ufcs-and-records.flix
- main/src/ca/uwaterloo/flix/language/ast/Kind.scala
- main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala
- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/UnificationError.scala
- main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala
- main/test/ca/uwaterloo/flix/language/phase/unification/TestUnification.scala
- main/test/flix/Test.Exp.Record.Polymorphism.flix
Adds kind checking to
* functions with explicit parameters
* enums
* type aliases
Turns out that kind vars are not needed (I think). I reverted to the "Unbound" kind.
Before pushing, I'd like to:
But the logic is all there, so this should be review-worthy.
> kind-check everywhere

- main/test/ca/uwaterloo/flix/TestUtils.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
Adds more tests relating to https://github.com/flix/flix/issues/808
However, I didn't cover all the cases:
`TypeError.NonSchemaType` and `TypeError.NonRecordType` overlap somewhat with the purpose of `TypeError.MismatchedKinds` and `TypeError.MismatchedTypes`, so some cases where I expected to get one, I got the other. (`project`, `fold`). I think part of this is `unifyTypes`'s dependency on parameter order. E.g.
```scala
val rec = Type.mkRecordExtend("a", Type.Str, Type.RecordEmpty)
val str = Type.Str
val res1 = Unification.unifyTypes(rec, str) // NonRecordType
val res2 = Unification.unifyTypes(str, rec) // MismatchedTypes
```
It would be nice to have a contract where `unifyTypes(a, b) ~== unifyTypes(b, a)`
And I would propose some principles on when a user could expect each error:
* …
> add mismatched kind tests

- main/src/ca/uwaterloo/flix/language/ast/Kind.scala
- main/src/ca/uwaterloo/flix/language/debug/FormatKind.scala
- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
Fixes #348 
Ensures that parameters of enum cases, existential and universal types, and functions all have proper types (`*` kind).
I didn't include relation parameters since it seemed that we ignore these anyway (?).
E.g. this program runs without error.
```
rel A(a: Int)
A("abc").
```
> Check param kinds

- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala
- main/src/ca/uwaterloo/flix/language/debug/FormatType.scala
- main/src/ca/uwaterloo/flix/language/debug/TypeDiff.scala
- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
- main/src/ca/uwaterloo/flix/language/phase/Finalize.scala
- main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala
- main/src/ca/uwaterloo/flix/language/phase/Synthesize.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/test/ca/uwaterloo/flix/language/debug/TestFormatType.scala
Fixes https://github.com/flix/flix/issues/1224
Note that I chose to put the effect as the first parameter to the type constructor. This allowed for a slightly easier head/tail split for separating the proper types from the effect.
> Refactor the Arrow Type Constructor to take an Effect (Bool) as its First Argument

- main/src/library/Console.flix
- main/src/library/String.flix
- main/test/ca/uwaterloo/flix/library/TestString.flix
Fixes #1174.
Switches the argument order of `String.contains` (formerly named `isInfixOf`) to ensure that the UFCS makes sense.
> Rename String prefix/suffix/infix functions

- main/src/library/List.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
This PR adds `distinct` and `distinctWith` to List which remove duplicates from the input list. 
`distinctWith` is the generalization with a user supplied equality test. `distinct` uses Flix's builtin in `(==)` via calling `memberOf`.
See issue #1293 Add nubBy (remove duplicates) to List
> Adding distinct and distinctWith to List.

- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/test/ca/uwaterloo/flix/language/feature/Test.Decl.Def.flix
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.Def.flix
Fixes https://github.com/flix/flix/issues/929
The parser greedily accepts `true`/`false`/`null` as an expression and doesn't know what to do when it turns out it wasn't a keyword after all.
I added a rule `keyword` to the parser, which ensures the keyword isn't just a prefix of a longer name. I only applied it to a couple places where I saw it was needed, but if we like this solution, it might save us some trouble in the future to use it for all keywords.
> fix keyword-prefixed name parsing

- main/src/ca/uwaterloo/flix/language/ast/Kind.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala
- main/src/ca/uwaterloo/flix/language/debug/FormatType.scala
- main/src/ca/uwaterloo/flix/language/phase/Finalize.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Synthesize.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/tools/BenchmarkCompiler.scala
- main/src/library/Choice.flix
- main/test/ca/uwaterloo/flix/TestExamples.scala
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/flix/Test.Exp.Choose.flix
- main/test/flix/Test.Exp.Null.Match.flix
- main/test/flix/Test.Typ.Gen.Bool.Null.flix
> Introduce Choice Data Type, Part III

- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/library/Choice.flix
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/ca/uwaterloo/flix/library/TestChoice.flix
- main/test/flix/Test.Def.Generalization.flix
- main/test/flix/Test.Exp.Choose.flix
> Introduce Choice Data Type, Part V

- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/tools/BenchmarkCompiler.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/flix/LangSuite.scala
- main/test/flix/Test.Exp.Choose.flix
> Introduce Choice Data Type, Part VI

- main/src/ca/uwaterloo/flix/api/lsp/Entity.scala
- main/src/ca/uwaterloo/flix/api/lsp/Index.scala
- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/LocationLink.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/FindReferencesProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/GotoProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala
- main/src/ca/uwaterloo/flix/language/debug/FormatSignature.scala
Goto:
Hover:
FindRefs:
Highlight:
Other:
> LSP: Add preliminary support for classes and instances

- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
Currently, because of the way we do keywords in the parser, we get error messages like: "`Expecting ' ', '\t', or keyword`".
This changes the error message to the more useful "`Expecting ' ', '\t', or def`".
> improve parsing error messages for keywords

- main/src/library/Array.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/MutList.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/src/library/Nel.flix
- main/src/library/Option.flix
- main/src/library/Result.flix
- main/src/library/Set.flix
- main/src/library/ToString.flix
- main/src/library/Validation.flix
- main/test/ca/uwaterloo/flix/library/LibrarySuite.scala
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestMap.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
- main/test/ca/uwaterloo/flix/library/TestMutMap.flix
- main/test/ca/uwaterloo/flix/library/TestMutSet.flix
- main/test/ca/uwaterloo/flix/library/TestSet.flix
- main/test/ca/uwaterloo/flix/library/TestString.flix
- main/test/ca/uwaterloo/flix/library/TestToString.flix
> Add ToString Instances

- main/test/ca/uwaterloo/flix/TestTutorials.scala
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/flix/LangSuite.scala
Reverts the additions of `Options.TestWithLibrary` made in #1589 and #1592.
> Remove std. library from tests

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Monoid.flix
- main/test/ca/uwaterloo/flix/library/LibrarySuite.scala
- main/test/ca/uwaterloo/flix/library/TestMonoid.flix
This PR adds a Monoid typeclass, see:
Add Monoid Type Class #1545
At them moment this class is quite simple - it just has `empty` and `combine`. It doesn't have a `mconcat`-like method that Haskell's Monoid has. Ideally we would be able to supply a default implementation for `mconcat` (or however it gets named). As I don't think we can do this yet I have left it out.
Also when Flix gets superclasses we should follow Haskell and move the `combine` method into a `Semigroup` class.
The instances implemented so far are essentially "uncontroversial" except Option. By uncontroversial I mean the type has a single sensible instance - e.g Strings are obviously `""` for `empty` and `+` (String.append) for `concat`. 
The Set instance uses `union` which seems the most obvious choice.
The Validation …
> Add Monoid typeclass and first set of instances to the standard library

- main/src/library/Bool.flix
- main/src/library/Char.flix
- main/src/library/Float32.flix
- main/src/library/Float64.flix
- main/src/library/Int16.flix
- main/src/library/Int32.flix
- main/src/library/Int64.flix
- main/src/library/Int8.flix
- main/src/library/LowerBound.flix
- main/src/library/UpperBound.flix
- main/test/ca/uwaterloo/flix/library/LibrarySuite.scala
- main/test/ca/uwaterloo/flix/library/TestLowerBound.flix
- main/test/ca/uwaterloo/flix/library/TestUpperBound.flix
Hi Magnus
I noticed the LowerBound and UpperBound classes only had Tuple instances so I've added instances for Unit, Bool, Char and the number types (except BigInt). 
I've also added tests.
Happy Christmas, please don't rush to review the changes.
> Added primitive instances and tests for LowerBound and UpperBound 

- main/src/library/List.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
See issue #1672
This PR makes `zip`, `zipWith` and `unzip` for List tail recursive by writing them in the continuation passing style. It also adds `zip3`, `zipWith3` and `unzip3` in CPS.
> List zip, zipWith and unzip made tail recursive. Added zip3, zipWith3 and unzip3.

- main/src/library/Order.flix
This enables and adds a neat syntax in the `compare` functions for tuples:
```
def compare(t1: (a1, a2, a3, a4), t2: (a1, a2, a3, a4)): Comparison =
use Order.>>-;
let (x1, x2, x3, x4) = t1;
let (y1, y2, y3, y4) = t2;
(x1 <=> y1) >>
lazy (x2 <=> y2) >>-
lazy (x3 <=> y3) >>-
lazy (x4 <=> y4)
```
Fixes #1638.
EDIT: We should discuss what the operator and/or keyword should be (I chosed `>>-` at random)
> Add lazy combine operator to Order

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/language/ast/Name.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Scheme.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/library/PartialOrder.flix
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/flix/Test.Dec.Class.flix
The plan is to split this up into multiple PRs:
1. Add laws to front-end. Laws can be added to classes and can be type-checked.
2. Refactor existing laws to use a signature `() -> Bool`, and move them into their respective classes.
3. Create dedicated AST structure for laws (instead of reusing `Def`)
4. Add and check `lawless`, `unlawful` modifiers.
> Add laws to classes, Part 1

- AUTHORS.md
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/test/flix/Test.Exp.Concurrency.Select.flix
This change reduces the size of generated code.
The use of the `TABLESWITCH` instruction also seems natural here. :slightly_smiling_face: 
It most likely doesn't improve performance.
I think the JIT optimiser can automatically transform the series of if-then-else constructs to a switch (you can manually investigate this, if you have the time :upside_down_face:).
Even if it cannot, any performance improvement will be overshadowed by the expensive locking operations involved in the select statement.
For further reduction of code size, you can hoist the `GETFIELD "element"` instruction out of each branch at the cost of a `SWAP`, such that
```
DUP
GETFIELD "branchNumber"
TABLESWITCH ...
case 0:
GETFIELD "element"
...
```
becomes
```
DUP
GETFIELD "element"
SWAP
GETFIELD "branchNumber" …
```
> Use TableSwitch when generating code for SelectChannel

- main/src/ca/uwaterloo/flix/runtime/interpreter/Channel.java
- main/src/ca/uwaterloo/flix/runtime/interpreter/ChannelIndexPair.java
- main/test/flix/Test.Exp.Concurrency.Select.flix
Fix #1718.
Note: my early attempts at implementing this fix caused `Test.Exp.Concurrency.Select.testSelectRandom10` and `Test.Exp.Concurrency.Select.testSelectRandom02` to sometimes deadlock. If these tests deadlock in the future, it may be because of a bug in my implementation.
> Add Random Probing to Select

- main/src/ca/uwaterloo/flix/language/errors/InstanceError.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
Fixes #1749 
* The error message should start with a message, e.g. "Mismatched signature bar declared in class foo" (with colors).
* It would be nice if the expected and actual types were aligned.
> improve MismatchedSignature error

- main/src/ca/uwaterloo/flix/language/errors/InstanceError.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
Fixes #1747 
* The error message should start with a message, e.g. "Missing implementation of X defined in class Y" (with proper colors)
* The error message should not report the entire instance as wrong (too much red). Better to just report "Foo" as the location.
> improve MissingImplementation error

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
#1781 was supposed to ensure singleton instances of RedBlackTree leafs and colors, but used namespace syntax to refer to a type. This fixes that.
> Fix singleton unit tags

- main/src/library/Map.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/src/library/RedBlackTree.flix
- main/src/library/Set.flix
The intended usecase is to rewrite MutSet.query followed by List.foreach into MutSet.queryWith. This is to avoid allocating a temporary buffer to store the query result.
For example:
````
let s = MutSet.empty();
MutSet.query(x -> ..., s) |>
List.foreach(...)
````
Can now be written as:
````
let s = MutSet.empty();
MutSet.queryWith(x -> ..., ...., s)
````
> Add MutSet.queryWith

- AUTHORS.md
- doc/PROJECTS.md
The fixpoint documentation has moved, so this updates a link to match.
> Update link to fixpoint documentation

- examples/domains/Belnap.flix
- examples/domains/Constant.flix
- examples/domains/ConstantParity.flix
- examples/domains/ConstantSign.flix
- examples/domains/Interval.flix
- examples/domains/IntervalAlt.flix
- examples/domains/IntervalInf.flix
- examples/domains/Mod3.flix
- examples/domains/Parity.flix
- examples/domains/PrefixSuffix.flix
- examples/domains/Sign.flix
- examples/domains/StrictSign.flix
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/library/Bounded.flix
- main/src/library/JoinLattice.flix
- main/src/library/MeetLattice.flix
- main/src/library/PartialOrder.flix
- main/src/library/Prelude.flix
- main/src/library/TotalOrder.flix
- main/test/ca/uwaterloo/flix/TestExamples.scala
- main/test/ca/uwaterloo/flix/language/phase/TestInstances.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/flix/Test.Dec.Class.flix
Fixes https://github.com/flix/flix/issues/1759
```flix
law myLaw: forall (_x: a) . true
law myLaw2: forall[b](_x: b) . true
```
is equivalent to
```flix
def myLaw(_x: a): Bool = true
def myLaw2[b](_x: b) = true
```
A lot ended up getting commented out, since there's some not-easily-automated refactoring to be done around existing laws.
* Update law syntax
> update law syntax

- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/test/flix/Test.Dec.Class.flix
Fixes https://github.com/flix/flix/issues/1670
And maybe related to https://github.com/flix/flix/issues/1765 ?
If there were no instances of a class, we didn't add it to the class environment, so we couldn't come to any conclusions about superclasses, etc.
This change builds the ClassEnv from the map of classes rather than map of instances, so we're no longer missing anything if there are no instances.
> Build ClassEnv from classes rather than instances

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
Fixes https://github.com/flix/flix/issues/1750
Also separates type parameters from type constraints.
* Disallow type constraints on class tparams
* Disallow type constraints on enum tparams
* Disallow type constraints on lattice tparams
* Disallow type constraints on relation tparams
* Disallow type constraints on opaque type tparams
* Disallow type constraints on type alias tparams
> Tighten restrictions on class tparams

- main/src/library/ToString.flix
When printing an empty array, there is an access to index 0 in ToStringOps.arrayToStringHelper.
> Fix index out of bounds in ToStringOps.arrayToStringHelper

- main/src/library/MutMap.flix
It doesn't make sense and none of the functions it calls requires it.
> Remove Eq from MutMap.isEmpty

- main/src/library/Array.flix
c.f Datalog: Optimize Array.filter #1897
`Array.filter` has been re-implemented to use an interim array rather than an interim list. Because we don't know ahead of time the length of the output array, it is initialized to the same size as the input array; at the end of filtering the input array the output array is truncated to contain just the positives.
@magnus-madsen I've committed the version that calls Array.length on the input array within the helper. Results were a bit mixed on my PC - maybe some background task was running. Both versions with an interim array look faster. The odd and even tests are essentially the same so the results should be just about the same in a run - the version using Array.length in the helper had a very fast run for odd array size 1048576 and the code is a …
> A faster version of Array.filter

- main/src/library/Benchmark/Bench.Fixpoint.flix
- main/src/library/Fixpoint/Ast/Datalog.flix
- main/src/library/Fixpoint/Ast/PrecedenceGraph.flix
- main/src/library/Fixpoint/Compiler.flix
- main/src/library/Fixpoint/IndexSelection.flix
- main/src/library/Fixpoint/Interpreter.flix
- main/src/library/Fixpoint/Ram/RamStmt.flix
- main/src/library/Fixpoint/Simplifier.flix
- main/src/library/Fixpoint/Solver.flix
- main/src/library/Fixpoint/Stratifier.flix
- main/src/library/Fixpoint/VarsToIndices.flix
Introduce a new Datalog constructor `Model`. The idea is to represent facts as a minimal model to avoid frequent marshalling between models computed by the solver and arrays consumed by Flix.
Models are immutable.
> Refactor Datalog representation

- main/src/library/Float32.flix
- main/src/library/Float64.flix
- main/test/ca/uwaterloo/flix/library/TestFloat32.flix
- main/test/ca/uwaterloo/flix/library/TestFloat64.flix
Currently Float32 and Float64 are missing explicit rounding functions. The conversion functions like `tryToInt32` obviously perform rounding but the round is always equivalent to `floor` because it uses Java's `Double.longValue`.
This PR adds the rounding functions `ceil`, `floor` and `round`. It also add `abs` which was present for Int32 etc. but missing for Float32 and Float64. 
`ceil`, `floor` and `round` are `Float64 -> Float64`. `round` in Java is actually `double -> long` (ceil and floor are `double -> double`). As we already have quite a number of conversions functions in the Float32 and Float64 modules, I think it makes sense to have `round` behave like `ceil` and `floor` - a user can then choose an appropriate conversion function after rounding. In the .net world `round` is also …
> Add abs, ceil, floor and round to Float32 and Float64

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompleteProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/debug/FormatSignature.scala
- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
Fixes https://github.com/flix/flix/issues/2065
Also fixes a bug where LSP showed the whole function type in the place of the return type.
> Show purity for pure functions and expressions in LSP

- .gitignore
- AUTHORS.md
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
- main/src/flix/test/TestClass.java
- main/test/flix/LangSuite.scala
- main/test/flix/Test.Exp.Jvm.GetFieldDoubleNestedClass.flix
- main/test/flix/Test.Exp.Jvm.GetFieldStaticInnerClass.flix
- main/test/flix/Test.Exp.Jvm.GetStaticFieldStaticInnerClass.flix
This is a proposal for handling native static inner classes.
It would allow importing for example the `Map.Entry` class, this way:
```
import java.util.Map$Entry.getKey();
```
> Import native static inner classes

- main/src/library/List.flix
This PR changes various List functions to be in CPS so they don't burst the stack. It also changes `toString` and `formatWith` to use a StringBuilder as an imperative accumulator so they are stack safe too (the functions are pure as the use of StringBuilder is entirely encapsulated).
I have just covered functions with either a single definition or a top-line `pub def` and one helper function. I haven't looked at the most complicated functions like `groupBy' which have various helpers (they can be tackled in another PR).
> Make List.filterMap, List.toString and other functions stack overflow safe

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/LazyList.flix
- main/test/ca/uwaterloo/flix/library/LibrarySuite.scala
- main/test/ca/uwaterloo/flix/library/TestLazyList.flix
`LazyList.empty`, `LazyList.isEmpty`, `LazyList.range`, `LazyList.head`, `LazyList.take`, `LazyList.length`, `LazyList.toList` (and `LazyList.toLazy` from `List` type)
> Add Basic LazyList Functions

- main/src/library/LazyList.flix
- main/test/ca/uwaterloo/flix/library/TestLazyList.flix
Note that `foldLeft` and `Eq` have been implemented here, but are also implemented in #2141 and #2109 respectively.
> Add `LazyList.{append, count, drop, flatten}`

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
- main/test/flix/LangSuite.scala
- main/test/flix/Test.Derivation.flix
Fixes https://github.com/flix/flix/issues/2155
* Can add `with ...` to enums.
* A type class name is never repeated.
* Every type class name is one of `Eq`, `Order`, and `ToString`.
> Add `with` syntax to enum declarations

- examples/datalog/delivery-date.flix
- main/src/library/JoinLattice.flix
Fixes #2148
> 
> * [X]  Add instance for `Int8`.
> * [X]  Add instance for `Int16`.
> * [X]  Add instance for `Int32`.
> * [X]  Add instance for `Int64`.
> * [X]  Add instance for `BigInt`.
> 
> The integer instances should simply delegate to `Order.max`.
> 
> * [X]  Add instances for tuple (N = 2 to N = 10).
> 
> There is already an example for N = 2.
> 
> No test cases are required. Just be careful :)
>
> Add JoinLattice Instances (Fixes #2148)

- examples/datalog/delivery-date.flix
- main/src/library/MeetLattice.flix
Fixes #2149
###(Edited task list from the issue):
> * [X]  Add instance for `Int8`.
> * [X]  Add instance for `Int16`.
> * [X]  Add instance for `Int32`.
> * [X]  Add instance for `Int64`.
> * [X]  Add instance for `BigInt`.
> 
> The integer instances should simply delegate to `Order.min`.
> 
> * [X]  Add instances for tuple (N = 2 to N = 10).
> 
> There is already an example for N = 2.
> 
> No test cases are required. Just be careful :)
> Add MeetLattice Instances (Fixes #2149)

- examples/datalog/delivery-date.flix
- main/src/library/PartialOrder.flix
Fixed: #2150
> * [X]  Add instance for `Int8`.
> * [X]  Add instance for `Int16`.
> * [X]  Add instance for `Int32`.
> * [X]  Add instance for `Int64`.
> * [X]  Add instance for `BigInt`.
> 
> The integer instances should directly use `$INT8_LE$(x, y)` and so forth. See `Order.flix` for examples.
> 
> * [X]  Add instances for tuple (N = 2 to N = 10).
> 
> There is already an example for N = 2.
> 
> No test cases are required. Just be careful :)
> Add PartialOrder Instances (Fixes #2150)

- main/src/library/LazyList.flix
`LazyList.take` could be lazier than it currently is. This minor change brings it more in line with the idea for LazyList.
> Refactor `LazyList.take`

- AUTHORS.md
- main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala
- main/src/ca/uwaterloo/flix/language/debug/FormatSignature.scala
This is an attempt to address #2210. The attached image shows what it looks like in VS Code.
> Use Markdown for LSP hover

- AUTHORS.md
- main/src/ca/uwaterloo/flix/api/lsp/DocumentSymbol.scala
- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
- main/src/ca/uwaterloo/flix/api/lsp/Request.scala
- main/src/ca/uwaterloo/flix/api/lsp/SymbolTag.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SymbolProvider.scala
Partially fixies: #2051
* Add Data structures for `DocumentSymbol` and `lsp/symbols` request.
* Add dummy implementation of `SymbolProvider` which returns always an hardcoded list, in a second PR (or adding a commit to this one) I will also add the logic to gather the information from the AST.
> Bootstrap DocumentSymbol support in LSP (#2051)

- docs/BUILD.md
The situation just occurred with 2601c1926daef4d1d74c3be975e51b51df0f904b.
> Addition to troubleshooting in build documentation

- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
- main/src/library/LazyList.flix
@magnus-madsen The "|>| string in names currently mangles to $bor$gt and is used in the names of some def classes
> mangle handling of pipe string

- main/src/ca/uwaterloo/flix/api/lsp/Index.scala
- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
- main/src/ca/uwaterloo/flix/api/lsp/Request.scala
- main/src/ca/uwaterloo/flix/api/lsp/SemanticToken.scala
- main/src/ca/uwaterloo/flix/api/lsp/SemanticTokenModifier.scala
- main/src/ca/uwaterloo/flix/api/lsp/SemanticTokenType.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
This is a first step towards making the language server capable of providing useful semantic tokens.
There is probably room for improvement in the code as I'm not very familiar with Scala nor with the Flix compiler API.
The image below shows that the code is able to provide semantic tokens to the VS Code extension (once it has been extended as described [here](https://github.com/flix/vscode-flix/issues/122)).
> LSP: Add skeleton support for Semantic Tokens

- main/src/library/LazyList.flix
- main/test/ca/uwaterloo/flix/library/TestLazyList.flix
The tests `dropWhileDropWhileFusion0X` produce the same pattern of letters when evaluated eagerly and lazily. Is there something we can do about that to observe the effects of being evaluated eagerly and lazily?
> Add `LazyList.dropWhile`

- main/src/ca/uwaterloo/flix/language/phase/jvm/AsmOps.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenLazyClasses.scala
Fixes #2328
Current benchmark:
```flix
use Benchmark.Benchmark;
use Benchmark.defBenchmark;
pub def bench1(): Benchmark = 
defBenchmark("List", () -> { 
List.range(1, 10_000) |>
List.map(x -> x + 1) |>
List.map(x -> x + 1) |>
List.map(x -> x + 1)
})
pub def bench2(): Benchmark = 
defBenchmark("LazyList", () -> { 
LazyList.range(1, 10_000) |>
mapE(x -> x + 1) |>
mapE(x -> x + 1) |>
mapE(x -> x + 1 as & Impure)
} as & Pure)
pub def mapE(f: a -> b & ef, l: LazyList[a]): LazyList[b] & Impure =
let r = MutList.new();
mapERec(f, l, r);
MutList.foldRight((x, xs) -> ECons(x, xs), ENil, r)
def mapERec(f: a -> b & ef, l: LazyList[a], r: MutList[b]): Unit & Impure =
match l {
case ENil         => ()
case ECons(x, xs) => 
MutList.push!(f(x), r);
mapERec(f, xs, r)
case LCons(x, xs) => …
```
> Improved CodeGen for `Lazy`

- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SymbolProvider.scala
Partially fix: https://github.com/flix/flix/issues/2290
Trying to add `Enum` and `EnumCase` SymbolKind Provider. I have tested the changes and the outline and breadcumbs in vscode are looking fine.
I have still some doubts about the documentation, I don't know when the docs is included in the AST and how to use it to return the correct `range` field of `DocumentSymbol`. I also noticed that `EnumCase` doesn't have any documentation attached, is it true?
> Add Enum and EnumCase DocumentSymbolProvider (#2290)

- main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala
Fixes #1973
The program
```
def main(_args: Array[String]) : Int32 & Impure =
let p = #{ A(1, 2). B(1) :- not A(1, _). };
query p select x from B(x) |> println;
0
```
results in this error:
```
-- Safety Error -------------------------------------------------- examples\misc\test.flix
>> Illegal negatively bound wildcard '_'.
2 |     let p = #{ A(1, 2). B(1) :- not A(1, _). };
^^^^^^^^^^^
the wildcard occurs in this negated atom.
Compilation failed with 1 error(s).
```
When `_` is changed to `_x` the error is:
```
-- Safety Error -------------------------------------------------- examples\misc\test.flix
>> Illegal negatively bound variable '_x'.
2 |     let p = #{ A(1, 2). B(1) :- not A(1, _x). };
^^^^^^^^^^^^
the variable occurs in this negated atom.
Compilation failed with 1 error(s). …
```
> Check Negatively Bound Wildcards

- main/src/library/LazyList.flix
- main/test/ca/uwaterloo/flix/library/TestLazyList2.flix
Related to #2307 
Should the `compare` function be defined within the `LazyList` namespace?
> Add `{Functor, Order}` instances to `LazyList`

- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
- main/src/ca/uwaterloo/flix/api/lsp/LocationLink.scala
- main/src/ca/uwaterloo/flix/api/lsp/Request.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/ImplementationProvider.scala
Add [ImplementationProvider](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_implementation) to LSP. This will allow to have go to implementation capabilities
.
> LSP: Add ImplementationProvider capability and lsp/implementation request

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala
- main/src/ca/uwaterloo/flix/language/debug/FormatExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Linter.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Statistics.scala
- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Terminator.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
- main/src/library/LazyList.flix
This PR reintroduces `reifyEff`. The long-term goal is to replace `reifyEff` by a more general `reify` construct. In meanwhile, the `reifyEff` construct is sound whereas soundness for the other reify constructs (w.r.t. Booleans) is still an open question.
> Reintroduce `reifyEff`

- main/src/library/LazyList.flix
- main/test/ca/uwaterloo/flix/library/TestLazyList.flix
Closes #2618 
Also uncommented `LazyList.toIterator` and associated tests. Renamed `LazyList.toIter` to `LazyList.toIterator`.
> Update LazyList `reify` to `reifyEff`

- main/src/ca/uwaterloo/flix/language/phase/jvm/BytecodeInstructions.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/ClassMaker.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenGlobalCounterClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenMatchErrorClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenUnitClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmName.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmType.scala
Part of #2591 
* Array types are missing but I am not sure that can be done incrementally. 
* method string are literals. I am not sure where to store them. I think it could be nice to store them on their JvmName class but this is also a bit weird because of subtyping (youd have to use `JvmName.Object.toStringMethod`)
* The generated class is changed a little bit (a few extra unreachable goto).
Generated class on this PR:
```
package dev.flix.runtime;
public final class MatchError extends FlixError {
public final ReifiedSourceLocation location;
public MatchError(ReifiedSourceLocation var1) {
super("Non-exhaustive match at " + var1.toString());
this.location = var1;
}
public boolean equals(Object var1) {
if (this == var1) {
return true;
} else if (var1 != null) {
if (this.getClass() == …
```
> Rewrite GenMatchErrorClass to use bytecode DSL

- docs/STYLE.md
- main/src/ca/uwaterloo/flix/language/phase/jvm/AsmOps.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BytecodeInstructions.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/ClassMaker.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenGlobalCounterClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenHoleErrorClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenMatchErrorClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordExtend.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRefClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenReifiedSourceLocationClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenTagClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenUnitClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmName.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmType.scala
part of #2591 
This PR:
```
public final class Ref$Char {
public char value;
public Ref$Char(char var1) {
this.value = var1;
}
}
```
```
public final class Ref$Obj {
public Object value;
public Ref$Obj(Object var1) {
this.value = var1;
}
}
```
Master:
```
public final class Ref$Char {
private char value;
public Ref$Char(char var1) {
this.value = var1;
}
public char getValue() {
return this.value;
}
public void setValue(char var1) {
this.value = var1;
}
public final String toString() {
throw new UnsupportedOperationException("toString method shouldn't be called");
}
public final int hashCode() {
throw new UnsupportedOperationException("hashCode method shouldn't be called");
}
public final boolean equals(Object var1) {
throw new UnsupportedOperationException("equals method shouldn't be …
```
> Rewrite GenRefClasses to use bytecode DSL

- main/src/ca/uwaterloo/flix/language/phase/jvm/BytecodeInstructions.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordEmpty.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordEmptyClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordInterfaces.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
Part of #2591 
* ~~Is there any reason this is not a singleton pattern?~~ No, I've changed it
* ~~This should be called GenRecordEmptyClass according to the other files~~ Changed it
Genrated class
```
public final class RecordEmpty implements  {
public static final RecordEmpty INSTANCE = new RecordEmpty();
private RecordEmpty() {
}
public final  lookupField(String var1) {
throw new UnsupportedOperationException("lookupField method shouldn't be called");
}
public final  restrictField(String var1) {
throw new UnsupportedOperationException("restrictField method shouldn't be called");
}
}
```
> Rewrite GenRecordEmpty to use bytecode DSL

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
- main/src/ca/uwaterloo/flix/language/phase/Reader.scala
- main/src/ca/uwaterloo/flix/tools/Packager.scala
Closes #2680
I'm not sure the LSP Flix instance should configure a Formatter. It's guarded by an if-check but it should probably still not be there.
> Configure Flix instance with `AnsiTerminalFormatter`

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BytecodeInstructions.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/ClassMaker.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenMatchErrorClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordExtend.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordExtendClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRefClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
Part of #2591
```
public final class RecordExtend$Int32 implements IRecord$ {
public String label;
public int value;
public IRecord$ rest;
public RecordExtend$Int32() {
}
public final IRecord$ lookupField(String var1) {
return (IRecord$)(!this.label.equals(var1) ? this.rest.lookupField(var1) : this);
}
public final IRecord$ restrictField(String var1) {
if (!this.label.equals(var1)) {
this.rest = this.rest.restrictField(var1);
return this;
} else {
return this.rest;
}
}
}
```
> Rewrite GenRecordExtendClasses to use bytecode DSL

- main/src/ca/uwaterloo/flix/api/lsp/Diagnostic.scala
- main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
Fixes errors messages containing a `Some(...)` or `None` at the end of an error message.
Tested as a freshly built jar in a small flix project.
> Fix printing `explain` message as `Optional`

- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
> refactor: use `Symbol.freshDefnSym` inside `LambdaLift.scala`

- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
- main/src/ca/uwaterloo/flix/language/errors/CodeHint.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
> feat: add `CodeHint.UnsafePurityCast` and `CodeHint.Deprecated`.

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenClosureAbstractClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenClosureClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
every closure call invokes `getUniqueThreadClosure` and operates on that. An abstract class between specific closure classes and the abstract function class is added that declares this method abstractly (fixes #2741).
> fix: copy closure objects before invocation

- main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala
Note line 488(old) is changed, seemed like a typo, cannot see any reason it should be exp when e was written.
There was a suspicious amount of unused code line 112(old)
> refactor: cleanup `ClosureConv`

- docs/PULLREQUEST.md
> docs: no tense requirement for PR titles

- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
- main/test/ca/uwaterloo/flix/library/TestString.flix
Causes any string containing `${` to be considered an interpolation (which means that it doesn't fall back to reading it as a string). You can avoid this with `\${` (`\$` is an illegal escape) (fixes #2798).
Examples:
code | behaviour 
--- | ---
`"\$"` | illegal escape sequence
`"${"` | parsing error: expected <expression things> not "
`"$"` | just the string `$`
`"${f(Map#{}}"` | parsing error: did not expect `}`
`"\${"` | the string `${`
> fix: make interpolation parsing strict

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/flix/Test.Exp.Jvm.GetField.flix
- main/test/flix/Test.Exp.Jvm.GetFieldDoubleNestedClass.flix
- main/test/flix/Test.Exp.Jvm.GetFieldStaticInnerClass.flix
- main/test/flix/Test.Exp.Jvm.GetStaticField.flix
- main/test/flix/Test.Exp.Jvm.GetStaticFieldStaticInnerClass.flix
- main/test/flix/Test.Exp.Jvm.InvokeConstructor.flix
- main/test/flix/Test.Exp.Jvm.InvokeMethod.flix
- main/test/flix/Test.Exp.Jvm.InvokeStaticMethod.flix
- main/test/flix/Test.Exp.Jvm.PutField.flix
- main/test/flix/Test.Exp.Jvm.PutStaticField.flix
In this draft, the ascriptions are desugared to casts. In the future I'd like to explore more strict options, such as requiring the type ascriptions to be valid subtyping-wise.
> feat: allow type/eff casts/ascriptions on imports

- main/src/library/List.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
Add implementation of foldRightL to List namespace together with the testcases. This first PR is used to check if the style and content is ok then I will implement the method in all the namespaces requested in the issue with another PR.
As discussed in #2877 I removed the polymorphic effect.
> feat: add `foldRightL` to List

- main/src/ca/uwaterloo/flix/language/errors/CodeHint.scala
- main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
Adds the effect to the summary of `CodeHint.NonTrivialEffect` as seen in the image below.
> feat: add effect to `CodeHint.NonTrivialEffect` summary

- main/src/library/Applicative.flix
- main/src/library/Functor.flix
- main/src/library/Monad.flix
- main/test/ca/uwaterloo/flix/library/LibrarySuite.scala
- main/test/ca/uwaterloo/flix/library/TestApplicative.flix
- main/test/ca/uwaterloo/flix/library/TestFunctor.flix
- main/test/ca/uwaterloo/flix/library/TestMonad.flix
This PR adds a small set of combinators to Functor, Applicative and Monad and adds test suites for those modules.
I've limited the combintors in this PR to named ones (no operators) and avoided traversals (examples would be `mapM` etc). I'd like Flix to have operators and effectful traversals soon, but there is probably more bikeshedding about naming and typing for these functions so I've left them out.
The PR adds:
`ignore` to Functor - this is called `void` in Haskell but I wanted to avoid the name.
`seqLeft` to Applicative - this is `(<*)` in Haskell 
`seqRight` to Applicative - this is `(*>)` in Haskell 
`whenTrue` to Applicative - this is `when` in Haskell / PureScript
`whenFalse` to Applicative - this is `unless` in Haskell / PureScript
`join` to Monad
`bind` to Monad - this is …
> feat: add functor-applicative-monad combinators and test suites

- main/src/library/Iterator.flix
- main/test/ca/uwaterloo/flix/library/TestIterator.flix
Closes #2892
The goal is to have tests for every function that modifies or creates the `done` function.
> feat: add `Iterator.isEmpty`

- main/test/ca/uwaterloo/flix/library/TestIterator.flix
Move `isEmpty` for `unfoldWithOk` to `isEmpty` section. Mentioned in #2907
> refactor: test for `Iterator.unfoldWithOk`

- main/src/library/Applicative.flix
- main/test/ca/uwaterloo/flix/library/TestApplicative.flix
This PR adds `product3`, `product4` and `product5` to `Applicative` - these are a family of functions like `liftN` but they produce tuples rather than take a "consolidation function".
Naming follows `liftA`.
See issue  #2935 "Applicative - product3, product4 and product5 ?"
> feat: add product3, product4 and product5 to Applicative #2935

- main/src/library/Foldable.flix
- main/test/ca/uwaterloo/flix/library/LibrarySuite.scala
- main/test/ca/uwaterloo/flix/library/TestFoldable.flix
This PR adds `foldLeftM`, `foldRightM` and `foreachM` to `Foldable` as functions in the namespace plus a test suite.
Discussion points: 
I added `foldLeftM` etc. as functions rather than class methods because the implementations are a bit "tricky" - `foldLeftM` and `foldRightM` are ported from Haskell's stdlib, they build functions that are applied to the state.
`foreachM` could have been called `mapX` following a naming convention we've used a bit with "X" meaning _forgetful_. I'm now not so happy with this convention (even though I think I introduced it) so I have avoided it.
> feat: add monadic folds to Foldable

- main/src/ca/uwaterloo/flix/runtime/shell/Command.scala
- main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
> refactor: remove `:browse`, `:benchmark`, `:doc`, `:hole`, and `:search`

- main/src/library/Result.flix
> refactor: rename `xs` to `l` in `Result.{foldLeftM, foldRightM}`

- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
- main/test/flix/Test.Dec.Enum.flix
~This implementation allows the `()` and parses as if it were not there. The other option is to disallow it.~
This implementation disallows `()` at the end of an enum case. (E.g. `case C()`)
fixes https://github.com/flix/flix/issues/3002
> feat: disallow `()` after enum case

- main/src/library/Fixpoint/Ast/VarSym.flix
- main/src/library/Fixpoint/Ram/RamSym.flix
> refactor: inline `Eq` and `Order` instances for `{VarSym, RamSym}`

- main/src/library/MutMap.flix
Closes #2981
This PR adds
- `MutMap.minimumKey`
- `MutMap.minimumKeyBy`
- `MutMap.minimumValue`
- `MutMap.minimumValueBy`
- `MutMap.maximumKey`
- `MutMap.maximumKeyBy`
- `MutMap.maximumValue`
- `MutMap.maximumValueBy`
> feat: add `MutMap.{min/max key/value}`

- .github/workflows/community-build.yaml
A basic initial version. Takes a list of projects and installs and builds each individually.
Future work includes:
* actually adding projects to the list
* collecting a list of failures instead of failing fast
* dependency management
Depends on https://github.com/flix/flix/pull/3044
Related to #2943
> ci: add community build script

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- main/src/ca/uwaterloo/flix/tools/BenchmarkCompiler.scala
- main/src/ca/uwaterloo/flix/tools/Packager.scala
- main/src/ca/uwaterloo/flix/tools/SocketServer.scala
- main/src/ca/uwaterloo/flix/util/Options.scala
- main/test/ca/uwaterloo/flix/TestMain.scala
> feat: do not emit JVM bytecode unless `--output` is specified

- main/src/library/List.flix
- main/src/library/Nel.flix
- main/src/library/Option.flix
- main/src/library/Result.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestNel.flix
- main/test/ca/uwaterloo/flix/library/TestOption.flix
- main/test/ca/uwaterloo/flix/library/TestResult.flix
Rename `foldRightL` to `foldRightLazy` for List, Nel, Result, Option
#2977
> Rename foldRightL to foldRightLazy

- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
Introduce an error for reserved type name clashes.
First milestone of: #1965
> Add WeederError.ReservedTypeName

- examples/analysis/IFDS.flix
- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Identity.flix
- main/test/ca/uwaterloo/flix/library/LibrarySuite.scala
- main/test/ca/uwaterloo/flix/library/TestIdentity.flix
This PR adds the Identity type and instances - see issue Add Identity type and instances #3092
The PR adds the derivable instances and:
SemiGroup
Monoid
Functor
Applicative
Monad
Foladble
Traversable
It also adds the "number" instances: 
Add
Sub
Mul
Div
Neg
Haskell's Identity functor has the equivalent number instances so I have added them too.
The test suite is very simple as there isn't really anything "mechanical" about the Identity functor - if one test works for a class method any other should work.
> feat: Add the Identity Functor/Monad - #3092

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/CommutativeSemiGroup.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/Option.flix
- main/src/library/SemiGroup.flix
- main/src/library/Set.flix
- main/src/library/Validation.flix
- main/test/ca/uwaterloo/flix/library/TestSemiGroup.flix
Closes #1922
I'm not sure how to enforce the commutative law when extending `SemiGroup` which has instances of combine defined for `String` as concatenation which is clearly not commutative. Does the compiler enforce the laws yet? Any ideas? I'll take a look at typelevel / cats meanwhile.
> feat: add `CommutativeSemiGroup`

- main/src/library/Boxable.flix
- main/src/library/Functor.flix
> fix: mark `{Functor, Boxable}` as pub

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/CommutativeMonoid.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/Monoid.flix
- main/src/library/Option.flix
- main/src/library/Set.flix
- main/src/library/Validation.flix
- main/test/ca/uwaterloo/flix/library/TestMonoid.flix
Closes #1681
I've added the `identity` law to the `Monoid` TC as that is a requirement for the algebraic structure. Should it perhaps be phrased differently like
```flix
law identity: forall(x: a) with Eq[a] . Monoid.combine(x, Monoid.empty()) == x and Monoid.combine(Monoid.empty(), x) == x
```
> feat: add `CommutativeMonoid`

- main/src/library/CommutativeSemiGroup.flix
- main/src/library/Prelude.flix
- main/src/library/SemiGroup.flix
- main/test/ca/uwaterloo/flix/library/LibrarySuite.scala
- main/test/ca/uwaterloo/flix/library/TestCommutativeSemiGroup.flix
- main/test/ca/uwaterloo/flix/library/TestSemiGroup.flix
Fixes #3063
I cannot add these directly to Prelude because it breaks our tests. Maybe we need two Preludes? Not sure what to do.
> feat: add `SemiGroup` and `CommutativeSemiGroup` symbolic operators

- main/src/library/Foldable.flix
- main/test/ca/uwaterloo/flix/library/TestFoldable.flix
Fixes `Foldable.toArray`. It reversed the elements before this fix (with `foldRight`) and there were no tests to ensure correct behavior.
> fix: `Foldable.toArray`

- main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala
- main/test/flix/Test.Exp.Fixpoint.Solve.Lattice.flix
This includes adding `fix` in the rewrite of query expressions like
```
query p select (x, y) from A(x; y)
```
this is understood as
```
query p select (x, y) from fix A(x; y)
```
which you can also write yourself, but it is added automatically.
> feat: add check to disallow lattice variables used in relational contexts without fix

- main/src/library/Int16.flix
- main/src/library/Int32.flix
- main/src/library/Int64.flix
- main/src/library/Int8.flix
- main/src/library/Object.flix
- main/src/library/Order.flix
> Refactor: import syntax in library part 3

- .github/workflows/community-build.yaml
To support including this package I also had to:
- remove example code after running `flix init`
- update to Java 13
> ci: add `mlutze/fcwg` to community build

- main/src/library/List.flix
`List.groupBy` is not tail recursive this PR rewrites it in the CPS style.
This program is a pathological case for `groupBy` - the input list is long and there are no groups:
~~~
def main(_args: Array[String]): Int32 & Impure =
println("Small `groupBy` ...");
testGroupBy(10) |> println;
println("Big `groupBy` ...");
testGroupBy(100000) |> println;
0
def testGroupBy(e: Int32): Int32 = 
List.range(0, e) |> List.groupBy((x,y) -> x == y) |> List.length
~~~
With the current head, it runs out of memory rather than directly burst the stack on my PC...
~~~ 
Small `groupBy` ...
10
Big `groupBy` ...
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
at List.Clo%reverse%1028348.getUniqueThreadClosure(Unknown Source)
at List.Clo%reverse%1028348.invoke(Unknown Source)
at …
> refactor: List.groupBy rewritten to be in CPS

- main/src/library/Applicative.flix
Enforces the `ef` convention for effects
> refactor: rename `& e` to `& ef` in `Applicative` TC

- main/src/library/GetOpt.flix
- main/src/library/List.flix
- main/src/library/Nec.flix
- main/src/library/Option.flix
- main/src/library/Validation.flix
- main/test/ca/uwaterloo/flix/library/TestGetOpt.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestMonoid.flix
- main/test/ca/uwaterloo/flix/library/TestNec.flix
- main/test/ca/uwaterloo/flix/library/TestOption.flix
- main/test/ca/uwaterloo/flix/library/TestSemiGroup.flix
- main/test/ca/uwaterloo/flix/library/TestValidation.flix
This PR changes `Validation` to use `Nec` rather than `Nel` to track failures. It adds some new functionality so `Nec` can replace `Nel`: 
* `Order` instance to `Nec`
* `toNel` and `toNec` to `List`
All tests that use `Validation` have been updated. These were minor changes except to the `Validation` test module. I've changed the Validation test module so its namespace is `TestValidation` which is the usual style (before it was just `Validation`). Functions under test are now called with qualified names e.g. `Validation.ap` etc. Because constructing `Nec` s can't reuse `List` syntax (whereas `Nel` can) I've added the family of `necOf2` etc. functions as internal helpers to `TestValidation`.
> refactor: Change Validation to use Nec rather than Nel (related to #3232)

- main/src/ca/uwaterloo/flix/api/lsp/DocumentSymbol.scala
I have found a little bug in DocumentSymbol, where the detail field where incorrecly encoded.
> Properly encode DocumentSymbol into JSON

- main/src/library/Concurrent/Channel/Timer.flix
- main/test/ca/uwaterloo/flix/library/TestTimer.flix
This PR replaces `java.lang.Thread.sleep(Int64)` with `java.lang.Thread.sleep(Int64, Int32)`.
To convert Int64 to Int32, this PR uses [Int64.clampToInt32](https://api.flix.dev/#Int64) API.
close #3031
> Use better precision for Timer.sleepAndSend

- main/src/library/MutList.flix
Closes #3156
Also fixes a bug where `forall` called `exists`... that doesn't seem like the correct behavior.
```flix
def forallHelper(f: a -> Bool, a: Array[a], len: Int32, i: Int32): Bool & Impure =
if (i >= len)
true
else
f(a[i]) and existsHelper(f, a, len, i + 1)
```
> refactor: use let rec in `MutList`

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenMainClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- main/src/ca/uwaterloo/flix/runtime/CompilationResult.scala
- main/src/ca/uwaterloo/flix/tools/Packager.scala
The backend can cope with main methods of the form `def main(_: Array[String]): A`. flix `-run` still uses `System.exit`. Fixes some of #3338.
> feat: remove `System.exit` call in `Main.class` and support all return types of the flix main

- main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala
fixes #3400 
```
$ grep dbg -r main/src/ca/uwaterloo/flix/api/lsp || echo "no dbg :)"
no dbg :)
```
I didn't find any actual uses. Was there anything in particular I should be looking for?
> chore: ensure dbg package is not used in LSP

- main/src/library/Int16.flix
- main/src/library/Int32.flix
- main/src/library/Int64.flix
- main/src/library/Int8.flix
- main/test/ca/uwaterloo/flix/library/TestInt16.flix
- main/test/ca/uwaterloo/flix/library/TestInt64.flix
- main/test/ca/uwaterloo/flix/library/TestInt8.flix
Add `log2` and `factorial` functions to `Int8`, `Int16`, and `Int64` just like #1247.
I think this PR is not enough to close #1246, due to a lack of consideration for negative values. If we have a clear plan (e.g. returning 0) I will implement it in this branch later. :)
> feat: add log and factorial function to Int8, Int16, and Int64

- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
Allow: 
```
pub def count(f: a -> Bool, a: ScopedArray[a, r]): Int32 \ { Read(r) } =
foldLeft((b,x) -> if (f(x)) b + 1 else b, 0, a)
```
to be written as:
```
pub def count(f: a -> Bool, a: ScopedArray[a, r]): Int32 \ Read(r) = // Note: No braces
foldLeft((b,x) -> if (f(x)) b + 1 else b, 0, a)
```
when there is a single effect.
> feat: allow single effect without braces

- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/util/Validation.scala
This change more clearly separates the steps in the `visit*` functions, gets rid of some redundancy, and better distinguishes between parts that can fail and those that can't, all making way for a cleaner implementation of #1230 in the Namer.
> refactor: reorganize `Namer.visitSig` and `Namer.visitDef`

- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
> fix: don't show `Bool` on hovering pure defs and sigs

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompleteProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Scheme.scala
- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
- main/src/ca/uwaterloo/flix/language/fmt/FormatScheme.scala
- main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala
- main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/BoolUnification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/test/ca/uwaterloo/flix/language/phase/unification/TestUnification.scala
- changes type parameters to use `TypeVarSym`s instead of `TypeVar`s
- changes scheme quantifiers to use `TypeVarSym`s instead of `TypeVar`s
- changes substitution to use `TypeVarSym`s instead of `TypeVar`s
- adds semantic token for type variable
fixes #2510
> fix: separate TypeVarSym and TypeVar source locations

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/util/Validation.scala
- main/test/ca/uwaterloo/flix/util/TestValidation.scala
> refactor: remove uses of `Validation.flatMap` from `Weeder`

- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
Introduces a couple of helpers to make the top-level visitor a little cleaner and more regular.
> refactor: clean up `Namer`

- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
I think we should have a more robust solution moving forward. Specifically, we know that any time we introduce a type variable without text, its location must be generic, so we should enforce this somehow.
related to #3463
> fix: mark unification tvars as synthetic in `Kinder`

- main/src/ca/uwaterloo/flix/api/lsp/Entity.scala
- main/src/ca/uwaterloo/flix/api/lsp/Index.scala
- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/FindReferencesProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/GotoProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/RenameProvider.scala
Leads the way to a cleaner implementation of handling type vars in the LSP for various providers
related to #3463
> refactor: replace Entity.TypeCon with Entity.Type in LSP

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
This cleans up some of the code and actually fixes a couple bugs where we forgot to add the `acc` in the `foldLeft`.
> refactor: use Index.traverse in Indexer

- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
An experiment. The `tenv` appears useless, so we will see what happens when we take it away.
> refactor: remove `tenv` from `Resolver`

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenMainClass.scala
Right now `Main.class` always calls `NS.m_main` instead of the correct `NS.m_???` for the given entrypoint. This is fixed now.
> fix: `Main.class` should call the entry point

- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
> chore: remove old TODO from `Namer`

- .github/workflows/build.yaml
Fixes #3500. Splits up the build and test gradle steps so that the timeout can be applied just to the tests.
> ci: add testing timeout to ci

- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala
> fix: propogate empty row type locations in Resolver

- main/src/ca/uwaterloo/flix/language/phase/jvm/Bootstrap.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
This PR makes `Flix.scala` call `main` on `Main.class` that calls the program main. On master both `Flix.scala` and `Main.class` calls the program main which means that mistakes in `Main.class` are hard to find since `java -jar Flix.jar ...` would not use `Main.class`.
This was discussed in #3487.
> fix: make `Flix.scala` call `Main.class`

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenMainClass.scala
`Main.class` is always
```java
public final class Main {
public static void main(String[] var0) {
dev.flix.runtime.Global.setArgs(var0);
Ns.m_entrypoint(dev.flix.runtime.Unit.INSTANCE);
}
}
```
except that `m_entrypoint` will be whatever `root.entrypoint` dictates
> refactor: clean up `Main.class`

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
related to #3542. This only contains some unused Parser structures. I am separating this from the next step since there may be complications to handle in the Weeder in order to support the new grammar without breaking the old.
> feat: set up for migration to effect sets

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
related to #3542, depends on #3559
This is just the refactoring step. Next I'll add tests using the full power of the new syntax.
> refactor: migrate to new Effect AST

- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/test/flix/LangSuite.scala
- main/test/flix/Test.Eff.Advanced.flix
- main/test/flix/Test.Eff.Simplification.flix
fixes #3570, related to #3604
This isn't a totally reliable solution, as type aliases and probably other features make everything more complicated. But I'm hoping the new boolean unification stuff will address this issue more robustly.
So this is a quick fix in order to unblock #3604
> fix: use smart Boolean constructors in Kinder

- main/src/ca/uwaterloo/flix/language/phase/EntryPoint.scala
When testing with lib nix it is nice that this is avoided such that `def main(): Unit = ???` doesn't crash the compiler.
> fix: Delay ToString instance lookup for entrypoint

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenGlobalClass.scala
- main/test/ca/uwaterloo/flix/language/TestProgramArgs.scala
- main/test/ca/uwaterloo/flix/library/TestEnvironment.flix
Fix environment test, add test of environment getargs functionality and change pre-entrypoint args value from null to []
> fix: Environment getArgs tests and pre-entrypoint args default

- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
> fix: remove assumption that types have same kind in `Unification`

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
> refactor: remove sig and op from ParsedAst.Declaration trait

- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
- main/test/flix/Test.Dec.Effect.flix
- main/test/flix/Test.Exp.Effect.flix
related to #3543
Handles the following requirements:
Constructs:
- Introduce `Declaration.Eff`.
Checks:
- Reject effects with type parameters (but allow them to be parsed).
- Duplicate Modifier.
- Require public (or?)
- Ban effects called `Pure`, `Read` and `Write`. (Maybe even have an error for each to explain whats up)
> feat: weed effect declarations

- main/src/ca/uwaterloo/flix/language/phase/Inliner.scala
Task 3 from #3638 
Do we need to somehow check that the value of `e` points to the single case in the enum?
> feat: eliminate single case enum

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
It fooled me into thinking it actually meant something, but really it is only used for this one enum case case, which IMO is more the responsibility of the Weeder.
> refactor: remove ParsedAst.Type.Unit

- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
fixes #3692. This IllegalType error also needs a refactor separately, as it uses `formatWellKindedType` on unkinded types.
> fix: make type alias erasure work for both unkinded and kinded types

- main/src/ca/uwaterloo/flix/tools/Packager.scala
I think there was a copy/paste error with a recent change to `packager.scala` and the directory that `buildPkg` packages into a zip was changed from `src` to `build` so subsequently the `.fpkg` file wrongly contains `.class` files not Flix source files.
This change puts it back to `src`.
> fix: make flix-pkg zip the src directory not the build directory

- main/src/ca/uwaterloo/flix/tools/BenchmarkCompiler.scala
- main/src/ca/uwaterloo/flix/util/StatUtils.scala
related to #3703. Are we sure we want mean over median? I added some more stats for experimentation. We can report these details, but I did not want to break consumers.
> feat: change phase benchmarking to report average times

- main/test/flix/CompilerSuite.scala
- main/test/flix/LangSuite.scala
> refactor: move `Test.Exp.{Apply, Ascribe, BigInt, Binary, Match, Record}`

- main/test/flix/CompilerSuite.scala
- main/test/flix/LangSuite.scala
Related to https://github.com/flix/flix/issues/3144
In this PR
- Block
- Cast
- Char
- Choose
- Concurrency
- Default
- Discard
- Effects
- Floats
- Force
- Hole
- IfThenElse
- Infix
- Int
- Interpolation
> refactor: move `Test.Exp.*`

- main/src/ca/uwaterloo/flix/language/phase/UllmansAlgorithm.scala
- main/test/ca/uwaterloo/flix/language/phase/TestStratifier.scala
fixes #3704.
The error was these lines in `UllmansAlgorithm.scala` combined with a set used in the graph holding the edges
```
sealed trait DependencyEdge {
override def equals(obj: Any): Boolean = obj match {
case that: DependencyEdge => this.head == that.head && this.body == that.body
case _ => false
}
}
// ...
case class Weak(head: Name.Pred, body: Name.Pred, loc: SourceLocation) extends DependencyEdge
case class Strong(head: Name.Pred, body: Name.Pred, loc: SourceLocation) extends DependencyEdge
```
> fix: correct equality on strong/weak edges (fixes #3704)

- .github/workflows/build.yaml
- .github/workflows/community-build.yaml
We have had some timeouts recently. I guess we are simply naturally approaching the limit as we add more tests. This increases the limit by 11% and adds a timeout to the community build.
> ci: increase testing time limits

- main/src/library/Option.flix
- main/test/ca/uwaterloo/flix/library/TestOption.flix
This PR changes the `Option` functions `toOk`, `toErr`, `toSuccess` and `toFailure` to be subject last.
`TestAll` implies the functions aren't used elsewhere in the stdlib or tests so the changes are limited to `Option.flix` and `TestOption.flix`.
> refactor: change Option.toOk and related functions to subject last (fixes #3748)

- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
I introduced the `EffectAndPurity` structure as a lightweight insurance that things are in the right order, since there's now no type-enforced difference and it will be easy to get confused.
> refactor: use types for effects

- main/src/library/Array.flix
- main/src/library/Chain.flix
- main/src/library/DelayList.flix
- main/src/library/Foldable.flix
- main/src/library/List.flix
- main/src/library/Nec.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestChain.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
- main/test/ca/uwaterloo/flix/library/TestNec.flix
> refactor: use regions in `_.toMutList`

- main/src/library/DelayMap.flix
- main/src/library/Fixpoint/Solver.flix
- main/src/library/Map.flix
> refactor: use regions in `_.toMutMap`

- .github/workflows/build.yaml
It seems that 10 minutes was not enough. I still get timeouts.
> ci: increase testing time limit to 15 minutes

- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
this inconsistency broke my VIM macro :(
> chore: use consistent `for` syntax in Typer

- main/src/library/Map.flix
- main/src/library/RedBlackTree.flix
- main/src/library/Set.flix
This PR changes the Map, Set and RedBlackTree modules so that the `find` functions are effect polymorphic.
Also these others effect polymorphic: 
~~~
Map.filter
Map.filterWithKey
Set.exists
Set.forall
Set.filter
Set.partition
~~~
The find generalizations are needed for PR #3822
> refactor: refactor Map, Set, and RedBlackTree functions to be effect polymorphic

- examples/datalog/stratifier.flix
- examples/deriving-type-classes.flix
- examples/opaque-types.flix
- examples/simple-card-game.flix
- main/src/library/Concurrent/Condition.flix
- main/src/library/Concurrent/ReentrantLock.flix
- main/src/library/Fixpoint/Ast/PrecedenceGraph.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/src/library/Random.flix
- main/src/library/StringBuilder.flix
- main/src/library/Time/Instant.flix
- main/src/library/Traversable.flix
- main/test/ca/uwaterloo/flix/library/TestFoldable.flix
- main/test/flix/Test.Dec.OpaqueType.flix
- main/test/flix/Test.Dec.TopLevel.flix
- main/test/flix/Test.Dec.TypeAlias.flix
- main/test/flix/Test.Derives.Eq.flix
- main/test/flix/Test.Derives.Hash.flix
- main/test/flix/Test.Derives.Order.flix
- main/test/flix/Test.Derives.ToString.flix
- main/test/flix/Test.Exp.Lambda.Match.flix
- main/test/flix/Test.Use.Type.flix
> refactor: new syntax for `opaque type`

- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
fixes #3868 
```
❌ -- Resolution Error -------------------------------------------------- file:///home/matt/Documents/flix-home/flix/personal/flix-sandbox/src/Main.flix
>> Missing dependency jakarta/servlet/http/HttpServletResponse for JVM class 'org.eclipse.jetty.server.Server'.
8 |>     import new org.eclipse.jetty.server.Server(ThreadPool): ##org.eclipse.jetty.server.Server & Impure as newServer;
9 |>     let threadPool = newThreadPool();
10 |>     setThreadPoolName(threadPool, "server");
11 |>     let server = newServer(threadPool);
12 |>     println("Hello World!")
missing dependency jakarta/servlet/http/HttpServletResponse.
```
> fix: add `MissingJvmDependency` error

- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
Eliminates some redundant "... and r and r" booleans. We have 2 smart constructors for Booleans, Type.mkX and BoolUnification.mkX. The latter is smarter, but presumably significantly more expensive. We may need some kind of principle about when to use which.
> fix: use smarter boolean constructor in Kinder

- main/src/ca/uwaterloo/flix/language/phase/jvm/AsmOps.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BytecodeInstructions.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/ClassMaker.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenContinuationAbstractClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenFunctionAbstractClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenGlobalClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenHoleErrorClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenMainClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenMatchErrorClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordEmptyClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordExtendClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRefClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenReifiedSourceLocationClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenUnitClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmName.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmType.scala
Field objects are used to hold all permanent information about a field which is used in generation and code. Related to #2591.
> refactor: rewrite backend to use field objects

- examples/datalog/connect-graph.flix
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
> chore: allow `inject` as an alias for `project`

- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/test/flix/Test.Exp.Fixpoint.Constraint.flix
Fixes #3193.
When a predicate occurs with a type variable as term type then the stratifier assumes that it is a nullary predicate of relational type. This should be safe since any construct to add facts of the predicate would introduce type constraints.
> fix: allow predicates with unconstrained terms

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
Fixes #3959
(I don't think adding a space makes sense after any of the other completions that are currently in place, but let me know if I've missed anything).
> chore: add space after auto-completing keywords

- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
> fix: allow whitespace just after and before multiuse braces

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Chain.flix
- main/src/library/DelayList.flix
- main/src/library/FunctorFilter.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/Option.flix
- main/src/library/RedBlackTree.flix
- main/test/ca/uwaterloo/flix/library/TestFunctorFilter.flix
- main/test/ca/uwaterloo/flix/library/TestMap.flix
- main/test/ca/uwaterloo/flix/library/TestRedBlackTree.flix
This PR adds the `FunctorFilter` class of issue #3819 and instances for "emptyable" Functor types:
Chain
DelayList
List
Map
Option
RedBlackTree
Tests in the `TestFunctorFilter.flix` file as the existing test modules usually already had tests for `filter` and `filterMap` but they used the versions in the namespace directly rather than resolved the implementations through the `FunctorFilter` class.
If the namespace was missing `filter` / `filterMap` (both in `RedBlackTree` , `filterMap` in `Map`) I added them only via the `FunctorFilter` class.
> feat: add FunctorFilter class (related to #3819)

- gradlew
To avoid Java heap space errors that have recently started happening
> chore: increase default memory for Gradle

- main/src/library/Fixpoint/Ast/BodyPredicate.flix
Related to #3896.
sidenote: This is currently unused. The parser has implementation but it results in questionmarks everywhere. Is this a upcomming feature or an abandoned feature @magnus-madsen?
Alternative option 1: remove Loop1 from the flix code (-3 lines)
Alternative option 2: remove Loop1 from the copiler (-150 lines)
> refactor: change array to list in `BodyPredicate.Loop1`

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenAnonymousClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
- main/test/flix/Test.Exp.Jvm.NewObject.flix
This is now successfully creating the bytecode for NewObject, creating an instance of it, and calling the constructor.
No support for method implementations yet, or naming the anonymous class.
> feat: code generation for `NewObject`

- main/src/library/Array.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
This PR generalizes various Array functions (`flatMap`, `flatten`, etc.) to use a polymorphic region rather than the Static region. 
Presumably these functions were the first to be converted to use regions and got missed when the `Scoped` class was introduced allowing allowed more generalization.
> refactor: generalize Array functions to use Arrays with a polymorphic region rather than the Static region

- main/src/library/MutList.flix
I was going over `MutList` while working on #3582 and decided to reduce some of the verbosity in `MutList` that had been introduced when adding regions.
> chore: prettify `MutList.flix`

- main/src/library/Fixpoint/IndexSelection.flix
Fixes #4027.
This `???` case follows mutiple other `???` cases for non `Eq` bool exps so this code is unreachable.
> fix: exhaustive pattern in datalog engine

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
- main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
remInput just blanks the text of the given input, so requiring the previous text to be passed is unnecessary.
> chore: remove text argument to remSourceCode

- main/src/library/Fixpoint/Ast/BodyPredicate.flix
- main/src/library/Fixpoint/Compiler.flix
- main/src/library/Fixpoint/IndexSelection.flix
- main/src/library/Fixpoint/Interpreter.flix
- main/src/library/Fixpoint/Ram/RamStmt.flix
- main/src/library/Fixpoint/Ram/RelOp.flix
- main/src/library/Fixpoint/Simplifier.flix
- main/src/library/Fixpoint/VarsToIndices.flix
Part of #3896.
Also uses `list |> List.join(", ")` instead of `list |> List.map(ToString.toString) |> String.intercalate(", ")`
> refactor: `RamStmt` to use `List`

- main/test/ca/uwaterloo/flix/library/TestList.flix
The tests were written like shuffle is destructive. @magnus-madsen this was caught by the check in #3667, for our upcoming discussion
> fix: `List.shuffle` tests

- main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala
- main/test/ca/uwaterloo/flix/language/phase/TestPatExhaustiveness.scala
Refactors the PatternExhaustiveness phase:
- uses `Validation[Unit, _]` instead of passing around unused AST nodes
- productizes validations so that we can catch multiple errors at once (fixes #3426)
- changes some names to follow convention
- removes some unused vars
- marks private defs private
- checks inside nested patterns (fixes #4024)
> refactor: clean up PatternExhaustiveness

- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/library/Fixpoint/Ast/HeadPredicate.flix
- main/src/library/Fixpoint/Compiler.flix
- main/src/library/Fixpoint/Solver.flix
related to #3896.
It seems pretty easy from here to make `query` return a list. Should we try this although it will break a lot of things?
> refactor: use `List` in `HeadPredicate`

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/EntryPoint.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/src/ca/uwaterloo/flix/util/collection/ListOps.scala
Adds the inference logic to the Typer for the effect sets.
This currently doesn't do anything because a hack is added to type unification which makes it succeed automatically if the types have kind `Effect`.
~depends on #4057~
related to #4050
> refactor: set up for effect inference

- main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
This stops jline from treating a backslash as an escape character. Before this change:
```
flix> "\n"                                                                      
n                                                                               
flix> def sub(x: Int32, y: Int32): Int32 \ { } = ??? 
Error: Input cannot be parsed.
```
After this change:
```
flix> "\n"                                                                      
flix> def sub(x: Int32, y: Int32): Int32 \ { } = ???
Ok. 
```
> feat: stop jline from handling backslashes

- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
related to #4050 
We can't tell what the type of `resume` should be locally; we have to use the type of the handled expression.
This change adds a `henv` to the Kinder that gives the `resume` expression the same tvar as the handled expression.
> fix: add handler env to Kinder

- main/src/library/RedBlackTree.flix
Going over the `RedBlackTree` I made some minor stylistic changes like adding white space where needed. Also refactored `size` to run in parallel for large trees.
Closes #3582
> refactor: make `RedBlackTree.size` tail recursive

- main/src/library/DelayMap.flix
> refactor: remove impure cast in `DelayMap.foreach`

- main/src/ca/uwaterloo/flix/language/ast/Scheme.scala
- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala
- main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Regions.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/BoolUnification.scala
- main/test/ca/uwaterloo/flix/language/fmt/TestFormatType.scala
- main/test/ca/uwaterloo/flix/language/phase/unification/TestUnification.scala
I replaced it with an `isRegion` parameter to support the `Regions` phase, but at least this makes things less ambiguous and eliminates all the unused `InstantiateMode` stuff. Fixes #3923
> refactor: remove rigidity from type var sym

- main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
- main/src/ca/uwaterloo/flix/runtime/shell/ShellParser.scala
- main/src/library/Validation.flix
I will freely admit that this is heading towards "voodoo programming". Jline does an awful lot, and the documentation is unhelpfully sparse, so I've cobbled this together by reading the source and looking at examples of other projects that use jline.
But, it does seem to do the right thing:
```
flix> 1 + \                                                                     
> 2
3                                                                               
flix> def myFunction(x: Int32): Int32 = \
> x + 1
Ok.                                                                             
flix> myFunction(1)
2 
```
> feat: single backslash at the end of the line acts as continuation

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/flix/Test.Exp.ForEach.flix
`ForEach` was not properly formatted.
> refactor: add consistent naming to `foreach`

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Chain.flix
- main/src/library/DelayList.flix
- main/src/library/List.flix
- main/src/library/MonadZero.flix
- main/src/library/Option.flix
Adds `MonadZero` and instances to `List`, `DelayList`,`Chain`, `Option`.
I tried experimenting with adding `Applicative` and `Monad` instances to `Result` but it seems the `point` function causes problems with the type variable `e` in `Result[t, e]`. Besides, there is no empty element for `Result` so it wouldn't make sense to add a `MonadZero` instance either.
Also, removed a todo from `List` and changed `& e` to `& ef`.
Closes #4214
> feat: add `MonadZero`

- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/runtime/shell/Command.scala
- main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
This implements another of the suggestions within #3989
Draft for now because there are some unanswered questions.
This works reasonably nicely:
But...
I haven't found a way to display the type of a class (so all that's displayed is the documentation):
And it would probably make sense to display its signatures (in the same way as does api.flix.dev).
I *have* managed to find a way to display the signature of an enum, but that relies on using `tpeDeprecated` which probably isn't a good thing?
And the formatting can get messy:
So, to do this properly, we probably need to:
* Do something about formatting markdown nicely for terminal output
* Extract some of the code within the documentor phase to re-use here. Or run the documentor when compiling within the repl and make the results available?
> add `:doc` command to REPL

- main/src/library/Fixpoint/Compiler.flix
- main/src/library/Fixpoint/Interpreter.flix
- main/src/library/Fixpoint/Solver.flix
Fixes #3896.
With this PR the debugging messages will now be erased by the optimizer. This is probably just the way it is for now.
The remaining impure methods are related to debug messages and the use of `Global.newId`.
The remaining unsafe Pure casts are from the above and then the unsafe implementation of `Tuple`
> refactor: use regions in `SearchEnv`

- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
Italicizing the `()` felt out of place to me. It's subjective, but here's the change:
> fix: do not stylize Unit as Enum

- main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala
- main/test/ca/uwaterloo/flix/language/fmt/TestFormatType.scala
changes from `({ef1, ef2}) & E` to `{ef1, ef2} & E`
> fix: remove extra parentheses from union type formatting

- main/src/library/Map.flix
- main/src/library/RedBlackTree.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestRedBlackTree.flix
This PR adds an `iterator` to `RedBlackTree` and changes `Set` and `Map` to use the RedBlackTree iterator rather than make an iterator via a conversion to List.
Like `Map` the `RedBlackTree` iterator works over a pair of `(key, value)`. Maybe there is scope to add `keyIterator` and `valueIterator` at some point, but client code can use `Iterator.mapL(fst)` or `Iterator.mapL(snd)` to get this.
I haven't looked at an iterator for `MultiMap` - I think this would need a nested iterator and need a direct implementation rather than be able to reuse `RedBlackTree.iterator`.
> feat: add RedBlackTree iterator and enumerator (fixes #4166)

- main/src/ca/uwaterloo/flix/language/ast/Operator.scala
- main/src/ca/uwaterloo/flix/language/ast/SemanticOperator.scala
- main/src/ca/uwaterloo/flix/language/dbg/PrettyExpression.scala
- main/src/ca/uwaterloo/flix/language/dbg/PrettyPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
The todo comment had been there since 2017. I think it's okay to call it `Modulo`.
> docs: remove old todo

- main/src/ca/uwaterloo/flix/api/lsp/Entity.scala
- main/src/ca/uwaterloo/flix/api/lsp/Index.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/FindReferencesProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/GotoProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SymbolProvider.scala
- main/src/ca/uwaterloo/flix/language/fmt/FormatSignature.scala
related to #4236 
Enables the following from `Do` expressions:
* Find references
* Go to implementation
* Highlight
* Hover
This also demonstrates the `SymUse` idea I proposed as a larger refactor of LSP, where we consider uses of symbols as entities.
> feat: enable additional LSP features for effect operations

- main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/TreeShaker.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenAnonymousClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
- main/test/flix/Test.Exp.Jvm.NewObject.flix
This is definitely not ready to be merged, but I've hit a problem that I think I need assistance with.
I'm halfway through and you're definitely seeing how the sausage gets made. The structure isn't right, the method is still throwing an exception, and I've not written any comments, so please don't worry too much about those things.
I've fixed a couple of problems that became apparent as I was working through this:
* The type of the closure needed to be set to an arrow type
* The `NewObject` case within `closuresOf` was returning `Set.empty` (blush).
Given the following Flix:
```
@test
def f():Int32 & Impure =
import java.lang.Comparable.compareTo(##java.lang.Object): Int32 & Impure;
let x = 0;
let anon = object ##java.lang.Comparable {
def compareTo(_this: ##java.lang.Comparable, _that: …
```
> feat: object code generation

- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenAnonymousClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
- main/src/flix/test/TestClassWithDefaultConstructor.java
- main/src/flix/test/TestDefaultMethods.java
- main/src/flix/test/TestGenerics.java
- main/src/flix/test/TestOverloadedMethods.java
- main/src/flix/test/TestPrimitiveTypes.java
- main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala
- main/test/flix/Test.Exp.Jvm.NewObject.flix
I'm not done yet, but I think that there's enough here to be worth a review and merge.
This PR implements tests which confirm that `object` can:
* Implement methods taking and returning primitive types.
* Implement overloaded methods.
* Implement interfaces with default methods.
* Implement generic interfaces, and generic methods within an interface.
* Implement methods taking boxed primitive types (within the test for generics).
* Implement classes with a default constructor.
These are all "happy path" tests (i.e. they only test things that should work, not that things that shouldn't work fail correctly.
> feat: NewObject tests

- main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/src/flix/test/TestClassWithNonDefaultConstructor.java
- main/src/flix/test/TestNonPublicInterface.java
- main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala
- main/test/flix/Test.Exp.Jvm.NewObject.flix
This tidies up the existing error case tests, and adds tests for non-default constructors and non-public superclasses.
I think that this completes the non-happy-path tests, but shout if you think I've missed anything!
> test: negative tests for `NewObject`

- main/src/ca/uwaterloo/flix/language/ast/Name.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/flix/Test.Exp.Jvm.NewObject.flix
Fixes #4363
I've deliberately kept the changes in this PR minimal, but that does lead to some odditites such as `ParsedAst.Imports.Import` wrapping a `JavaName` with source positions which now already exist within `JavaName`.
> fix: introduce `Name.Java`

- main/src/ca/uwaterloo/flix/language/errors/RedundancyError.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
- main/test/flix/Test.Dec.Effect.flix
- main/test/flix/Test.Exp.ReifyEff.flix
related to #4236
Uses the same rule as enum: use in a type is not enough; it must be used in an expression.
> feat: add UnusedEffectSym error

- main/src/library/Array.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
Makes `Array.unzip` take two regions in which to put the unzipped arrays.
> feat: generalize `Array.unzip`

- main/src/library/List.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
While looking at changing `Traversable.mapAccumLeft` to use local mutable state I discovered that `List.traverse` does not run its effects in left-to-right order. Instead, it traverses the List, builds up a stack of effects to run and performs them backwards (the rightmost effect is top of the stack so it is performed first). 
This PR fixes `List.traverse` to perform the effects in left to right order and adds tests so we can see it working.
Counter-intuitively `List.sequence` for all appearances does the same traversal as the original `List.traverse` but it performs the effects in the correct left to right order (I have added tests for `List.sequence` but the implementation is unchanged). 
The new implementation `List.traverse` is a bit tricky - to get left-to-right effects and to not …
> fix: Make List.traverse effects run left-to-right 

- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/test/flix/Test.Unused.Def.flix
- main/test/flix/Test.Unused.Var.flix
> fix: Allow underscores within math, greek, and operator names

- main/src/library/DelayList.flix
- main/src/library/List.flix
- main/src/library/Nec.flix
- main/src/library/RedBlackTree.flix
- main/test/ca/uwaterloo/flix/library/TestChain.flix
- main/test/ca/uwaterloo/flix/library/TestDelayList.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestMap.flix
- main/test/ca/uwaterloo/flix/library/TestNec.flix
- main/test/ca/uwaterloo/flix/library/TestNel.flix
- main/test/ca/uwaterloo/flix/library/TestRedBlackTree.flix
This PR fixes the `traverse` implementations for `DelayList`, `Nec` and `RedBlackTree` (called `mapAWithKey`) to go left-to-right (this is a prelude to implementing `Traverse.mapAccumLeft` with mutable state).
It also simplifies the `List.traverse` fix from two days ago so the helper function `consAD` is no longer needed, and it adds `sequence` and `traverse` tests for the container types than provide them in their APIs.
The `sequence` tests for `List` from two days ago overstated their "effectiveness" (pun intended). The effects `sequence01` etc. were supposed to show were actually being performed by the `List.map` calls that preprocessed the input and not by the call to `List.sequence`. To show `List.sequence` running effects in left-to-right order, we would need a monad that does …
> fix: make traverse implementations run left-to-right

- main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
> fix: reject `par` `Apply` instead of crashing

- main/src/library/Traversable.flix
- main/test/ca/uwaterloo/flix/library/TestTraversable.flix
This PR re-implements `Traversable.mapAccumLeft` with mutable state. The previous version used a cont-state monad that used casts that were causing problems.
The PR also removes `Traversable.mapAccumRight` - unlike `mapAccumLeft` this cannot be written in terms of `Traverse.traverse`.
> refactor: reimplement Traversable.mapAccumLeft to use mutable state and remove mapAccumRight

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/tools/SimpleRunner.scala
related to #3720 
This moves the default (non-package) functionality to a new file, making the `main` function simpler. Should make #4534 easier to implement.
> refactor: move simple cli use to new file

- main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala
- main/test/ca/uwaterloo/flix/language/fmt/TestFormatType.scala
> fix: use = formatting for record types in error messages

- main/src/ca/uwaterloo/flix/language/phase/Regions.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/BoolUnification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
The problem is that the region checks assume that a type is fully minimized, but our minimization technique is not a true minimization, in that irrelevant variables may remain inside. This means that a region variable that is actually irrelevant to the formula may still appear in the formula and therefore be identified as escaping.
I've made a change where we no longer rely on minimization, and we instead explicitly check whether the variable is relevant to the formula. To see if a variable `r` is relevant in a type `t`, I calculate `t0 = t[r -> false]` and `t1 = t[r -> true]`. Then I check if `t0 == t1` modulo Boolean equivalence (where all type variables are rigid).
This seems to work, but we move from a state of "variable elimination order is related to errors" to "variable elimination …
> fix: check variable essentialness in regions checks

- main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala
Fixes #4611.
This is what the message now looks like:
> fix: Fix syntax highlighting in hover

- main/src/ca/uwaterloo/flix/api/lsp/provider/InlayHintProvider.scala
This modifies inlay hints so that instead of hiding long hints, they're now abbreviated. So instead of this:
We now have this:
A couple of things to perhaps consider before merging this:
* I've left the length of a "long" inlay hint at 14 characters. Other languages [apparently use 30 characters](https://github.com/ionide/ionide-vscode-fsharp/issues/1694), we might want to follow suit?
* I've (almost) copied the `truncate` function from `ProgressBar.scala`, which might not be the right thing to do. Is there somewhere where this kind of utility should live?
* The difference between my copy of `truncate` and the one in `ProgressBar.scala` is that I'm using the Unicode ellipsis character `…` instead of three periods `...`. This strikes me as the right thing to do given that space is at a …
> feat: Abbreviate instead of hide long inlay hints

- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala
- main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala
- main/src/ca/uwaterloo/flix/language/phase/Finalize.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
Preparing to introduce region syms which will have a type constructor called Region. Related to #4653
> refactor: rename TypeConstructor.Region -> TypeConstructor.RegionToStar

- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
> fix: highlight region types in VSCode

- main/src/ca/uwaterloo/flix/language/phase/Regions.scala
related to #4653. Might even improve performance since substitution does some simplification
> refactor: use substitution in essentialness check

- main/src/ca/uwaterloo/flix/language/phase/jvm/AsmOps.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenTagClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenTupleClasses.scala
Related to #4664.
* Tuples are `(a, b, c, d)`, using java toString of the elements
* Tags omit parentheses for tuples to avoid `Test((1, 2))`.
* Tags only use their tag, not their enum
> feat: improve tuple java `toString`

- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/flix/test/TestClassWithStaticNestedClass.java
- main/test/flix/Test.Exp.Jvm.InvokeConstructor.flix
- main/test/flix/Test.Exp.Jvm.NewObject.flix
Fixes #4663
It turns out that this already works: the trick is to use '$' to separate the nested class instead of '.'.
I've added a few tests to confirm that this works, and improved the error messages to make this more discoverable.
> feat: Improve tests and error messages for static nested classes

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BytecodeInstructions.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmName.scala
- main/test/ca/uwaterloo/flix/library/TestPrelude.flix
Related to #4664.
* `{}` is `{}`
* `{ field = 42}` is `{field = 42}`
* `{ fieldA = 1, fieldB = 123 }` is `{fieldA = 1, fieldB = 123}` (order not defined I suppose)
> feat: improve `java.lang.Object.toString` of record objects

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/library/Fixpoint/Interpreter.flix
- main/src/library/Fixpoint/Tuple/Tuple.flix
- main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala
- main/test/flix/Test.Use.Type.flix
Part of  #4649
This fixes cases where the names of classes, enums, aliases, or effects clash with the names of used or imported types. It doesn't fix the case where used types clash with imported types (see commented out test in `TestNamer` for an example).
I think that the right way to address the latter is to merge `ImportEnv` into `UseEnv`, but that involves largely undoing the change I made a while ago to plumb `ImportEnv` through the namer. Given that that means hundreds of lines changing (eugh!) I wanted to check this in separately.
A note about testing: To test this exhaustively, we would have to test every possible combination of classes, enums, aliases, effects, uses and imports, with various different levels of nesting. I've only added a subset of the missing combinations: I'm …
> fix: Towards fixing duplicate names

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BytecodeInstructions.scala
- main/test/ca/uwaterloo/flix/library/TestPrelude.flix
Realted to #4664.
Functions print their (java, i.e. no String or Unit) erased type, so `Int32 -> Int32`, `Obj -> Bool` etc. I've programmed other arities `() -> Int32` and `(Int32, Float32) -> Char` but I don't think any can exist
> feat: improve `toString` of function objects

- main/src/ca/uwaterloo/flix/language/errors/NameError.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala
Fixes #4649
Buckle up, this was less straightforward than I thought it was going to be.
The basic problem was that neither uses nor imports were checking to see if they clashed with pre-existing upper case names (enums, classes, aliases, effects). The solution is easy enough: call `lookupUpperName` within both `mergeUseEnvs` and `mergeImportEnvs`.
The problem is that that requires the namespace and compilation unit root, which need to be plumbed all the way through, which amounts to a lot of changes.
The parameter lists are starting to get uncomfortably long. Given that just about every function takes the same set of parameters now, we might like to think about packaging them up into a single data structure (but not as part of this change).
> fix: Prevent duplicate upper names

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Chain.flix
- main/src/library/DelayList.flix
- main/src/library/Filterable.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/Option.flix
- main/src/library/RedBlackTree.flix
- main/src/library/Witherable.flix
- main/test/ca/uwaterloo/flix/library/TestFilterable.flix
This PR renames the class `FunctorFilter` to `Filterable`. `Filterable` is the name Haskell and PureScript use for the equivalent class.
> refactor: rename FunctorFilter to Filterable, issue #4713

- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/src/flix/test/TestClassWithProtectedConstructor.java
- main/test/flix/Test.Exp.Jvm.NewObject.flix
Requiring that the type passed to `new` has a public constructor is too strict: a protected constructor will do just fine.
> fix: Allow new with protected constructor

- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
Fixes #4666
This works, but I'm not 100% happy with it: I've had to effectively re-implement the definition of `UpperCaseName`. I'd love to use the same code, but I can't see how I could reuse a portion of the parser?
If there is a way, I'd love to hear about it.
> fix: Disallow java names which aren't also Flix names

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/test/flix/Test.Exp.Jvm.InvokeConstructor.flix
- main/test/flix/Test.Exp.Jvm.InvokeStaticMethod.flix
This fixes calling a constructor which takes an array argument (calling methods and static methods with array arguments already works).
The problem was that the code to put the arguments on the stack for constructors was different from the equivalent code for methods and static methods. This PR pulls that code out into a separate method to ensure that it's always done the same way.
> fix: Calling a constructor that takes an array argument

- main/src/library/BigDecimal.flix
- main/src/library/Int16.flix
- main/src/library/Int32.flix
- main/src/library/Int64.flix
This PR tidies up the occurrences of `##java.math.BigDecimal` that slipped through the BigDecimal stdlib PR.
`##java.math.BigDecimal` in import signatures is replaced with `BigDecimal`.
> chore: find and replace ##java.math.BigDecimal to BigDecimal

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
```
def foo(): Unit = ???
foo (position 1)
"Hello world!" |> foo (position 2)
```
At position 1 it would complete as ```foo(?_unit)``` which this changes to ```foo()```
At position 2 it would complete as ```foo``` which this changes to not being suggested as the pipeline requires at least one argument.
> fix: lsp complete function arguments correctly.

- main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmName.scala
- main/test/flix/Test.Java.Function.flix
This PR adds `IntPredicate` the Java functional interface of functions `Int32 -> Bool`.
The code is patterned after the `IntUnaryOperator` code so hopefully there is nothing suprising.
A test is in the module `Test.Java.Function.flix`.
> feat: add IntPredicate to the translated functional interfaces (see issue #4721)

- main/src/library/Down.flix
Fixes #4763
No tests 😱, but there don't seem to be any tests for `Down`? And I guess it's pretty simple?
> fix: Add UpperBound to Down

- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/test/flix/Test.Exp.Jvm.NewObject.flix
> fix: Don't require that java.lang.Object methods are implemented

- main/src/library/Graph.flix
* Reduce comments to 80char width
* put private methods after public methods
* normalize naming of query result `let res = query ...`
* write `query .. select ... from ... where ...` on separate lines
> refactor: `Graph.flix` formatting

- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/library/Channel.flix
- main/test/flix/Test.Exp.Concurrency.Buffered.flix
- main/test/flix/Test.Exp.Concurrency.Unbuffered.flix
This addresses the "Add $CHANNEL_GET(exp)$" task of #4755
I've also changed a number of the channel gets in the tests to use `Channel.recv` (not all of them, but enough to be confident that this works).
> chore: Add $CHANNEL_GET$ to internal syntax and use in Channel.recv.

- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
Part of #4746
Add tests to confirm that parent namespace declarations are not visible in child namespace
> test: Add tests to confirm that parent namespace not visible in child

- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/library/Channel.flix
- main/test/flix/Test.Exp.Concurrency.Buffered.flix
- main/test/flix/Test.Exp.Concurrency.Unbuffered.flix
This fixes the "Add CHANNEL_GET to internal syntax and use in Channel.send" task within #4755
> chore: Add CHANNEL_PUT to internal syntax and use in Channel.send

- main/src/library/Prelude.flix
- main/test/flix/Test.Exp.TypeMatch.flix
related to #4773 and #2428. The default function requires casts, unfortunately. I do not think there is a way around it.
> feat: add Proxy type

- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/flix/Test.Exp.Concurrency.Buffered.flix
- main/test/flix/Test.Exp.Concurrency.Unbuffered.flix
This is an attempt to remove the type from NewObject, as discussed in #4755
But this results in errors of the form:
```
- Test.Currying.flix *** FAILED ***
Unable to compile. Failed with: 6 errors.
-- Type Error -------------------------------------------------- RedBlackTree.flix
>> Expected type: '?elm155501' but found type: 'Bool'.
392 |                         spawn (chanL <- parExists((n - 2) / 2, f, a)); // We divide the rest of the threads as follows:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
expression has unexpected type.
```
Which I'm not sure I understand.
I'd be grateful for a pointer as to what might be going on @magnus-madsen
> chore: Remove type from NewChannel

- main/src/library/Thread.flix
Fixes "Support sub-millisecond sleep in Thread.sleep." in #4755
> feat: add support for nanosecond sleep to `Thread.sleep`

- main/src/ca/uwaterloo/flix/language/ast/Name.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
As per discussion on Gitter, this allows lambda parameters to be marked as synthetic (which means that syntax colouring is correct for match lambdas).
> fix: Allow Ident to be marked as synthetic

- main/src/ca/uwaterloo/flix/language/ast/MonoType.scala
- main/src/ca/uwaterloo/flix/language/phase/Finalize.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
This fixes the Remove MonoType.Channel task of #4755
> chore: Remove sender and receiver monotypes

- examples/select-with-defaults-and-timers.flix
- examples/using-channels-and-select.flix
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
- main/test/flix/Test.Exp.Concurrency.Select.flix
- main/test/flix/Test.Unused.Var.flix
This addresses the Update select syntax to case x <- recv(exp) (and optionally case x <- Channel.recv(exp)) task of #4755
> feat: New select syntax

- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/InferMonad.scala
- main/src/ca/uwaterloo/flix/util/Result.scala
There should be almost no semantic change here ultimately. We may get a slight speedup by short-circuiting inference over lists. The point of this is that it better communicates what is going on: What we do in InferMonad is more like Validation.traverse because it does not collect error, unlike Validation.sequence.
> refactor: replace uses of seqM with traverseM

- main/src/library/Console.flix
* Changed the return type from `Option` to `Result` to add an explanation and to signal that `read` shouldn't be reattempted on error.
* Correctly handle null strings
> fix: `Console.readLine`

- main/src/ca/uwaterloo/flix/language/phase/jvm/FlixClassLoader.scala
- main/src/ca/uwaterloo/flix/util/ExternalJarLoader.scala
- main/test/flix/Test.Import.flix
Fixes #4898
Apologies: this was me being dense.
The original code passed `null` as the parent classloader, which means the bootstrap classloader. This knows how to load built-in packages like `java.lang` and `java.util`, but not `java.sql`.
This change switches to the platform class loader which does know how to load those classes (but still isn't the full system class loader, so still doesn't give compiled code access to compiler internals).
> fix: Use platform class loader, not bootstrap class loader

- AUTHORS.md
- build.gradle
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
Unfortunately there is a severe performance regression in the newer Scala compiler.
See e.g.:
I can confirm this locally too.
> fix: Revert "chore: update Scala 2 version"

- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/library/Array.flix
- main/src/library/BigDecimal.flix
- main/src/library/Bool.flix
- main/src/library/Char.flix
- main/src/library/Float32.flix
- main/src/library/Float64.flix
- main/src/library/Int16.flix
- main/src/library/Int32.flix
- main/src/library/Int64.flix
- main/src/library/Int8.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/Nel.flix
- main/src/library/Option.flix
- main/src/library/Prelude.flix
- main/src/library/RedBlackTree.flix
- main/src/library/Result.flix
- main/src/library/Set.flix
- main/src/library/String.flix
- main/src/library/Validation.flix
Removes all @Time and @Space annotations from the library. Related to #4892
> refactor: remove time and space annotations

- main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
- main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala
- main/test/flix/Test.Exp.Supercast.flix
Changes supercast syntax from `supercast(e)` to `super_cast e`
Related to https://github.com/flix/flix/issues/4939
> refactor: change supercast syntax

- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
This is, I think, all that's necessary to address the "Modify the type rule for Select to use the regions of all the Sender[t, r] as its effect." task of #4850?
> feat: Add region to select effect

- main/src/ca/uwaterloo/flix/language/ast/Name.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/util/Validation.scala
- main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala
The Namer is changed to two passes:
1. To transform the tree
2. To build the symbol table.
The symbol table consists of 3 parts:
1. symbols: namespace -> declaration
2. instances: namespace -> declaration
- instances are treated different
3. uses: namespace -> uses/imports
There are a few TODOs I have accumulated which I didn't think directly relevant to the PR:
1. Avoid using `NName`: I think this may even be removed from the compiler altogether, or at least greatly limited
2. Remove `tenv` from cases in `Namer` where it's not used
3. parallelize the first pass in Namer
- This could be done now but I am interested in seeing the impact parallel vs. non-parallel
In the next step, uses and imports can be largely moved to `Resolver`, I think.
related to #4967
> refactor: bring tree structure to Resolver

- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
Adds slightly more code duplication but simplifies `isJavaSubtype` and removes redundant data structure.
Closes https://github.com/flix/flix/issues/4959
> refactor: remove `JavaSubtypeResult` from Safety

- main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
Closes https://github.com/flix/flix/issues/5008
> fix: use `unsafe_cast` in Shell

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala
- main/test/flix/Test.Java.Function.flix
Follow-ups:
* rename things to `visitX` in resolver
* improve use of `QName`: a `QName` _is qualified_, otherwise it should just be an `ident`
> refactor: resolve uses and imports in Resolver

- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
related to #4967, doing separately since it extends beyond Namer/Resolver
> refactor: remove head/rule split for constraint params

- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/test/flix/Test.Exp.ParYield.flix
Suppose we have
```flix
let b = 1;
par (
a <- b;
c <- 2;
e <- exp1;
f <- exp2
) yield exp3
```
This PR changes `ParYield` to no longer spawn threads for `a` and `c` since these are just a variable lookup and a literal respectively.
Related to https://github.com/flix/flix/issues/4609
> feat: evaluate literals and variables in calling thread in `ParYield`

- .github/workflows/community-build.yaml
I made a (WIP) parser library which I think will fit nicely in the community project test suite.
> chore: add jaschdoc/flix-parsers to community build

- main/src/ca/uwaterloo/flix/language/ast/MonoType.scala
- main/src/ca/uwaterloo/flix/language/phase/Finalize.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRegionClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
This is the first step towards the "Add a GenRegionClasses which generates a Region class" task of #4850. It's creating a `Region` class in the backend which currently does nothing. But it does type check (finally: working out what to do with MonoTypes was a PITA but I think I've got there eventually).
> feat: Add backend Region class

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BytecodeInstructions.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmName.scala
- main/src/library/Concurrent/Channel.flix
- main/test/flix/Test.Exp.Regions.flix
This replaces #5122 (which I will close).
This completes the Region class tasks of https://github.com/flix/flix/issues/4850 (so the Region class is both being generated and called on scope exit)
It also includes the fix to `size` within the channel code discussed within #5121 because once I addressed the race condition discussed there, I did see occasional failures as a result of this.
With this code, I have run the tests in `Test.Exp.Concurrency.Spawn.flix` 100 times without a single failure.
> feat: Generate Region.exit and call it

- main/src/library/Array.flix
- main/src/library/Benchmark.flix
- main/src/library/Concurrent/Channel.flix
- main/src/library/File.flix
- main/src/library/MutDeque.flix
- main/src/library/MutList.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/src/library/Reducible.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
- main/test/flix/Test.Exp.Jvm.NewObject.flix
This PR adds an "output" region parameter to the signatures of functions on mutables (Array, MutDeque, MutList, MutMap, MutSet) that return new mutables.
Exception - `iterator` and `enumerator` functions and the `Iterable` class left untouched. Firstly, I was having to do extra copying / casting or both to fit using a new region inside the interator. Secondly and a worse problem, changing the signature of the `Iterable` class was having some strange name resolution problems that I couldn't resolve e.g. the (non-mutable) `Set.toString` stopped compiling where it uses `enumerator` in the comprehension.
The naming scheme of the new region params in the function signatures probably needs some discussion. I've wanted to avoid calling the region var `r` as `r` is usually used as a type variable …
> refactor: add extra region paramater to functions on Array, etc. that return new Arrays etc. (issue #4962)

- main/test/ca/uwaterloo/flix/util/FlixSuite.scala
- main/test/flix/Test.Test.flix
> fix: Get @Skip annotation working in `./gradlew testAll`

- main/src/library/Array.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
As per discussion in #5131
This PR removes all calls to `regionOf` from Array.flix, apart from the one in `iterator`.
I *think* I've got this right from the POV of "functions that allocate a new data structure should take a region parameter".
I think that this is mostly uncontroversial, with the possible exception of `groupBy` which used to return arrays allocated in two different regions, and I've modified it to use a single region for the new arrays it creates.
> chore: Remove (almost) all regionOfs from Array.flix

- main/src/library/Fixpoint/Interpreter.flix
- main/src/library/Fixpoint/Solver.flix
As per #5131
I believe that these changes are correct, but I'm not sure why `evalOp` and `evalBoolExp` have two regions (`r1` and `r2`) as it seems that a single region would suffice?
> chore: Remove regionOfs from Interpreter.flix

- .github/workflows/community-build.yaml
We've gotten a lot of 403 errors recently, which may be due to rate limiting from the GitHub API.
This changes the CI to run the community builds one at a time, which may improve the odds of the API calls succeeding.
> ci: run community builds sequentially

- main/src/library/File.flix
- main/test/ca/uwaterloo/flix/library/TestFile.flix
As per #5131
This goes some way towards removing `Static` from `File.flix`, on the assumption that [this](https://github.com/flix/flix/issues/5131#issuecomment-1362754812) is correct.
I've not been able to go as far as I'd like because it turns out that Java interop doesn't know how to cope with arrays in any region other than `Static`. So I'll address that next.
> chore: Remove Static from File.flix

- main/src/library/Result.flix
- main/src/library/Validation.flix
- main/test/ca/uwaterloo/flix/library/TestResult.flix
- main/test/ca/uwaterloo/flix/library/TestValidation.flix
This PR adds `Functor`, `Applicative` and `Monad` instances to `Result` and `Functor` and `Applicative` instances to `Validation` (which doesn't have a valid implementation of `flatMap`).
Second part of three of issue #5191 "Swap type arguments of Result and Validation".
> feat: add Functor Applicative and Monad instances to Result and Validation (issue #5191)

- examples/copying-characters-into-array-with-foreach.flix
- main/src/library/Array.flix
- main/src/library/Chain.flix
- main/src/library/DelayList.flix
- main/src/library/Foldable.flix
- main/src/library/Iterable.flix
- main/src/library/Iterator.flix
- main/src/library/List.flix
- main/src/library/MutSet.flix
- main/src/library/Nec.flix
- main/src/library/Nel.flix
- main/src/library/Option.flix
- main/src/library/Result.flix
- main/src/library/Set.flix
- main/src/library/String.flix
- main/src/library/StringBuilder.flix
- main/test/ca/uwaterloo/flix/library/TestChain.flix
- main/test/ca/uwaterloo/flix/library/TestDelayList.flix
- main/test/ca/uwaterloo/flix/library/TestIterator.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestNec.flix
- main/test/ca/uwaterloo/flix/library/TestNel.flix
- main/test/ca/uwaterloo/flix/library/TestString.flix
- main/test/ca/uwaterloo/flix/library/TestStringBuilder.flix
This PR changes the argument orders of `zipWithIndex` and `enumerator` so they match `mapWithIndex` - see issue #5080
I think `zipWithIndex` with index first is a good improvement over the status quo - a list of (index, value) pairs seems consistent with how we represent other data e.g. Map (key, value) pairs rather than (value, index) pairs.
Similarly a `foreach` comprehension with an `enumerator` seems more consistent with a traditional for-loop if the loop variables are in (index, value) order.
> refactor: make zipWithIndex and enumerator consistent with mapWithIndex (issue #5080)

- main/src/library/MutMap.flix
As per #5131
I think I've got the signatures of these functions correct. The casts are necessary because the iterators need to take regions of the form `r1 and r2` (I believe)? These could be replaced with `upcast` if/when it supports casts of non-pure values.
> chore: Remove remaining uses of regionOf from MutMap

- main/src/library/DelayList.flix
Disregard the complicated title. It just keeps the `DelayList` lazy when called via `Foldable.toDelayList`.
Closes https://github.com/flix/flix/issues/5146
> refactor: return `identity` in `Foldable.toDelayList` for `DelayList`

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Chain.flix
- main/src/library/Collectable.flix
- main/src/library/Iterator.flix
- main/src/library/List.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestChain.flix
- main/test/ca/uwaterloo/flix/library/TestIterator.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestSet.flix
This PR adds a `Collectable` type class with a single function `collect` and instances for `List`, `Chain` and `Set`.
`toChain` has been added to `Iterator` and tests have been added to `TestIterator`  for `toChain` and `toList` (previously missing).
`Collectable.collect` tests are in the respective collection modules.
> feat: add Collectable type class (issue #5190)

- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
Related to #5229
This work
```
restrictable enum List[s][t] {
case Nil
case Cons(t, List[s][t])
case Cons2(t, List[s, t])
}
def head(l: List[Cons][t]): t = ???
```
> fix: change restrictable enum index from `<>` to `[]`

- main/src/library/Array.flix
- main/src/library/MutDeque.flix
- main/src/library/MutList.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestMutDeque.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
- main/test/ca/uwaterloo/flix/library/TestMutMap.flix
- main/test/ca/uwaterloo/flix/library/TestMutSet.flix
This PR adds `toString` to `MutDeque`, `MutList`, `MutMap` and `MutSet`.
It also adds `forEachWithIndex` to `MutDeque`, `MutMap` and `MutSet` (`MutList` had it already).
In `Set.flix` and `Array.flix` it removes instances of unnecessary quantification that had slipped into the `toString` functions during  `foreach` changes.
`TestMutMap` and `TestMutSet` didn't have any `forEach` tests - so some have been added as well as `toString` and `forEachWithIndex` tests.
> feat: add toString to mutable collections (issue #5214)

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
related to #5229
Fixes #5244
Only pattern like `case Tag(x...) => ...` are allowed now, and additionally, the body of `choose*` must be `Tag` or `Tag(x...)`
> feat: Add `choose` to weeder

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/ClassMaker.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenUncaughtExceptionHandlerClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmName.scala
- main/test/ca/uwaterloo/flix/language/TestFlixErrors.scala
- main/test/flix/Test.Exp.Concurrency.Spawn.flix
This is the first step towards addressing #5123 (there's more to do, but I wanted to keep the PR as small as possible).
This PR:
* Adds code to generate `UncaughtExceptionHandler`
* Modifies `Region` as discussed
* Modifies the code generated for `Scope` as discussed
* Adds a couple of tests to confirm that things work as expected
* Temporarily removes support for virtual threads (I'll reinstate in the next PR)
I'll create followup PRs to:
* Reinstate support for virtual threads
* Switch from uninterruptible to interruptible locking where appropriate
I was contemplating whether we should wrap re-thrown exceptions to make it clear that they've been re-thrown in a thread other than the one in which they originated, but this doesn't seem to be what …
> feat: Handle uncaught exceptions in spawned threads

- main/src/library/Concurrent/Channel.flix
- main/src/library/Concurrent/Condition.flix
- main/test/ca/uwaterloo/flix/language/TestFlixErrors.scala
Further towards #5123
This switches locks within the channel code to be interruptible, and adds a couple of tests which manufacture deadlock within channel code and confirm that it can be interrupted.
> fix: Use interruptible locking in Channel code

- examples/imperative-style-foreach-loops.flix
- main/test/ca/uwaterloo/flix/library/TestDelayList.flix
- main/test/ca/uwaterloo/flix/library/TestDelayMap.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestMap.flix
- main/test/ca/uwaterloo/flix/library/TestMultiMap.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
- main/test/ca/uwaterloo/flix/library/TestOption.flix
- main/test/ca/uwaterloo/flix/library/TestReducible.flix
- main/test/ca/uwaterloo/flix/library/TestSet.flix
- main/test/ca/uwaterloo/flix/library/TestString.flix
- main/test/flix/Test.Exp.Discard.flix
- main/test/flix/Test.Exp.IfThenElse.flix
- main/test/flix/Test.Exp.Let.Rec.flix
- main/test/flix/Test.Exp.Mask.flix
- main/test/flix/Test.Exp.Regions.flix
- main/test/flix/Test.Java.Function.flix
This PR changes tests and one example to use explicit regions for ref initializations where they had previously used an implicit region.
Ref initializations without explicit regions were identified with this grep (first a match grep then a not match grep). There might still be some instances the grep didn't find.
> find . -name "*.flix" | xargs grep -n " ref " | grep -v "@"
Fusion tests (`TestDelayList` / `TestDelayMap`) - I've added explicit region to all, if a test doesn't use a cast to IO I've removed IO from the type signature.
For the `__Consumer` tests in `Test.Java.Function.flix` I have unfortunately had to use the Static region to get them to compile - this seems a instance of this issue: "Java function interfaces seem to be hardcoded to use Static?" #5172
> chore: change ref initializations in tests to use explicit regions (part of issue #5215)

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/ast/Scheme.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/ClassEnvironment.scala
- main/src/ca/uwaterloo/flix/util/Validation.scala
- main/test/ca/uwaterloo/flix/util/TestValidation.scala
fixes #5377. I added an implicit extension method so that Flix.scala does not become a big mess, but I am not sure whether it is worth it.
> chore: remove flatMap from Validation

- examples/larger-examples/restrictable-variants/boolean-formulas.flix
> test: use open-as expression in example

- examples/larger-examples/restrictable-variants/boolean-formulas.flix
- examples/larger-examples/restrictable-variants/sequences.flix
- main/src/ca/uwaterloo/flix/language/phase/inference/RestrictableChooseInference.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
* `open Tag(...)` uses the schema instantiation `t -> Enum[s][targs...]` and then returns the type `Enum[s + {Tag}][targs...]`
* this means that an open tag might still have an upper bound, compared to the previous rule
* this means that for nested tags, the inner expression does not have to include the constructed label
* `Tag(...)` uses the schema instantiation `t -> Enum[{Tag}][targs...]` and returns `Enum[{Tag}][targs...]`
* This rule exist to limit type variables for non-recurse tags
* `open Tag` for non-recusive tags have no upperbound
* For non-recursive tags, `open_as Enum Enum.Tag(...)` is equivalent to `open Enum.Tag(...)`.
> feat: new restrictable tag type rule

- main/src/library/Chain.flix
- main/test/ca/uwaterloo/flix/library/TestChain.flix
This PR adds an `Order` instance to `Chain`.
`compare` is provided by a function inside the `Chain` module - `equals` already worked like this and directly implementing `compare` in the instance would be a bit ugly due to needing to use the view constructors with qualified names.
> feat: add Order instance to Chain (issue #5408)

- main/src/ca/uwaterloo/flix/language/phase/unification/CaseSetUnification.scala
Idea: minimize formulas after mkEq duplicates the formula
Its not clear that this is always beneficial, but it is for monomorphization since it instantiates all variables to ``{}` and have crazy big types representing constant sets
> feat: optimize `mkEq` in `CaseSetUnification`

- examples/larger-examples/restrictable-variants/boolean-formulas.flix
Examples taken directly from the paper
* module is required since std lib already has `Exp` defined
* #5417 is required for typing 
* #5425 is required to monomorphization
> test: update exp example

- examples/larger-examples/datalog/palindrome.flix
- main/src/library/Array.flix
- main/src/library/Console.flix
- main/src/library/File.flix
- main/src/library/List.flix
- main/src/library/MutDeque.flix
- main/src/library/String.flix
- main/src/library/Vector.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestString.flix
This PR changes `slice` functions to use named params for "start" and "end" - without named params I'd sometimes thought the params were "start" and "length" and this has caused bugs.
The String variants `sliceLeft` and `sliceRight` are also changed.
> refactor: slice functions given name parameters for start and end (issue #5393)

- main/src/library/DelayMap.flix
- main/src/library/Map.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestMutMap.flix
- main/test/ca/uwaterloo/flix/library/TestMutSet.flix
This PR adds a region into the enum for `MutSet` and `MutMap` (`MutDeque` and `MutList` carried a region already).
It also changes `TestMutSet` and `TestMutMap` to use `rc` as the region name in region blocks.
> refactor: add region to MutSet and MutMap (issue #5350)

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala
- main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala
- main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala
- main/src/ca/uwaterloo/flix/language/phase/Finalize.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/library/Vector.flix
This PR adds the `Vector` type and uses it in `Vector.flix`. Thus this brings us closer to a standalone `Vector` type.
This should enable us to write type class instances. 
The next steps would be to add compiler intrinsics for `Vector` operations to get rid of unsafe casts.
> feat: add `Vector` type

- main/src/library/Vector.flix
- main/test/ca/uwaterloo/flix/library/TestVector.flix
This PR adds instances equivalent to List to Vector and uses the Eq instance and Vector literals to clean up TestVector.
To implement `Traversable` I've added `sequence` and `traverse` to the `Vector` module. Likewise I've added `zipWithA` to Vector so it can implement `MonadZip`. The implementations of `sequence` , `traverse` and `zipWithA` are a bit "tricksy" - basically they follow the List versions except the output array exists in advance so there is no consing (the helper `putA!` replaces `consA`) but to allow "failure" for applicatives like `Option` `putA!` takes and returns an array wrapped by the applicative rather than a direct reference to the array. Using a monad could short circuit failure but it uses too much power for the method types (see issue #4540 - which I need to …
> refactor: use Vector literals in TestVector plus feat: add Vector instances (issues #5433 and #5432)

- AUTHORS.md
- main/src/library/Result.flix
- main/test/ca/uwaterloo/flix/library/TestResult.flix
Adds a `toValidation` conversion function to the flix library `Result` type (related to #5532)
(full disclosure: not sure if I flubbed the semantic commit msg format)
> feat: add `toValidation` to `Result`

- main/src/ca/uwaterloo/flix/tools/Tester.scala
Fixes #5459
This PR:
* Adds `TeeOutputStream` and uses it to both immediately output stdout and stderr, and collect the output
* Modifies `runTest` so that both stdout and stderr are printed in the event of a test failing
> fix: Test output

- main/src/library/Result.flix
- main/test/ca/uwaterloo/flix/library/TestResult.flix
This PR changes `Result.try` to catch / match on `Java.Lang.Exception` rather than `Java.Lang.RuntimeException` as `Java.Lang.Exception` is the base class of all exceptions.
As `try` is a keyword the PR changes it to `guard`. I'm open to discussion and suggestion of alternative names.
> refactor: change Result.try to catch on Java.Lang.Exception, and rename to Result.guard (issue #5465)

- .github/workflows/community-build.yaml
The community build runner now checks out the head commit of each repository, instead of getting the latest release.
This change makes it so that community build owners do not have to draft a new release every time a change is made to the Flix compiler. Instead, they can simply add a new commit to their repository.
I think this is nice as it lightens the load of maintaining a community build, and establishes a reasonable guideline for community build owners: the repo head should track Flix development head, and releases can be pinned to Flix releases (instead of halfway between two Flix releases)
> ci: use head commits for community build

- main/src/ca/uwaterloo/flix/tools/pkg/FlixPackageManager.scala
- main/test/ca/uwaterloo/flix/tools/TestFlixPackageManager.scala
Checks for cached versions of toml and fpkg files before downloading them. Also changes the names of both toml and fpkg files to be "package-version.extension" and stores them in `lib/github/user/package/version`
> feat: allow package manager to work completely offline if everything is already downloaded

- main/src/ca/uwaterloo/flix/language/phase/Reader.scala
> fix: use package name in `Reader.unpack`

- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
related to #5647. We may be able to ease this restriction later, but it keeps things simpler for now.
> refactor: reduce associated types to one argument

- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/test/flix/experimental/Test.Dec.AssocType.flix
> fix: erase types before specializing signatures in Monomorph

- main/src/ca/uwaterloo/flix/language/ast/ErasedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Eraser.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenClosureClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
Removes `ErasedAst` prefix from names in `ErasedAst`.
- Rename `ErasedAst.Expression` -> `ErasedAst.Expr`
- Rename `ErasedAst.Expression` -> `Expr`
- Rename `ErasedAst.IntrinsicOperatorX` -> `IntrinsicOperatorX`
- Rename `ErasedAst.X` -> `X`
Closes https://github.com/flix/flix/issues/5564
> refactor: shorten names in `ErasedAst`

- build.gradle
split from https://github.com/flix/flix/pull/5751
> chore: parboiled2: 2.2.1 → 2.4.1

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/MatchCompleter.scala
Fixes an issue when using auto-completion to complete a `match ...`.
Old implementation:
```
enum Color2 {
case Red, Blue, Green
}
def foo(c: Color2): Unit \ IO =
match ??? {
case Red => ???
case Blue => ???
case Green => ???
}
```
New implementation:
```
enum Color2 {
case Red, Blue, Green
}
def foo(c: Color2): Unit \ IO =
match ??? {
case Color2.Red => ???
case Color2.Blue => ???
case Color2.Green => ???
}
```
This is when the user auto-complete `match Color2`.
> fix: Provide valid pattern match in `MatchCompleter`

- main/src/ca/uwaterloo/flix/tools/Tester.scala
Add the source file name and line of a failing test to the output.
Now:
```
FAIL  testContains01
Assertion Error: Does Map contain 43?
Expected: Map#{bar => 42, foo => 12} contains 43
Actual:   Map#{bar => 42, foo => 12} does not contain 43
```
With PR:
```
FAIL  testContains01
/Users/roland/Documents/code/flix-assertions/test/TestMain.flix:182
Assertion Error: Does Map contain 43?
Expected: Map#{bar => 42, foo => 12} contains 43
Actual:   Map#{bar => 42, foo => 12} does not contain 43
```
See https://github.com/flix/flix/issues/5872
> feat: add source location to failed test output

- main/src/library/Char.flix
- main/test/ca/uwaterloo/flix/library/TestChar.flix
This PR adds numeric character conversion functions to the Char module wrapping the JDK functions:
Character.getNumericValue(char)
Character.getNumericValue(int)
Character.digit 
Character.forDigit
See issue #5891
These functions operate on chars that can represent numeric values (e.g. '1' => 1) they are not general char to integer conversions.
> feat: add wrappers to the JDK functions getNumericValue, digit and forDigit (issue #5891)

- main/src/library/Regex.flix
- main/test/ca/uwaterloo/flix/library/TestRegex.flix
This PR addresses issue #5882 and adds more functions to Regex particularly to extract matched strings rather than indices of the match and to match within a range of the input string.
Functions added to extra matched text:
~~~
pub def getPrefix(substr: {substr = Regex}, s: String): Option[String]
pub def getSuffix(substr: {substr = Regex}, s: String): Option[String]
pub def getFirst(substr: {substr = Regex}, s: String): Option[String]
pub def getLast(substr: {substr = Regex}, s: String): Option[String]
pub def getFirstWithOffset(substr: {substr = Regex}, offset: {offset = Int32}, s: String): Option[String]
pub def getLastWithOffset(substr: {substr = Regex}, offset: {offset = Int32}, s: String): Option[String]
~~~
`getPrefix` is the content version of `startsWith`
`getSufffix` is the …
> feat: add more functions to Regex (issue #5882)

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
https://github.com/flix/flix/issues/5919
> fix: Removes unnecessary `()` for enum tags

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
fixes https://github.com/flix/flix/pull/5920 and https://github.com/flix/flix/issues/5919
> fix: Remove unnecessary `()` for enum tags

- main/src/library/String.flix
There are a few typos in the comments of `String.flix` where `"`s are used instead of `` ` ``.
> chore: fix typos ` -> " in comments

- main/src/library/String.flix
- main/test/ca/uwaterloo/flix/library/TestString.flix
This adds `String.stripMargin` which is a wrapper for `String.stripMarginWith`.
> feat: add String.stripMargin

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/util/Validation.scala
- main/src/library/Array.flix
- main/src/library/Choice.flix
- main/src/library/Iterator.flix
- main/src/library/MutDeque.flix
- main/src/library/MutList.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/src/library/StringBuilder.flix
- main/test/ca/uwaterloo/flix/language/phase/TestInstances.scala
- main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
- main/test/flix/Test.Kind.Class.flix
This removes the `and` syntax from the parser. `+` now means `and`, and `&` means `or`. 
After this PR we should be able to re-enable most of the disabled tests,
> chore: unify effect set syntax

- main/src/ca/uwaterloo/flix/runtime/shell/Command.scala
- main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
I understood this to include the command itself as well: `:doc / :d` -> `:info / :i`
Fixes #5918
> chore: rename `Command.Doc` to `Command.Info`

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
Also, hopefully, makes `and` & `or` faster :rocket: :crossed_fingers: 
Closes https://github.com/flix/flix/issues/5853
> refactor: use 1 label in `BoolOp.And` and `BoolOp.Or` byte code

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
> fix: Lowered priority and removed dot snippet when choosing the `ModCompletion`

- main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/SimplifiedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
After loweredAst, defs store their full type, i.e. `def f(x: Int32): Int32 \ Impure` stores the type `Int32 -> Int32 \ Impure`. This means that code that needs either purity or the return type needs to unsafely destruct the expected arrow type. 
This PR extracts the return type and the purity of the def, since the parameter types are already known form the formal parameters. 
I've asserted that, for all tests, this new implied type (reconstructing it from the formal parameters and the new fields) and the old type is identical. 
The purity should be `Purity` instead of `Type` but monomorph doesn't actually guarantee that at the moment
> refactor: destruct simplified def type

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/BoolUnification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/SimpleBoolFormulaAlgClassic.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/SimpleBoolUnification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/src/library/Choice.flix
- main/src/library/File.flix
- main/src/library/Iterator.flix
- main/src/library/Prelude.flix
- main/src/library/System.flix
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
The names are not great. I propose we follow up:
- rename `BoolUnification` to `EffUnification`
- rename `SimpleBoolUnification` to `BinaryUnification` or something like that. `Bool` is just too overloaded.
This copy-pastes a lot from `BoolUnification`. We should be able to generalize the implementation eventually.
> feat: create separate unification path for Bool kind

- main/src/ca/uwaterloo/flix/Main.scala
> fix: use stdout for packager logging

- build.gradle
Release flag had to be added manually, additional context https://github.com/gradle/gradle/issues/23962
Related
https://github.com/flix/flix/pull/4896
https://github.com/flix/flix/pull/4916
https://github.com/flix/flix/pull/4896#issuecomment-1509886116
```
time ./gradlew clean jar                   Wed 07 Jun 2023 06:26:25 PM CST
> Task :clean
> Task :compileJava NO-SOURCE
> Task :compileScala
Unexpected javac output: warning: [options] system modules path not set in conjunction with -source 11
1 warning.
> Task :processResources NO-SOURCE
> Task :classes
> Task :jar
BUILD SUCCESSFUL in 1m 7s
3 actionable tasks: 3 executed
________________________________________________________
Executed in   68.28 secs    fish           external
usr time    1.39 secs    0.00 micros    1.39 secs
sys time …
```
> chore: scala: 2.13.5 → 2.13.11

- build.gradle
From 3.5.5 (2019-06-08) to 3.6.12 (2021-11-05)
From
```
+--- org.json4s:json4s-native_2.13:3.5.5
|    +--- org.scala-lang:scala-library:2.13.0 -> 2.13.11
|    \--- org.json4s:json4s-core_2.13:3.5.5
|         +--- org.scala-lang:scala-library:2.13.0 -> 2.13.11
|         +--- org.json4s:json4s-ast_2.13:3.5.5
|         |    \--- org.scala-lang:scala-library:2.13.0 -> 2.13.11
|         +--- org.json4s:json4s-scalap_2.13:3.5.5
|         |    \--- org.scala-lang:scala-library:2.13.0 -> 2.13.11
|         +--- com.thoughtworks.paranamer:paranamer:2.8
|         \--- org.scala-lang.modules:scala-xml_2.13:1.2.0 -> 2.1.0
|              \--- org.scala-lang:scala-library:2.13.8 -> 2.13.11
```
To
```
+--- org.json4s:json4s-native_2.13:3.6.12
|    +--- org.scala-lang:scala-library:2.13.7 -> 2.13.11
| …
```
> chore: json4s: 3.5.5 → 3.6.12

- build.gradle
From 4.0.1 (2021-05-13) to 4.1.0 (2022-07-02)
From
```
+--- com.github.scopt:scopt_2.13:4.0.1
|    \--- org.scala-lang:scala-library:2.13.4 -> 2.13.11
```
To
```
+--- com.github.scopt:scopt_2.13:4.1.0
|    \--- org.scala-lang:scala-library:2.13.8 -> 2.13.11
```
> chore: scopt: 4.0.1 → 4.1.0

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/LoweredAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Regions.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/src/ca/uwaterloo/flix/language/phase/Statistics.scala
- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
- main/src/ca/uwaterloo/flix/language/phase/inference/RestrictableChooseInference.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/ChoiceMatch.scala
It is consistently confusing that the rules are called "Choice" but the expression is called "Choose".
> chore: rename *Choice* to *Choose*

- main/src/ca/uwaterloo/flix/api/Flix.scala
This means that you automatically get the asts in `build/asts` and you also get a `crash_report_i.txt`
> feat: handle verifier errors

- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
The only place where we have nullary lambdas/defs is these two places as far as I can see. This causes problems with the new def return type rep.
> fix: avoid nullary functions

- main/src/ca/uwaterloo/flix/language/ast/ErasedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Eraser.scala
- main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/ClosureInfo.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenClosureClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- Remove `ClosureInfo` (and their collection) and instead generate closures based on the `cparams` of defs
- Ensure that `cparams` for closures are always non-empty by adding a unit cparam if it is.
- Another option is to actually separate closures/defs with a flag or a new case class, in which case it would be okay to have empty cparams
Metrics
- 8 % decrease in code size (from the clarification of closures vs defs)
- performance of eraser/backend seems slightly faster, hard to say
- Might slow down flix runtime a little with the added unit args
> refactor: remove ClosureInfo

- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
- main/src/ca/uwaterloo/flix/language/fmt/FormatEff.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
fixes #6083. I wanted to do something prettier, but a combination of us not having set effects anymore and annoyances I am blaming on the escaping region bug covinced me to take this lazy approach.
> chore: rename effect-poly error to effectful error

- main/src/ca/uwaterloo/flix/language/ast/MonoType.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/MonoTypePrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/MonoTyper.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
Because of #5867, vars are now never present
> refactor: remove MonoType.Var

- main/src/ca/uwaterloo/flix/language/phase/MonoTyper.scala
Because of #5867 erase aliases are guaranteed to be absent
* remove eraseAliases in MonoTyper
* remove unused variables
* private privately used defs
> refactor: remove eraseAliases in MonoTyper

- main/src/ca/uwaterloo/flix/language/ast/ReducedAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/ReducedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/MonoTyper.scala
- main/src/ca/uwaterloo/flix/language/phase/Reducer.scala
I've noted that the purity is unused on defs in SimplifiedAst, LiftedAst/OccurrenceAst, and ReducedAst. It is then erased in MonoTypedAst. The optimizer uses the def calls to look at purity, not looking at the definition itself.
Should we remove this unused purity information on defs or keep it around? In my opinion, it seems sensible to store it. It might be important for implementing handlers at some point.  Do you have input @mlutze?
> refactor: ReducedAst def return type

- main/src/ca/uwaterloo/flix/tools/pkg/Dependency.scala
- main/src/ca/uwaterloo/flix/tools/pkg/ManifestParser.scala
- main/src/ca/uwaterloo/flix/tools/pkg/MavenPackageManager.scala
- main/test/ca/uwaterloo/flix/tools/TestManifestParser.scala
This PR relaxes the Packager so `MavenDependency` now parses the version number of a Maven package dependency a just as `String` and not a `SemVer`. Maven (the repository) does not enforce adherence to SemVars so the Packager has to be relaxed about what it parses. 
I've reordered the tests in `TestManifestParser.scala` so it looks like there are a lot of changes but really this is just changing the Maven dependency parsing examples to "Ok" tests as they no longer fail when the tag is not a strict `SemVer`.
> fix: packager - relax MavenDependency versionTag to just String (issue #6155)

- main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala
> refactor: fix `Expression.Resume` case in `ClosureConv`

- main/src/ca/uwaterloo/flix/language/ast/LiftedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/OccurrenceAst.scala
- main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/DocAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/LiftedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/SimplifiedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala
- main/src/ca/uwaterloo/flix/language/phase/Inliner.scala
- main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala
- main/src/ca/uwaterloo/flix/language/phase/LateTreeShaker.scala
- main/src/ca/uwaterloo/flix/language/phase/OccurrenceAnalyzer.scala
- main/src/ca/uwaterloo/flix/language/phase/Reducer.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
Related to https://github.com/flix/flix/issues/6112
Related to https://github.com/flix/flix/issues/6109
Closes https://github.com/flix/flix/issues/6110
> refactor: move `HoleError` and `MatchError` exps to ApplyAtomic case

- main/src/ca/uwaterloo/flix/language/dbg/DocAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/DocAstFormatter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/ErasedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/LiftedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/LoweredAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/MonoTypedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/OpPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/ReducedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/SimplifiedAstPrinter.scala
* changed the DocAst.Def to have the return type directly
* Removed the `DocAst.Expression.fromAtomic` function since its a duplicate function to `OpPrinter.print`, sorry for the confusing namespaces jakob (note: debug printers should not throw!)
> refactor: `DocAst` contain ret type directly

- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/CaseSetUnification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/EffUnification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/UnificationError.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
fixes #6066
```
❌ -- Type Error --------------------------------------------------
>> Unable to unify the Boolean formulas: 'true' and 'false'.
152 | def test02(): Bool = mkTrue() == mkNot(mkTrue())
^^^^^^^^^^^^^^^^^^^^^^^^^^^
mismatched Boolean formulas.
Type One: A[true] -> (A[true] -> Bool)
Type Two: A[true] -> (A[false] -> Bool)
```
> feat: add specific boolean unification errors

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
May require a thorough review. There are some expressions I'm unsure about. For instance, is `NewObject` failable? It should have been type checked, so no runtime should happen.
Closes https://github.com/flix/flix/issues/5852
> refactor: add `addSourceLine` in `GenExpression` before failable exprs

- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
> fix: traverse argument types properly in Typer

- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/flix/Test.Exp.Record.Polymorphism.flix
I don't know if this was intentional, but this is currently allowed:
```scala
pub def main(): Unit \ IO =
let p = { pub = 125, def = 1284, let = 22 };
println(p.pub);
println(p.def);
println(p.let)
```
This PR makes the compiler throw a `WeederError` when using reserved words. Note that Scala disallows reserved words for fields in (case) classes, too.
> refactor: check valid field name in records

- main/src/ca/uwaterloo/flix/language/ast/ErasedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ReducedAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/ErasedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/ReducedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/Eraser.scala
- main/src/ca/uwaterloo/flix/language/phase/Reducer.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/AnonClassInfo.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenAnonymousClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
This splits `JvmMethod` into two: `JvmMethodSpec` and `JvmMethodImpl`. 
Now `NewObject` depends on `JvmMethodImpl`, whereas `anonClasses` uses `JvmMethodSpec`.
This is in preparation for removal of the `ErasedAst` phase.
> refactor: rework `JvmMethod`

- main/src/ca/uwaterloo/flix/api/lsp/provider/ShowAstProvider.scala
Fixes this problem:
```
// Eraser.flixir
Unknown phase: 'Eraser'. Try one of these 'Parser', 'Weeder', 'Kinder', 'Resolver', 'TypedAst', 'Documentor', 'Lowering', 'EarlyTreeShaker', 'Monomorph', 'MonomorphEnums', 'Simplifier', 'ClosureConv', 'LambdaLift', 'Tailrec', 'Optimizer', 'LateTreeShaker', 'Reducer', 'VarNumbering', 'MonoTyper', 'Eraser'
```
> fix: show proper error message when requesting to show WIP phases

- main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
Proposes quickfix to derive type classes (`Eq`, `Order`, `ToString`) for enums when trying to do something that depends on them.
> feat: add quickfix to derive missing type classes

- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
Adds additional checks for `RedundancyError.ShadowingName` in tests that already check for `RedundancyError.ShadowedName`.
@mlutze - thanks! - suggested these changes in https://github.com/flix/flix/pull/6279#issuecomment-1649020296.
> test: also check for RedundancyError.ShadowingName in relevant TestRedundancy.scala tests

- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
Should make debugging faster. related to #6300
> chore: shorten toString for Ast.Source

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Adaptor.flix
- main/test/ca/uwaterloo/flix/library/TestAdaptor.flix
This PR adds a module `Adaptor` for marshaling between Flix and Java.
Currently it just covers collection marshaling as per sub issues #6332 and #6333. 
Iterators - I've actually implemented `fromIterator` rather than `toIterator`, i.e. make a Flix Iterator from a Java one. Java Iterators have a (`hasNext`, `next`) API whereas Flix iterators have just a `next` API (which the return type being Option - None shows the iterator is finished). I think its possible to make a Java iterator from a Flix one with a one element buffer but it would be rather involved so I haven't look at it so far.
Marshaling collection elements (not the collection itself) is currently done with casting this means we can't have numbers and chars in collections (Java overcomes this with object types for prim types …
> feat: add Adaptor module (issue #6331)

- main/src/ca/uwaterloo/flix/language/ast/MonoType.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/MonoTypePrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
Small mistakes / smells that I spotted when working on the code. This PR changes the following:
- `MonoType.{SchemaEmpty, RecordEmpty}` are now case objects instead of case classes with empty constructors
- Helper functions in `Simplifier` were public. They are now marked as private.
> style: mark functions as private & remove redundant constructors

- main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
> feat: don't show ` \ Pure` in HTML docs

- main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
- main/src/resources/doc/styles.css
Displayed in the upper left hand corner
I think it would be great to add a logo here too.
Related to #6327
> feat: display version in HTML documentation

- main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala
I was looking into #6290 but @jaschdoc scooped me 😅 which is totally fine, since I was mostly trying to learn how it works anyway. I did find a few smaller things that seems worth fixing so opening a pull request here.
(Also if people don't mind me asking - what's a good reference for how that phase works? I am reading through [Warnings for pattern matching](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/3165B75113781E2431E3856972940347/S0956796807006223a.pdf/warnings-for-pattern-matching.pdf) which is referenced in the comments, and it still seems like fairly accurate?
> chore: cleanup documentation and unused variable in PatternExhaustiveness

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Chain.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/Nec.flix
- main/src/library/Nel.flix
- main/src/library/Prelude.flix
- main/src/library/Set.flix
- main/src/library/ToJava.flix
- main/src/library/Vector.flix
- main/test/ca/uwaterloo/flix/library/TestToJava.flix
This PR adds the `ToJava` class from issue #6348 and several collection instances.
I think the only contentious instance is for (Flix) Vector which goes to ##java.util.List. Java's ##java.util.Vector would have been an alternative but Vector seems disfavoured in Java now and is not used so much as an argument or a result in API calls.
> feat: add ToJava class (issue #6348)

- main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
> chore: write out name of 'Operations' in HTML documentation

- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
- Cleaned up comments, collected gen into sensible chunks
- Improved the `link` method to fail fast when the method doesn't exist
- Improved the naming of some functions
> refactor: clean up JvmBackend

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BytecodeInstructions.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
From the example code:
```
// TODO: Implement other reverse function.
Frames reverse() { ... }
```
I don't know what the TODO means and `reverse` is actually unused since `Handler` uses `reverseOnto` directly.
Frames:
```java
package dev.flix.runtime;
public interface Frames {
Frames push(Frame var1);
Frames reverse();
Frames reverseOnto(Frames var1);
}
```
FramesCons:
```java
package dev.flix.runtime;
public final class FramesCons implements Frames {
public final Frame head;
public final Frames tail;
public FramesCons() {
}
public final Frames push(Frame var1) {
FramesCons var10000 = new FramesCons();
var10000.head = var1;
var10000.tail = this;
return var10000;
}
public final Frames reverse() {
return this.reverseOnto(new FramesNil());
}
public final Frames reverseOnto(Frames var1) { …
```
> feat: gen Frames FramesCons and FramesNil

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/api/Bootstrap.scala
`Build` `Run` and `Test` did not respect the given options. Just using default options.
This means that they forget the github key, and just breaks with `--entrypoint Company.run`
> fix: use options in all commands

- main/src/ca/uwaterloo/flix/language/ast/MonoType.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/MonoTypePrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Verifier.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
Why does this type have a special name compared to everywhere else in the compiler?
> style: rename `MonoType.Str` -> `MonoType.String`

- main/src/ca/uwaterloo/flix/language/ast/Token.scala
- main/src/ca/uwaterloo/flix/language/ast/TokenErrorKind.scala
- main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala
- main/src/ca/uwaterloo/flix/language/errors/LexerError.scala
- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
Write a `LexerError` type for compilation messages when lexing fails.
> feat: Add `LexerError` as a new type of `CompilationMessage`

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
It was marked as a comment instead of a doc comment.
> docs: update documentation for `GenExpression.addSourceLine`

- main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
- main/src/resources/doc/styles.css
All files should now pass the https://validator.w3.org/nu/ validator.
Maybe it should be included in the test suite?
> fix: validation errors in HTML documentation

- examples/file-information.flix
- examples/working-with-files-and-directories.flix
- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Files.flix
- main/test/ca/uwaterloo/flix/library/TestFiles.flix
This PR renames `File` to `Files`. It is a prelude to adding a new `File` module.
This PR breaks some of the community-builds.
> refactor: rename stdlib module File to Files

- main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala
Some token names were changed to make sure similar tokens are colocated when sorting alphabetically. These are:
- `*Keyword` becomes `Keyword*`. ie. `KeywordIf`
- `*Comment` becomes `Comment*`. 
- `*Name` becomes `Name*`. 
- `*Hole` becomes `Hole*`. 
A nice side-effect is that now editor suggestions work neatly. For instance `Name` suggests the different kinds of names available, making it easy to browse and select.
> feat: add `TokenKind` for new lexer

- main/src/library/Char.flix
- main/src/library/Float32.flix
- main/src/library/Float64.flix
- main/src/library/Int16.flix
- main/src/library/Int32.flix
- main/src/library/Int64.flix
- main/src/library/Int8.flix
- main/test/ca/uwaterloo/flix/library/TestChar.flix
- main/test/ca/uwaterloo/flix/library/TestFloat32.flix
- main/test/ca/uwaterloo/flix/library/TestFloat64.flix
- main/test/ca/uwaterloo/flix/library/TestInt16.flix
- main/test/ca/uwaterloo/flix/library/TestInt32.flix
- main/test/ca/uwaterloo/flix/library/TestInt64.flix
- main/test/ca/uwaterloo/flix/library/TestInt8.flix
See issue #6426 
This PR add conversion functions to Char and the primitive number types to convert them to and from their Java corresponding Java objects. Converting to Java objects is necessary to store them in generic collections from `java.util` that can only store objects and not primitive types. 
`BigInt` and `BigDecimal` are not primitive types so don't need these conversion functions.
Possible design issues: 
1. Maybe these functions should go in `Adaptor`, though they would need name changes to distinguish the types.
2. If they stay in the current modules, maybe they should diverge from the Java naming for for `charValue`, `byteValue` etc.
Potential work todo - I haven't used the new `valueOf` functions at other places in their respective modules that are already importing and …
> feat: add conversion functions for Char and the number types to/from their Java object versions (issue #6426)

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala
Fixes #6025 
...which is caused by incorrectly adding surrounding parentheses for Enum tags. From the commit history it seems that the intended logic correct but the implementation isn't ([comment](https://github.com/flix/flix/pull/5977/commits/dfe95cdfc76a5e1c0aa92f91e7d4ded1a429a397#r1197611912)).
This changes the logic so that instead of looking at the type of the arguments, we just look at the arity and would only add parentheses when arity is 1.
Screenshot -
> fix: single argument enum tag display bug in LSP completion

- main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
> fix: recurse in `filterItems` in HTML documentation

- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
Fixes #6465
This is also a fun use case for boolean phantom types (end with optWS Yes/No and is optional Yes/No)
> fix: class signature doc parsing

- main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
Before, nested classes, enums and effects would result in a 404.
> fix: module recursion bug in HTML documentation

- main/src/library/Files.flix
- main/src/library/IOError.flix
This PR changes `Files.flix` to use `IOError` for failure and adds more class derivings to the `IOError` type. `TestFiles.flix` did not need updating.
In `Files`, functions with simple control flow (no internal reference to `Ok` / `Err`) I've changed to use IOError.tryCatch otherwise I've kept the implementations the same.
> refactor: change Files.flix to use IOError on failure (issue ##6501)

- main/src/library/Map.flix
I found this quite confusing when reading the docs, since the equality character is meant as a comparison and not an assignment / binding. So I think when reading code docs, it's better to have consistency between the syntax of the language and the meaning of the docs.
> docs: fix ambiguity in `Map.empty`

- main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/src/ca/uwaterloo/flix/language/phase/Statistics.scala
- main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala
- main/test/flix/Test.Exp.TypeMatch.flix
I thought we did this already, but looks like some cases were missed.
> refactor: rename MatchType to TypeMatch throughout compiler

- main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
> fix: differentiate uses of item's name and qualified name in HTML documentation

- main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
Before, empty enum cases would be displayed like `case Empty(Unit)`, whereas now it's just `case Empty`.
> fix: display empty enum cases correctly in HTML documentation

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
This PR makes the `Lexer` able to reuse tokens from sources that are still fresh when the compiler is run incrementally.
> feat: use `ChangeSet` in `Lexer`

- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
Creates a `ParserInput` to be used in a `SourceLocation` when spawning `LexerErrors`.
The program `def f(): String = "${"` gives these errors for instance:
```
-- Lexer Error -------------------------------------------------- foo.flix
>> Missing '}' in string interpolation.
1 | def f(): String = "${"
^
Interpolation starts here.
-- Lexer Error -------------------------------------------------- foo.flix
>> missing '"' in string.
1 | def f(): String = "${"
^
String starts here.
```
> fix: Show source code in `LexerError`s

- main/test/ca/uwaterloo/flix/library/TestFile.flix
This PR updates TestFile.flix to write `outfile01.bin` to the temp directory identified by `Environment.getTemporaryDirectory` rather than the `{tests-path}/library/testdata` folder as was reported on Flightdeck.
As far as I can tell the answer from `Environment.getTemporaryDirectory` is already suffixed with a path separator so we don't need to add one directly.
Not done / should I do? - I don't delete `outfile01.bin` at the end of the tests. Should I write a test at the end of the file that does this?
> fix: make TestFile.flix use the temp directory for creating outfile01.bin

- .editorconfig
As Intellij says "Spaces are allowed in the file pattern but it may be a typo"
> chore: fix `.editorconfig` typo

- main/src/resources/doc/styles.css
The values are identical, so it's just for maintainability
> fix: missing CSS variable overrides in HTML documentation

- main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala
- main/src/ca/uwaterloo/flix/util/ParOps.scala
> refactor: rename `ParOps.mapValues` to `ParOps.parMapValues`

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/KeywordOtherCompleter.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
This PR updates the completions in `KeywordOtherCompleter` and the set of reserved words in `Weeder` to recognize the new `trait` keyword.
Part of the work on rename `class` to `trait` issue #6591 .
> refactor: update KeywordOtherCompleter and Weeder to recognize `trait` keyword

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/KeywordOtherCompleter.scala
- main/src/ca/uwaterloo/flix/language/ast/LiftedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/OccurrenceAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ReducedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Inliner.scala
- main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala
- main/src/ca/uwaterloo/flix/language/phase/OccurrenceAnalyzer.scala
- main/src/ca/uwaterloo/flix/language/phase/Reducer.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- `try a with b` generates code `a`
- `resume(...)` generates code `throw null`
- `do ...` generates code `()`
- I've copied the analyser/inliner code from `tryCatch` so `tryWith` should also work, given that the previous code works?
> feat: add effect defs and operations to backend

- .github/workflows/build.yaml
- .github/workflows/community-build.yaml
- .github/workflows/jar-on-demand.yaml
- .github/workflows/semantic-commit.yaml
I found several actions still depend on old major releases, so I suggest updating them in batch.
I've confirmed that all workflows work fine with these fixes:
- [Compiler Tests](https://github.com/KengoTODA/flix/actions/runs/6705975929)
- [Community Build](https://github.com/KengoTODA/flix/actions/runs/6705975928)
- [Semantic Commit Message](https://github.com/KengoTODA/flix/actions/runs/6705975941)
- [JAR on Demand](https://github.com/KengoTODA/flix/actions/runs/6706049488)
> chore: update GitHub actions to the latest major release for security

- main/src/ca/uwaterloo/flix/tools/BenchmarkCompilerOld.scala
- main/src/ca/uwaterloo/flix/tools/SimpleRunner.scala
This is to make space for a new implementation.
> refactor: rename `BenchmarkCompiler`

- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
This PR adds two things:
1. Checks sub expressions of for loops before throwing potential errors
2. Checks that for loops do not begin with `if`
> feat: check loop fragments do no start with `if`

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/phase/PatMatch.scala
(This will make it easier to print graphs with phase names).
> chore: rename `PatternExhaustiveness` to `PatMatch`

- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
This PR also has these other changes
- Rewrites Deref to follow same style as other cases
- Uses `.` for `map` method call instead of space
> feat: use recoverOne in for-loops

- main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/src/ca/uwaterloo/flix/language/phase/TreeShaker1.scala
- main/src/ca/uwaterloo/flix/language/phase/TreeShaker2.scala
- main/src/ca/uwaterloo/flix/language/phase/TypeInference.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/util/ParOps.scala
> refactor: rename `ParOps` functions.

- main/src/ca/uwaterloo/flix/language/phase/TypeInference.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/flix/Test.Exp.Effect.flix
- main/test/flix/Test.Exp.TryWith.flix
Fixes #6642
```
eff MyEffect {
pub def yield(x: Int32): Unit
}
def main(): Int32 = {
try {
let x = 42;
do MyEffect.yield(1);
let y = 13;
do MyEffect.yield(1);
x + y
} with MyEffect {
def yield(x, rr) = rr() + x
}
}
```
- `resume` still exists as a keyword and ast node
- usability is bad, if you just write `yield(rr)` in the handler above, you get a type error with unknown location
> feat: add resumption argument to effect handlers

- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
Instead of converted it to a full type first (which is more work and requires more implicits) just do erasure instantly
> refactor: improve `JvmOps.getErasedJvmType`

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
Compile-time crash on the use of the explicit `resume` operation, instead of run-time crash
> feat: crash on `resume`

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenEffectClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmType.scala
An effect class like this:
```
eff SomeEffect {
pub def flip(): Bool
pub def add(x: Int32, y: Int32): Int32
}
```
Is conceptually understood as (`Resumption` is a backend interface):
```
eff SomeEffect {
pub def flip(unit: Unit, cont: Resumption): Value
pub def add(x: Int32, y: Int32, cont: Resumption): Value
}
```
and is generated like so:
```
public final class Eff$SomeEffect implements Handler {
public Fn2$Obj$Obj flip
public Fn3$Int32$Int32&Obj add
}
```
> feat: Generate Effect classes

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
It adds a lot of bytes of code and the code still fails fast since there is a cast to `Value` immediately following the suspension check
> feat: remove suspension exceptions

- main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala
Like done with NewObject, equally as non-type-preserving
> feat: Convert handlers to closures

- main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala
- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
Amazingly I forgot these tokens in the initial push for the lexer.
> feat: Add `TokenKind.BangEqual` and `TokenKind.ArrowThin` 

- main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala
- main/src/ca/uwaterloo/flix/language/errors/LexerError.scala
- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
- main/test/ca/uwaterloo/flix/language/phase/TestLexer.scala
Lex regex literals such as `regex"{Alpha}"`
> feat: Lex regex literals

- main/src/ca/uwaterloo/flix/language/errors/RedundancyError.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/util/collection/ListMap.scala
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
- Introduce `LocalContext`
- Introduce `SharedContex`
- Drop `IllegalSingleVariable` (but see #6724)
- Drop support for restrictable variants.
> refactor: introduce `LocalContext` and `SharedContext` in `Redundancy`

- main/src/ca/uwaterloo/flix/language/phase/Reducer.scala
Should be faster, because of the removed flatMap
> refactor: make `nestedTypesOf` tail recursive

- main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala
- Eliminate unused errors.
- Rename errors to be more precise.
- Update documentation.
- Re-order to be alphabetical.
> refactor: cleanup `SafetyError`

- main/src/ca/uwaterloo/flix/api/lsp/provider/ShowAstProvider.scala
- main/src/ca/uwaterloo/flix/language/phase/EffectBinder.scala
A compromise between a simple let-binder and a clever solution. We let bind everything, but complexity is added since, when looking at the body of a top-level let-binding (`let x = e1; e2`) we don't want to let-bind the outermost structure of `e1`.
This last small optimization is about a 2x decrease in let-binders and avoid the type issues with regions and the bug with if-statements generated from pattern matches.
> feat: make effects stack-less

- main/src/ca/uwaterloo/flix/language/phase/EffectBinder.scala
- main/test/flix/Test.Exp.Binary.Logic.flix
fixes  #6813
And and Or use shortcircuiting which was not represented in the translation. luckily, in the code gen for these operations, the right operand is not on the stack when the left operand is evaluated, so translation is like an if-statement.
I've verified that no tests crash, but some still fail, probably due to https://github.com/mlutze/flix-json/issues/75
> fix: correct bool-op shortcircuit handling

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenFunAndClosureClasses.scala
The newFrame is unchagned for a given function
> refactor: move newFrame to MethodContext

- main/src/ca/uwaterloo/flix/language/ast/Token.scala
- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
This PR adds convenient conversions from a `Token` to `SourcePosition`, both at the start and end of the token, as well as a conversion into `SouceLocation`
> feat: convert `Token` to `SourcePosition` and `SourceLocation`

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenTagClasses.scala
The backend uses `instanceof` so nothing uses the string tag
> fix: remove unused generated `<Case>.getTag` method

- main/src/ca/uwaterloo/flix/language/ast/ReducedAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/ReducedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/EffectBinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Reducer.scala
In order to have pc labels in the backend we need to precompute them, which means knowing the number of points where the continuation will be captured (PC points).
> feat: count pc points

- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/dbg/DocAst.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenFunAndClosureClasses.scala
Instead of magic `+1`s all around, its a number stored in the method argument and is required in `var.getStackOffset(localOffset)`
This means that genexpression is not hardcoded to a specific context (an instance method without actual jvm arguments)
This PR also changes the `+1` to `+2` since the value argument added for arguments were not accounted for.
> refactor: local offset argumet

- main/src/ca/uwaterloo/flix/language/phase/Reducer.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenEffectClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
* `ResumptionWrapper` is a helper calls to make a `Resumption` a callable function in flix protocol
* `Effect.op` functions are unused, but will be used to generate code in try-with
* Reducer now also looks for types in effects (this is needed now since the above functions assume the existence of some function interfaces)
From the docs:
```java
eff SomeEffect {
pub def flip(unit: Unit, cont: Bool -> Result): Value
pub def add(x: Int32, y: Int32, cont: Int32 -> Result): Value
}
```
is generated like so:
```java
public final class Eff$SomeEffect implements Handler {
public Fn2$Obj$Obj$Obj flip;
public Fn3$Int32$Int32&Obj$Obj add;
public static EffectCall flip(Object var0, Handler h, Resumption r) {
Fn2$Obj$Obj$Obj f = ((Eff$SomeEffect) h).flip;
f.arg0 = var0;
f.arg1 = new …
```
> feat: backend effect functions

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenFunAndClosureClasses.scala
- getUniqueThreadClosure and copy now both copy all fields of the closure
I don't think its safe anymore to copy only the closure arguments. Do can now extract a closure at any point and all the fields might matter. This is perhaps too defensive but lets do correct first
> fix: make closure copy a full copy

- main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
> chore: rename 'class' to 'trait' in HTML documentation

- main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
Should be redundant when using panic mode
> refactor: disable safe mode in documentation parsing

- main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
Fixes #6918
This just escapes all `&amp;` instances once, but it should actually just be done inside code blocks.
This means that outside of code blocks, writing `&` and `&amp;` will both just result in a `&`, but I hope that's acceptable for now.
> fix: escaping of doc comments

- main/src/resources/doc/styles.css
When changing the references in the HTML, some CSS selectors became invalid. 
I've gone ahead and changed the internal variables as well.
> fix: change 'class' to 'trait' in CSS for HTML documentation

- main/src/ca/uwaterloo/flix/language/dbg/AstPrinter.scala
> refactor: use `FileOps` in `AstPrinter.writeToDisk`

- main/src/ca/uwaterloo/flix/language/phase/Eraser.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- tuple unpacking
- Record unpacking
- lazy unpacking
- function call
> feat: move more casts to `Eraser`

- main/src/ca/uwaterloo/flix/language/ast/MonoType.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/MonoTypePrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/Reducer.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
Fixes #6963.
Not removed from DocAst since it will be used by the frontend at some point
> refactor: remove schemas in backend

- main/src/ca/uwaterloo/flix/language/phase/jvm/AsmOps.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BytecodeLoader.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/ClassMaker.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/FlixClassLoader.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenAnonymousClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenClosureAbstractClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenEffectClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenEnumInterfaces.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenFunAndClosureClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenLazyClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenMainClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenNamespaceClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenTagClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenTupleClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
- remove unused implicits 
- removed unused parameters
- removed unused pattern match variables
- remove unused imports
- inline simple methods with one occurance
> refactor: clean up jvm code

- .github/workflows/community-build.yaml
- AUTHORS.md
- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/api/Bootstrap.scala
- main/src/ca/uwaterloo/flix/tools/SimpleRunner.scala
- main/src/ca/uwaterloo/flix/tools/pkg/ReleaseError.scala
- main/src/ca/uwaterloo/flix/util/Options.scala
Resolves #6973
- renamed the command line option from `--github-key` to `--github-token`
- renamed the field `githubKey` to `githubToken` in `Options` and `CmdOpts` classes
> refactor: rename `--github-key` to `--github-token`

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
It incorrectly called `Thunk.invoke` first before checking, even though it should accept any result
> fix: `unwindThunk`

- main/src/ca/uwaterloo/flix/util/Validation.scala
- main/test/ca/uwaterloo/flix/util/TestValidation.scala
Introduces `toSoftResult` & `toHardResult`.
Related to https://github.com/flix/flix/pull/6912
> feat: split Validation.toResult

- main/src/ca/uwaterloo/flix/tools/SocketServer.scala
- main/src/ca/uwaterloo/flix/util/Validation.scala
- main/src/ca/uwaterloo/flix/util/collection/Chain.scala
- main/test/ca/uwaterloo/flix/util/TestChain.scala
Depends on https://github.com/flix/flix/pull/7008
Related to https://github.com/flix/flix/issues/6989
> refactor: remove `Iterable` dependency in `Chain`

- main/src/ca/uwaterloo/flix/language/phase/TypeInference.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/test/flix/Test.Exp.Effect.flix
The new type rule permits multiple effects:
```scala
eff Gen {
pub def gen(x: Int32): Unit
}
eff Print {
pub def print(x: String): Unit
}
def generator(x: Int32): Unit \ Gen + Print =
do Gen.gen(x); do Print.print("abc"); generator(x + 1)
def sample(limit: Int32): List[Int32] \ Print =
try {
generator(0); Nil
} with Gen {
def gen(x, k) = if (x == limit) Nil else x :: k()
}
def main(): Unit \ IO =
try {
println(sample(4))
} with Print {
def print(x, k) = { println(x); k() }
}
```
I know its incomplete (i.e. it rejects programs with polymorphic handlers), but I am not sure if it is unsound. 
Possibly it could be sound still.
In any case, this is just a temporary measure while we wait for sets :)
> feat: new type rule for `try-with`

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/ShowAstProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/LiftedAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/AstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/LiftedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/EffectBinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Eraser.scala
- main/src/ca/uwaterloo/flix/language/phase/Inliner.scala
- main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala
- main/src/ca/uwaterloo/flix/language/phase/Reducer.scala
Related to #7011
This avoids the maintenance of the local parameters and moves it before the eraser
The pcPoints will be removed form Lifted again in the next PR where EffectBinder will introduce ReducedAst instead of Reducer
> refactor: Move EffectBinder before Reducer

- main/src/ca/uwaterloo/flix/language/ast/ReducedAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/ReducedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/EffectBinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Reducer.scala
- main/src/ca/uwaterloo/flix/language/phase/VarOffsets.scala
- main/src/ca/uwaterloo/flix/language/phase/Verifier.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenAnonymousClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenFunAndClosureClasses.scala
Related to #7011
Stmt is removed from ReducedAst and expressions are handled consistently in JvmMethod
> refactor: Align Lifted and Reduced Ast

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
field name and rest type is irrelevant for the generated class and were unused
> refactor: simplify record extend backend type

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenAnonymousClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenEffectClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
The logic is duplicated in JvmOps and BackendObjectType so now its not
> refactor: clean up `getFunctionInterfaceType`

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/ShowAstProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/LiftedAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/AstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/LiftedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/EffectBinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Eraser.scala
- main/src/ca/uwaterloo/flix/language/phase/Inliner.scala
- main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala
- main/src/ca/uwaterloo/flix/language/phase/Reducer.scala
What does this achieve? good question
- Effect Binder introduces pcPoints to defs, which means that LiftedAst now doesn't have to know about that
- Reducer still introduces lparams, root.types, and root.anonclasses. So an argument can be made that reducedAst should be split into two
Could be really cool to have polymorphic records here
> refactor: move ReducedAst up two phases

- main/src/ca/uwaterloo/flix/api/lsp/Index.scala
- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
The existing pattern in Indexer:
```
idx1 = ...
idx2 = ...
idx1 ++ idx2 ++ ...
```
is clunky and error-prone.
It is easy to forget to `++` something at the end, and any time we add or remove a field, we have to change the indices.
This new system solves both of those.
If this is deemed reasonable, then I'd like to do the same thing in SemanticTokensProvider.
> refactor: get rid of indexed indices in Indexer

- examples/larger-examples/program-analysis/IDE.flix
Looking through historical code, it seems this stems from a typo in an early Flix implementation of this example. An old implementation had this:
(case <(NonBotTrans <a1 b1 c2>) (NonBotTrans <a2 b2 c2>)>
(if (== 0 (% (- b1 b2) (- a2 a1)))
// is divisible
(NonBotTrans <a1 b2 (lub (Cst (+ (* a1 (/ (- b1 b2) (- a2 a1))) b1)) (lub c1 c2))>)
// is not divisible
(NonBotTrans <1 0 Top>)
)
)
Notice that this should not have even compiled back then, since it references variable c1, which is not even bound. The typo there was that NonBotTrans <a1 b1 c2> should have been NonBotTrans <a1 b1 c1>. The spurious requirement that c1 == c2 was probably added during the translation of that code with the typo to modern Flix.
> fix: join implementation in IDE example

- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
White space is not allowed in `unchecked_cast` between the opening parenthesis and the inner expression. This PR fixes that bug.
```scala
unchecked_cast(    { ... } as _ \ {}) // notice the white space
```
is now allowed.
> fix: allow whitespace in `unchecked_cast`

- .github/workflows/build.yaml
- .github/workflows/community-build.yaml
- .github/workflows/jar-on-demand.yaml
Bumps major version of GitHub Actions to non-deprecated version.
- `actions/upload-artifact` to `v4`
- `actions/download-artifact` to `v4`
- `actions/setup-java` to `v4`
Currently we get the following warnings:
Build workflow:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-java@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
Community build workflow:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-java@v3, actions/download-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
> chore: bump github actions versions

- main/src/ca/uwaterloo/flix/runtime/shell/ShellParser.scala
Parsed is now more conformant with what JLine expects.
Tested \\\\ for multi-line statements still works as before.
> fix: update repl's Parsed class so tab won't crash repl (#7214)

- main/src/ca/uwaterloo/flix/language/errors/LexerError.scala
An error for bad number literals like  `12e12e10`.
> feat: Add LexerError.DoubleEInNumber

- main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala
- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
When parsing the standard library a number of missing `TokenKind` s where discovered.
> feat: Add missing `TokenKind`s

- examples/larger-examples/restrictable-variants/boolean-formulas.flix
- examples/larger-examples/restrictable-variants/colors.flix
- examples/larger-examples/restrictable-variants/sequences.flix
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/flix/Test.Def.ChooseStar.Simple.flix
- main/test/flix/Test.Exp.Choose.Polymorphic.flix
- main/test/flix/Test.Exp.Choose.Recursive.flix
- main/test/flix/Test.Exp.Choose.Simple.flix
- main/test/flix/Test.Exp.Choose.SimpleTerms.flix
- main/test/flix/Test.Exp.ChooseStar.Polymorphic.flix
- main/test/flix/Test.Exp.ChooseStar.Simple.flix
Fixes #7222
* `open` -> `open_variant`
* `open_as` -> `open_variant_as`
> feat: rename `open` and `open_as`

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/ast/MonoAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/AstPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/MonoDefs.scala
- main/src/ca/uwaterloo/flix/language/phase/MonoTypes.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
Fixes  #7167
This PR is pure refactoring
* MonoDefs was `Lowered -> Lowered` and is now `Lowered -> MonoAst`
* MonoTypes was `Lowered -> Lowered` and is now `MonoAst -> MonoAst`
* Simplifier was `Lowered -> Simplified` and is now `MonoAst -> Simplified`
* MonoAst is copied from LoweredAst but I've removed things that MonoDefs set to empty (like instances fx)
* The only extra work is that MonoDefs traverses effects now, which was arguably a bug it didn't before
The idea is that in a followup PR, monotypes and monodefs can be merged and monoAst will then contain monotypes
a followup PR is also needed to prettyprint MonoAst
> refactor: add MonoAst

- main/src/ca/uwaterloo/flix/language/dbg/AstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/DocAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/DocAstFormatter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/TypedAstPrinter.scala
This PR doesn't fix everything:
- Some expressions are not pretty printed (just printing as unknown)
- effects are largely ignored
- only defs and enums are pretty printed
But all the things that can be done "for free" have been added - better than nothing and a stepping stone onward
> feat: pretty print `TypedAst`

- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
> chore: rename 'args' to 'exps' in front-end ASTs

- main/src/ca/uwaterloo/flix/api/lsp/provider/ShowAstProvider.scala
When you ask for the print of Ast `MattIsCool` it currently gives you `MattIsCool.flixir` with some AST instead of `realName.flixir`. This PR fixes that
> feat: return actual phase name

- main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
Fixes #7333
Note that there is still a cast, but its only for the type when the effect is IO
> feat: avoid redundant `IO` cast on import
