flix/flix

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/language/ast/PropertyError.scala
- main/src/ca/uwaterloo/flix/language/ast/package.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/runtime/debugger/RestServer.scala
- main/src/ca/uwaterloo/flix/util/ConsoleCtx.scala
- main/test/ca/uwaterloo/flix/runtime/TestDeltaSolver.scala
> Added support for multiline error reporting.

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/ast/ExecutableAst.scala
- main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala
- main/src/ca/uwaterloo/flix/language/phase/Codegen.scala
- main/src/ca/uwaterloo/flix/language/phase/CreateExecutableAst.scala
- main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala
- main/src/ca/uwaterloo/flix/language/phase/LoadBytecode.scala
- main/src/ca/uwaterloo/flix/language/phase/Tailrec.scala
- main/src/ca/uwaterloo/flix/language/phase/VarNumbering.scala
- main/src/ca/uwaterloo/flix/runtime/Interpreter.scala
- main/src/ca/uwaterloo/flix/runtime/evaluator/SymbolicEvaluator.scala
- main/test/ca/uwaterloo/flix/language/phase/PhaseSuite.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTailrec.scala
See #157 
- Needs code review.
- Refactoring + Cleanup.
- More tests.
> Add support for tail recursion.

- main/src/library/BigInt.flix
- main/src/library/Float32.flix
- main/src/library/Float64.flix
- main/src/library/Int16.flix
- main/src/library/Int64.flix
- main/src/library/Int8.flix
- main/test/ca/uwaterloo/flix/library/TestBigInt.scala
- main/test/ca/uwaterloo/flix/library/TestFloat32.scala
- main/test/ca/uwaterloo/flix/library/TestFloat64.scala
- main/test/ca/uwaterloo/flix/library/TestInt16.scala
- main/test/ca/uwaterloo/flix/library/TestInt32.scala
- main/test/ca/uwaterloo/flix/library/TestInt64.scala
- main/test/ca/uwaterloo/flix/library/TestInt8.scala
- Added library for Int64 along with corresponding tests
- Cleaned up some functionality for Int32
- Int16, Int8, BigInt, etc.  to follow
> Libraries for Int8, Int16, Int64, BigInt, Float32, Float64

- main/src/library/BigInt.flix
- main/src/library/Float32.flix
- main/src/library/Float64.flix
- main/src/library/Int16.flix
- main/src/library/Int32.flix
- main/src/library/Int64.flix
- main/src/library/Int8.flix
- Replaced "/* */" comments with "///" comments for documentation purposes.
- Fixed some typos/errors.
- All library tests pass.
> Fixed library function comments.

- main/src/library/List.flix
- main/test/ca/uwaterloo/flix/library/TestList.scala
> List Library WIP

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/ast/package.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/Unification.scala
- main/src/ca/uwaterloo/flix/runtime/debugger/RestServer.scala
- main/test/ca/uwaterloo/flix/library/TestList.scala
- main/test/ca/uwaterloo/flix/library/TestOption.scala
- main/test/ca/uwaterloo/flix/library/TestResult.scala
- main/test/ca/uwaterloo/flix/util/FlixTest.scala
> Issue 259 monomorphization

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
> Added support for if-guards in pattern matching.

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/phase/Disambiguation.scala
- main/src/ca/uwaterloo/flix/util/Options.scala
- main/test/ca/uwaterloo/flix/TestExamples.scala
- main/test/ca/uwaterloo/flix/TestMain.scala
- main/test/ca/uwaterloo/flix/TestTutorials.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
- main/test/ca/uwaterloo/flix/library/TestOption.scala
- main/test/ca/uwaterloo/flix/library/TestResult.scala
- main/test/ca/uwaterloo/flix/util/FlixTest.scala
> Added -Xcore flag.

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/CreateExecutableAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala
> Replaced Fact and Rule by Constraint.

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
> Fixes #337

- main/src/ca/uwaterloo/flix/language/ast/ExecutableAst.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/CreateExecutableAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Indexer.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/runtime/Interpreter.scala
- main/src/ca/uwaterloo/flix/runtime/Solver.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
> Refactored body predicates to use patterns.

- main/src/ca/uwaterloo/flix/language/phase/Codegen.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/test/ca/uwaterloo/flix/util/FlixTest.scala
> Fixed issue #350.

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/runtime/Benchmarker.scala
- main/src/ca/uwaterloo/flix/runtime/Model.scala
- main/src/resources/benchmark/BenchmarkList.flix
- main/test/ca/uwaterloo/flix/TestMain.scala
> Added initial implementation of benchmark tool.

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/runtime/Model.scala
- main/src/ca/uwaterloo/flix/util/RpcServer.scala
- main/test/ca/uwaterloo/flix/TestMain.scala
The following PR adds minimal support for invocation of the compiler and runtime via a JSON RPC call. The purpose is to allow Flix to be invoked from a website.
> Add RPC Server

- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/library/Prelude.flix
> Issue 385 equality

- main/src/library/Float32.flix
- main/src/library/Float64.flix
- main/test/ca/uwaterloo/flix/library/TestFloat32.flix
- main/test/ca/uwaterloo/flix/library/TestFloat64.flix
- Addressed Library Review for Float Types (https://github.com/flix/flix/issues/368)
> Addressed Library Review: Float Types

- main/src/library/Prelude.flix
- main/test/ca/uwaterloo/flix/library/TestPrelude.flix
- Addressed Library Review for Prelude.flix (https://github.com/flix/flix/issues/366)
> Library Review: Prelude

- main/src/library/Option.flix
- main/src/library/Result.flix
- main/test/ca/uwaterloo/flix/library/TestOption.flix
- main/test/ca/uwaterloo/flix/library/TestResult.flix
- Addressed Library Review for Option and Result Types (https://github.com/flix/flix/issues/370 and https://github.com/flix/flix/issues/367)
> Library Review: Option and Result Types

- main/src/library/List.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- Addressed Library Review for List (https://github.com/flix/flix/issues/382)
> Library Review: List

- main/src/library/List.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestSet.flix
- Addressed Set Library Review (https://github.com/flix/flix/issues/373)
> Set Library Review

- main/src/library/BigInt.flix
- main/src/library/Int16.flix
- main/src/library/Int32.flix
- main/src/library/Int64.flix
- main/src/library/Int8.flix
- main/test/ca/uwaterloo/flix/library/TestBigInt.flix
- main/test/ca/uwaterloo/flix/library/TestInt16.flix
- main/test/ca/uwaterloo/flix/library/TestInt32.flix
- main/test/ca/uwaterloo/flix/library/TestInt64.flix
- main/test/ca/uwaterloo/flix/library/TestInt8.flix
- Addressed Library Review for Int Types (https://github.com/flix/flix/issues/375)
> Library Review: Int Types

- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestMap.flix
- main/test/ca/uwaterloo/flix/library/TestSet.flix
- Addressed Map Library Review (https://github.com/flix/flix/issues/374)
> Map Library Review

- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/Option.flix
- main/src/library/Result.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestMap.flix
- main/test/ca/uwaterloo/flix/library/TestOption.flix
- main/test/ca/uwaterloo/flix/library/TestResult.flix
- main/test/ca/uwaterloo/flix/library/TestSet.flix
- Addressed https://github.com/flix/flix/issues/381
> Replace Functionality

- main/src/ca/uwaterloo/flix/language/phase/TreeShaker.scala
- Address "TreeShaker should consider Property" (https://github.com/flix/flix/issues/418)
> Handle Property Searching

- main/src/ca/uwaterloo/flix/language/ast/ExecutableAst.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/debug/PrettyPrinter.scala
- main/src/ca/uwaterloo/flix/language/errors/NameError.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala
- main/src/ca/uwaterloo/flix/language/phase/Codegen.scala
- main/src/ca/uwaterloo/flix/language/phase/CreateExecutableAst.scala
- main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala
- main/src/ca/uwaterloo/flix/language/phase/LoadBytecode.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/TreeShaker.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/VarNumbering.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/runtime/Interpreter.scala
- main/src/ca/uwaterloo/flix/runtime/evaluator/SymbolicEvaluator.scala
- main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
> Add support for native constructors.

- build.xml
- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/runtime/library/Console.java
- main/src/library/Console.flix
> Added implementation of Console.

- main/src/ca/uwaterloo/flix/language/ast/ExecutableAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/phase/Codegen.scala
- main/src/ca/uwaterloo/flix/language/phase/LoadBytecode.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/Unification.scala
- main/src/ca/uwaterloo/flix/runtime/Interpreter.scala
- main/src/ca/uwaterloo/flix/runtime/evaluator/SymbolicEvaluator.scala
> Added references to the ExecutableAst.

- .gitignore
- AUTHORS.md
- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/ast/package.scala
- main/src/ca/uwaterloo/flix/language/errors/ExhaustiveMatchError.scala
- main/src/ca/uwaterloo/flix/language/errors/NonExhaustiveMatchError.scala
- main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala
- main/src/ca/uwaterloo/flix/runtime/debugger/RestServer.scala
- main/src/library/List.flix
- main/src/tutorials/interpreter.flix
- main/src/tutorials/lambda-calculus-promises.flix
- main/test/ca/uwaterloo/flix/language/phase/PhaseSuite.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
- main/test/ca/uwaterloo/flix/language/phase/TestPatExhaustiveness.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/ca/uwaterloo/flix/runtime/TestBackend.scala
It's not quite done, but it's passing some basic tests now (the ones included), and I figured if I'm going to start prettying it up, I should get some feedback before I go too far. I suspect my code is not particularly idiomatic Scala.
There's still quiet a bit left to do:
- Fix the error message
- Thoughly test it
- Add the useless pattern check(?)
- Fix all the tests that broke due to non exhaustive patterns
> Pattern Matching

- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala
- main/src/ca/uwaterloo/flix/language/phase/CreateExecutableAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
- main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/VarNumbering.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
> Add Inline Keyword

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
> Support Lambdas with Type Parameters.

- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/util/ParOps.scala
> Parallelize the typer.

- main/src/ca/uwaterloo/flix/language/errors/StratificationError.scala
- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/runtime/Solver.scala
- main/test/ca/uwaterloo/flix/language/feature/FeatureSuite.scala
- main/test/ca/uwaterloo/flix/language/feature/TestStratifiedNegation.flix
- main/test/ca/uwaterloo/flix/language/phase/PhaseSuite.scala
- main/test/ca/uwaterloo/flix/language/phase/TestStratifier.scala
PRing this more as a check-in rather than a PR.
I've implemented a simple graph structure/adjacency list and a check for negative cycles. It _seems_ to work for the very basic test cases that I have, but to be frank, I don't know enough about the logic side of Flix to come up with anything more complex -- I'll bring that up in the Flix meeting tomorrow.
The graph and algorithm are ... very imperative and could probably be cleaned up to be more functional.
> Stratification

- main/src/ca/uwaterloo/flix/language/ast/ExecutableAst.scala
- main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/debug/PrettyPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala
- main/src/ca/uwaterloo/flix/language/phase/CodeGen.scala
- main/src/ca/uwaterloo/flix/language/phase/CodegenHelper.scala
- main/src/ca/uwaterloo/flix/language/phase/CreateExecutableAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Inliner.scala
- main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala
- main/src/ca/uwaterloo/flix/language/phase/Optimizer.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/TreeShaker.scala
- main/src/ca/uwaterloo/flix/language/phase/TupleGen.scala
- main/src/ca/uwaterloo/flix/language/phase/Uncurrier.scala
- main/src/ca/uwaterloo/flix/language/phase/VarNumbering.scala
- main/src/ca/uwaterloo/flix/runtime/Interpreter.scala
- main/src/ca/uwaterloo/flix/runtime/Linker.scala
- main/src/ca/uwaterloo/flix/runtime/evaluator/SymbolicEvaluator.scala
- main/src/ca/uwaterloo/flix/runtime/quickchecker/QuickChecker.scala
- main/src/ca/uwaterloo/flix/runtime/verifier/Verifier.scala
> Added Block and Jump to ASTs.

- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
The stratifier was ignoring non atoms. It now handles them properly. This should fix #560.
I'm not sure how to test this though. Is there a way to have a test stop after a given phase and make assertions?
I can show that in the debugger, running the sample program in #560 that rules 2-4 are put in the 3rd Stratum.
> Fix Stratification of Non Atoms

- main/src/ca/uwaterloo/flix/language/phase/jvm/AsmOps.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenContext.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenContinuationInterfaces.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenFunctionInterfaces.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenNamespaces.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmName.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmType.scala
So far, I have implemented GenContext, GenContinuationInterfaces, GenNamespaces and GenFunctionInterfaces.     
These are obviously not tested since JvmOps isn't fully implemented.
> JvmBackend implementation 

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenClosureClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenFunctionClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenNamespaces.scala
I changed the code so that the stack is as empty as possible before calls.
No OSR in the generated bytecode.
> Fixing the issue with OSR

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/runtime/shell/Command.scala
- main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
- main/src/ca/uwaterloo/flix/runtime/verifier/Verifier.scala
> Added :verify command

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/runtime/solver/datastore/IndexedRelation.scala
- main/test/ca/uwaterloo/flix/language/feature/FeatureSuite.scala
- main/test/ca/uwaterloo/flix/language/feature/Test.Predicate.Nullary.flix
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
See #714 
This allows nullary relations and lattices.
> Generalize True and False

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/util/Validation.scala
- main/test/ca/uwaterloo/flix/language/feature/FeatureSuite.scala
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.Record.Extend.flix
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.Record.Literal.flix
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.Record.Multiple.flix
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.Record.Polymorphism.flix
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.Record.Restrict.flix
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.Record.Select.flix
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.Record.Update.flix
- main/test/ca/uwaterloo/flix/util/TestValidation.scala
> Improve Record Syntax

- main/src/ca/uwaterloo/flix/language/ast/MonoType.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
- main/src/ca/uwaterloo/flix/language/phase/Finalize.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Unification.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
- main/src/ca/uwaterloo/flix/util/Validation.scala
- main/src/library/Prelude.flix
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.Constraint.flix
> Row Polymorphic Schema

- main/src/ca/uwaterloo/flix/api/Version.scala
- main/src/ca/uwaterloo/flix/runtime/interpreter/Channel.java
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.PutChannel.flix
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.SelectChannel.flix
Fixed issue #722.
Implemented unbuffered channels to allow synchronous communication between processes.
> Unbuffered channels

- main/src/flix/runtime/fixpoint/ConstraintSystem.java
- main/src/flix/runtime/fixpoint/predicate/AtomPredicate.java
- main/src/flix/runtime/fixpoint/symbol/LatSym.java
- main/src/flix/runtime/fixpoint/symbol/RelSym.java
> Improved toString of ConstraintSystem.

- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/test/ca/uwaterloo/flix/language/feature/TestNativeCall.flix
This partially addresses #798.
> Infer return types for native methods

- main/src/ca/uwaterloo/flix/language/phase/Synthesize.scala
- main/src/ca/uwaterloo/flix/language/phase/TreeShaker.scala
> Improvements to Tree Shaker

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
- main/src/library/BigInt.flix
- main/src/library/Char.flix
- main/src/library/Console.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/Option.flix
- main/src/library/Prelude.flix
- main/src/library/Result.flix
- main/src/library/Set.flix
> Tidy up the Standard Library

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/flix/channel/Channel.flix
- main/test/ca/uwaterloo/flix/library/TestChannel.flix
> Added Channel to Standard Library

- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
- main/src/ca/uwaterloo/flix/language/phase/Unification.scala
> Gracefully reported mismatched arity in types

- AUTHORS.md
- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/flix/runtime/library/MonoStringBuilder.java
- main/src/flix/runtime/library/StringBuilderWrapper.java
- main/src/library/String.flix
- main/src/library/StringBuilder.flix
- main/test/ca/uwaterloo/flix/library/LibrarySuite.scala
- main/test/ca/uwaterloo/flix/library/TestStr.flix
- main/test/ca/uwaterloo/flix/library/TestStringBuilder.flix
Hi Magnus, here is the pull request for review.
> String builder

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.BigInt.flix
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.Int.flix
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.Int16.flix
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.Int32.flix
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.Int64.flix
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.Int8.flix
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
Replacing https://github.com/flix/flix/pull/996 since it didn't like working with the squashed commit.
> Int Radices

- main/src/library/Array.flix
- main/src/library/List.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
This pull request replaces - Array additions #1031
Hi Magnus - I've done some of the simple changes:
+ Added my name to the copyright notices
+ Put TestArray in a namespace.
+ Reformatted various if-expressions, removing parens if they have a single line "else" expression and spacing some one-liner if-expressions onto multiple lines.
+ Moved the "base case" to the "then" part rather than the "else" part of several if-expressions.
+ Made `head` and `last` Impure.
I haven't started on making the other "queries" like `memberOf` Impure - I think I understood what you said about "equal under substitution" but I'll need to check.
> Array additions2

- main/src/library/Array.flix
- main/src/library/StringBuilder.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestStringBuilder.flix
Hi Magnus - here are the `StringBuilder` name changes.
This includes the new implementation of `StringBuilder.append!`.
I've also included `appendLineWith!` `appendLines!` and `appendLinesWith!` that have been written for the String Additions changes. I'm happy to remove them and resubmit them with the String changes if you just want a "minimum" pull request.
Array depends on StringBuilder so the `Array.flix` and `TestArray.flix` files have changed.
> StringBuilder - name changes for the 'great renaming'

- main/src/library/Option.flix
- main/src/library/Result.flix
- main/src/library/Validation.flix
- main/test/ca/uwaterloo/flix/library/TestOption.flix
- main/test/ca/uwaterloo/flix/library/TestResult.flix
- main/test/ca/uwaterloo/flix/library/TestValidation.flix
Hi Magnus 
Here are the lifters for Option, Result and Validation. Plus `toErr` etc. on Option.
> Liftn functions for Option, Result and Validation

- .travis.yml
- main/src/library/Float32.flix
- main/src/library/Float64.flix
- main/src/library/String.flix
- main/test/ca/uwaterloo/flix/library/TestFloat32.flix
- main/test/ca/uwaterloo/flix/library/TestFloat64.flix
- main/test/ca/uwaterloo/flix/library/TestString.flix
I have temporarily removed:
- String.indent (#1083)
- String.stripIndent (#1083)
- Float32.toDecimalString (#1086)
- Float64.toDecimalString (#1086)
> Fix Build with Java 11

- AUTHORS.md
- main/src/library/List.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
Adds a function to conveniently remove the last element from a List
> Add init function to List

- main/src/library/Core/Io/File.flix
- main/test/ca/uwaterloo/flix/library/Core/Io/TestFile.flix
I think this is already done. A few helper functions to ease usage of the module
> Add helper functions to `File`

- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
- main/src/ca/uwaterloo/flix/language/CompilationError.scala
- main/src/ca/uwaterloo/flix/language/errors/LinterError.scala
- main/src/ca/uwaterloo/flix/language/errors/NameError.scala
- main/src/ca/uwaterloo/flix/language/errors/NonExhaustiveMatchError.scala
- main/src/ca/uwaterloo/flix/language/errors/ParseError.scala
- main/src/ca/uwaterloo/flix/language/errors/PropertyError.scala
- main/src/ca/uwaterloo/flix/language/errors/RedundancyError.scala
- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala
- main/src/ca/uwaterloo/flix/language/errors/StratificationError.scala
- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
> LSP Error Messages

- main/src/library/Prelude.flix
- main/src/resources/benchmark/BenchmarkList.flix
> Remove assert, assertNot, and assertEq

- build.gradle
> Fix Gradle Path Issue

- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
> Disallow `length` field name

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala
- main/src/ca/uwaterloo/flix/language/debug/FormatExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/Linter.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Synthesize.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/tools/BenchmarkCompiler.scala
- main/test/flix/LangSuite.scala
- main/test/flix/Test.Exp.Null.flix
- main/test/flix/Test.Exp.NullMatch.flix
> Add Null Match

- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
> fix unconditional recursion check

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Finalize.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Synthesize.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/flix/Test.Typ.Gen.Bool.Null.flix
> Keep Nullable into the Resolver

- main/src/ca/uwaterloo/flix/language/ast/SemanticOperator.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
> Add Semantic Operator for EqNull

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/flix/Test.Exp.Null.Nullify.flix
- main/test/flix/Test.Typ.Gen.Bool.Null.flix
> Nullable Syntax

- main/src/ca/uwaterloo/flix/language/phase/unification/BoolUnification.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
> Ensure Rigidity of Boolean Type Variables

- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/library/Prelude.flix
- main/test/flix/Test.Eff.Advanced.flix
- main/test/flix/Test.Typ.Gen.Bool.Null.flix
> Unify the Syntax of Boolean Effects and Nullity

- main/src/ca/uwaterloo/flix/language/debug/FormatType.scala
- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
- main/src/ca/uwaterloo/flix/language/phase/Linter.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/BoolUnification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/UnificationError.scala
- main/test/ca/uwaterloo/flix/language/debug/TestFormatType.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/ca/uwaterloo/flix/language/phase/unification/TestUnification.scala
> Rename unifyEffM, etc.

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/BoolUnification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/src/ca/uwaterloo/flix/tools/SocketServer.scala
- main/src/ca/uwaterloo/flix/util/Options.scala
- main/test/ca/uwaterloo/flix/TestMain.scala
> Rename --Xno-effects to --Xno-bool-unification

- main/src/library/Nel.flix
Fixes #1087. The only file with missing effect annotations was Nel.flix.
> Ensure fold, reduce and scan functions are effect polymorphic

- main/src/library/Array.flix
- main/src/library/BigInt.flix
- main/src/library/Bool.flix
- main/src/library/Char.flix
- main/src/library/Float32.flix
- main/src/library/Float64.flix
- main/src/library/Int16.flix
- main/src/library/Int32.flix
- main/src/library/Int64.flix
- main/src/library/Int8.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/Nel.flix
- main/src/library/Option.flix
- main/src/library/Prelude.flix
- main/src/library/RedBlackTree.flix
- main/src/library/Result.flix
- main/src/library/Set.flix
- main/src/library/String.flix
- main/src/library/Validation.flix
> Add complexity annotations to std. library

- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
> kind-check type ascriptions

- main/src/library/Core/Io/File.flix
Fixes https://github.com/flix/flix/issues/1309
> make File.readAll tail-recursive

- main/src/library/List.flix
> make List.append and List._eq tail-recursive

- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
- main/src/ca/uwaterloo/flix/api/lsp/Request.scala
> LSP Request id from Int to String

- main/src/library/Map.flix
- main/src/library/Set.flix
> Rename toMutable -> toMut

- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
> Fix #1335: Exit LSP with status code on exception

- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
- main/src/ca/uwaterloo/flix/api/lsp/Request.scala
> Add api/version

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Array.flix
- main/src/library/List.flix
- main/src/library/MutList.flix
- main/test/ca/uwaterloo/flix/library/LibrarySuite.scala
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
#1035
A mutable list similar to java.util.ArrayList.
> MutList implementation

- main/src/ca/uwaterloo/flix/api/lsp/Entity.scala
- main/src/ca/uwaterloo/flix/api/lsp/Index.scala
- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
> Index Formal Params

- main/src/ca/uwaterloo/flix/api/lsp/Index.scala
- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
> LSP: Distinguish enums and tags

- main/src/ca/uwaterloo/flix/api/lsp/Entity.scala
- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
> Add support for tags to lsp/hover and lsp/uses

- main/src/ca/uwaterloo/flix/api/lsp/Entity.scala
- main/src/ca/uwaterloo/flix/api/lsp/Index.scala
- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
> Added support for find references for enums

- main/src/ca/uwaterloo/flix/api/lsp/Entity.scala
- main/src/ca/uwaterloo/flix/api/lsp/Index.scala
- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
Partially fixes #1357. Works for let, but not select.
> Partial Fix #1357

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala
- main/test/flix/Test.Use.Def.flix
- main/test/flix/Test.Use.Tag.flix
- main/test/flix/Test.Use.Type.flix
> allow uses in namespaces

- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
- main/src/ca/uwaterloo/flix/api/lsp/Request.scala
- main/src/ca/uwaterloo/flix/api/lsp/TextEdit.scala
- main/src/ca/uwaterloo/flix/api/lsp/WorkspaceEdit.scala
> LSP: Rename Defs and Local Variables

- main/src/ca/uwaterloo/flix/api/lsp/DocumentHighlight.scala
- main/src/ca/uwaterloo/flix/api/lsp/DocumentHighlightKind.scala
- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
- main/src/ca/uwaterloo/flix/api/lsp/Request.scala
> LSP: Add Document Highlight Support

- main/src/ca/uwaterloo/flix/api/lsp/Diagnostic.scala
- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
> LSP: Print to Standard Error

- .github/workflows/build.yaml
> Add pull_request to GitHub Workflow

- main/src/ca/uwaterloo/flix/api/lsp/Entity.scala
- main/src/ca/uwaterloo/flix/api/lsp/Index.scala
- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/FindReferencesProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/GotoProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala
> Improvements to Highlight

- main/src/ca/uwaterloo/flix/language/errors/NameError.scala
- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
> LSP: Improve support for errors with multiple source locations

- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/library/Choice.flix
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
> Introduce Choice Data Type, Part VII

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/tools/Packager.scala
- main/src/ca/uwaterloo/flix/tools/Tester.scala
Not sure if this is the best way to do this.
I'm also not sure how best to test this. How do you create the jar from Intellij?
> exit 1 on test failure

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Core/Cmp/Ordering.flix
- main/src/library/Map.flix
- main/src/library/MutList.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/src/library/RedBlackTree.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestMap.flix
- main/test/ca/uwaterloo/flix/library/TestSet.flix
Add {Set/Map}.query methods implemented on RedBlackTree.
Fixes #1305.
> Add query method

- main/src/ca/uwaterloo/flix/language/phase/Synthesize.scala
> Add SynthesisError

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Optimizer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/tools/BenchmarkCompiler.scala
- main/src/library/Core/FromString.flix
- main/src/library/Core/ToString.flix
- main/test/ca/uwaterloo/flix/library/TestToString.flix
- main/test/flix/LangSuite.scala
- main/test/flix/Test.Exp.Interpolation.flix
> Use ToString in Interpolation

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/errors/NameError.scala
- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/library/Core/FromString.flix
- main/src/library/Core/ToString.flix
- main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala
- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/ca/uwaterloo/flix/library/TestFromString.flix
- main/test/ca/uwaterloo/flix/library/TestToString.flix
- main/test/flix/LangSuite.scala
- main/test/flix/Test.Dec.Class.flix
- main/test/flix/Test.Exp.Infix.flix
- main/test/flix/Test.Exp.Interpolation.flix
- main/test/flix/Test.Use.Sig.flix
Addresses signatures for https://github.com/flix/flix/issues/1489
> Improve Scoping of Signatures

- examples/using-laziness-for-infinite-streams.flix
- examples/using-laziness-for-logging.flix
- examples/using-laziness-to-compute-fibonacci.flix
- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/LazyList.flix
- main/src/library/LazyList2.flix
- main/test/ca/uwaterloo/flix/TestExamples.scala
- main/test/ca/uwaterloo/flix/library/LibrarySuite.scala
- main/test/ca/uwaterloo/flix/library/TestLazyList.flix
Fixes #1395.
Defined functions:
- empty
- repeat
- from
- isEmpty
- length
- head
- last
- append
- reverse
- take
- drop
- tail
- toList
- fold
- foldLeft
- foldRight
- exists
- forall
- map
- filter
- unfold
- zipWith
- zip
- __eq
> Add LazyList

- main/src/ca/uwaterloo/flix/language/ast/Scheme.scala
- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/ClassEnvironment.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/UnificationError.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
fixes https://github.com/flix/flix/issues/1552
> Add Specific TypeError for Missing Type Classes

- main/src/ca/uwaterloo/flix/language/errors/InstanceError.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/test/ca/uwaterloo/flix/language/phase/TestInstances.scala
Part of https://github.com/flix/flix/issues/1558
> Check for complex instances

- main/src/library/BigInt.flix
- main/src/library/Char.flix
- main/src/library/Float32.flix
- main/src/library/Float64.flix
- main/src/library/Int16.flix
- main/src/library/Int32.flix
- main/src/library/Int64.flix
- main/src/library/Int8.flix
- main/src/library/ToString.flix
> Refactor ToString instances

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/library/Add.flix
- main/src/library/Div.flix
- main/src/library/Mul.flix
- main/src/library/Sub.flix
- main/src/tutorials/introduction.flix
- main/test/ca/uwaterloo/flix/TestTutorials.scala
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/flix/LangSuite.scala
- main/test/flix/Test.Exp.Interpolation.flix
> Add intrinsics and type classes for Add, Sub and Div

- examples/analysis/IDE.flix
- examples/analysis/SUopt.flix
- examples/domains/Constant.flix
- examples/fixpoint-computations-on-lattices.flix
- examples/misc/FloydWarshall.flix
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/library/PartialOrder.flix
- main/src/tutorials/introduction.flix
Adds lattice constraints for Datalog constraints with a lattice interpretation.
> Add Lattice Constraints for Datalog Constraints

- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
fixes https://github.com/flix/flix/issues/1603
> Add sealed modifier for classes

- main/src/library/Hash.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/Nel.flix
- main/src/library/Option.flix
- main/src/library/Result.flix
- main/src/library/Set.flix
- main/src/library/Validation.flix
- main/test/ca/uwaterloo/flix/library/TestHash.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestMap.flix
- main/test/ca/uwaterloo/flix/library/TestNel.flix
- main/test/ca/uwaterloo/flix/library/TestOption.flix
- main/test/ca/uwaterloo/flix/library/TestResult.flix
- main/test/ca/uwaterloo/flix/library/TestSet.flix
- main/test/ca/uwaterloo/flix/library/TestValidation.flix
> Refactor hash type class instances and tests

- main/src/library/Array.flix
- main/src/library/ToString.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestToString.flix
> Make ToString[Array] independent of std. lib

- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
As per https://github.com/flix/flix/issues/1586#issuecomment-751760737
> Rewrite boolean operators as semantic operators

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/errors/NameError.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala
- main/test/flix/Test.Dec.Class.flix
fixes https://github.com/flix/flix/issues/1575
depends on https://github.com/flix/flix/pull/1577
> Remove 'use class' syntax.

- main/src/library/Array.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/MutList.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/src/library/Nel.flix
- main/src/library/Order.flix
- main/src/library/RedBlackTree.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestMap.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
- main/test/ca/uwaterloo/flix/library/TestNel.flix
- main/test/ca/uwaterloo/flix/library/TestSet.flix
> Add minimum/maximum to collections

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Core/Io/InputStream.flix
- main/src/library/Core/Io/OutputStream.flix
- main/src/library/Drop.flix
> Add Drop type class

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Array.flix
- main/src/library/Copy.flix
- main/src/library/MutList.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/src/library/Ref.flix
> Add Copy type class

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Array.flix
- main/src/library/Foldable.flix
- main/src/library/List.flix
- main/src/library/MutList.flix
- main/src/library/MutSet.flix
- main/src/library/Nel.flix
- main/src/library/Option.flix
- main/src/library/Set.flix
> Add Foldable type class

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Scheme.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/errors/InstanceError.scala
- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/ClassEnvironment.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/test/ca/uwaterloo/flix/language/phase/TestInstances.scala
- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
- main/test/flix/Test.Dec.Class.flix
Fixes https://github.com/flix/flix/issues/1556
> Add superclasses

- main/src/library/Prelude.flix
- main/test/ca/uwaterloo/flix/library/TestPrelude.flix
> Fixes #1698

- examples/using-channels-and-select.flix
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
> Fixes #1652

- AUTHORS.md
- main/src/ca/uwaterloo/flix/runtime/interpreter/Channel.java
> Unlock channel locks in reverse order

- main/src/library/Map.flix
- main/test/ca/uwaterloo/flix/library/TestMap.flix
> Add Map.invert

- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/test/ca/uwaterloo/flix/language/phase/TestInstances.scala
- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
- main/test/flix/Test.Dec.Class.flix
Fixes https://github.com/flix/flix/issues/1757
* Type class constraints are expressed with `with`
> replace 'extends' with 'with'

- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/test/ca/uwaterloo/flix/language/phase/TestInstances.scala
Fixes #1748 
* Accumulate errors in instances phase
> accumulate errors in Instances

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
This is temporary for fix for certain enums until the new backend arrives.
> Singleton Instances for Certain Unit Tags

- main/src/library/UnsafeBox.flix
- main/test/ca/uwaterloo/flix/library/TestUnsafeBox.flix
This is necessary to be able to use UnsafeBox in the new Datalog solver.
> Implement toString on UnsafeBox

- main/src/library/RedBlackTree.flix
> Optimize RedBlackTree.insert

- examples/analysis/IDE.flix
- examples/misc/FloydWarshall.flix
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/library/Eq.flix
- main/src/library/Hash.flix
- main/src/library/Order.flix
- main/src/library/ToString.flix
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
- main/test/ca/uwaterloo/flix/library/TestGetOpt.flix
- main/test/flix/Test.Dec.Class.flix
https://github.com/flix/flix/issues/1755 but only for instances.
I'm waiting on classes until https://github.com/flix/flix/pull/1736 goes through since it may change things.
* Perform redundancy checks on instances
> Perform redundancy check on instances

- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
Fixes https://github.com/flix/flix/issues/1758
> Minor refactor of ResolvedAst

- main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala
- main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/library/Order.flix
- main/test/ca/uwaterloo/flix/language/phase/TestPatExhaustiveness.scala
Part of https://github.com/flix/flix/issues/1769, for instances
* Perform pattern match check on instance defs
> perform pattern exhaustiveness check on instance defs

- main/src/library/MutList.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
> Fix MutList.toArray

- main/src/ca/uwaterloo/flix/language/errors/InstanceError.scala
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/Option.flix
- main/src/library/Order.flix
- main/src/library/Result.flix
- main/src/library/Set.flix
- main/src/library/UnsafeBox.flix
- main/test/flix/Test.Exp.Binary.Spaceship.flix
> Refactor Order.{less, lessThan, greater, greaterThan}

- main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala
- main/test/ca/uwaterloo/flix/language/phase/TestPatExhaustiveness.scala
Fixes https://github.com/flix/flix/issues/1769
* Pattern match exhaustiveness check is run for signatures with implementations.
> check pattern exhaustiveness for classes

- main/src/library/Order.flix
> Optimize Order.compare for primitive types

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/Nel.flix
- main/src/library/Prelude.flix
- main/src/library/RedBlackTree.flix
> Add bug! and unreachable!

- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/ast/Scheme.scala
- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/ClassEnvironment.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/UnificationError.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
Fixes https://github.com/flix/flix/issues/1619
* Point to sig/def use in NoMatchingInstance error message
> improve location for NoMatchingInstance errors

- main/src/library/Map.flix
> Optimize Map.unionWithKey

- examples/an-interpreter-for-a-trivial-expression-language.flix
- examples/enums-and-parametric-polymorphism.flix
- examples/using-channels-and-select.flix
- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
Fixes https://github.com/flix/flix/issues/1799
* Throw an error when main does not have the expected type scheme.
> Add IllegalMain error

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/debug/FormatTypeConstraint.scala
- main/src/ca/uwaterloo/flix/language/errors/RedundancyError.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/ClassEnvironment.scala
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
Fixes https://github.com/flix/flix/issues/1753
Fixes https://github.com/flix/flix/issues/1754
Fixes https://github.com/flix/flix/issues/1825
* Check for redundant tconstrs in defs
* Check for redundant tconstrs in sigs
* Check for redundant tconstrs in classes
* Check for redundant tconstrs in instances
* Ensure error messages are reasonable
> add check for redundant type constraints

- main/src/library/Boxable.flix
- main/src/library/Eq.flix
- main/src/library/Order.flix
- main/src/library/ToString.flix
This is a contraction of the PR - Relation support to N=15 #1885 - with just the instances and no changes to the solver.
> Up to n=15 tuple instances of Boxable, Eq, Order and ToString

- main/src/ca/uwaterloo/flix/language/debug/FormatScheme.scala
Fixes https://github.com/flix/flix/issues/1935
> properly format type constraints in type schemes

- main/src/library/Fixpoint/Compiler.flix
- main/src/library/Fixpoint/Ram/RamSym.flix
- main/src/library/Fixpoint/Simplifier.flix
- main/src/library/Fixpoint/Solver.flix
Rewrite loops that copy one relation into another into a merge
statement.
> Add new pattern to Simplifier.

- main/src/library/Comparison.flix
- main/src/library/Order.flix
- main/src/library/PartialOrder.flix
- main/test/ca/uwaterloo/flix/library/TestOrder.flix
Implements #1560 (remaining parts).
> Clean up `Order`

- main/src/library/Array.flix
- main/src/library/Boxable.flix
- main/src/library/Fixpoint/Ast/PrecedenceGraph.flix
- main/src/library/Fixpoint/Ast/VarSym.flix
- main/src/library/Fixpoint/Debugging.flix
- main/src/library/Fixpoint/Interpreter.flix
- main/src/library/Fixpoint/Ram/RamSym.flix
- main/src/library/Fixpoint/Solver.flix
- main/src/library/Map.flix
- main/src/library/Order.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/flix/Test.Exp.Binary.Spaceship.flix
> Make `Order` require `Eq`, add laws for `Order`, tests

- main/src/library/Fixpoint/Solver.flix
- main/test/flix/Test.Exp.Fixpoint.Solve.flix
See #1863 
This PR adds factsN functions to the solver up to N=15 in `main/src/library/Fixpoint/Solver.flix`
Tests added for a selection of arities to `main/test/flix/Test.Exp.Fixpoint.Solve.flix`
> Solver adding facts6 to facts15

- main/src/ca/uwaterloo/flix/language/errors/RedundancyError.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
Fixes https://github.com/flix/flix/issues/1755
Fixes https://github.com/flix/flix/issues/1734
* UnusedFormalParam is not checked for sigs without implementation.
* UnconditionalRecursion is checked for sigs with implementations.
* Other redundancy checks are run for sigs.
> Add Redundancy Checks for Classes/Instances

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/library/Div.flix
- main/src/library/Rem.flix
- main/test/flix/Test.Exp.Binary.Arithmetic.flix
Fixes https://github.com/flix/flix/issues/1967
* `x % 0 == 0`
> Override modulo zero to equal zero

- .github/workflows/benchmark-on-demand.yaml
> Allow spaces between robots to summon benchmarker

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/CompleteProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/debug/FormatSignature.scala
- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/runtime/CompilationResult.scala
Fixes part 1 of https://github.com/flix/flix/issues/1984
> Add returnType metadata to TypedAst.Spec

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/library/String.flix
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
- main/test/ca/uwaterloo/flix/library/TestGetOpt.flix
- main/test/ca/uwaterloo/flix/library/TestString.flix
- main/test/flix/Test.Exp.Interpolation.flix
- main/test/flix/Test.Exp.Match.String.flix
- main/test/flix/Test.Exp.String.flix
Fixes https://github.com/flix/flix/issues/1854
* Escapes work with characters
* Escapes work with strings
* Escapes work with interpolations
* Escapes work in pattern matching
> Fix string escapes

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala
- main/src/ca/uwaterloo/flix/language/debug/FormatExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/Linter.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Terminator.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/feature/FeatureSuite.scala
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.Lambda.flix
- main/test/flix/LangSuite.scala
- main/test/flix/Test.Def.Scoped.flix
- main/test/flix/Test.Exp.Let.flix
Part 1 of https://github.com/flix/flix/issues/770
* Allow `scoped` on formal parameters
* Allow `scoped` on let-bindings
* Allow `scoped` on lambdas
> Add `scoped` modifier

- main/src/ca/uwaterloo/flix/language/debug/FormatScheme.scala
- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
Fixes https://github.com/flix/flix/issues/1955
> Remove constraint information from GeneralizationErrors

- main/src/ca/uwaterloo/flix/language/ast/Scopedness.scala
- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
Part 2 of https://github.com/flix/flix/issues/770
> Add scopedness to VarSym

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Console.flix
- main/src/library/Environment.flix
- main/test/ca/uwaterloo/flix/library/LibrarySuite.scala
- main/test/ca/uwaterloo/flix/library/TestEnvironment.flix
Hi,
I tried to implement the Environment API #2062 but since I'm using `Iterator`, `getEnv` is impure.
I don't know how to get around that. Then I wasn't very inspired for the tests :)
> Environment API

- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.Lambda.flix
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
Fixes some issues, but does not fix https://github.com/flix/flix/issues/2050. There are some constraint-specific problems at play here.
> Unify non-parametric defs in Monomorph

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/flix/Test.Dec.Class.flix
fixes https://github.com/flix/flix/issues/2094
> Allow type constraints on laws

- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/flix/Test.Dec.Class.flix
Fixes https://github.com/flix/flix/issues/2097
```scala
def f(x:a, y: m[a]): String with ToString[m[a]] = ???
```
> Allow parsing of tconstrs with multiple vars

- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
Fixes https://github.com/flix/flix/issues/2119
> Parallelize Kinder

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
Fixes https://github.com/flix/flix/issues/1853
> Disallow empty interpolations

- main/src/library/Object.flix
- main/test/ca/uwaterloo/flix/library/LibrarySuite.scala
- main/test/ca/uwaterloo/flix/library/TestObject.flix
Fixes https://github.com/flix/flix/issues/2086
> Add `Object.toOption`

- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala
Fixes https://github.com/flix/flix/issues/2123
> Allow parentheses in Kinds

- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/test/flix/Test.Kind.Enum.flix
Fixes an issue with Schemas in enums: https://github.com/flix/flix/issues/2113#issuecomment-897479174
> Visit enums in Lowering

- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/test/ca/uwaterloo/flix/language/feature/Test.Expression.Lambda.flix
Fixes https://github.com/flix/flix/issues/1966
> Unify lambda fparam tvar with its ascription

- main/src/library/LazyList.flix
- main/test/ca/uwaterloo/flix/library/TestLazyList.flix
> Add LazyList Eq,  Filter, and clean code

- main/src/library/LazyList.flix
- main/test/ca/uwaterloo/flix/library/TestLazyList.flix
Add `LazyList.toArray`
Add `LazyList.toMap`
Add `LazyList.toSet`
Add additional tests for `LazyList.toList`
Implement `Foldable` typeclass
> Add `LazyList.{toArray, toMap, toSet}`

- main/src/library/CodePatterns.flix
- main/src/library/Console.flix
- main/src/library/Object.flix
- main/src/library/Prelude.flix
> Revise Prelude.flix

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Epoch.flix
> Add Epoch.flix

- main/src/library/LazyList.flix
- main/test/ca/uwaterloo/flix/library/TestLazyList.flix
> Add `LazyList.{repeat, from, last, tail, toIter}`

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenMainClass.scala
> Add system exit call to main (Fixes #1654)

- examples/analysis/IDE.flix
- examples/analysis/SUopt.flix
- examples/domains/Constant.flix
- examples/misc/FloydWarshall.flix
- main/src/library/Fixpoint/Ast/Denotation.flix
- main/src/library/PartialOrder.flix
- main/src/tutorials/introduction.flix
- main/test/flix/Test.Exp.Fixpoint.Solve.Lattice.flix
> Renaming of PartialOrder function (Fixes #2151)

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/CompleteProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/Scheme.scala
- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala
- main/src/ca/uwaterloo/flix/language/debug/FormatType.scala
- main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala
- main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
- main/src/ca/uwaterloo/flix/language/phase/Finalize.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Linter.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/BoolUnification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/test/ca/uwaterloo/flix/TestUtils.scala
- main/test/ca/uwaterloo/flix/language/debug/TestFormatType.scala
- main/test/ca/uwaterloo/flix/language/phase/unification/TestUnification.scala
Part of https://github.com/flix/flix/issues/2120
> Add locations to all types

- main/src/library/PartialOrder.flix
> PartialOrder Laws (Fixes #2228)

- main/src/library/LazyList.flix
- main/test/ca/uwaterloo/flix/library/TestLazyList.flix
> Add `LazyList.flatMap`

- main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala
- main/test/ca/uwaterloo/flix/language/phase/TestPatExhaustiveness.scala
- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
Fixes https://github.com/flix/flix/issues/2269#issuecomment-911961944
> Use TestWithLibNix in TestNamer, TestResolver, TestPatExhaustiveness

- main/src/library/LazyList.flix
- main/test/ca/uwaterloo/flix/library/TestLazyList.flix
> Add `LazyList.{findLeft, findRight}`

- main/src/library/LazyList.flix
Optimize `LazyList.findRight` and introduce even more laziness in the `LazyList` data structure.
> Refactor `LazyList`

- main/src/library/Array.flix
- main/src/library/Fixpoint/Solver.flix
- main/src/library/Foldable.flix
- main/src/library/Functor.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/MutList.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/src/library/Nel.flix
- main/src/library/Option.flix
- main/src/library/Prelude.flix
- main/src/library/RedBlackTree.flix
- main/src/library/Set.flix
- main/src/library/String.flix
> Rename `e` to `ef`

- main/src/ca/uwaterloo/flix/language/errors/InstanceError.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/test/ca/uwaterloo/flix/language/phase/TestInstances.scala
Fixes https://github.com/flix/flix/issues/2145
> Remove lawless superclass check

- main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
- main/src/ca/uwaterloo/flix/language/phase/util/PredefinedClasses.scala
- main/test/flix/LangSuite.scala
- main/test/flix/Test.Derives.Order.flix
Fixes https://github.com/flix/flix/issues/2158
> Derive Order

- main/src/library/LazyList.flix
- main/test/ca/uwaterloo/flix/library/TestLazyList.flix
> Add `LazyList.mapWithIndex`

- main/src/library/Comparison.flix
- main/src/library/List.flix
- main/src/library/Nel.flix
- main/src/library/Option.flix
- main/src/library/Result.flix
- main/src/library/Validation.flix
Completing Phase 2 of https://github.com/flix/flix/issues/2154
> Use derivations in the standard library

- main/src/library/LazyList.flix
- main/test/ca/uwaterloo/flix/library/TestLazyList.flix
> Add `LazyList.intercalate`

- main/src/library/List.flix
- main/src/library/Nel.flix
Part of https://github.com/flix/flix/issues/2304
> Revert use of Eq for List and Nel

- main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/library/Option.flix
- main/src/library/Result.flix
- main/test/flix/Test.Derives.Boxable.flix
Fixes https://github.com/flix/flix/issues/2159
> Derive Boxable

- main/src/library/LazyList.flix
- main/test/ca/uwaterloo/flix/library/TestLazyList.flix
> Add `LazyList.intersperse`

- main/src/library/LazyList.flix
- main/test/ca/uwaterloo/flix/library/TestLazyList.flix
> Add `LazyList.takeWhile`

- examples/analysis/IDE.flix
- examples/analysis/SUopt.flix
- examples/domains/Belnap.flix
- examples/domains/Constant.flix
- examples/domains/ConstantParity.flix
- examples/domains/ConstantSign.flix
- examples/domains/Interval.flix
- examples/domains/IntervalAlt.flix
- examples/domains/Mod3.flix
- examples/domains/Parity.flix
- examples/domains/ParitySign.flix
- examples/domains/PrefixSuffix.flix
- examples/domains/Sign.flix
- examples/domains/StrictSign.flix
- examples/misc/FloydWarshall.flix
- examples/using-get-opt.flix
Part of https://github.com/flix/flix/issues/2154
> Use derivations in examples

- main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/test/flix/Test.Derives.Hash.flix
Part of https://github.com/flix/flix/issues/2154
> Derive Hash

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala
- main/src/ca/uwaterloo/flix/language/debug/FormatExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Linter.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Statistics.scala
- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Terminator.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/library/LazyList.flix
A possible replacement for `matchEff`.
> Add if* for conditional compilation

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
> Fixes #2330

- main/src/library/LazyList.flix
- main/test/ca/uwaterloo/flix/library/TestLazyList2.flix
> Add `LazyList.findMap`

- main/src/library/LazyList.flix
- main/test/ca/uwaterloo/flix/library/TestLazyList2.flix
This PR concludes the minimal `LazyList` implementation as defined in #2059
> Add `LazyList.partition`

- main/src/library/LazyList.flix
- main/test/ca/uwaterloo/flix/library/TestLazyList2.flix
I'm not sure there is any way to make this effect polymorphic, since the recursive structure of `(span(f, l), ENil)` or something to that effect would nest tuples within in tuples. Thoughts?
> Add `LazyList.span`

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/List.flix
- main/src/library/Stream.flix
- main/test/ca/uwaterloo/flix/library/LibrarySuite.scala
- main/test/ca/uwaterloo/flix/library/TestStream.flix
Related to #2334 
Adds the following functions
> Add `Stream` data structure

- main/src/library/List.flix
- main/src/library/Stream.flix
- main/test/ca/uwaterloo/flix/library/TestStream.flix
Related to #2334 
Is the type cast sound in `Stream.filterE`?
> Add `Stream.{range, filter}`

- main/src/library/Stream.flix
- main/test/ca/uwaterloo/flix/library/TestStream.flix
> Add `Stream.map`

- main/src/library/Stream.flix
- main/test/ca/uwaterloo/flix/library/TestStream.flix
Related to #2334 
Still needs some tweaks, but this is a basic implementation.
> Add `Stream.{foldLeft, foldRight}`

- main/src/library/Stream.flix
- main/test/ca/uwaterloo/flix/library/TestStream.flix
> Add `Stream.{exists, forall}

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenGlobalCounterClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmName.scala
> Generate Global Counter Class

- main/src/library/LazyList.flix
- main/src/library/List.flix
- main/src/library/Nel.flix
- main/test/ca/uwaterloo/flix/library/TestLazyList2.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestNel.flix
> Add `Sum` to data structures

- main/src/library/Stream.flix
- main/test/ca/uwaterloo/flix/library/TestStream.flix
> Add `Stream.take`

- main/src/ca/uwaterloo/flix/api/lsp/provider/SymbolProvider.scala
Trying to add support for def and classes to DocumentSymbol Provider. I have tested the changes and the outline and breadcumbs in vscode are looking fine.
> Add DocumentSymbols for def and classes

- main/src/library/Array.flix
- main/src/library/MutList.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
> Add `{Array, MutList}.sum`

- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
- main/src/ca/uwaterloo/flix/api/lsp/Request.scala
- main/src/ca/uwaterloo/flix/api/lsp/SymbolInformation.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SymbolProvider.scala
Add [WorkspaceSymbolProvider](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_symbol) to LSP.
Fix: https://github.com/flix/flix/issues/2384
> LSP: Add WorkspaceSymbol Provider capability and lsp/workspaceSymbols Request

- AUTHORS.md
- main/src/library/Fixpoint/Solver.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/MutList.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/src/library/RedBlackTree.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestIterator.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
> Rename toMut and toImm

- docs/STYLE.md
This is just the start. The idea is that in a PR if we discover a style principle then that principle can immediately be added to this file.
> Add Style Guide

- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/flix/Test.Use.Def.flix
Fixes https://github.com/flix/flix/issues/2535
> Fix use operator bug

- main/src/library/Array.flix
- main/src/library/Fixpoint/Debugging.flix
- main/src/library/Iterator.flix
- main/src/library/List.flix
- main/src/library/String.flix
- main/src/resources/benchmark/BenchmarkList.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestIterator.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
- main/test/ca/uwaterloo/flix/library/TestString.flix
> Argument order of repeat

- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/SourceLocation.scala
> Fix #2514 - Semantic tokens for curried functions

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
> Fix #2553 - Set and Map literal source locations

- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
Fixes https://github.com/flix/flix/issues/2549
(untested but reasonably confident)
> Fix range of operator locations

- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
Fixes https://github.com/flix/flix/issues/2554 (for real this time (probably))
> Fix relation and lattice type locations

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/errors/InstanceError.scala
- main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
Fixes https://github.com/flix/flix/issues/2511
> Introduce InstanceSym

- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/test/flix/LangSuite.scala
- main/test/flix/Test.Integ.Fixpoint.TypeAlias.flix
Fixes https://github.com/flix/flix/issues/2567
> Erase aliases for checking types in Lowering

- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/debug/FormatType.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
> Alias constructor

- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/test/flix/LangSuite.scala
- main/test/flix/Test.Dec.Namespace.flix
- main/test/flix/Test.Integ.Enum.TypeAlias.flix
Fixes https://github.com/flix/flix/issues/2566
> Look up enums and type aliases in parallel

- main/src/library/DelayMap.flix
- main/src/library/RedBlackTree.flix
Added a lot of functions from `Map` which are mostly just copy + paste implementations. Should we add some tests to this?
> Add `DelayMap` Functions

- main/src/library/DelayMap.flix
- main/test/ca/uwaterloo/flix/library/TestDelayMap.flix
> Add `DelayMap.{adjust, adjustWithKey, update, updateWithKey}`

- main/src/library/DelayMap.flix
- main/src/library/DemandList.flix
> Refactor `reify ef` to `reifyEff`

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
Fixes https://github.com/flix/flix/issues/2616
> Don't resolve JVM classes in Namer

- main/src/library/LazyList.flix
> Reorder `LazyList`

- main/test/ca/uwaterloo/flix/TestExamples.scala
> Fix a wrong path in TestExamples

- main/src/ca/uwaterloo/flix/language/ast/SourceLocation.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
> Use correct source locations for `query` and `solve`

- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/src/ca/uwaterloo/flix/language/phase/UllmansAlgorithm.scala
- main/test/flix/Test.Stratification.flix
This program is now accepted
```
pub def negativeCycle(): Unit =
let _a = #{
B(x + 1) :- A(x), Diff1(x).
};
let _b = #{
A(x + 1) :- not B(x), Diff2(x).
};
()
```
I don't know what to call the graph based on the whole rule. Constraint graph? Rule graph? Grouped dependency graph?
> Introduce ConstraintGraph

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- main/src/ca/uwaterloo/flix/runtime/CompilationResult.scala
- main/src/ca/uwaterloo/flix/tools/BenchmarkCompiler.scala
- main/test/ca/uwaterloo/flix/TestMain.scala
> Add compiler flag to see code output size

- main/src/library/Chain.flix
- main/src/library/DelayMap.flix
- main/src/library/Iterator.flix
- main/src/library/LazyList.flix
- main/src/library/List.flix
> Remove redundant casts in std lib

- main/src/library/Array.flix
- main/src/library/Chain.flix
- main/src/library/GetOpt.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/MutList.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/src/library/Nel.flix
- main/src/library/Option.flix
- main/src/library/RedBlackTree.flix
- main/src/library/Result.flix
- main/src/library/Set.flix
- main/src/library/String.flix
Fixes #2010 
I'm no completely finished with the issue, but this is the work so far. I still have some questions, which I have mentioned in the issue / thread.
> Refactor functions that require impure functions

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/library/DelayMap.flix
- main/src/library/Iterator.flix
- main/src/library/Map.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/src/library/RedBlackTree.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestSet.flix
- main/test/flix/Test.Dec.Class.flix
- main/test/flix/Test.Eff.Polymorphism.flix
> Remove  impure arrow `~>` (Fix #2657)

- main/src/library/DelayMap.flix
- main/test/ca/uwaterloo/flix/library/TestDelayMap.flix
> Add `Delaymap.{toIterator, sum}`

- main/src/library/Iterator.flix
- main/test/ca/uwaterloo/flix/library/TestIterator.flix
Related to #2459 
Note that `toIterator` already exists on `Foldable`.
> Iterator Phase 5

- main/src/ca/uwaterloo/flix/util/Formatter.scala
Closes #2678
I'm still a bit uncertain on the implementation of `underline` since it depends on the `Console` object.
> Move `{line, code, underline}` to `Formatter` trait

- main/src/ca/uwaterloo/flix/util/Formatter.scala
> Fix Broken Source Location

- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
> Fix project out type bug

- main/src/library/MutList.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
> Remove `Order`, `ToString`, `Functor, `Foldable` from `MutList`

- main/src/library/MutSet.flix
- main/test/ca/uwaterloo/flix/library/TestMutSet.flix
> Remove unsafe instances from MutSet

- main/src/library/MutMap.flix
- main/test/ca/uwaterloo/flix/library/TestMutMap.flix
> Remove`ToString` from `MutMap`

- main/src/library/Iterator.flix
- main/test/ca/uwaterloo/flix/library/TestIterator.flix
> Iterator Phase 7

- docs/STYLE.md
> docs: update `STYLE.md` (Fix #2209)

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmName.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
> refactor: introduce `Flix.Delimiter` (Fix #2717)

- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
> fix: type diff formatting

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/BoolUnification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/src/ca/uwaterloo/flix/util/Options.scala
- main/test/ca/uwaterloo/flix/TestMain.scala
> refactor: remove `--Xno-bool-unification`.

- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/util/Formatter.scala
- main/src/library/BigInt.flix
- main/src/library/Fixpoint/Simplifier.flix
- main/src/library/Monad.flix
- main/test/flix/Test.Exp.Let.MatchStar.flix
> Revert "feat: `let*` to use `Monad.flatMap`."

- docs/PULLREQUEST.md
> docs: add `PULLREQUEST.md`.

- main/src/library/MutList.flix
- main/test/ca/uwaterloo/flix/library/TestChain.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
> Remove unsafe `eq` instance `MutList`

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala
- main/src/ca/uwaterloo/flix/language/debug/FormatExpression.scala
- main/src/ca/uwaterloo/flix/language/errors/RedundancyError.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Statistics.scala
- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Terminator.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
- main/src/library/Fixpoint/Ast/BodyPredicate.flix
- main/src/library/Fixpoint/Ast/HeadPredicate.flix
- main/src/library/String.flix
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
- main/test/flix/Test.Exp.Reify.flix
> feat: added `RedundantPurityCast` and `RedundantEffectCast`

- main/src/library/Array.flix
- main/src/library/Fixpoint/Ast/Datalog.flix
- main/src/library/Fixpoint/Interpreter.flix
- main/src/library/Fixpoint/Solver.flix
- main/src/library/MutList.flix
> refactor: introduced `Tuple` type

- main/src/ca/uwaterloo/flix/language/ast/ErasedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/FinalAst.scala
- main/src/ca/uwaterloo/flix/language/ast/LiftedAst.scala
- main/src/ca/uwaterloo/flix/language/debug/PrettyPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/Eraser.scala
- main/src/ca/uwaterloo/flix/language/phase/Finalize.scala
- main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala
- main/src/ca/uwaterloo/flix/language/phase/Optimizer.scala
- main/src/ca/uwaterloo/flix/language/phase/TreeShaker.scala
- main/src/ca/uwaterloo/flix/language/phase/VarNumbering.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenClosureClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
All tests in #2777 and #237 pass (fixes #237)
> feat: add support for let-rec

- main/src/library/Array.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
> refactor: remove `Order` from `Array`

- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
Fixes https://github.com/flix/flix/issues/2681
> fix: avoid name clashes with generated variable names

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BytecodeInstructions.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenContinuationAbstractClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
> refactor: rewrote genContinuationAbstractClasses to use bytcode dsl

- AUTHORS.md
- main/src/library/Result.flix
- main/test/ca/uwaterloo/flix/library/TestResult.flix
> refactor: apply subject last principle for `Result`

- docs/STYLE.md
> docs: add subject-last to flix style

- main/src/library/Array.flix
- main/src/library/MutList.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestIterator.flix
- main/test/ca/uwaterloo/flix/library/TestLazyList.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
> refactor: remove `Eq` instance for `Array`

- main/src/ca/uwaterloo/flix/language/phase/jvm/AsmOps.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BytecodeInstructions.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/ClassMaker.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenContinuationAbstractClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenGlobalCounterClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenMatchErrorClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordEmptyClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordExtendClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordInterface.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenReifiedSourceLocationClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmName.scala
> refactor: rewrite GenReifiedSourceLocationClass to use bytecode dsl

- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
> feat: added `MissingArrowInstance`

- main/src/library/Iterator.flix
- main/test/ca/uwaterloo/flix/library/TestIterator.flix
> feat: add `Iterator.intercalate`

- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
> feat: split `sigs` and `defs`

- main/src/library/Array.flix
- main/src/library/List.flix
- main/src/library/Option.flix
- main/src/library/String.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestOption.flix
- main/test/ca/uwaterloo/flix/library/TestString.flix
> refactor: remove `map2`

- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/library/Boxable.flix
- main/src/library/Fixpoint/Ast/Denotation.flix
- main/src/library/Fixpoint/Debugging.flix
- main/src/library/Fixpoint/IndexSelection.flix
- main/src/library/Fixpoint/Options.flix
- main/src/library/Fixpoint/Ram/RamSym.flix
- main/src/library/Fixpoint/Solver.flix
- main/src/library/Fixpoint/ToString.flix
- main/src/library/Fixpoint/VarsToIndices.flix
> feat: add `@Internal` annotation

- main/src/library/List.flix
> feat: add effect polymorphism to `List.partition`

- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
> fix: hide `@Space` and `@Time` annotations

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SymbolProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
fixes https://github.com/flix/flix/issues/2860
Also added semantic tokens for derivations
> docs: add derives information to documentor

- main/src/library/Console.flix
> feat: improve color support for `Console`

- main/src/ca/uwaterloo/flix/language/errors/CodeHint.scala
- main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
Fix: #2832 
The Deprecated code hint was already done. As discussed privately @magnus-madsen I'm opening the PR with a first implementation to receive further guidance and feedback on the feature :)
> feat: Add code hints for @Experimental, @Parallel, @Lazy, @Unsafe

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/ClassMaker.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenClosureClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenContinuationAbstractClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenFunctionClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenGlobalCounterClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenLazyClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenMatchErrorClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenNamespaceClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordEmptyClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordExtendClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordInterface.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenUnitClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
> refactor: add method objects to backend

- main/src/library/DelayMap.flix
> feat: add `DelayMap` annotations

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/ClassMaker.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenClosureClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenContinuationAbstractClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenFunctionClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenGlobalCounterClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenLazyClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenMatchErrorClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenNamespaceClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordEmptyClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordExtendClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordInterface.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenUnitClass.scala
> Revert "refactor: add method objects to backend"

- main/src/ca/uwaterloo/flix/language/debug/FormatType.scala
- main/test/ca/uwaterloo/flix/language/debug/TestFormatType.scala
> refactor: improve formatting of type variables

- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
> refactor: documenter: omit empty namespaces

- main/src/library/List.flix
> refactor: use letrec in `List`

- main/src/library/File.flix
> refactor: use letrec in `File`

- main/src/ca/uwaterloo/flix/language/ast/SemanticOperator.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/library/Mod.flix
- main/src/library/Rem.flix
> refactor: remove `{mod, rem}` for floats

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/ClassMaker.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenClosureClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenContinuationAbstractClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenFunctionClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenGlobalCounterClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenLazyClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenMatchErrorClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenNamespaceClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordEmptyClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordExtendClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordInterface.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenUnitClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
Now without nullpointer exceptions. Related to #2591.
> refactor: add method objects to backend types

- main/src/library/MutDeque.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/test/ca/uwaterloo/flix/library/TestMutDeque.flix
- main/test/ca/uwaterloo/flix/library/TestMutMap.flix
- main/test/ca/uwaterloo/flix/library/TestMutSet.flix
> feat: add `sameElements` to `MutDeque`, `MutSet` and `MutMap`

- main/src/library/Environment.flix
- main/src/library/Iterator.flix
- main/src/library/List.flix
- main/src/library/Monoid.flix
- main/src/library/Prelude.flix
- main/src/library/Set.flix
- main/src/library/ToString.flix
- main/test/ca/uwaterloo/flix/library/TestIterator.flix
> chore: clean up misc issues

- main/src/library/Console.flix
> refactor: use `ToString` in `Console` coloring functions

- examples/koans/half-siblings.flix
- main/src/ca/uwaterloo/flix/language/errors/InstanceError.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/ClassEnvironment.scala
- main/test/ca/uwaterloo/flix/language/phase/TestInstances.scala
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/ca/uwaterloo/flix/library/TestApplicative.flix
- main/test/ca/uwaterloo/flix/library/TestChain.flix
- main/test/ca/uwaterloo/flix/library/TestDemandList.flix
- main/test/ca/uwaterloo/flix/library/TestIterator.flix
- main/test/ca/uwaterloo/flix/library/TestMonad.flix
- main/test/ca/uwaterloo/flix/library/TestMutDeque.flix
- main/test/ca/uwaterloo/flix/library/TestMutMap.flix
- main/test/ca/uwaterloo/flix/library/TestMutSet.flix
- main/test/ca/uwaterloo/flix/library/TestOption.flix
- main/test/ca/uwaterloo/flix/library/TestRedBlackTree.flix
- main/test/ca/uwaterloo/flix/library/TestSemiGroup.flix
- main/test/ca/uwaterloo/flix/library/TestTraversable.flix
- main/test/flix/Test.Dec.Class.flix
- main/test/flix/Test.Stratification.flix
Fixes https://github.com/flix/flix/issues/2689
> feat: allow complex instances for true/false

- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
Fixes https://github.com/flix/flix/issues/2945
> perf: parallelize instance visits in `Typer`

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/phase/Reader.scala
> refactor: remove `Input.Str`

- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/ast/ChangeSet.scala
- main/src/ca/uwaterloo/flix/language/ast/Sourceable.scala
- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Reader.scala
> refactor: incrementalize `Parser`

- main/src/ca/uwaterloo/flix/Main.scala
> feat: disable progress bar when no console is attached

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/util/ParOps.scala
> feat: incrementalize `Weeder`

- main/src/library/Chain.flix
- main/src/library/Condition.flix
- main/src/library/DelayMap.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/Option.flix
- main/src/library/Result.flix
- main/src/library/Set.flix
> refactor: mark enums as pub

- main/src/library/Console.flix
> feat: add `bold` to `Console`

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/util/Options.scala
- main/test/ca/uwaterloo/flix/TestMain.scala
> refactor: introduce `--Xincremental` flag

- main/src/library/Set.flix
> refactor: update doc for `Set.count`

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
- main/src/ca/uwaterloo/flix/util/Options.scala
- main/test/ca/uwaterloo/flix/TestMain.scala
> feat: add --Xperf

- main/src/library/Map.flix
- main/src/library/MutMap.flix
- main/src/library/RedBlackTree.flix
- main/test/ca/uwaterloo/flix/library/TestMap.flix
> feat: add `Map.{maximum*}`

- main/src/library/Set.flix
> refactor: parallelize `Set.maximumBy`

- main/src/library/DelayMap.flix
- main/test/ca/uwaterloo/flix/library/TestDelayMap.flix
Closes #2982 
This PR adds
- `DelayMap.minimumKey`
- `DelayMap.minimumKeyBy`
- `DelayMap.minimumValue`
- `DelayMap.minimumValueBy`
- `DelayMap.maximumKey`
- `DelayMap.maximumKeyBy`
- `DelayMap.maximumValue`
- `DelayMap.maximumValueBy`
> feat: add `DelayMap.{min/max key/value}`

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenFlixErrorClass.scala
> fix: FlixError constructor call superclass

- main/src/library/DelayMap.flix
- main/src/library/MutMap.flix
- main/src/library/Set.flix
Closes #3025
Also adds
- `DelayMap.maximumValue`
- `DelayMap.maximumValueBy`
Apparently these functions were missing...
> fix: update `cmp` signature in `{Set, MutMap, DelayMap}`

- main/src/library/DelayMap.flix
- main/src/library/Map.flix
- main/src/library/RedBlackTree.flix
- main/src/library/Set.flix
> refactor: rename `RedBlackTree.{minimum, maximum}` -> `{minimumKey, maximumKey}`

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/tools/Packager.scala
- main/src/ca/uwaterloo/flix/util/Result.scala
Some manual testing seems to indicate that it's working properly.
I didn't do anything for the internal options (`--Xbenchmark-compiler`), only packager commands.
fixes https://github.com/flix/flix/issues/2964
> fix: return exit code 1 on packager failure

- main/src/library/LazyList.flix
- main/test/ca/uwaterloo/flix/library/TestLazyList.flix
> feat: add laziness to `LazyList.span`

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompleteProvider.scala
- main/src/ca/uwaterloo/flix/tools/Packager.scala
fixes https://github.com/flix/flix/issues/3077
> fix: indent four spaces in templates

- main/src/library/List.flix
- main/src/library/MutDeque.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestMutDeque.flix
> feat: add `MutDeque.{foldRight, toList}` & `List.toMutDeque`

- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
Fixes https://github.com/flix/flix/issues/3079
> fix: disallow `pub` modifier on instances

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/UllmansAlgorithm.scala
- main/src/ca/uwaterloo/flix/util/Options.scala
- main/test/ca/uwaterloo/flix/TestMain.scala
> chore: remove --Xno-stratifier and cleanup.

- main/src/library/Nel.flix
- main/src/library/Reducible.flix
- main/test/ca/uwaterloo/flix/library/LibrarySuite.scala
- main/test/ca/uwaterloo/flix/library/TestReducible.flix
Related to #1678 
This PR adds the following functions to `Reducible`:
- reduceLeft
- reduceRight
- reduce
- reduceMap
- foldLeft
- foldRight
- fold
> feat: add `Reducible` reduces & folds

- main/src/library/Reducible.flix
- main/test/ca/uwaterloo/flix/library/TestReducible.flix
Related to #1678
This PR adds
- head
- last
- init
- tail
- reverse
- count
- length
- sum
- sumWith
- product
- productWith
> feat: add `Reducible.{head, last, init, tail, reverse, count, length, sums, products}`

- main/src/library/Reducible.flix
- main/test/ca/uwaterloo/flix/library/TestReducible.flix
> feat: add `Reducible.{exists, forall, foreach, findLeft, findRight, memberOf}`

- main/src/ca/uwaterloo/flix/tools/Packager.scala
fixes https://github.com/flix/flix/issues/3099
> feat: don't require `lib` directory for `Packager` operations

- main/src/library/String.flix
> refactor: rewrite `import` in `String.flix`

- main/src/library/Chain.flix
- main/src/library/DemandList.flix
- main/src/library/Foldable.flix
- main/src/library/LazyList.flix
- main/src/library/List.flix
- main/src/library/Nel.flix
- main/src/library/Set.flix
> fix: `Foldable.joinWith` effect

- main/src/library/Add.flix
- main/src/library/BigInt.flix
- main/src/library/Char.flix
- main/src/library/Console.flix
- main/src/library/Div.flix
- main/src/library/Environment.flix
- main/src/library/Time/Instant.flix
Related to #3148
Done in this PR:
> Refactor: import syntax in library part 1

- main/src/library/Float32.flix
- main/src/library/Float64.flix
- main/src/library/Hash.flix
> Refactor: import syntax in library part 2

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/api/PhaseTime.scala
- main/src/ca/uwaterloo/flix/tools/BenchmarkCompiler.scala
> feat: add `--Xbenchmark-incremental` compiler flag

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
> feat: incrementalize `Kinder`

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
> feat: incrementalize `Resolver`

- main/src/ca/uwaterloo/flix/language/phase/UllmansAlgorithm.scala
> fix: cycle detection bug

- main/src/library/Set.flix
> refactor: remove `Set.map` annotation

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/test/ca/uwaterloo/flix/library/TestOption.flix
> fix: wrong unit tag backend optimization

- main/src/library/DelayMap.flix
- main/src/library/Map.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestDelayMap.flix
- main/test/ca/uwaterloo/flix/library/TestMap.flix
- main/test/ca/uwaterloo/flix/library/TestSet.flix
> refactor: parallelize `{Map, MutMap, Set, MutSet}.{sumWith, productWith}`

- main/src/library/Console.flix
> feat: add method to check if the JVM has an associated console

- main/src/library/Console.flix
Use `ToString` and misc improvements
> refactor: improve `Console.flix` to use `ToString` class

- main/src/library/DelayMap.flix
> refactor: fix annotations and doc in `DelayMap`

- main/src/ca/uwaterloo/flix/language/errors/CodeHint.scala
- main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
- main/src/library/DelayMap.flix
- main/src/library/Map.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/src/library/RedBlackTree.flix
- main/src/library/Set.flix
> docs: rename purity polymorphism to reflection

- main/src/library/File.flix
- main/test/flix/Test.Exp.Jvm.GetField.flix
- main/test/flix/Test.Exp.Jvm.GetFieldDoubleNestedClass.flix
- main/test/flix/Test.Exp.Jvm.GetFieldStaticInnerClass.flix
- main/test/flix/Test.Exp.Jvm.InvokeConstructor.flix
> Refactor: import syntax in library part 7

- main/src/library/Chain.flix
> refactor: use let rec in `Chain`

- main/src/library/DelayMap.flix
- main/src/library/MutDeque.flix
- main/test/ca/uwaterloo/flix/library/TestMutDeque.flix
> feat: Add `MutDeque.foreach`

- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/test/flix/LangSuite.scala
- main/test/flix/Test.Def.Op.flix
Fixes https://github.com/flix/flix/issues/3246
> fix: allow user-defined `||` and `&&` operators

- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
Related to #3148.
This time I borrowed Matthews code to refactor. So I hope this should be the last one.
> Refactor: import syntax in library part 8

- main/src/library/MutList.flix
- main/test/ca/uwaterloo/flix/library/TestDelayMap.flix
- main/test/ca/uwaterloo/flix/library/TestMap.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
- main/test/ca/uwaterloo/flix/library/TestRedBlackTree.flix
- main/test/ca/uwaterloo/flix/library/TestSet.flix
> Refactor: `MutList.append!` to be subject last.

- main/src/ca/uwaterloo/flix/language/phase/OccurrenceAnalyzer.scala
> fix: occurrenceanalyzer perfomance

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala
- main/src/ca/uwaterloo/flix/language/debug/FormatExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Statistics.scala
- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Terminator.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
> chore: handle `LetRegion` correctly in `Redundancy`

- main/src/library/Map.flix
Closes #3155
Also includes some cleanup, like consistent naming and removal of white space
> refactor: use let rec in `Map`

- .github/workflows/greetings.yml
Automagically greets new contributors and asks them to add themselves to the authors document.
> ci: create greetings.yml

- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/util/Validation.scala
- main/src/library/RedBlackTree.flix
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
- main/test/ca/uwaterloo/flix/library/TestDelayList.flix
- main/test/ca/uwaterloo/flix/library/TestRedBlackTree.flix
- main/test/flix/Test.Exp.Binary.Spaceship.flix
- main/test/flix/Test.Kind.Def.flix
related to #3247 
In this PR:
Next steps:
- lets
- patterns
- imports
- uses
- types
- type variables
- formal params
> fix: add `WeederError.ReservedName`

- main/src/library/List.flix
- main/src/library/Nel.flix
- main/test/ca/uwaterloo/flix/library/TestNel.flix
> refactor: use let rec in `Nel`

- main/src/library/Option.flix
> refactor: use let rec in `Option`

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/test/flix/Test.Exp.Jvm.InvokeStaticMethod.flix
> fix: `INVOKESTATIC` to work for both classes and interfaces

- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
> feat: erase `LetRegion` in `Lowering`

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
> chore: remove rigid type variables

- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/library/Array.flix
- main/src/library/MutList.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
Related to #3322
Should it close the issue or do we leave it open?
> Refactor: remove `mut` keyword

- main/src/ca/uwaterloo/flix/api/lsp/provider/FindReferencesProvider.scala
Address: https://github.com/flix/flix/issues/3337
If this approach is ok, we will need to extend it for other entities
.
> Add Def's declaration location when computing its references

- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/test/flix/Test.Dec.Class.flix
> fix: bug in `Kinder`

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Scoped.flix
> feat: add `Scoped` type class

- main/src/ca/uwaterloo/flix/api/lsp/provider/FindReferencesProvider.scala
Expand from https://github.com/flix/flix/issues/3337 and related PR.
@magnus-madsen just one doubt: Do I need to apply the fix also to Fields, Preds and Tags?
> fix: use def sites in `FindReferencesProvider`

- main/src/library/MutSet.flix
> refactor: region syntax in `MutSet`

- main/src/ca/uwaterloo/flix/util/ProgressBar.scala
> chore: fix trailing chars in `ProgressBar`.

- main/src/ca/uwaterloo/flix/language/fmt/FormatSignature.scala
- main/test/ca/uwaterloo/flix/language/LanguageSuite.scala
- main/test/ca/uwaterloo/flix/language/fmt/TestFormatType.scala
> chore: format Unit -> X signatures correctly

- main/test/flix/Test.Exp.Ref.Assign.flix
> tests: use regions in `Test.Exp.Ref.Assign`

- main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
Fix: https://github.com/flix/flix/issues/2831
Use same approach as for enums. This one should be the last PR for now since we don't want to add support for typealiases
> feat: add deprecation and experimental warnings for classes

- main/src/ca/uwaterloo/flix/api/CrashHandler.scala
- main/src/ca/uwaterloo/flix/api/Flix.scala
> feat: add `CrashHandler`

- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
Fixes https://github.com/flix/flix/issues/3255
> feat: ignore recursive calls when checking for uses of definitions

- main/src/library/Concurrent/Channel/Timer.flix
> refactor: `sleepAndSend` to not break on negative input

- main/src/library/Concurrent/Channel/Ticker.flix
> refactor: `sleepSendAndRepeat` to not break on negative inputs

- main/src/library/List.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
> feat: `List.splitAt`

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompleteProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Scheme.scala
- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala
- main/src/ca/uwaterloo/flix/language/phase/Finalize.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/BoolUnification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/test/ca/uwaterloo/flix/language/fmt/TestFormatType.scala
- main/test/ca/uwaterloo/flix/language/phase/unification/TestUnification.scala
> refactor: introduce `Symbol.TypeVarSym`

- main/test/flix/Test.Exp.Ref.Deref.flix
> test: use regions in `Test.Exp.Ref.Deref`

- main/test/flix/Test.Exp.Ref.Precedence.flix
> test: use regions in `Test.Exp.Ref.Precedence`

- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
> refactor: use correct function for visiting type alias parameters in Namer

- .github/workflows/greetings.yml
Apparently there's a known issue with the greetings action. This is the fix/workaround as described in the comments here: https://github.com/actions/first-interaction/issues/10
> ci: fix greetings script

- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
- main/test/flix/LangSuite.scala
- main/test/flix/Test.Dec.TopLevel.flix
> feat: make top-level declarations implicitly public

- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
> fix: perform semantic token highlighting in effects

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
> fix: enable kind information on hovering type variables

- main/src/ca/uwaterloo/flix/api/lsp/Index.scala
- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/RenameProvider.scala
> fix: enable renaming for type variables

- main/src/ca/uwaterloo/flix/api/lsp/Entity.scala
- main/src/ca/uwaterloo/flix/api/lsp/Index.scala
- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/FindReferencesProvider.scala
> fix: support Find References for type variables

- main/src/ca/uwaterloo/flix/api/lsp/LocationLink.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/GotoProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala
> fix: enable type variable highlighting and jump to definition

- main/test/flix/Test.Exp.ArrayLength.flix
> test: use regions in `Test.Exp.ArrayLength`

- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/util/Validation.scala
> refactor: productize `Validation`s in `Namer` and `Resolver`

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompleteProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/ast/Scheme.scala
- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala
- main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala
- main/test/ca/uwaterloo/flix/language/fmt/TestFormatType.scala
- main/test/ca/uwaterloo/flix/language/phase/unification/TestUnification.scala
> feat: use `VarText` datatype

- main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala
- main/test/ca/uwaterloo/flix/language/fmt/TestFormatType.scala
> fix: format Type.Apply properly

- main/src/library/Environment.flix
- main/test/ca/uwaterloo/flix/library/TestEnvironment.flix
> feat: add `getArgs` to `Environment`

- main/src/library/DelayMap.flix
- main/src/library/Fixpoint/Interpreter.flix
- main/src/library/Fixpoint/Solver.flix
- main/src/library/Map.flix
- main/src/library/MutMap.flix
- main/test/ca/uwaterloo/flix/library/TestMutMap.flix
> Revert "refactor: use `ScopedRef` (regions) in `MutMap`"

- main/src/library/Set.flix
> feat: add `Set.toMutSet`

- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
> feat: add fallback text to type variables

- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
> refactor: productize `Resolver`

- main/test/flix/Test.Exp.ArrayLit.flix
> test: use regions in `Test.Exp.ArrayLit`

- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/library/Array.flix
- main/src/library/Prelude.flix
- main/test/flix/Test.Exp.ReifyType.flix
> feat: add ReifiedUnit to reifyType

- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
> refactor: productize `Typer`

- main/src/library/Prelude.flix
related to #3338; builds on #3508
> feat: add `printUnlessUnit`

- examples/using-get-opt.flix
- main/src/library/GetOpt.flix
- main/test/ca/uwaterloo/flix/library/TestGetOpt.flix
> chore: update `GetOpt` to use lists

- main/test/flix/Test.Exp.ArrayStore.flix
> test: use regions in `Test.Exp.ArrayStore`

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
> refactor: rename effect to purity in Parser

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/flix/LangSuite.scala
- main/test/flix/Test.Dec.Effect.flix
related to #3542, depends on #3544
> feat: add parsing of effect declarations

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/flix/LangSuite.scala
- main/test/flix/Test.Exp.Effect.flix
related to #3542, depends on #3547
> feat: parse `try-with`, `do`, `resume` expressions

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/flix/Test.Exp.Effect.flix
related to #3542. Also allows empty handlers
> fix: move handler qualifier to after 'with'

- main/src/library/Chain.flix
- main/src/library/List.flix
- main/src/library/Nel.flix
Related to https://github.com/flix/flix/issues/3226
> refactor: `List.foldRight` to `let rec`

- docs/STYLE.md
> docs: add AST organization rules to `STYLE.md`

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/BoolFormula.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/BoolTable.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/BoolUnification.scala
- main/src/ca/uwaterloo/flix/util/Options.scala
- main/src/ca/uwaterloo/flix/util/collection/Bimap.scala
- main/src/library/List.flix
- main/test/ca/uwaterloo/flix/TestMain.scala
- main/test/ca/uwaterloo/flix/language/phase/PhaseSuite.scala
- main/test/ca/uwaterloo/flix/language/phase/unification/TestBoolTable.scala
```
BEFORE:
====================== Flix Compiler Throughput ======================
Throughput (best): 11.906 lines/sec (with 8 threads.)
min:  4.782, max: 11.906, avg: 10.082, median: 10.536
The highest throughput was in iteration: 5 (out of 15).
The ratio between the best and worst iteration was: 2,5x.
Finished 15 iterations on 53.780 lines of code in 83 seconds.
AFTER:
====================== Flix Compiler Throughput ======================
Throughput (best):  8.012 lines/sec (with 8 threads.)
min:  4.080, max:  8.012, avg:  6.928, median:  7.356
The highest throughput was in iteration: 8 (out of 15).
The ratio between the best and worst iteration was: 2,0x.
Finished 15 iterations on 53.780 lines of code in 119 seconds.
Process finished with exit code 0
```
> feat: add support for Boolean minimization via tabulation

- main/src/ca/uwaterloo/flix/language/errors/CodeHint.scala
> chore: lazy and parallel should be hints

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/library/Prelude.flix
> feat: add `static` region

- main/src/library/Reducible.flix
- main/src/library/Result.flix
- main/test/ca/uwaterloo/flix/library/TestReducible.flix
- main/test/ca/uwaterloo/flix/library/TestResult.flix
> refactor: new `foldRight` in namespaces `Result` and `Reducible`

- main/src/library/Chain.flix
- main/src/library/DelayList.flix
- main/src/library/Foldable.flix
- main/src/library/Identity.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/Nec.flix
- main/src/library/Nel.flix
- main/src/library/Option.flix
- main/src/library/RedBlackTree.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestIdentity.flix
> refactor: new `foldRight` in `Foldable`

- main/test/ca/uwaterloo/flix/language/LanguageSuite.scala
- main/test/ca/uwaterloo/flix/language/TestFlixErrors.scala
fixes #3029.
I'm not sure how to write a program that results in a runtime match exception.
> test: add tests for `FlixError` and `HoleError`

- main/src/library/Map.flix
- main/src/library/RedBlackTree.flix
- main/test/ca/uwaterloo/flix/library/TestRedBlackTree.flix
This was done during #3355 but put into a separate PR here.
> feat: parallelize `{RedBlackTree, Map}.{exists, forall}`

- main/src/library/Chain.flix
- main/src/library/List.flix
- main/src/library/MutList.flix
- main/src/library/Nel.flix
- main/src/resources/benchmark/BenchmarkList.flix
- main/test/ca/uwaterloo/flix/library/TestChain.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
- main/test/ca/uwaterloo/flix/library/TestNel.flix
> Refactor: add `foldRightWithCont` to namespaces `Chain`, `List`, `MutList` and `Nel`

- main/src/library/Concurrent/Channel.flix
- main/src/library/Fixpoint/Interpreter.flix
- main/src/library/Fixpoint/Solver.flix
- main/src/library/MutDeque.flix
- main/src/library/MutMap.flix
- main/test/ca/uwaterloo/flix/library/TestMutDeque.flix
- main/test/ca/uwaterloo/flix/library/TestMutMap.flix
> refactor: remove `{MutDeque, MutMap}.empty`

- main/src/library/DelayList.flix
- main/src/library/Iterator.flix
- main/src/library/MutDeque.flix
- main/test/ca/uwaterloo/flix/library/TestDelayList.flix
- main/test/ca/uwaterloo/flix/library/TestIterator.flix
- main/test/ca/uwaterloo/flix/library/TestMutDeque.flix
Related to https://github.com/flix/flix/issues/3226
> Refactor: add `foldRightWithCont` to namespaces `DelayList`, `Iterator` and `MutDeque`

- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
> chore: rename effects to purity in Weeder

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/flix/Test.Exp.Effect.flix
> feat: finish parsing effects

- main/src/library/Nec.flix
- main/src/library/Option.flix
- main/src/library/RedBlackTree.flix
- main/src/library/Reducible.flix
- main/src/library/Result.flix
- main/test/ca/uwaterloo/flix/library/TestNec.flix
- main/test/ca/uwaterloo/flix/library/TestOption.flix
- main/test/ca/uwaterloo/flix/library/TestReducible.flix
- main/test/ca/uwaterloo/flix/library/TestResult.flix
> Refactor: add `foldRightWithCont` to namespaces `Nec`, `Option`, `Reducible` and `Result`

- main/src/library/Chain.flix
- main/src/library/DelayList.flix
- main/src/library/Foldable.flix
- main/src/library/Identity.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/Nec.flix
- main/src/library/Nel.flix
- main/src/library/Option.flix
- main/src/library/RedBlackTree.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestIdentity.flix
> feat: Add `foldRightWithCont` to `Foldable`

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
depends on #3649, related to #3543
Constructs:
- Introduce `Expression.Do`.
- Introduce `Expression.Resume`.
- Introduce `Expression.TryWith`.
> chore: perform Weeding on effect expressions

- main/test/ca/uwaterloo/flix/util/FlixSuite.scala
> test: ensure that one test failure does not cause subsequent failures

- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
related to #3543, depends on #3650.
> feat: add IllegalResume error

- main/src/library/Foldable.flix
- main/test/ca/uwaterloo/flix/library/TestFoldable.flix
> refactor: Use `Foldable.foldRightWithCont` and add `Foldable.{head, last}`

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
> refactor: rename UseDefOrSig to UseLower and UseClassOrType to UseUpper

- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
> test: add more IllegalResume tests

- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
- main/test/flix/Test.Dec.Effect.flix
- main/test/flix/Test.Exp.Effect.flix
related to #3543, depends on #3678
> feat: ban non-unit return types on operations

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
> feat: add effect-related symbols and nodes to NamedAst

- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
> chore: remove outdate todo

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/errors/NameError.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala
> feat: perform naming on effect declarations

- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
> chore: update message in `IllegalResume`

- main/src/library/List.flix
- main/src/library/MutList.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
- main/test/ca/uwaterloo/flix/library/TestString.flix
> refactor: remove `{MutList, List}.formatWith`

- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
> refactor: rename eff to pur in Resolve*.scala

- main/src/library/List.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
> refactor: make `List.IndexOf` return `Option`

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/flix/CompilerSuite.scala
- main/test/flix/Test.Exp.Effect.flix
> refactor: put pur before eff in AST nodes

- main/src/library/Set.flix
> refactor: use regions in `toMutSet`

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/util/Validation.scala
> feat: add eff to functions in Namer

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
This changes the documentor output. Will that break the API site?
> feat: add annotations to effects and instances

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/test/flix/Test.Dec.Effect.flix
> feat: resolve effect structures

- build.gradle
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/errors/NameError.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala
> feat: perform naming on effect expressions

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
> feat: add "without" expression

- main/test/flix/CompilerSuite.scala
- main/test/flix/Test.Dec.Class.flix
- main/test/flix/Test.Dec.Namespace.flix
- main/test/flix/Test.Dec.OpaqueType.flix
- main/test/flix/Test.Dec.TypeAlias.flix
- main/test/flix/Test.Def.Generalization.flix
- main/test/flix/Test.Derives.Eq.flix
- main/test/flix/Test.Derives.Hash.flix
- main/test/flix/Test.Equality.Tag.flix
- main/test/flix/Test.Exp.Interpolation.flix
- main/test/flix/Test.Exp.Match.Array.flix
- main/test/flix/Test.Exp.Match.Guard.flix
- main/test/flix/Test.Exp.Match.List.flix
- main/test/flix/Test.Exp.Match.Tag.flix
- main/test/flix/Test.Exp.Match.Wild.flix
- main/test/flix/Test.Exp.Null.flix
- main/test/flix/Test.Exp.Tuple.flix
- main/test/flix/Test.Unused.Var.flix
- main/test/flix/Test.Use.Def.flix
- main/test/flix/Test.Use.Sig.flix
> refactor: tests in `CompilerSuite`

- .github/workflows/build.yaml
- main/src/library/Chain.flix
- main/src/library/Nec.flix
- main/test/ca/uwaterloo/flix/library/TestChain.flix
- main/test/ca/uwaterloo/flix/library/TestNec.flix
> refactor: make `IndexOf` in `Chain` and `Nec` return `Option`

- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/Kind.scala
- main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala
- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/language/fmt/FormatKind.scala
- main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala
- main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala
- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
- main/src/ca/uwaterloo/flix/language/phase/Finalize.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
> feat: introduce set type constructors

- main/src/library/Fixpoint/Ast/Denotation.flix
- main/src/library/Fixpoint/Compiler.flix
- main/test/flix/CompilerSuite.scala
- main/test/flix/Test.Exp.Fixpoint.flix
> fix: a bug in the Datalog to RAM compiler

- main/src/library/Option.flix
> feat: add lattice on `Option`

- main/src/library/Array.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
> refactor: use regions in `Array` pt. 3

- main/src/ca/uwaterloo/flix/language/ast/Name.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/test/flix/experimental/Test.Exp.Effect.flix
> feat: resolve effect expressions

- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
> feat: add `{MutSet, MutMap}.singleton`

- main/test/ca/uwaterloo/flix/library/TestArray.flix
Related to #3363 
This PR refactors tests for functions that operate on `ScopedArray` but had not had their tests updated.
> test: refactor ScopedArray tests

- main/src/library/Array.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
> refactor: use regions in `Array` pt. 5

- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestMutDeque.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
> refactor: `join` and `joinWith` tests to use `Regions`

- main/src/library/Array.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
> refactor: use regions in `Array` pt. 6

- main/src/library/Array.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
> refactor: use regions in `Array` pt. 7

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
- main/test/flix/Test.Dec.Enum.flix
> feat: add singleton enum syntax

- main/src/library/Array.flix
> refactor: `Array.swap!` to pub and subject last

- main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/library/MutDeque.flix
- main/src/library/MutList.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/src/library/Prelude.flix
- main/test/flix/Test.Exp.Null.flix
- main/test/flix/Test.Exp.Ref.Deref.flix
- main/test/flix/Test.Exp.Ref.Ref.flix
> refactor: rename `ScopedRef` to `Ref`

- AUTHORS.md
- main/src/ca/uwaterloo/flix/tools/Packager.scala
> fix: use `mkMessages` for `build` command

- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
Improve derivable instance explanations. Fixes #3851
> fix: improve derivable instance explanations

- main/src/library/List.flix
> refactor: remove redundant let rec in `List`

- main/src/library/MutList.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
> refactor: rename `MutList.append!` to `pushAll!`

- main/src/library/Chain.flix
> refactor: remove redundant let rec in `Chain`

- main/src/library/Array.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
> refactor: `Array.put` to return unit

- main/src/library/DelayList.flix
- main/test/ca/uwaterloo/flix/library/TestDelayList.flix
Related to https://github.com/flix/flix/issues/3761
> feat: add `DelayList.toMutDeque`

- main/src/library/Chain.flix
- main/src/library/Map.flix
- main/test/ca/uwaterloo/flix/library/TestMap.flix
> feat: add `Map.foldMapWithKey`

- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/test/flix/experimental/Test.Exp.Effect.flix
> feat: perform kinding on Effect expressions

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/ast/SourceLocation.scala
> feat: sort errors by location

- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala
- main/test/flix/Test.Integ.Enum.TypeAlias.flix
> fix: address issues relating to arrows, type aliases, and enums

- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/test/flix/Test.Exp.Scope.flix
> fix: add region tvar to kenv in region expressions

- main/src/ca/uwaterloo/flix/api/lsp/CompletionItem.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
> chore: better filter text for def and sig completions

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
When a file is removed within the editor, also remove it from the Flix compiler.
Fixes https://github.com/flix/vscode-flix/issues/192
> fix: remove source files from the compiler when they're removed from the editor

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
> feat: improve auto-completion for pipelines

- main/src/library/Iterator.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestIterator.flix
> refactor: use regions in `Iterator` (Part 2)

- main/src/library/Iterator.flix
- main/test/ca/uwaterloo/flix/library/TestIterator.flix
> refactor: use regions in `Iterator` (Part 3)

- main/src/library/Int8.flix
- main/test/ca/uwaterloo/flix/library/TestInt8.flix
> refactor: `Int8` functions to subject last

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BytecodeInstructions.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/ClassMaker.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenContinuationAbstractClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenGlobalClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordEmptyClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordExtendClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordInterface.scala
> refactor: collect finality/publicity/code in method objects

- main/src/library/Iterator.flix
- main/test/ca/uwaterloo/flix/library/TestIterator.flix
> refactor: use regions in `Iterator` (Part 5)

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BytecodeInstructions.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/ClassMaker.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenContinuationAbstractClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenFlixErrorClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenFunctionAbstractClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenGlobalClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenHoleErrorClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenMatchErrorClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmName.scala
related to #2591.
@magnus-madsen This could be made in smaller PR's but I also don't want to throw a lot of small PR's at you
> refactor: make more method objects in backend

- main/src/library/Fixpoint/Ast/BodyPredicate.flix
- main/src/library/Fixpoint/Ast/BodyTerm.flix
- main/src/library/Fixpoint/Ast/Constraint.flix
- main/src/library/Fixpoint/Ast/Datalog.flix
- main/src/library/Fixpoint/Ast/Denotation.flix
- main/src/library/Fixpoint/Ast/Fixity.flix
- main/src/library/Fixpoint/Ast/HeadPredicate.flix
- main/src/library/Fixpoint/Ast/HeadTerm.flix
- main/src/library/Fixpoint/Ast/Polarity.flix
- main/src/library/Fixpoint/Ast/PrecedenceGraph.flix
- main/src/library/Fixpoint/Ast/VarSym.flix
- main/src/library/Fixpoint/Ram/BoolExp.flix
- main/src/library/Fixpoint/Ram/RamStmt.flix
- main/src/library/Fixpoint/Ram/RamSym.flix
- main/src/library/Fixpoint/Ram/RamTerm.flix
- main/src/library/Fixpoint/Ram/RelOp.flix
- main/src/library/Fixpoint/Ram/RowVar.flix
- main/src/library/Fixpoint/Shared/PredSym.flix
> refactor: mark enums in `Fixpoint.{Ast/Ram/Shared}` as `@Internal`

- main/src/library/Chain.flix
- main/src/library/List.flix
- main/src/library/Nec.flix
- main/src/library/Nel.flix
> refactor: All `.sort`, `.sortWith` and `.sortBy` functions sort in-place

- docs/CHANGELOG.md
- main/src/ca/uwaterloo/flix/api/Version.scala
```
Version 0.29.0:
- Language: Added syntactic sugar for singleton enums (thanks Matt!)
- Language: Added a specific error message for when a function is under applied (thanks Jonathan!)
- Language: Added a specific error message about missing dependencies (thanks Matt!)
- Compiler: Improved type and effect formatting (thanks Matt!)
- Library: Refactored integer namespaces to use subject-last (thanks Nina!)
- Library: Refactored all sort functions to internally use arrays (thanks Nina!)
- Library: Refactored more functions to be effect polymorphic (thanks Nina!)
- LSP: Added support for auto-completion of types (thanks Paul!)
- LSP: Improved auto-completion in pipelines (thanks Paul!)
- LSP: Improved auto-completion prioritization (thanks Paul!)
- Tooling: Resurrected the REPL with more …
```
> release 0.29.0

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/fmt/FormatSignature.scala
- main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
- main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
- main/src/ca/uwaterloo/flix/language/phase/EntryPoint.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
related to #4050; no behavioral change
> refactor: rename `eff` to `pur` in Typer

- main/src/ca/uwaterloo/flix/runtime/shell/Command.scala
- main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
> refactor: remove watcher from shell

- main/src/library/DelayList.flix
- main/src/library/Iterable.flix
- main/src/library/List.flix
- main/src/library/Nec.flix
- main/src/library/Nel.flix
- main/src/library/Option.flix
- main/src/library/Result.flix
- main/test/ca/uwaterloo/flix/library/TestResult.flix
> refactor: remove `StaticIterator`

- main/src/library/Option.flix
Related to #3582 and also some small housekeeping.
> refactor: remove redundant let rec from `Option`

- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala
- main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala
- main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala
- main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
- main/src/ca/uwaterloo/flix/language/phase/Finalize.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/test/ca/uwaterloo/flix/language/fmt/TestFormatType.scala
- main/test/ca/uwaterloo/flix/language/phase/TestInstances.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
> feat: add effects to types

- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/library/Fixpoint/Ast/Constraint.flix
- main/src/library/Fixpoint/Compiler.flix
- main/src/library/Fixpoint/Solver.flix
- main/src/library/Fixpoint/Stratifier.flix
> refactor: remove array use from `Constraint` in Datalog engine

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/test/flix/Test.Exp.Ref.Deref.flix
> fix: cast ref in deref expression generated code

- main/test/flix/CompilerSuite.scala
- main/test/flix/Test.Exp.Regions.flix
> test: add region tests

- main/src/library/Set.flix
A bit of housekeeping for `Set`
> style: reorder `insert`, `remove`, `isEmpty` in `Set`

- main/src/library/Result.flix
> refactor: remove redundant let rec from `Result`

- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
> chore: remove chained `<-` operations

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BytecodeInstructions.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRecordEmptyClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenRefClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenUnitClass.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmName.scala
> refactor: collect more backend objects

- main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
> chore: don't display progress within REPL apart from :reload

- main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
As per @magnus-madsen comment in #4097
> feat: only display progress on first compile

- main/src/library/Iterator.flix
> refactor: remove redundant let rec in `Iterator`

- main/src/library/Environment.flix
> refactor: remove impure casts in `Environment`

- main/src/library/Array.flix
- main/src/library/Chain.flix
- main/src/library/DelayList.flix
- main/src/library/Fixpoint/Compiler.flix
- main/src/library/Fixpoint/Interpreter.flix
- main/src/library/Fixpoint/Solver.flix
- main/src/library/Foldable.flix
- main/src/library/Iterator.flix
- main/src/library/List.flix
- main/src/library/MutDeque.flix
- main/src/library/MutList.flix
- main/src/library/Nec.flix
- main/src/library/Nel.flix
- main/src/library/Reducible.flix
- main/src/library/String.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestChain.flix
- main/test/ca/uwaterloo/flix/library/TestDelayList.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestMutDeque.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
- main/test/ca/uwaterloo/flix/library/TestNec.flix
- main/test/ca/uwaterloo/flix/library/TestReducible.flix
- main/test/ca/uwaterloo/flix/library/TestString.flix
> refactor: make `_.toArray` take region as first parameter

- main/src/library/MutDeque.flix
- main/test/ca/uwaterloo/flix/library/TestMutDeque.flix
> feat: add `MutDeque.{peekFront, peekBack}`

- main/src/library/Array.flix
> refactor: make `copyOfRange` use regions in internal casts

- main/src/library/Array.flix
- main/src/library/Chain.flix
- main/src/library/DelayList.flix
- main/src/library/Foldable.flix
- main/src/library/List.flix
- main/src/library/MutList.flix
- main/src/library/Nec.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestChain.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
- main/test/ca/uwaterloo/flix/library/TestNec.flix
> refactor: make `_.toMutList` take region as first parameter

- main/src/library/Set.flix
> refactor: make `_.toMutSet` take region as first parameter

- main/src/library/DelayMap.flix
- main/src/library/Fixpoint/Solver.flix
- main/src/library/Map.flix
> refactor: make `_.toMutMap` take region as first parameter

- main/src/library/MutList.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
- main/test/ca/uwaterloo/flix/library/TestNec.flix
> refactor: make `_.range` take region as first parameter

- main/src/ca/uwaterloo/flix/runtime/shell/SourceFiles.scala
> fix: crash with empty directory

- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/InferMonad.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/flix/experimental/Test.Exp.Effect.flix
related to #4050
Depends on (hoping this list auto-updates with Github magic **(nope)**):
- #4105
> feat: perform type inference for effects

- main/src/library/DelayMap.flix
- main/src/library/MultiMap.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/src/library/RedBlackTree.flix
- main/test/ca/uwaterloo/flix/library/TestDelayMap.flix
- main/test/ca/uwaterloo/flix/library/TestMultiMap.flix
- main/test/ca/uwaterloo/flix/library/TestMutMap.flix
- main/test/ca/uwaterloo/flix/library/TestMutSet.flix
- main/test/ca/uwaterloo/flix/library/TestRedBlackTree.flix
> feat: add `{DelayMap, MultiMap, MutMap, MutSet, RedBlackTree}.toMutDeque`

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/flix/Test.Exp.Foreach.flix
Related to #3950
Is there a better title for this PR?
> feat: add `foreach (x <- xs; y <- ys) exp` expression

- main/src/library/Fixpoint/Compiler.flix
- main/src/library/Fixpoint/IndexSelection.flix
- main/src/library/Fixpoint/Interpreter.flix
- main/src/library/Fixpoint/Ram/BoolExp.flix
- main/src/library/Fixpoint/VarsToIndices.flix
> refactor: use `List` in `BoolExp`

- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala
- main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala
- main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala
- main/src/ca/uwaterloo/flix/language/phase/Finalize.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/SetUnification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala
- main/test/ca/uwaterloo/flix/language/phase/unification/TestSetUnification.scala
> feat: port boolean unification for sets

- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/library/Fixpoint/Ast/Datalog.flix
- main/src/library/Fixpoint/Compiler.flix
- main/src/library/Fixpoint/Solver.flix
- main/src/library/Fixpoint/Stratifier.flix
> refactor: use `List` in `Datalog`

- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/flix/Test.Exp.Foreach.flix
> refactor: use `Iterator.foreach` in `foreach` loops

- main/src/library/Array.flix
- main/src/library/Benchmark/Bench.Chain.flix
- main/src/library/Benchmark/Bench.Fusion.flix
- main/src/library/MutDeque.flix
- main/src/library/MutList.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestDelayList.flix
- main/test/ca/uwaterloo/flix/library/TestIterator.flix
- main/test/ca/uwaterloo/flix/library/TestMutDeque.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
- main/test/ca/uwaterloo/flix/library/TestToString.flix
> refactor: make `_.shuffle`, `_.singleton` and benchmarks take region as first parameter

- main/src/library/Iterator.flix
- main/test/ca/uwaterloo/flix/library/TestIterator.flix
> feat: add `Iterator.takeL`

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
Fix whitespace to avoid unnecessary diffs (e.g. #4159)
> chore: cleanup whitespace to avoid clashing with IDEA

- main/src/library/MutDeque.flix
- main/src/library/MutList.flix
This is why mutlist was counted as region polymorphic @magnus-madsen
> fix: add Impure to shuffles set effect

- main/src/library/Array.flix
- main/src/library/DelayMap.flix
- main/src/library/Foldable.flix
- main/src/library/Iterable.flix
- main/src/library/Result.flix
> feat: add `enumerator` to more namespaces

- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/SetFormula.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/SetTable.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/SetUnification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/src/library/Map.flix
- main/src/library/Nec.flix
- main/src/library/Nel.flix
- main/src/library/RedBlackTree.flix
- main/src/library/Reducible.flix
- main/src/library/Traversable.flix
- main/test/flix/experimental/Test.Exp.Effect.flix
Related to:
* #4050 
Depends on:
* #4145
> feat: activate unification for effect sets

- main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala
related to #4050 
Depends on:
- #4194 
Some caveats:
1. This cannot yet be tested with VSCode because of https://github.com/flix/vscode-flix/issues/208
2. Effect-related expressions are still erased in TypedAst, so their effects will not be shown
Addressing 2 is next on my TODO list. I'll see if there's an easy fix for 1.
> feat: enable effect hovering

- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
> fix: desugar zero-arg do-expression to unit

- main/src/ca/uwaterloo/flix/language/phase/unification/SetTable.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/SetUnification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
- main/test/ca/uwaterloo/flix/language/phase/PhaseSuite.scala
- main/test/ca/uwaterloo/flix/language/phase/unification/TestSetUnification.scala
> fix: improve effect unification

- examples/analysis/IDE.flix
- examples/analysis/IFDS.flix
- examples/analysis/SUopt.flix
- examples/misc/FloydWarshall.flix
- main/src/library/Fixpoint/IndexSelection.flix
- main/src/library/Fixpoint/Interpreter.flix
- main/src/library/Fixpoint/Simplifier.flix
- main/src/library/Fixpoint/Solver.flix
- main/src/library/Fixpoint/Stratifier.flix
- main/src/library/Fixpoint/VarsToIndices.flix
- main/src/tutorials/introduction.flix
Related to #3896.
Lots of pure casts and impure functions gone in this one 🎉
> refactor: add region to `Fixpoint.Database`

- main/src/library/Array.flix
- main/src/library/Chain.flix
- main/src/library/DelayList.flix
- main/src/library/Iterable.flix
- main/src/library/List.flix
- main/src/library/MutDeque.flix
- main/src/library/MutList.flix
- main/src/library/Nec.flix
- main/src/library/Nel.flix
- main/src/library/Option.flix
- main/src/library/Reducible.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestMutDeque.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
> refactor: add `Iterable` instances to mutable collections

- main/src/library/Monad.flix
- main/src/library/MutMap.flix
- main/src/library/Nel.flix
- main/src/library/Prelude.flix
- main/test/flix/Test.Exp.Reify.flix
> refactor: update effect syntax

- main/src/library/Iterator.flix
> feat: add `Iterable` instance for `Iterator`

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
> feat: add `foreach` snippet to `CompletionProvider`

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
> feat: add `for`, `yield` to CompletionProvider

- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/util/Options.scala
> fix: handle effects properly in Redundancy

- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala
- main/src/ca/uwaterloo/flix/language/phase/Finalize.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/BoolFormula.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/SetUnification.scala
- main/test/ca/uwaterloo/flix/language/fmt/TestFormatType.scala
> refactor: treat effect difference as syntactic sugar

- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/flix/Test.Exp.ForEach.flix
Changes desugaring to `Iterator.foreach(f, Iterable.iterator(list))`
Related to #4224
> refactor: update `foreach` desugaring

- main/src/library/Iterator.flix
- main/src/library/Prelude.flix
> feat: add `iterator` and `enumerator` to Prelude

- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/flix/experimental/Test.Exp.Effect.flix
replaces #4251; related to #4236
> feat: allow sets in without expressions

- main/src/ca/uwaterloo/flix/runtime/shell/Command.scala
- main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
- main/src/ca/uwaterloo/flix/runtime/shell/SourceFiles.scala
> feat: allow package operations to be carried out within REPL

- main/src/ca/uwaterloo/flix/language/ast/ErasedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/FinalAst.scala
- main/src/ca/uwaterloo/flix/language/ast/LiftedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/OccurrenceAst.scala
- main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/PrettyPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala
- main/src/ca/uwaterloo/flix/language/phase/Eraser.scala
- main/src/ca/uwaterloo/flix/language/phase/Finalize.scala
- main/src/ca/uwaterloo/flix/language/phase/Inliner.scala
- main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala
- main/src/ca/uwaterloo/flix/language/phase/OccurrenceAnalyzer.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/TreeShaker.scala
- main/src/ca/uwaterloo/flix/language/phase/VarNumbering.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenAnonymousClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
- main/test/flix/Test.Exp.Jvm.NewObject.flix
I'll leave this draft, but I suspect it would make sense to review.
I'm particularly unsure whether I'm doing the right thing in `OccurrenceAnalyzer`
> feat: add `JvmMethod` to the backend

- docs/WISHLIST.md
> docs: add `WISHLIST.md`

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/test/flix/Test.Exp.Effect.flix
> fix: allow set types as enum parameters

- main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
- main/test/flix/Test.Exp.ReifyEff.flix
related to #4236
fixes https://github.com/flix/flix/issues/4281
> fix: check for set effects in reifyEff

- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
> feat: improve IllegalPrivateDeclaration message

- main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala
- main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/BoolTable.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/BoolUnification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/SetUnification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/TypeMinimization.scala
related to #4235 
sets up for #4310
> refactor: introduce TypeMinimization.scala

- main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala
- main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenClosureClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
> chore: tidy up some closure-related cruft

- main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala
> feat: only show non-pure types and effects in HoverProvider

- main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala
> feat: minimize types on hover

- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/TypeMinimization.scala
> feat: perform type minimization on schemes in generalization error

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
> feat: add autocomplete for effects

- main/src/library/MutMap.flix
- main/src/library/Random.flix
- main/src/library/Result.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestChain.flix
- main/test/ca/uwaterloo/flix/library/TestDelayList.flix
- main/test/ca/uwaterloo/flix/library/TestList.flix
- main/test/ca/uwaterloo/flix/library/TestMutDeque.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
- main/test/ca/uwaterloo/flix/library/TestNec.flix
- main/test/ca/uwaterloo/flix/library/TestNel.flix
- main/test/ca/uwaterloo/flix/library/TestRandom.flix
- main/test/ca/uwaterloo/flix/library/TestRedBlackTree.flix
- main/test/ca/uwaterloo/flix/util/FlixSuite.scala
> refactor: use `NonDet` in `Random`

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenAnonymousClasses.scala
- main/src/flix/test/TestBoolArrayInterface.java
- main/src/flix/test/TestCharArrayInterface.java
- main/src/flix/test/TestFloat32ArrayInterface.java
- main/src/flix/test/TestFloat64ArrayInterface.java
- main/src/flix/test/TestInt16ArrayInterface.java
- main/src/flix/test/TestInt32ArrayInterface.java
- main/src/flix/test/TestInt64ArrayInterface.java
- main/src/flix/test/TestInt8ArrayInterface.java
- main/test/flix/Test.Exp.Jvm.NewObject.flix
> feat: add array support hack to NewObject

- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
> fix: use Type.eraseAliases in Safety
