main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
=> feat: allow type in NewObject

main/src/flix/test/TestFunctionalInterface.java, main/src/flix/test/TestThrowingInterface.java, main/src/flix/test/TestVarargsInterface.java, main/test/flix/Test.Exp.Jvm.NewObject.flix
This concludes, I believe, all the "happy path" tests for NewObject (shout if you think I've missed any)
=> test: additional `NewObject` tests

main/src/ca/uwaterloo/flix/language/phase/Safety.scala
=> fix: use `eraseTypeAliases` in `Safety`.

main/src/library/Prelude.flix
=> fix: `bug!`

main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
=> feat: make IO and NonDet imply impure

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> fix: allow deconstructing opaque types from child namespaces

main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
NB: This desugars to type aliases. Later we will want to avoid desugarings.
=> feat: add support for top-level imports

main/src/ca/uwaterloo/flix/api/lsp/Entity.scala, main/src/ca/uwaterloo/flix/api/lsp/Index.scala, main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
Goto, find references, etc. waiting on a larger LSP refactor
=> feat: perform indexing on type aliases

main/test/flix/Test.Exp.Jvm.NewObject.flix
=> chore: Use aliases in NewObject tests

main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
Makes constraint parameters consistent with formal parameters.
=> refactor: regularize constraint params

main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/Type.scala, main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala, main/src/ca/uwaterloo/flix/language/phase/Deriver.scala, main/src/ca/uwaterloo/flix/language/phase/Documentor.scala, main/src/ca/uwaterloo/flix/language/phase/Finalize.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/test/ca/uwaterloo/flix/language/fmt/TestFormatType.scala
=> refactor: remove Type.Tag

main/src/ca/uwaterloo/flix/language/phase/Parser.scala
=> fix: disallow empty type applications

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/tools/Packager.scala, main/src/ca/uwaterloo/flix/tools/Tester.scala, main/src/ca/uwaterloo/flix/util/Duration.scala, main/src/ca/uwaterloo/flix/util/TimeOps.scala
This rewrites the `Tester`. No new features are added, but the architecture is changed.
=> refactor: rewrite `Tester`

examples/select-with-defaults-and-timers.flix, main/test/ca/uwaterloo/flix/library/TestStringBuilder.flix
=> chore: remove Impure from tests

main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
=> fix: fix typo in Unification.getUnderOrOverAppliedError

main/src/ca/uwaterloo/flix/tools/Packager.scala
=> chore: show better error messages for malformed packages

.github/workflows/semantic-commit.yaml
Prevents sneaking bad PR names by adding a commit to the PR
=> ci: fix semantic commit checker

main/src/ca/uwaterloo/flix/language/phase/unification/RecordUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/SchemaUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
=> refactor: dispatch unification by kind

main/src/ca/uwaterloo/flix/language/phase/unification/BoolAlgebra.scala, main/src/ca/uwaterloo/flix/language/phase/unification/BoolAlgebraTable.scala, main/src/ca/uwaterloo/flix/language/phase/unification/TypeMinimization.scala, main/test/ca/uwaterloo/flix/language/phase/PhaseSuite.scala, main/test/ca/uwaterloo/flix/language/phase/unification/TestBoolAlgebraTable.scala
=> chore: generalize names for Boolean algebra

main/src/ca/uwaterloo/flix/api/lsp/provider/InlayHintProvider.scala
=> chore: hide long inlay hints

main/src/library/Set.flix, main/test/ca/uwaterloo/flix/library/TestSet.flix
=> feat: add `Set.filterMap`

examples/using-get-opt.flix, main/src/library/BigInt.flix, main/src/library/Float32.flix, main/src/library/Float64.flix, main/src/library/FromString.flix, main/src/library/Int16.flix, main/src/library/Int32.flix, main/src/library/Int64.flix, main/src/library/Int8.flix, main/test/ca/uwaterloo/flix/library/TestBigInt.flix, main/test/ca/uwaterloo/flix/library/TestFloat32.flix, main/test/ca/uwaterloo/flix/library/TestFloat64.flix, main/test/ca/uwaterloo/flix/library/TestInt16.flix, main/test/ca/uwaterloo/flix/library/TestInt32.flix, main/test/ca/uwaterloo/flix/library/TestInt64.flix, main/test/ca/uwaterloo/flix/library/TestInt8.flix
=> fix: consistent fromString signature

main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala, main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala, main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala, main/test/flix/Test.Exp.Jvm.NewObject.flix
=> feat: rename object to new

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
Adds an LSP command (rather than option) to the CLI. Does not remove the existing --lsp option.
=> feat: add LSP command

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala, main/src/ca/uwaterloo/flix/util/Options.scala, main/test/ca/uwaterloo/flix/language/phase/unification/TestUnification.scala, main/test/flix/Test.Exp.Jvm.InvokeMethod.flix
=> feat: add Xno-bool-effects

main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/flix/test/TestClassWithInheritedMethod.java, main/test/flix/Test.Exp.Jvm.InvokeMethod.flix
As per @mlutze suggestion in #4392.
Note: This only addresses calling methods. We'll need to make similar changes for fields and static methods, but I wanted to get this reviewed before going too far.
=> feat: Allow inherited methods to be invoked

main/src/ca/uwaterloo/flix/language/errors/TypeError.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala, main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
=> feat: Suggest upcast for assignable Java types

examples/misc/Reachable.flix
* Functional solution is tail-recursive
* use memberOf instead of exists generally (again tail recursive)
* change imp solution to be dfs instead of bfs to align with fp solution
=> docs: improve reachable paradigm example

main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala, main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala, main/test/flix/Test.Exp.Upcast.flix
Related to https://github.com/flix/flix/issues/4264 https://github.com/flix/flix/issues/4486
Closes #4282
=> feat: add support for algebraic effects in `upcast`

main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
First step towards maintaining import environment as per #4392
=> feat: Plumb imports through to resolver

main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/unification/KindUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala, main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala, main/test/ca/uwaterloo/flix/language/phase/unification/TestUnification.scala
=> fix: check kinds before unifying

main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
=> chore: fix #4557

main/src/ca/uwaterloo/flix/runtime/shell/Command.scala, main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
=> feat: reload and eval

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/InlayHintProvider.scala, main/src/ca/uwaterloo/flix/language/ast/Scheme.scala, main/src/ca/uwaterloo/flix/language/ast/Type.scala, main/src/ca/uwaterloo/flix/language/dbg/PrettyPrinter.scala, main/src/ca/uwaterloo/flix/language/errors/CodeHint.scala, main/src/ca/uwaterloo/flix/language/errors/EntryPointError.scala, main/src/ca/uwaterloo/flix/language/errors/InstanceError.scala, main/src/ca/uwaterloo/flix/language/errors/RedundancyError.scala, main/src/ca/uwaterloo/flix/language/errors/ReificationError.scala, main/src/ca/uwaterloo/flix/language/errors/StratificationError.scala, main/src/ca/uwaterloo/flix/language/errors/TypeError.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatCase.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatEff.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatOptions.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatScheme.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatSignature.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatTypeConstraint.scala, main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala, main/src/ca/uwaterloo/flix/language/phase/Documentor.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Regions.scala, main/src/ca/uwaterloo/flix/language/phase/UllmansAlgorithm.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala, main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala, main/test/ca/uwaterloo/flix/language/fmt/TestFormatType.scala
related to #4445 
(incidentally fixes part of #4541)
=> feat: use bool and eff deactivation options for type formatting

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/language/phase/Optimizer.scala, main/src/ca/uwaterloo/flix/util/Options.scala
fixes https://github.com/flix/flix/issues/4581
=> feat: add Xno-optimizer option

main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
=> feat: add names to UndefinedX error messages

main/src/library/Array.flix, main/src/library/Foldable.flix, main/src/library/Iterator.flix, main/src/library/MutDeque.flix, main/src/library/MutList.flix, main/src/library/RedBlackTree.flix, main/src/library/Result.flix, main/test/ca/uwaterloo/flix/library/TestArray.flix, main/test/ca/uwaterloo/flix/library/TestChain.flix, main/test/ca/uwaterloo/flix/library/TestDelayList.flix, main/test/ca/uwaterloo/flix/library/TestDelayMap.flix, main/test/ca/uwaterloo/flix/library/TestIterator.flix, main/test/ca/uwaterloo/flix/library/TestList.flix, main/test/ca/uwaterloo/flix/library/TestMap.flix, main/test/ca/uwaterloo/flix/library/TestMultiMap.flix, main/test/ca/uwaterloo/flix/library/TestMutDeque.flix, main/test/ca/uwaterloo/flix/library/TestMutList.flix, main/test/ca/uwaterloo/flix/library/TestMutMap.flix, main/test/ca/uwaterloo/flix/library/TestMutSet.flix, main/test/ca/uwaterloo/flix/library/TestOption.flix, main/test/ca/uwaterloo/flix/library/TestRedBlackTree.flix, main/test/ca/uwaterloo/flix/library/TestResult.flix, main/test/ca/uwaterloo/flix/library/TestSet.flix
=> fix: use 1 for product of empty collections

main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
=> fix: enable highlighting on variable subpatterns

main/src/ca/uwaterloo/flix/runtime/shell/SourceFiles.scala
=> fix: unpack Flix packages in shell sources

main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/test/flix/Test.Exp.Let.Rec.flix
Fixes https://github.com/flix/flix/issues/3249
=> feat: add support for nested symbolic operator definitions

main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/test/flix/Test.Exp.Par.flix
=> refactor: remove ParApply

main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/test/flix/Test.Exp.Let.Rec.flix
fixes #3239. still have to add tests
=> feat: allow type annotations on nested functions

main/src/ca/uwaterloo/flix/language/phase/jvm/GenAnonymousClasses.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala, main/test/flix/Test.Exp.Jvm.NewObject.flix
=> fix: Closure code generation for NewObject

main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala, main/test/flix/Test.Import.flix
Follow-on from #4538 and as per #4392
=> feat: Track import environment within Namer

main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala, main/test/flix/Test.Import.flix
Follows on from #4608 and related to #4392
=> feat: Switch to new import implementation

main/src/ca/uwaterloo/flix/tools/Packager.scala
=> feat: change init command to ignore existing files when possible

main/src/ca/uwaterloo/flix/language/phase/Deriver.scala, main/src/library/Hash.flix, main/src/library/List.flix, main/src/library/Map.flix, main/src/library/MultiMap.flix, main/src/library/Set.flix
=> feat: avoid use of 0 for hashing

main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
=> fix: allow set effects in entry point

main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmName.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmType.scala
=> fix: avoid using Scala types in bytecode

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
=> feat: auto-complete inserts formal parameters with holes

main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/test/flix/Test.Exp.Interpolation.flix
related to #4664. I went with % instead of # since there were some parsing weirdnesses related to schemas and we use # for e.g. Map#{
=> feat: introduce debug interpolation

main/src/library/Prelude.flix, main/test/ca/uwaterloo/flix/library/TestPrelude.flix
=> feat: improve array formatting for stringify

main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala, main/src/library/Array.flix, main/src/library/Prelude.flix, main/test/flix/Test.Exp.ReifyType.flix
=> feat: add BigInt and String to reifyType

main/src/library/Fixpoint/Ast/BodyPredicate.flix, main/src/library/Fixpoint/Ast/BodyTerm.flix, main/src/library/Fixpoint/Ast/Constraint.flix, main/src/library/Fixpoint/Ast/Datalog.flix, main/src/library/Fixpoint/Ast/HeadPredicate.flix, main/src/library/Fixpoint/Ast/HeadTerm.flix, main/src/library/Fixpoint/Compiler.flix, main/src/library/Fixpoint/Debugging.flix, main/src/library/Fixpoint/Interpreter.flix, main/src/library/Fixpoint/Ram/BoolExp.flix, main/src/library/Fixpoint/Ram/RamStmt.flix, main/src/library/Fixpoint/Ram/RamTerm.flix, main/src/library/Fixpoint/Ram/RelOp.flix, main/src/library/Fixpoint/Solver.flix
=> feat: refactor Datalog engine to use `stringify` instead of `ToString`

main/src/library/Prelude.flix, main/test/ca/uwaterloo/flix/library/TestPrelude.flix, main/test/flix/Test.Exp.Interpolation.flix
related to #4664. Note that this does not work for strings inside of arrays or other objects
=> feat: escape strings for debug output

main/src/library/Prelude.flix, main/test/ca/uwaterloo/flix/library/TestPrelude.flix
related to #4664
Note again that numbers nested inside objects are unaffected.
=> feat: add suffixes for numbers and escapes for characters

main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala, main/test/flix/Test.Exp.Record.Restrict.flix
=> fix: make record restrict non-destructive

main/src/library/Array.flix, main/test/ca/uwaterloo/flix/library/TestArray.flix
=> refactor: remove `Array.init2`

main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala, main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/test/flix/Test.Java.Function.flix
=> feat: interpret Intfunction as Int32 -> Object

main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmName.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmType.scala, main/test/flix/Test.Java.Function.flix
=> feat: implement `IntFunction` for functions `Int32 -> Object`

main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/test/flix/Test.Java.Function.flix
=> feat: add IntUnaryOperator to translated functional interfaces

main/src/library/Concurrent/Channel.flix, main/test/ca/uwaterloo/flix/library/TestChannel.flix
Simplify Channel API as discussed in #4730
=> chore: Simplify Channel API

main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmName.scala, main/test/flix/Test.Java.Function.flix
Fixes part of #4721.
Also fixes a bug where IntFunction did not properly use its argument
=> feat: add `IntUnaryOperator` to respective function objects

main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> refactor: move UnkindedType helpers to UnkindedType

main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
=> chore: Switch par code to new style channels

main/src/library/Channel.flix
=> chore: fix `Channel.send`

main/src/library/Graph.flix, main/test/ca/uwaterloo/flix/library/TestGraph.flix
Relates to #3906.
* Rename `distances` to `distancesFrom`
* add `{...}` to multiline defs
* add apsp def `distances`
* add `distances` tests
* Refactor a list fold to a datalog rule in `distancesFrom`
=> feat: add apsp to `Graph.flix`

main/src/library/Object.flix, main/test/ca/uwaterloo/flix/library/TestObject.flix
=> fix: define isNull for primitives

main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/src/library/Channel.flix, main/test/flix/Test.Exp.Concurrency.Buffered.flix, main/test/flix/Test.Exp.Concurrency.Unbuffered.flix
This is the Add CHANNEL_NEW to internal syntax task of #4755
=> chore: Add CHANNEL_NEW to internal syntax

examples/sending-and-receiving-on-channels.flix
=> chore: Example renaming

main/src/library/Prelude.flix
=> refactor: use typematch for stringify function

main/src/library/Prelude.flix, main/test/ca/uwaterloo/flix/library/TestPrelude.flix
=> fix: support null in stringify

main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/test/flix/Test.Exp.Upcast.flix
related to #4693. I did not handle arrays because the regions and type paramters make it scary.
=> feat: allow upcasting of types that are non-primitive in JVM

main/src/library/Graph.flix, main/test/ca/uwaterloo/flix/library/TestGraph.flix
Related to #3906.
* Fixed error in test `graph01`
* Added `Graph.toUndirected` with tests
* Added `Graph.toUndirectedWeighted` with tests
=> feat: `Graph.toUndirected` & `Graph.toUndirectedWeighted`

main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/test/flix/Test.Exp.BigDecimal.flix
=> feat: support precision in BigDecimal literals

main/src/library/Graph.flix, main/test/ca/uwaterloo/flix/library/TestGraph.flix
Related to #3906 
* Add `pub def toGraphViz(g: m[((t, t))]): String with Foldable[m], Boxable[t], ToString[t]` function
* Add `toGraphviz` tests
* Add `pub def toGraphvizWeighted(g: m[((t, Int32, t))]): String with Foldable[m], Boxable[t], ToString[t]` function
* Add `toGraphvizWeighted` tests
=> feat: `Graph` graphviz functions

main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> fix: improve error source location

main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> refactor: add Ast.Constant and use in WeededAst

main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/src/ca/uwaterloo/flix/util/Validation.scala
depends on #4861, not because it actually depends on it, but because it introduces a bunch of Options
=> refactor: introduce Validation.traverseOpt

main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
=> refactor: introduce compileConstant

main/src/ca/uwaterloo/flix/language/phase/Namer.scala
This addresses the "uenv and ienv should be merged" portion of #4746
=> chore: Merge ImportEnv into UseEnv

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/Immutable.flix
=> feat: Add `Immutable` type class and add common instances

main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
does not yet use the LoweredAst. related to #4779
=> refactor: qualify AST nodes in Lowering and introduce LoweredAst

main/src/library/Array.flix, main/src/library/Prelude.flix
=> refactor: remove uses of reifyType from stdlib

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/ast/Locatable.scala, main/src/ca/uwaterloo/flix/language/ast/Symbol.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala
replaces #4820, related to #4890
=> refactor: introduce modules and names to TypedAst

main/src/library/DelayList.flix, main/src/library/DelayMap.flix, main/src/library/Map.flix, main/src/library/RedBlackTree.flix, main/src/library/Set.flix
=> refactor: replace reifyEff with typematch in stdlib

main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/phase/EarlyTreeShaker.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
=> fix: mark region vars as Impure inside regions in Monomorph

main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
Related to https://github.com/flix/flix/issues/4609
=> refactor: spawn n-1 threads for `ParYield`

main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala, main/test/flix/Test.Exp.TypeMatch.flix
=> fix: recursive cases for typematch

main/src/library/Boxed.flix, main/src/library/Chain.flix, main/src/library/Channel.flix, main/src/library/Comparison.flix, main/src/library/DelayList.flix, main/src/library/DelayMap.flix, main/src/library/Down.flix, main/src/library/Identity.flix, main/src/library/List.flix, main/src/library/Map.flix, main/src/library/MultiMap.flix, main/src/library/Nec.flix, main/src/library/Nel.flix, main/src/library/Option.flix, main/src/library/RedBlackTree.flix, main/src/library/Result.flix, main/src/library/Set.flix, main/src/library/Validation.flix, main/test/flix/Test.Exp.Concurrency.Buffered.flix, main/test/flix/Test.Exp.Concurrency.Unbuffered.flix
=> feat: Require `Immutable` for `Channel.send`

main/src/ca/uwaterloo/flix/language/phase/Typer.scala
=> fix: use synthetic locs for constants and new schemes

main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala, main/src/ca/uwaterloo/flix/language/dbg/FormatExpression.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Regions.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/src/ca/uwaterloo/flix/language/phase/Statistics.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
=> refactor: bring use expressions through Typer

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/language/ast/Symbol.scala, main/src/ca/uwaterloo/flix/language/ast/Type.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala
=> refactor: remove TypeVarSym

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala
=> refactor: bring namespace uses through typer

main/test/flix/Test.Exp.TryWith.flix
=> test: add tests for TryWith expression

main/src/ca/uwaterloo/flix/language/phase/Typer.scala
fixes some LSP coloring issues
=> fix: mark all fresh schemes tvars as synthetic

main/src/ca/uwaterloo/flix/api/lsp/provider/HoleCompletion.scala
=> feat: add HoleCompletion.candidates

examples/select-with-defaults-and-timers.flix, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/library/Channel.flix
This, I think, addresses the "Modify Typer to account for the region parameter and to place it in the effect of ChannelGet and ChannelPut." task of https://github.com/flix/flix/issues/4850
But draft because:
* I am not entirely confident that I've got the code in Typer correct
* I don't know what I should be doing with `select`
Advice gratefully received
=> feat: Channel effects

main/src/ca/uwaterloo/flix/language/errors/TypeError.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
=> feat: Custom MissingSender error

main/src/library/DelayMap.flix
=> refactor: use ParYield in DelayMap

main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/test/flix/Test.Exp.Jvm.InvokeStaticMethod.flix, main/test/flix/Test.Exp.Jvm.NewObject.flix
Is `null` treated as `unit`?
Closes https://github.com/flix/flix/issues/5003
=> test: use `super_cast` in more JVM tests

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
=> feat: removed case completions

main/test/flix/Test.Exp.TypeMatch.flix
=> test: add typematch tests for records

main/test/flix/Test.Exp.Concurrency.Select.flix
Fixes #5028
I don't know where to put the random debug bug so i left it out. I don't know what triggered this bug so I don't know how to do modifications of it
=> test: add regression test

main/src/ca/uwaterloo/flix/language/ast/ErasedAst.scala, main/src/ca/uwaterloo/flix/language/ast/FinalAst.scala, main/src/ca/uwaterloo/flix/language/ast/LiftedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/OccurrenceAst.scala, main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala, main/src/ca/uwaterloo/flix/language/dbg/PrettyPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala, main/src/ca/uwaterloo/flix/language/phase/EarlyTreeShaker.scala, main/src/ca/uwaterloo/flix/language/phase/Eraser.scala, main/src/ca/uwaterloo/flix/language/phase/Finalize.scala, main/src/ca/uwaterloo/flix/language/phase/Inliner.scala, main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala, main/src/ca/uwaterloo/flix/language/phase/LateTreeShaker.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala, main/src/ca/uwaterloo/flix/language/phase/OccurrenceAnalyzer.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala, main/src/ca/uwaterloo/flix/language/phase/VarNumbering.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
This fixes the "Add Expression.Region to all remaining ASTs." task of #4850
=> feat: Plumb Region through to code generation

main/src/ca/uwaterloo/flix/api/lsp/provider/CodeLensProvider.scala
Closes https://github.com/flix/flix/issues/4716
=> refactor: require entrypoint to be public in `CodeLensProvider`

main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> refactor: remove type from enum in early phases

main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Deriver.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala
=> refactor: remove redundant type variable from Var expression

main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
Related to https://github.com/flix/flix/issues/4609
=> feat: spawn n-1 threads for `ParTag`

main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/test/flix/Test.Exp.Par.flix
Closes https://github.com/flix/flix/issues/4609
=> refactor: do not spawn threads for literals or vars in `ParTag`

main/src/ca/uwaterloo/flix/api/lsp/provider/HoleCompletion.scala
=> feat: order hole completions by precision of types

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
It does not really help much since VSCode is being annoying and suggesting it anyway.
related to https://github.com/flix/flix/issues/4554#issuecomment-1344833498
=> fix: no completions after ```_```

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/runtime/CompilationResult.scala, main/src/ca/uwaterloo/flix/tools/BenchmarkCompiler.scala, main/src/ca/uwaterloo/flix/tools/SimpleRunner.scala, main/test/ca/uwaterloo/flix/TestMain.scala
=> feat: add `--Xbenchmark-frontend`

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/util/Options.scala, main/test/ca/uwaterloo/flix/TestMain.scala
=> feat: add `--Xqmc`

main/src/ca/uwaterloo/flix/language/phase/unification/UnificationCache.scala, main/src/ca/uwaterloo/flix/tools/BenchmarkCompiler.scala
=> feat: flush caches in BenchmarkCompiler

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
Related to https://github.com/flix/flix/issues/4554#issuecomment-1344833498
=> fix: type completions in ```[]``` and after ```type alias ... =```

main/src/ca/uwaterloo/flix/language/ast/ErasedAst.scala, main/src/ca/uwaterloo/flix/language/ast/FinalAst.scala, main/src/ca/uwaterloo/flix/language/ast/LiftedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/OccurrenceAst.scala, main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala, main/src/ca/uwaterloo/flix/language/dbg/PrettyPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala, main/src/ca/uwaterloo/flix/language/phase/EarlyTreeShaker.scala, main/src/ca/uwaterloo/flix/language/phase/Eraser.scala, main/src/ca/uwaterloo/flix/language/phase/Finalize.scala, main/src/ca/uwaterloo/flix/language/phase/Inliner.scala, main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala, main/src/ca/uwaterloo/flix/language/phase/LateTreeShaker.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala, main/src/ca/uwaterloo/flix/language/phase/OccurrenceAnalyzer.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala, main/src/ca/uwaterloo/flix/language/phase/VarNumbering.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
This just plumbs the expression through (it's not in use yet). Re #4850
=> feat: Plumb region expression through to codegen for use in spawn

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> chore: remove dead code

main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
=> refactor: remove redundant validations

main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala, main/src/ca/uwaterloo/flix/api/lsp/LocationLink.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/ImplementationProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/Symbol.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/errors/InstanceError.scala, main/src/ca/uwaterloo/flix/language/phase/Deriver.scala, main/src/ca/uwaterloo/flix/language/phase/Documentor.scala, main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala
=> refactor: replace InstanceSym with ClassSymUse

main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> refactor: introduce Declaration object in ResolvedAst

examples/print-a-colorful-message.flix, main/src/library/Benchmark.flix, main/src/library/Console.flix, main/src/library/Prelude.flix
Closes https://github.com/flix/flix/issues/5112
=> refactor: remove `print` from Prelude

main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/ClassMaker.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala, main/test/flix/Test.Exp.Concurrency.Spawn.flix
Further progress towards #4850
=> feat: Add spawn method to Region class and call it

examples/enums-and-parametric-polymorphism.flix, main/src/ca/uwaterloo/flix/language/ast/Name.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/ast/Symbol.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/src/library/DelayMap.flix, main/src/library/GetOpt.flix, main/src/library/Map.flix, main/src/library/RedBlackTree.flix, main/src/library/Set.flix, main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala, main/test/ca/uwaterloo/flix/library/TestFilterable.flix, main/test/ca/uwaterloo/flix/library/TestRedBlackTree.flix, main/test/ca/uwaterloo/flix/library/TestTraversable.flix
=> feat: put enum cases in the enum's companion namespace

main/src/ca/uwaterloo/flix/language/errors/WeederError.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> fix: remove leftover array length check

main/src/library/MutDeque.flix
=> chore: Remove (almost) all regionOfs from MutDequeue.flix

main/src/library/Array.flix, main/src/library/MutList.flix, main/test/ca/uwaterloo/flix/library/TestMutList.flix
=> chore: Remove (almost) all regionOfs from MutList.flix

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/Concurrent/Channel.flix, main/src/library/Concurrent/CyclicBarrier.flix
=> fix: Add rendezvous

examples/imperative-style-foreach-loops.flix, main/test/ca/uwaterloo/flix/library/TestArray.flix, main/test/ca/uwaterloo/flix/library/TestObject.flix, main/test/flix/Test.Exp.Concurrency.Spawn.flix, main/test/flix/Test.Exp.Jvm.InvokeConstructor.flix, main/test/flix/Test.Exp.Jvm.InvokeStaticMethod.flix, main/test/flix/Test.Exp.TypeMatch.flix, main/test/flix/Test.Java.Function.flix
Towards #5131
This PR addresses the "quick and easy" cases where we can get rid of Static.
=> chore: Get rid of the simple to fix instances of Static

main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/library/Concurrent/Channel.flix, main/test/ca/uwaterloo/flix/library/TestChannel.flix
As per discussion in #5175
A PR with just this change before moving on to the remainder
=> chore: Switch from an array to a list in channel code

examples/copying-characters-into-array-with-foreach.flix, main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/src/library/Array.flix, main/src/library/Chain.flix, main/src/library/DelayList.flix, main/src/library/File.flix, main/src/library/Fixpoint/Interpreter.flix, main/src/library/List.flix, main/src/library/MutDeque.flix, main/src/library/MutList.flix, main/src/library/Nec.flix, main/src/library/Reflect.flix, main/src/library/String.flix, main/test/ca/uwaterloo/flix/library/TestArray.flix, main/test/ca/uwaterloo/flix/library/TestRandom.flix, main/test/ca/uwaterloo/flix/library/TestToString.flix, main/test/flix/Test.Exp.Regions.flix
- Rework `Array.new` and `Array.repeat`.
- Add `Array.get`.
=> feat: rework array functions

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala, main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala, main/src/library/MutMap.flix, main/src/library/MutSet.flix
=> fix: bug in CodeHinter

.github/workflows/community-build.yaml
To try to help with rate limiting
=> ci: sleep in community build

main/src/ca/uwaterloo/flix/util/Validation.scala, main/test/ca/uwaterloo/flix/util/TestValidation.scala
This PR also rename SuccessWithFailure to SoftFailure. Thoughts?
Related to https://github.com/flix/flix/issues/5026
=> feat: add implicit method `toSoftFailure`

main/test/ca/uwaterloo/flix/language/phase/TestIncremental.scala
related to #4967; definitely the last one maybe
=> test: refactor incremental tests for namespace migration

main/src/library/Concurrent/Channel.flix, main/src/library/DelayMap.flix, main/src/library/File.flix, main/src/library/MultiMap.flix
=> refactor: remove use of implicit regions from standard library

main/src/ca/uwaterloo/flix/language/phase/Parser.scala
=> feat: allow mod keyword

main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/library/Choice.flix, main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala, main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala, main/test/flix/Test.Def.Generalization.flix, main/test/flix/Test.Exp.Choose.flix, main/test/flix/Test.Exp.ChooseStar.flix
=> feat: change choose syntax to relational_choose

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
related to #5226  
first-time PR , just learning the ropes here
=> feat: disable autocomplete for `???`  #5226

main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/test/flix/Test.Exp.Fixpoint.Compose.flix
=> fix: open datalog arguments

main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
Part of #5229
```
restrictable enum List<s>[a] {
case Nil
case Cons(a, Unit)
}
```
=> feat: parse restrictable enum

main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/Symbol.scala, main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala, main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala, main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala, main/src/ca/uwaterloo/flix/language/phase/Finalize.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala
=> feat: add restrictable enum symbol and type constructor

main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> feat: add restrictable enum to weeder

main/src/ca/uwaterloo/flix/language/ast/Kind.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatKind.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala, main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
=> feat: add kind for case sets

main/src/ca/uwaterloo/flix/api/lsp/provider/CodeLensProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala, main/src/ca/uwaterloo/flix/language/phase/Deriver.scala, main/src/ca/uwaterloo/flix/language/phase/Documentor.scala, main/src/ca/uwaterloo/flix/language/phase/EarlyTreeShaker.scala, main/src/ca/uwaterloo/flix/language/phase/EntryPoint.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
=> chore: remove expressions from annotations

main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> feat: add Cons of to pre-resolver phases

main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala, main/src/ca/uwaterloo/flix/language/dbg/FormatExpression.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Regions.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/src/ca/uwaterloo/flix/language/phase/Statistics.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
=> feat: add restrictable tag post-resolver

main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
=> feat: lower restrictable tag

main/src/ca/uwaterloo/flix/language/phase/jvm/AsmOps.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenAnonymousClasses.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenClosureClasses.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenLazyClasses.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenTagClasses.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenTupleClasses.scala
=> fix: Mark lazy expression as volatile

main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/Symbol.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> feat: add restrictable enum declarations to namer

main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
related to #5229. There is a TODO in there that is waiting on another PR but it would not hurt to merge as-is.
=> feat: perform resolution on choose expressions

main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala
=> feat: perform resolution on 'of' expression

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala
=> feat: add restrictableTag to typer

main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
=> chore: Reinstate virtual threads support

main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
=> feat: add restrictable tag to documentor

main/src/ca/uwaterloo/flix/language/errors/RedundancyError.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
=> feat: check uses of `restrictable enum`

main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
=> feat: perform kinding on restrictable variant declarations

main/src/ca/uwaterloo/flix/language/phase/Finalize.scala
=> feat: finalize restrictable tag types

main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> feat: add sym to restrictable vars choice rule

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/Kind.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/Type.scala, main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala, main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala, main/src/ca/uwaterloo/flix/language/phase/Finalize.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/inference/RestrictableChooseInference.scala, main/src/ca/uwaterloo/flix/language/phase/unification/RestrictableChooseInference.scala
=> feat: perform typechecking on choose expressions

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> fix: add restrictable cases to module list

main/src/ca/uwaterloo/flix/language/ast/Type.scala, main/src/ca/uwaterloo/flix/language/phase/inference/RestrictableChooseInference.scala
=> feat: support inference for choose* expressions

main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/inference/RestrictableChooseInference.scala
=> feat: type restrictable tags

main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/Symbol.scala, main/src/ca/uwaterloo/flix/language/ast/Type.scala, main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala, main/src/ca/uwaterloo/flix/language/errors/TypeError.scala, main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala, main/src/ca/uwaterloo/flix/language/phase/Finalize.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/inference/RestrictableChooseInference.scala, main/src/ca/uwaterloo/flix/language/phase/unification/BoolFormula.scala, main/src/ca/uwaterloo/flix/language/phase/unification/CaseSetUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala, main/src/ca/uwaterloo/flix/language/phase/unification/TypeMinimization.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/UnificationError.scala, main/test/ca/uwaterloo/flix/language/phase/unification/TestCaseSetUnification.scala
=> feat: case set unification

main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
=> feat: perform stratification on restrictable choose rule

main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/inference/RestrictableChooseInference.scala
=> feat: perform type inference on 'of' expression

build.gradle
=> chore: Use strict versioning for Scala

main/src/ca/uwaterloo/flix/language/phase/inference/RestrictableChooseInference.scala
=> docs: add some documentation to RestrictableChooseInference

main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala, main/src/ca/uwaterloo/flix/language/dbg/FormatExpression.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Regions.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/src/ca/uwaterloo/flix/language/phase/Statistics.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
=> feat: handle 'of' expression after typing

main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala
=> feat: Add restrictable enums map to Typer

main/src/ca/uwaterloo/flix/language/phase/Inliner.scala
=> chore: add todo

main/src/ca/uwaterloo/flix/language/phase/inference/RestrictableChooseInference.scala, main/src/ca/uwaterloo/flix/language/phase/unification/CaseSetUnification.scala
=> fix: change choose star rule

main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/errors/RedundancyError.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/src/library/Result.flix, main/src/library/Validation.flix, main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
=> feat: add `@MustUse` annotation

main/src/ca/uwaterloo/flix/language/ast/Type.scala
=> fix: fix intersection construction

main/src/ca/uwaterloo/flix/language/phase/inference/RestrictableChooseInference.scala
=> feat: omit typing rule on trivial conditions

main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/src/ca/uwaterloo/flix/language/phase/inference/RestrictableChooseInference.scala, main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala, main/test/flix/Test.Exp.Choose.Polymorphic.flix, main/test/flix/Test.Exp.Choose.Recursive.flix, main/test/flix/Test.Exp.Choose.Simple.flix, main/test/flix/Test.Exp.Choose.SimpleTerms.flix, main/test/flix/Test.Exp.ChooseStar.Polymorphic.flix, main/test/flix/Test.Exp.ChooseStar.Simple.flix
=> feat: add tag open expression

main/src/ca/uwaterloo/flix/language/phase/unification/SetFormula.scala, main/src/ca/uwaterloo/flix/language/phase/unification/SetFormulaAlg.scala
Related to #5229 
Add simple SetFormula objects based on BoolFormula. Vars are simple integers and constants are sets of integers as well using the same mechanism. This should make thing easy in the set formula world and keep the translation simple too.
=> feat: primitive set formula

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/HoleCompletion.scala, main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/Scheme.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/phase/EntryPoint.scala, main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/inference/RestrictableChooseInference.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala, main/src/ca/uwaterloo/flix/language/phase/unification/ClassEnvironment.scala, main/src/ca/uwaterloo/flix/language/phase/unification/RecordUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/SchemaUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala, main/test/ca/uwaterloo/flix/language/phase/unification/TestUnification.scala
=> feat: allow non-expr restrictable enums

main/src/ca/uwaterloo/flix/language/phase/unification/CaseSetUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala
=> fix: finish removing case set hack

main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/Type.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
removes a few TODOs that are hanging about
=> chore: remove TODOs

main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> feat: allow parsing of custom kinds

main/src/ca/uwaterloo/flix/language/phase/inference/RestrictableChooseInference.scala, main/test/flix/Test.Exp.ChooseStar.Simple.flix
=> fix: `choose*` typing

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/HoleCompletion.scala, main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/Scheme.scala, main/src/ca/uwaterloo/flix/language/ast/Symbol.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/phase/EntryPoint.scala, main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/inference/RestrictableChooseInference.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala, main/src/ca/uwaterloo/flix/language/phase/unification/CaseSetUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/ClassEnvironment.scala, main/src/ca/uwaterloo/flix/language/phase/unification/RecordUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/SchemaUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/SetFormula.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala, main/test/ca/uwaterloo/flix/language/phase/unification/TestCaseSetUnification.scala, main/test/ca/uwaterloo/flix/language/phase/unification/TestUnification.scala
=> refactor: add universe to restrictable enum sym

main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> fix: fix case difference weeder bug

main/src/ca/uwaterloo/flix/language/phase/unification/CaseSetUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/SetFormula.scala, main/test/ca/uwaterloo/flix/language/phase/unification/TestCaseSetUnification.scala
=> feat: support rigidity in case set unification

main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
=> fix: Lower & monomorph restrictable tags

main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/inference/RestrictableChooseInference.scala
=> feat: Remove `choose*` body exp check

main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/test/flix/Test.Exp.Choose.Simple.flix, main/test/flix/Test.Exp.ChooseStar.Simple.flix
Related to #5229 
I've transformed a Unit pattern into a wild pattern to avoid expanding the AST's
=> feat: allow unit constants in restrictable tag patterns

main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala, main/src/ca/uwaterloo/flix/language/dbg/FormatExpression.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Regions.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/src/ca/uwaterloo/flix/language/phase/Statistics.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala, main/src/ca/uwaterloo/flix/language/phase/inference/RestrictableChooseInference.scala
=> feat: add open_as expression

main/test/flix/Test.Exp.ChooseStar.Polymorphic.flix
=> test: enable one more RV test

main/src/resources/benchmark/BenchmarkList.flix
=> test: fix benchmarks

main/test/flix/Test.Def.ChooseStar.Simple.flix
=> test: add some type signature tests

main/src/resources/benchmark/BenchmarkConstraint.flix, main/src/resources/benchmark/BenchmarkMap.flix, main/src/resources/benchmark/BenchmarkSet.flix, main/test/ca/uwaterloo/flix/BenchmarkSuite.scala
=> test: create BenchmarkSuite

main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
=> test: add RV test

main/src/ca/uwaterloo/flix/util/Validation.scala, main/test/ca/uwaterloo/flix/util/TestValidation.scala
Related to https://github.com/flix/flix/issues/5026#issuecomment-1407690857
=> feat: add `Validation.softRecoverOne`

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
Related to https://github.com/flix/flix/issues/5026
=> feat: improve error handling in Resolver

AUTHORS.md, main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/KeywordCompleter.scala
Refactored getKeywordCompletions and keywordCompletions into a new scala object KeywordCompletor.
=> refactor: CompletionProvider

main/src/ca/uwaterloo/flix/language/ast/ErasedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Eraser.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
=> feat: add intrinsics to `ErasedAst`

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EffectCompleter.scala
Refactored `CompletionProvider` into `EffectCompleter` for issue https://github.com/flix/flix/issues/5437 .
=> refactor: Add `EffectCompleter`

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/BuiltinTypeCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EffectCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/FieldCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/KeywordCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/PredicateCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/TypeCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/WithCompleter.scala
Added `WithCompleter` for issue https://github.com/flix/flix/issues/5437 .
Also changed all other `Completer`s to return the specific type of `Completion`. `KeywordCompleter` now returns a `KeywordCompletion`, and so forth for the rest.
=> refactor: Add `WithCompleter`

main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
Related to https://github.com/flix/flix/issues/5207
=> refactor: harmonize `ParsedAst` field names

main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/BuiltinTypeCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EffectCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/FieldCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/KeywordCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/PredicateCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/TypeCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/WithCompleter.scala
Fixes https://github.com/flix/flix/issues/4934
=> refactor: use `Option[Root]` in `CompletionProvider`

main/src/ca/uwaterloo/flix/language/phase/jvm/GenTupleClasses.scala
As found by @Sintrastes, our code relies on some weird coersion, so I've rewritten the toString of tuple, which should also be more null resistant
=> refactor: fix jvm tuple string

main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/test/flix/Test.Exp.ForYield.flix
Related to https://github.com/flix/flix/issues/5464
=> refactor: change `Monadic For` syntax to `forM`

main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/GotoProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala
Related to https://github.com/flix/flix/issues/4934
=> refactor: use `Option[Root]` in `XProvider`

main/src/ca/uwaterloo/flix/language/phase/Safety.scala
=> feat: rework `Safety` and use `SoftFailure` in it

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ClassCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
=> refactor: Add `ClassCompleter`

main/src/ca/uwaterloo/flix/language/ast/ErasedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Eraser.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
Related to https://github.com/flix/flix/issues/5434
=> refactor: move `ErasedAst.Exp.Is` into `ErasedAst.Intrinsic`

main/src/ca/uwaterloo/flix/language/phase/Typer.scala
=> feat: use `SoftFailure` in `Typer`

main/src/ca/uwaterloo/flix/language/ast/ErasedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Eraser.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
Related to https://github.com/flix/flix/issues/5434
=> refactor: move exps to `ErasedAst.IntrinsicOperator1`

main/src/ca/uwaterloo/flix/language/ast/ErasedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Eraser.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenAnonymousClasses.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
Related to https://github.com/flix/flix/issues/5434
=> refactor: move exps to `ErasedAst.IntrinsicOperator0`

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/DefCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/OpCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/SignatureCompleter.scala
=> refactor: Add `DefCompleter`, `SignatureCompleter` and `OpCompleter`

main/src/ca/uwaterloo/flix/api/Bootstrap.scala, main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala, main/src/ca/uwaterloo/flix/tools/Packager.scala, main/src/ca/uwaterloo/flix/tools/SimpleRunner.scala, main/test/ca/uwaterloo/flix/TestUtils.scala, main/test/ca/uwaterloo/flix/language/phase/TestIncremental.scala, main/test/ca/uwaterloo/flix/util/FlixSuite.scala
=> refactor: rework add source and path functions

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/UseCompleter.scala
=> refactor: Add `UseCompleter`

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ClassCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/DefCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EffectCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/FieldCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ImportFieldCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ImportMethodCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ImportNewCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/InstanceCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/KeywordCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/MatchCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/OpCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/PredicateCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/SignatureCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/SnippetCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/TypeAliasCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/TypeBuiltinCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/TypeCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/TypeEnumCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/UseCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/VarCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/WithCompleter.scala
=> refactor: Changed signature for `getCompletions` and `toCompletionItem`

main/src/ca/uwaterloo/flix/language/phase/Instances.scala
Fixes #5502
I think that this is all that's required here? I'm not sure whether there are any tests I could write that would be relevant?
=> chore: Return SoftFailure from Instances

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/Ref.flix, main/test/ca/uwaterloo/flix/library/TestRef.flix
Fixes https://github.com/flix/flix/issues/5194
=> feat: add `Ref` module

main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
=> feat: disable some redundancy checks when errors are present in a def

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionContext.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/FromErrorsCompleter.scala
Also resolved some warnings in the code, and made the code more readable.
=> refactor: Add `FromErrorsCompleter` and changed signature for `CompletionContext`

main/src/ca/uwaterloo/flix/language/errors/WeederError.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
=> feat: ensure alias casing matches original name

main/src/ca/uwaterloo/flix/language/ast/ErasedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Eraser.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
Related to https://github.com/flix/flix/issues/5564
=> refactor: move exps to `ErasedAst.Intrinsic`

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> refactor: remove unused allowCases parameter from Resolution lookups

main/src/ca/uwaterloo/flix/tools/pkg/FlixPackageManager.scala, main/src/ca/uwaterloo/flix/tools/pkg/PackageError.scala, main/test/ca/uwaterloo/flix/tools/TestFlixPackageManager.scala
=> fix: throw error when no file can be downloaded in Package Manager

main/src/ca/uwaterloo/flix/api/lsp/provider/HoleCompletion.scala, main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/Scheme.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatScheme.scala, main/src/ca/uwaterloo/flix/language/phase/Deriver.scala, main/src/ca/uwaterloo/flix/language/phase/Documentor.scala, main/src/ca/uwaterloo/flix/language/phase/EntryPoint.scala, main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala, main/src/ca/uwaterloo/flix/language/phase/unification/ClassEnvironment.scala, main/src/ca/uwaterloo/flix/language/phase/unification/InferMonad.scala, main/src/ca/uwaterloo/flix/language/phase/unification/RecordUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/SchemaUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala, main/src/ca/uwaterloo/flix/language/phase/unification/TypeMinimization.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala, main/src/ca/uwaterloo/flix/util/Result.scala, main/test/ca/uwaterloo/flix/language/phase/unification/TestUnification.scala, main/test/flix/experimental/Test.Dec.AssocType.flix
=> feat: implement unification for associated types

main/src/ca/uwaterloo/flix/Main.scala, main/test/ca/uwaterloo/flix/TestMain.scala
=> chore: remove `--output` flag

main/src/ca/uwaterloo/flix/api/Bootstrap.scala, main/test/ca/uwaterloo/flix/tools/TestBootstrap.scala
=> feat: emit packages and jars to `artifact` directory

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/api/Bootstrap.scala, main/src/ca/uwaterloo/flix/runtime/shell/Command.scala, main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala, main/test/ca/uwaterloo/flix/tools/TestBootstrap.scala
=> feat: re-enable package commands in shell

main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/Scheme.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/src/ca/uwaterloo/flix/language/phase/unification/InferMonad.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
=> feat: add syntax for equality constraints

main/src/ca/uwaterloo/flix/language/phase/Documentor.scala
=> fix: fix typo in Documentor

main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/Type.scala, main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala, main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala, main/src/ca/uwaterloo/flix/language/phase/Regions.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
related to #5647
(forgot this part)
=> refactor: reduce associated type parameters to 1, part II

main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala
=> refactor: use AssocTypeSymUse after Resolver

main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/Scheme.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/phase/EntryPoint.scala, main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/unification/AssocTypeSubstitution.scala, main/src/ca/uwaterloo/flix/language/phase/unification/ClassEnvironment.scala, main/src/ca/uwaterloo/flix/language/phase/unification/EqualityEnvironment.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/UnificationError.scala
depends on #5695 
related to #5647
=> feat: check equality constraints in Typer

main/src/ca/uwaterloo/flix/language/errors/TypeError.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatEqualityConstraint.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatScheme.scala
=> feat: add econstrs to scheme formatting

main/src/ca/uwaterloo/flix/language/fmt/FormatScheme.scala
=> fix: fix wording on scheme formatting

main/src/ca/uwaterloo/flix/language/phase/unification/EqualityEnvironment.scala, main/test/flix/experimental/Test.Dec.AssocType.flix
=> fix: fix entailment check on associated types

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/unification/EqualityEnvironment.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala, main/test/ca/uwaterloo/flix/language/phase/unification/TestAssocTypeUnification.scala, main/test/flix/experimental/ExperimentalSuite.scala, main/test/flix/experimental/Test.Dec.AssocType.flix
=> fix: fix monomorphization problems with associated types

main/src/ca/uwaterloo/flix/language/errors/WeederError.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
=> fix: add proper errors for associated types in Weeder

main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
=> fix: add resolver errors for associated types

main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
=> fix: add undefined kind error

main/src/ca/uwaterloo/flix/api/lsp/Entity.scala, main/src/ca/uwaterloo/flix/api/lsp/Index.scala, main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/FindReferencesProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/GotoProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/RenameProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala
=> feat: add LSP operations for associated types

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/library/Boxable.flix
=> chore: rework `Boxable.liftXY`

main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala
=> fix: bug in PatternExhaustiveness.scala

main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
=> fix: ensure termination for assoc type resolution

main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
=> fix: fix uncaught ambiguity in assoc types

main/test/ca/uwaterloo/flix/tools/TestFlixPackageManager.scala, main/test/ca/uwaterloo/flix/tools/TestMavenPackageManager.scala
=> refactor: Rework package manager tests to use flix/museum

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/VarRanker.scala
=> feat: Add `VarRanker`

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/DefRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Differ.scala
=> feat: Add `DefRanker`

main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/CompletionRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/DefRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/Differ.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/EnumTagRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/FieldRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/MatchRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/TypeEnumRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/VarRanker.scala
=> chore: Added rankers and provided 'best pick' information to the user

main/src/ca/uwaterloo/flix/api/lsp/Entity.scala, main/src/ca/uwaterloo/flix/api/lsp/Index.scala, main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala
=> refactor: rename AssociatedType* to AssocType*

build.gradle
Split from https://github.com/flix/flix/pull/5751
CVEs:
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-8908
=> chore: guava: 25.1 → 31.1

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
Also fixed a small issue with the split.
=> refactor: Refactored the boosting of bestComp into a separate function

build.gradle
split from https://github.com/flix/flix/pull/5751
CVEs:
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-11050
=> chore: Java-WebSocket: 1.3.9 → 1.5.3

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/api/Bootstrap.scala, main/test/ca/uwaterloo/flix/tools/TestBootstrap.scala
=> fix: args with run

main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/test/flix/experimental/Test.Dec.AssocType.flix
related to #5647. Also fixes a bug.
=> test: add associate type tests

main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
Related to https://github.com/flix/flix/issues/5713
=> refactor: remove `compileArithmeticExpr`

main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala, main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
just removing some unused code I encountered
=> chore: remove unused code

main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
Instead of nesting visits inside specialize, they're their own methods with implicit mutable objects
The diff is a mess, but I've functionally changed the one weird occurrence of `subst0` to `subst` and added `Def2Def` and `DefQueue` to implicit arguments
=> refactor: un-nest monomorph

main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
`specializedDefns` doesn't have to be in the Context currently (only used inside run locally) but if we monomorph enums "inline" (without a task queue) then helper methods will need the `specializedEnums` map and thus I put the `specializedDefns` map inside context for future consistency.
=> refactor: collect context in monomorph

main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
Closes https://github.com/flix/flix/issues/5846
=> refactor: inline `readVar` in GenExpression

main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
Closes https://github.com/flix/flix/issues/5847
=> refactor: remove `compileConstant` in GenExpression

main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala
Also:
* remove some unused variables
* remove some unused functions
=> fix: missing type substitutions in monomorph

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/CompletionRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/DefRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/EnumTagRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/FieldRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/Ranker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/TypeEnumRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/VarRanker.scala
Introduced an interface for all `Ranker`s.
Also changed the order of the priority for the different rankers in `CompletionRanker`.
=> refactor: introduced interface `Ranker`

main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
Closes https://github.com/flix/flix/issues/5848
=> refactor: remove `compileUnaryExpr`

main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
Closes https://github.com/flix/flix/issues/5713
=> refactor: add helper functions for comparison gode gen

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/tools/SimpleRunner.scala, main/test/ca/uwaterloo/flix/TestMain.scala, main/test/ca/uwaterloo/flix/tools/TestFlixPackageManager.scala
=> chore: remove `--benchmark` and `--test`

main/src/library/Array.flix, main/src/library/Benchmark.flix, main/src/library/Chain.flix, main/src/library/Debug.flix, main/src/library/DelayList.flix, main/src/library/DelayMap.flix, main/src/library/Environment.flix, main/src/library/File.flix, main/src/library/Foldable.flix, main/src/library/Graph.flix, main/src/library/List.flix, main/src/library/Map.flix, main/src/library/MultiMap.flix, main/src/library/MutDeque.flix, main/src/library/MutList.flix, main/src/library/MutMap.flix, main/src/library/MutSet.flix, main/src/library/Nec.flix, main/src/library/Nel.flix, main/src/library/RedBlackTree.flix, main/src/library/Set.flix, main/src/library/String.flix, main/src/library/Traversable.flix
=> chore: rename `region r`/` region rh` to ` region rc`

main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> chore: remove record selection lambda

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/tools/SimpleRunner.scala
Related to https://github.com/flix/flix/pull/5694
=> refactor: remove `getCode` in `Main`

build.gradle
=> fix: disable SLF4J warning

main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/errors/CodeHint.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala, main/src/library/Channel.flix, main/src/library/Debug.flix, main/src/library/Reflect.flix
=> chore: drop `@Unsafe` annotation

main/src/library/File.flix
=> fix: File.write inserts newline

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/tools/SocketServer.scala, main/src/ca/uwaterloo/flix/util/Options.scala, main/test/ca/uwaterloo/flix/ExampleSuite.scala, main/test/flix/experimental/ExperimentalSuite.scala
=> chore: remove `Options.xallowredundancies`

main/src/ca/uwaterloo/flix/language/errors/InstanceError.scala, main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/test/ca/uwaterloo/flix/language/phase/TestInstances.scala, main/test/flix/Test.Dec.Class.flix
This simplifies things. The same idea can later be achieved with associated types.
=> feat: remove special rule for Booleans in instances

main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala
also touches some other related TODOs
=> test: reenable some effect-related tests

examples/larger-examples/restrictable-variants/sequences.flix, examples/select-with-defaults-and-timers.flix, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala, main/test/ca/uwaterloo/flix/library/TestArray.flix, main/test/ca/uwaterloo/flix/library/TestMutList.flix, main/test/flix/Test.Exp.CheckedTypeCast.flix, main/test/flix/Test.Exp.Concurrency.Select.flix, main/test/flix/Test.Exp.Let.Rec.flix, main/test/flix/Test.Exp.Scope.flix, main/test/flix/Test.Exp.UncheckedTypeCast.flix
=> chore: remove Read/Write types

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EnumTagCompleter.scala
https://github.com/flix/flix/issues/5957
=> feat: Show type of tag in `EnumTagCompleter`

main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala, main/test/flix/Test.Exp.Concurrency.Select.flix, main/test/flix/Test.Exp.Let.Rec.flix
=> fix: check types in nested defs

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EnumCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ModuleCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ModuleSymFragment.scala
=> fix: rework `ModuleCompleter`

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/MatchCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/CompletionRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/DefRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/EnumTagRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/FieldRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/MatchRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/Ranker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/TypeEnumRanker.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/VarRanker.scala
=> feat: Introduced `MatchRanker`

main/src/ca/uwaterloo/flix/language/phase/jvm/GenClosureClasses.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenFunctionClasses.scala
Closes https://github.com/flix/flix/issues/5850
=> refactor: rework `GenExpression.compileExpression` signature

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EnumTagCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/EnumTagRanker.scala
=> fix: Label shows argument types and detail shows enum type in `EnumTagCompleter`

main/src/ca/uwaterloo/flix/language/ast/SemanticOperator.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/OperatorPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala, main/src/library/Add.flix
Related to https://github.com/flix/flix/issues/5709
=> refactor: remove `$BIGING_ADD$`

main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
Closes https://github.com/flix/flix/issues/5856
=> refactor: remove special case from `Tag` in `GenExpression`

main/src/ca/uwaterloo/flix/language/dbg/DocAstFormatter.scala
Part of #5972
* change `branching {...}` to `branch {...}`
* change `label something:` so `something:`
=> feat: reformat pretty branch

main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala, main/src/ca/uwaterloo/flix/language/phase/EarlyTreeShaker.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Regions.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala, main/src/ca/uwaterloo/flix/language/phase/Statistics.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
Unused expression taking up space
=> chore: remove Wild expression

main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala, main/test/flix/Test.Def.Generalization.flix, main/test/flix/Test.Exp.Fixpoint.flix
Closes https://github.com/flix/flix/issues/4287
=> feat: add Safety Error for non-unit parameter test

main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/InstanceCompleter.scala, main/src/ca/uwaterloo/flix/language/ast/Type.scala, main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala, main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatEff.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatSignature.scala, main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala, main/src/ca/uwaterloo/flix/language/phase/Deriver.scala, main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/MonoTyper.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala, main/src/ca/uwaterloo/flix/language/phase/Regions.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala, main/src/ca/uwaterloo/flix/language/phase/unification/BddFormulaAlg.scala, main/src/ca/uwaterloo/flix/language/phase/unification/BoolAlg.scala, main/src/ca/uwaterloo/flix/language/phase/unification/BoolFormula.scala, main/src/ca/uwaterloo/flix/language/phase/unification/BoolFormulaAlg.scala, main/src/ca/uwaterloo/flix/language/phase/unification/BoolUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala, main/test/ca/uwaterloo/flix/language/phase/unification/TestUnification.scala
=> chore: rename effect types

main/src/ca/uwaterloo/flix/language/phase/unification/AssocTypeSubstitution.scala, main/src/ca/uwaterloo/flix/language/phase/unification/BoolSubstitution.scala, main/src/ca/uwaterloo/flix/language/phase/unification/CaseSetSubstitution.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala
=> fix: remove redundancy in substitution

main/src/ca/uwaterloo/flix/language/ast/SemanticOperator.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/OperatorPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala, main/src/library/BigInt.flix, main/src/library/Div.flix, main/src/library/Eq.flix, main/src/library/Mul.flix, main/src/library/Neg.flix, main/src/library/Order.flix, main/src/library/PartialOrder.flix, main/src/library/Sub.flix
Related to https://github.com/flix/flix/issues/5709
=> refactor: remove `BigIntOp`

AUTHORS.md
=> chore: update AUTHORS.md

main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala, main/src/library/Nec.flix, main/src/library/Order.flix, main/test/ca/uwaterloo/flix/language/phase/TestPatExhaustiveness.scala
=> fix: do not count guarded rules for exhaustiveness

main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/src/ca/uwaterloo/flix/language/phase/unification/BoolUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/EffUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
=> chore: rename Boolean/effect types and unification

main/src/library/Vector.flix, main/test/ca/uwaterloo/flix/library/TestVector.flix
=> feat: add `Vector.splitAt`

main/src/ca/uwaterloo/flix/language/phase/unification/TypeNormalization.scala
=> fix: perform type normalization on booleans

main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
=> chore: remove ambiguous tag error

main/src/ca/uwaterloo/flix/language/ast/LiftedAst.scala, main/src/ca/uwaterloo/flix/language/ast/OccurrenceAst.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/LiftedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/Inliner.scala, main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala, main/src/ca/uwaterloo/flix/language/phase/OccurrenceAnalyzer.scala, main/src/ca/uwaterloo/flix/language/phase/Reducer.scala
=> refactor: LiftedAst & OccurrenceAst def return type

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/KeywordOtherCompleter.scala, main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala, main/src/ca/uwaterloo/flix/language/phase/Documentor.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
=> chore: remove `opaque` modifier

main/src/ca/uwaterloo/flix/language/dbg/printer/MonoTypedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/Eraser.scala, main/src/ca/uwaterloo/flix/language/phase/MonoTyper.scala, main/src/ca/uwaterloo/flix/language/phase/Verifier.scala
Wanted to do erasedAst also but that is a bit more involved so i left this for itself
=> refactor: MonoTypedAst def return type

main/src/ca/uwaterloo/flix/language/ast/ErasedAst.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/ErasedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/Eraser.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenClosureClasses.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenFunctionClasses.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenMainClass.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenNamespaceClasses.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
I've added the arrow type to the Def case class to avoid recomputation.
=> refactor: ErasedAst def type

main/src/ca/uwaterloo/flix/language/ast/ReducedAst.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/ReducedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/MonoTyper.scala, main/src/ca/uwaterloo/flix/language/phase/Reducer.scala, main/src/ca/uwaterloo/flix/language/phase/VarNumbering.scala
Related to https://github.com/flix/flix/pull/6148/files
=> refactor: use `AtomicOp.Closure` in `ReducedAst`

main/src/ca/uwaterloo/flix/language/ast/LiftedAst.scala, main/src/ca/uwaterloo/flix/language/ast/OccurrenceAst.scala, main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/LiftedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/Inliner.scala, main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala, main/src/ca/uwaterloo/flix/language/phase/LateTreeShaker.scala, main/src/ca/uwaterloo/flix/language/phase/OccurrenceAnalyzer.scala, main/src/ca/uwaterloo/flix/language/phase/Reducer.scala
Closes https://github.com/flix/flix/issues/6147
=> refactor: use `AtomicOp` in `LiftedAst` pt. 3

main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> feat: add type-level `xor`

main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/SimplifiedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala, main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
Supersedes https://github.com/flix/flix/pull/6129
Related to #6112
=> refactor: use `AtomicOp` in `SimplifiedAst` pt. 1

main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala, main/src/ca/uwaterloo/flix/language/dbg/DocAst.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/LiftedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/SimplifiedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala, main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
Related to https://github.com/flix/flix/issues/6112
=> refactor: use `AtomicOp` in `SimplifiedAst` pt. 2

main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/SimplifiedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala, main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
Closes https://github.com/flix/flix/issues/6112
=> refactor: use `AtomicOp` in `SimplifiedAst` pt. 3

main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
Closes https://github.com/flix/flix/issues/6049
=> refactor: eliminate `StringOp.Concat` in `Simplifier`

main/src/ca/uwaterloo/flix/language/phase/unification/BoolFormula.scala, main/src/ca/uwaterloo/flix/language/phase/unification/SimpleBoolFormulaAlgClassic.scala, main/src/ca/uwaterloo/flix/language/phase/unification/TypeMinimization.scala
=> fix: perform minimization on Bool types

main/src/library/Time/Instant.flix
Related to https://github.com/flix/flix/issues/5025
=> feat: add `ToString` instance to `Time.Instant`

main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/LoweredAstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/EarlyTreeShaker.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala, main/src/ca/uwaterloo/flix/language/phase/MonomorphEnums.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
Closes https://github.com/flix/flix/issues/6161
=> refactor: use `AtomicOp` in `LoweredAst` pt. 3

main/src/ca/uwaterloo/flix/language/ast/LiftedAst.scala, main/src/ca/uwaterloo/flix/language/ast/OccurrenceAst.scala, main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/ErasedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/LiftedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/Eraser.scala, main/src/ca/uwaterloo/flix/language/phase/Inliner.scala, main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala, main/src/ca/uwaterloo/flix/language/phase/LateTreeShaker.scala, main/src/ca/uwaterloo/flix/language/phase/OccurrenceAnalyzer.scala, main/src/ca/uwaterloo/flix/language/phase/Reducer.scala, main/src/ca/uwaterloo/flix/language/phase/Tailrec.scala
Closes https://github.com/flix/flix/issues/5824
=> refactor: use `Ast.CallType` in `LiftedAst`

main/src/library/String.flix, main/test/ca/uwaterloo/flix/library/TestString.flix
=> feat: add `String.center`

main/test/ca/uwaterloo/flix/library/TestRef.flix, main/test/flix/Test.Exp.CheckedEffectCast.flix, main/test/flix/Test.Exp.CheckedTypeCast.flix, main/test/flix/Test.Exp.Discard.flix, main/test/flix/Test.Exp.IfThenElse.flix, main/test/flix/Test.Exp.Let.Rec.flix, main/test/flix/Test.Exp.UncheckedEffectCast.flix, main/test/flix/Test.Exp.UncheckedMaskingCast.flix, main/test/flix/Test.Exp.UncheckedTypeCast.flix
=> refactor: `region rh` -> `region rc`

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/UseCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/UseEffCompleter.scala
++ doesnt seem to work on multiple lines, so for now I am jamming the uses in one line.
I also wasn't sure what do use for `kind` in `case Completion.UseEffCompletion`'s expression, but `enum` seems to work.
=> feat: add UseEffCompleter

main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala, main/test/flix/Test.Assoc.Type.flix
=> feat: add simplfied associated type syntax

main/src/ca/uwaterloo/flix/tools/pkg/MavenPackageManager.scala
=> fix: maven JAR paths

main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
=> fix: weeder error for empty char literals

main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
This proposes quickfix actions to add `use` statements for classes, effects and types.
It doesn't take into consideration whether they are public though.
=> feat: add more `use` code actions

main/src/ca/uwaterloo/flix/language/phase/Verifier.scala
=> chore: support `AtomicOps` in `Verifier`

main/src/ca/uwaterloo/flix/api/CrashHandler.scala, main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala, main/src/ca/uwaterloo/flix/api/lsp/ResponseStatus.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/CodeLensProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/FindReferencesProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/GotoProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/RenameProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
Related to flix/vscode-flix#202
=> feat: report compiler crash in LSP

main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala, main/src/ca/uwaterloo/flix/language/errors/RedundancyError.scala
Proposes to prefix certain unused symbols with a `_`
=> feat: add code actions for unused symbols

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/UseCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/UseSignatureCompleter.scala
=> feat: UseSignatureCompleter (relates to #6265)

main/src/ca/uwaterloo/flix/language/dbg/printer/ReducedAstPrinter.scala
Closes https://github.com/flix/flix/issues/6243
=> feat: add `JvmMethod` printer in `ReducedAstPrinter`

main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
Closes https://github.com/flix/flix/issues/5820
=> refactor: make Vector exprs pure

main/src/library/DelayList.flix
=> refactor: rename `DelayList.point` to `singleton`

main/src/ca/uwaterloo/flix/api/lsp/provider/CodeLensProvider.scala
=> chore: add symbol to 'Run' lense

main/src/library/Regex.flix, main/test/ca/uwaterloo/flix/library/TestRegex.flix
=> feat: introduce `Regex.indexOfFirstWithBounds` and `indexOfLastWithBounds`

main/src/ca/uwaterloo/flix/language/phase/PatternExhaustiveness.scala
Closes https://github.com/flix/flix/issues/6290
=> refactor: remove `numArgs` in `PatternExhaustiveness`

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/api/Bootstrap.scala, main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala, main/src/ca/uwaterloo/flix/language/phase/JsonDocumentor.scala, main/src/ca/uwaterloo/flix/util/Options.scala, main/test/ca/uwaterloo/flix/TestMain.scala
=> feat: introduce `doc` command

main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala, main/src/resources/doc/styles.css
=> feat: improve HTML documentation

main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
=> fix: write assets after generating HTML documentation

main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
=> chore: move effects right after classes in HTML documentation

main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
=> feat: show effect operations by default in HTML documentation

main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
=> feat: save prelude as index.html in HTML documentation

main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
Value
```java
package dev.flix.runtime;
public final class Value implements Result {
public boolean    b;
public char       c;
public byte       i8;
public short      i16;
public int        i32;
public long       i64;
public float      f32;
public double     f64;
public Object     o;
}
```
Result
```java
package dev.flix.runtime;
public interface Result { }
```
Suspension requires more prerequisites so that'll be later
=> feat: gen Value and Result

main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
Frame
```java
package dev.flix.runtime;
public interface Frame {
Result apply(Value var1);
}
```
=> feat: gen Frame

main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
Related to https://github.com/flix/flix/issues/5917
=> refactor: remove special cases in codegen for `AtomicOp.New`

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/IOError.flix, main/src/library/Reader.flix
=> feat: add `Reader.flix`

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/phase/EarlyTreeShaker.scala, main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/src/ca/uwaterloo/flix/language/phase/Optimizer.scala, main/src/ca/uwaterloo/flix/language/phase/Reducer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Statistics.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/VarNumbering.scala, main/src/ca/uwaterloo/flix/util/Duration.scala, main/src/library/Benchmark.flix
Trying to read through the phases to understand how the compiler work but my IntelliJ is showing a lot of warnings - I disabled a bunch of them but there are a few that seems worth fixing so here's this most useless pull request that tries to appease the linter.
=> chore: random spelling and lint fixes

main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala, main/src/resources/doc/styles.css
=> feat: add link to parent module

main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/test/flix/Test.Exp.CheckedTypeCast.flix
=> fix: allow safe casting with arrays

main/src/ca/uwaterloo/flix/language/phase/jvm/BytecodeInstructions.scala
This is unsused code atm but needed for next PR
=> feat: add `xSwap`

main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala, main/src/resources/doc/styles.css
=> feat: move classes to own page in HTML documentation

main/src/ca/uwaterloo/flix/language/ast/Symbol.scala, main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorph.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala
=> fix: give unique IDs to instance definitions

main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala, main/src/resources/doc/styles.css
Related to https://github.com/flix/flix/issues/6327
=> feat: put effects on their own page in HTML documentation

main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
=> feat: display associated types in HTML documentation

main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
=> feat: display equality constraints in HTML documentation

main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala, main/src/resources/doc/styles.css
=> feat: add link to class in type constraint in HTML documentation

main/src/resources/doc/index.js
* Hide side bar menu when an anchor link is clicked
* Deactivate all interactions for the main area when side bar menu is shown
=> feat: improve mobile menu interactions in HTML documentation

main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
Still not happy about it but here you go
Fixes #6484
=> feat: show companion modules under modules in menu in HTML documentation

main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
=> fix: broken source links in HTML documentation

main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
=> chore: add 'nofollow' to source links in HTML documentation

main/src/resources/doc/styles.css
=> refactor: consistent quoting and semicolons in CSS for HTML documentation

main/src/ca/uwaterloo/flix/language/ast/Token.scala, main/src/ca/uwaterloo/flix/language/ast/TokenErrorKind.scala, main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala, main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
Small updates to Token, TokenKind and TokenErrorKind as per https://github.com/flix/flix/pull/6350?notification_referrer_id=NT_kwDOAPFTIbM3Mzk0MzA3ODM1OjE1ODE1NDU3#pullrequestreview-1654486186
=> feat: tweak `Token`, `TokenKind`, and `TokenErrorKind`

main/src/ca/uwaterloo/flix/language/errors/LexerError.scala
Small updates to LexerError.scala  as per https://github.com/flix/flix/pull/6350?notification_referrer_id=NT_kwDOAPFTIbM3Mzk0MzA3ODM1OjE1ODE1NDU3#pullrequestreview-1654486186
=> feat: add  LexerError.StringInterpolationTooDeep

main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
=> feat: show all items as submodules in HTML documentation

main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala
=> feat: add DesugaredAst

main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Parser2.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/TypeInference.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/src/ca/uwaterloo/flix/util/ParOps.scala
=> refactor: introduce `ParOps.parMapValuesSeq`

main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> refactor: move `ForEach` to `Desugar`

main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> refactor: move `MonadicFor` to Desugar

main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> refactor: move `ForEachYield` to `Desugar`

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
Closes https://github.com/flix/flix/issues/6623
=> feat: make `Desugar` incremental

main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> refactor: move LambdaMatch to Desugar

main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
=> refactor: cleanup `Simplifier`

main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> refactor: move LetMatch to Desugar

main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
=> fix: check classes in PredDeps and Stratifier

main/src/ca/uwaterloo/flix/language/phase/MonoTypes.scala
I think its hard to trigger this error but conceptually this is more correct
=> fix: missing monotypes visit call

main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> refactor: move Tuple to Desugar

main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> refactor: move SetLit to Desugar

main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> refactor: move FAppend to Desugar

main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> refactor: move FCons to Desugar

main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> refactor: move ListLit to Desugar

main/src/ca/uwaterloo/flix/language/ast/MonoType.scala, main/src/ca/uwaterloo/flix/language/ast/ReducedAst.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/ReducedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/Reducer.scala, main/src/ca/uwaterloo/flix/language/phase/VarOffsets.scala
* Collect local variables in defs
* Clarifying comments in VarOffsets
* Changed TryCatch in VarOffsets not to reuse indices (variable re-initialization cannot handle that)
=> feat: collect def local args

main/src/ca/uwaterloo/flix/language/errors/KindError.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala
=> refactor: cleanup `KindError`

main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/UllmansAlgorithm.scala
- use `Result` and `toSoftFailure`
=> refactor: cleanup `Stratifier`

main/src/ca/uwaterloo/flix/language/errors/InstanceError.scala, main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/test/ca/uwaterloo/flix/language/phase/TestInstances.scala
- move some tips into the actual error message
- add more colors
- reword a few things
- sort
=> refactor: cleanup `InstanceError`

main/src/ca/uwaterloo/flix/language/errors/RedundancyError.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
- Rename a few errors and re-order.
=> refactor: cleanup `RedundancyError`

main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala, main/src/ca/uwaterloo/flix/language/errors/TypeError.scala, main/src/ca/uwaterloo/flix/language/phase/TypeInference.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala, main/test/ca/uwaterloo/flix/language/phase/TestIncremental.scala, main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- Rename a few errors
- Reorder all errors
=> refactor: cleanup `TypeError`

main/src/ca/uwaterloo/flix/language/errors/WeederError.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
=> refactor: cleanup `WeederError`

main/src/ca/uwaterloo/flix/api/Bootstrap.scala, main/src/ca/uwaterloo/flix/api/BootstrapError.scala, main/src/ca/uwaterloo/flix/language/errors/DerivationError.scala, main/src/ca/uwaterloo/flix/language/errors/EntryPointError.scala, main/src/ca/uwaterloo/flix/language/errors/InstanceError.scala, main/src/ca/uwaterloo/flix/language/errors/NameError.scala, main/src/ca/uwaterloo/flix/language/errors/NonExhaustiveMatchError.scala, main/src/ca/uwaterloo/flix/language/errors/RedundancyError.scala, main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala, main/src/ca/uwaterloo/flix/language/errors/Unrecoverable.scala, main/src/ca/uwaterloo/flix/language/phase/Deriver.scala, main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/PatMatch.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/unification/ClassEnvironment.scala, main/src/ca/uwaterloo/flix/language/phase/unification/UnificationError.scala, main/src/ca/uwaterloo/flix/util/Validation.scala
=> feat: add `Recoverable` and `Unrecoverable`. Add `softFailure` and `hardFailure`

main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- Reorder
- Drop one unused error
=> refactor: cleanup `ResolutionError`

main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> refactor: move FixpointInjectInto to Desugar

main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> refactor: move Static to Desugar

main/src/ca/uwaterloo/flix/language/errors/WeederError.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
fixes https://github.com/flix/flix/issues/6866
=> fix: create unqualified use error

docs/BUILD.md
=> docs: add troubleshooting step to BUILD.md

main/src/ca/uwaterloo/flix/Main.scala
with this change everybody preserves options, except shell
=> fix: dont ignore options

main/src/ca/uwaterloo/flix/api/Bootstrap.scala, main/src/ca/uwaterloo/flix/language/ast/Scheme.scala, main/src/ca/uwaterloo/flix/language/phase/Deriver.scala, main/src/ca/uwaterloo/flix/language/phase/EntryPoint.scala, main/src/ca/uwaterloo/flix/language/phase/Inliner.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lexer.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/OccurrenceAnalyzer.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Parser2.scala, main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala, main/src/ca/uwaterloo/flix/language/phase/Reader.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/TypeInference.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/src/ca/uwaterloo/flix/language/phase/unification/ClassEnvironment.scala, main/src/ca/uwaterloo/flix/util/Validation.scala, main/test/ca/uwaterloo/flix/util/TestValidation.scala
=> refactor: add Validation.success

main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/TypeInference.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala, main/src/ca/uwaterloo/flix/util/Result.scala, main/src/ca/uwaterloo/flix/util/Validation.scala, main/test/ca/uwaterloo/flix/util/TestValidation.scala
=> refactor: rename Validation.Failure to Validation.HardFailure

main/src/ca/uwaterloo/flix/language/phase/jvm/GenEffectClasses.scala
Simply call object constructor
=> fix: mising effect constructor

main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/BackendType.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenEffectClasses.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
The resumption takes a Value argument but ResumptionWrapper converts that into a specific function by boxing the input in a Value, and the rewinding the resumption.
The code also expects the continuation to be a closure, so resumption wrapper implements cloX$...
=> feat: specialize ResumptionWrapper

main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/BytecodeInstructions.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/ClassMaker.scala
clearly note where calls are interface or not, and do some automatically by the new interface specific method types
=> feat: better interface tracking in backend

main/src/ca/uwaterloo/flix/language/errors/EntryPointError.scala, main/src/ca/uwaterloo/flix/language/phase/EntryPoint.scala, main/test/ca/uwaterloo/flix/language/phase/TestEntryPoint.scala
=> feat: add `IllegalEntryPointEff`

main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
Closes https://github.com/flix/flix/issues/6421
=> style: tidy Desugar

main/src/ca/uwaterloo/flix/util/Validation.scala, main/test/ca/uwaterloo/flix/util/TestValidation.scala
=> feat: add Validation.toResult

main/src/ca/uwaterloo/flix/language/phase/Optimizer.scala, main/src/ca/uwaterloo/flix/tools/BenchmarkCompilerOld.scala, main/src/ca/uwaterloo/flix/tools/CompilerPerf.scala, main/src/ca/uwaterloo/flix/util/Validation.scala, main/test/ca/uwaterloo/flix/language/phase/TestIncremental.scala, main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala, main/test/ca/uwaterloo/flix/tools/TestBootstrap.scala
=> refactor: rename Validation.get to Validation.unsafeGet

main/src/ca/uwaterloo/flix/language/CompilationMessage.scala, main/src/ca/uwaterloo/flix/language/errors/DerivationError.scala, main/src/ca/uwaterloo/flix/language/errors/InstanceError.scala, main/src/ca/uwaterloo/flix/language/errors/KindError.scala, main/src/ca/uwaterloo/flix/language/errors/NameError.scala, main/src/ca/uwaterloo/flix/language/errors/NonExhaustiveMatchError.scala, main/src/ca/uwaterloo/flix/language/errors/ParseError.scala, main/src/ca/uwaterloo/flix/language/errors/RedundancyError.scala, main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala, main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala, main/src/ca/uwaterloo/flix/language/errors/StratificationError.scala, main/src/ca/uwaterloo/flix/language/errors/TypeError.scala, main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
Closes https://github.com/flix/flix/issues/6732
=> refactor: make CompilationMessage.explain default to None

main/src/ca/uwaterloo/flix/language/errors/DerivationError.scala, main/src/ca/uwaterloo/flix/language/errors/EntryPointError.scala, main/src/ca/uwaterloo/flix/language/errors/InstanceError.scala, main/src/ca/uwaterloo/flix/language/errors/LexerError.scala, main/src/ca/uwaterloo/flix/language/errors/RedundancyError.scala, main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala, main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala, main/src/ca/uwaterloo/flix/language/errors/TypeError.scala, main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
Related to https://github.com/flix/flix/issues/6817
=> style: ensure errors appear in alphabetical order

main/src/ca/uwaterloo/flix/language/phase/Inliner.scala
=> feat: rework `Inliner` criteria

main/src/ca/uwaterloo/flix/language/phase/PatMatch.scala
=> fix: run `PatMatch` in class defs

main/src/ca/uwaterloo/flix/language/phase/Safety.scala
=> fix: visit class sigs, instances and sigs in `Safety` phase

main/test/flix/Test.Exp.ForEachYield.flix
Discovered a few cases that were untested.
Related to https://github.com/flix/flix/issues/5663
=> test: add tests for let-bindings in `ForEachYield`

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/tools/pkg/ReleaseError.scala
=> feat: allow storing GitHub token in environment variable

main/test/ca/uwaterloo/flix/util/FlixSuite.scala
=> refactor: remove unused parameter in FlixSuite

main/src/ca/uwaterloo/flix/util/collection/Chain.scala, main/test/ca/uwaterloo/flix/util/TestChain.scala
Related to https://github.com/flix/flix/issues/6989
=> refactor: remove `Chain.Many` & `concat`

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/api/Bootstrap.scala, main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala, main/src/ca/uwaterloo/flix/language/ast/Scheme.scala, main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/TypeInference.scala, main/src/ca/uwaterloo/flix/language/phase/unification/ClassEnvironment.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala, main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala, main/src/ca/uwaterloo/flix/tools/SimpleRunner.scala, main/src/ca/uwaterloo/flix/tools/SocketServer.scala, main/src/ca/uwaterloo/flix/util/Result.scala, main/src/ca/uwaterloo/flix/util/Validation.scala, main/test/ca/uwaterloo/flix/TestUtils.scala, main/test/ca/uwaterloo/flix/language/TestFlixErrors.scala, main/test/ca/uwaterloo/flix/language/TestProgramArgs.scala, main/test/ca/uwaterloo/flix/util/FlixSuite.scala, main/test/ca/uwaterloo/flix/util/TestValidation.scala
Depends on https://github.com/flix/flix/pull/7004
Supersedes https://github.com/flix/flix/pull/6912
=> refactor: make Validation.Success constructor private

main/src/ca/uwaterloo/flix/api/Bootstrap.scala
Related to https://github.com/flix/flix/pull/7005
=> fix: return `HardFailure` on failure in `Bootstrap`

main/src/ca/uwaterloo/flix/tools/pkg/ManifestError.scala, main/src/ca/uwaterloo/flix/tools/pkg/PackageError.scala, main/src/ca/uwaterloo/flix/tools/pkg/ReleaseError.scala
=> chore: unindent all errors in build system

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/api/Bootstrap.scala, main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
=> refactor: make `Bootstrap.release` take an implicit `PrintStream`

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/api/Bootstrap.scala, main/src/ca/uwaterloo/flix/tools/pkg/ReleaseError.scala, main/src/ca/uwaterloo/flix/util/FileOps.scala
=> feat: allow storing the GitHub token in `.GITHUB_TOKEN` file

main/test/flix/Test.Handler.ZeroShot.flix
Closes https://github.com/flix/flix/issues/7015
=> test: rewrite `Test.Handler.ZeroShot.flix` with asserts

main/test/flix/Test.Handler.Gen.flix
Closes https://github.com/flix/flix/issues/7019
=> test: add `Test.Handler.Gen.flix`

main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
=> refactor: cleanup get record types

main/test/flix/Test.Handler.Ask.flix, main/test/flix/Test.Handler.Gen.AtomicInteger.flix, main/test/flix/Test.Handler.Gen.Bool.flix, main/test/flix/Test.Handler.Gen.Char.flix, main/test/flix/Test.Handler.Gen.Enum.flix, main/test/flix/Test.Handler.Gen.Float32.flix, main/test/flix/Test.Handler.Gen.Float64.flix, main/test/flix/Test.Handler.Gen.Int16.flix, main/test/flix/Test.Handler.Gen.Int32.flix, main/test/flix/Test.Handler.Gen.Int64.flix, main/test/flix/Test.Handler.Gen.Int8.flix, main/test/flix/Test.Handler.Gen.String.flix, main/test/flix/Test.Handler.Gen.Unit.flix
Closes https://github.com/flix/flix/issues/7060
=> test: add `Test.Handler.Gen.X.flix`

main/test/flix/Test.Handler.Gen.AtomicInteger.flix
Related to #7060 
Resolves https://github.com/flix/flix/pull/7075#discussion_r1460544770
=> test: use `List[AtomicInteger]` in `Test.Handler.Gen.AtomicInteger.flix`

main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/library/Array.flix, main/src/library/Chain.flix, main/src/library/DelayList.flix, main/src/library/List.flix, main/src/library/MutDeque.flix, main/src/library/MutList.flix, main/src/library/Nec.flix, main/src/library/Nel.flix, main/src/library/Prelude.flix, main/src/library/Random.flix, main/src/library/Vector.flix, main/test/ca/uwaterloo/flix/library/TestArray.flix, main/test/ca/uwaterloo/flix/library/TestChain.flix, main/test/ca/uwaterloo/flix/library/TestDelayList.flix, main/test/ca/uwaterloo/flix/library/TestList.flix, main/test/ca/uwaterloo/flix/library/TestMutDeque.flix, main/test/ca/uwaterloo/flix/library/TestMutList.flix, main/test/ca/uwaterloo/flix/library/TestNec.flix, main/test/ca/uwaterloo/flix/library/TestNel.flix, main/test/ca/uwaterloo/flix/library/TestRandom.flix, main/test/ca/uwaterloo/flix/library/TestRedBlackTree.flix, main/test/ca/uwaterloo/flix/library/TestVector.flix
=> chore: drop `NonDet` effect

main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
=> fix: issue #7031

main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenAnonymousClasses.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenNamespaceClasses.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
=> feat: add unhandled effect error

main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenTagClasses.scala
=> feat: remove `equals` and `hashcode` from backend objects

main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
Equality can be manually checked by fields
=> feat: add info fields to error

main/test/flix/Test.Handler.OneShot.AtomicInteger.flix, main/test/flix/Test.Handler.OneShot.Bool.flix, main/test/flix/Test.Handler.OneShot.Char.flix, main/test/flix/Test.Handler.OneShot.Enum.flix, main/test/flix/Test.Handler.OneShot.Float32.flix, main/test/flix/Test.Handler.OneShot.Float64.flix, main/test/flix/Test.Handler.OneShot.Int16.flix, main/test/flix/Test.Handler.OneShot.Int32.flix, main/test/flix/Test.Handler.OneShot.Int64.flix, main/test/flix/Test.Handler.OneShot.Int8.flix, main/test/flix/Test.Handler.OneShot.String.flix, main/test/flix/Test.Handler.OneShot.Unit.flix
Closes https://github.com/flix/flix/issues/7063
=> test: add `Test.Handler.OneShot.X.flix`

main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> feat: allow annotations on type aliases

main/src/ca/uwaterloo/flix/language/phase/Instances.scala
=> refactor: clean up Instances phase

main/test/flix/Test.Handler.OneShot.Bool.flix, main/test/flix/Test.Handler.OneShot.Char.flix, main/test/flix/Test.Handler.OneShot.Enum.flix, main/test/flix/Test.Handler.OneShot.Float32.flix, main/test/flix/Test.Handler.OneShot.Float64.flix, main/test/flix/Test.Handler.OneShot.Int16.flix, main/test/flix/Test.Handler.OneShot.Int32.flix, main/test/flix/Test.Handler.OneShot.Int64.flix, main/test/flix/Test.Handler.OneShot.Int8.flix, main/test/flix/Test.Handler.OneShot.Unit.flix
Closes https://github.com/flix/flix/issues/7063
=> test: rename `Ask` to `AskTell` in `Test.Handler.OneShot.X.flix`

main/test/flix/Test.Handler.MultiShot.AtomicInteger.flix, main/test/flix/Test.Handler.MultiShot.Bool.flix, main/test/flix/Test.Handler.MultiShot.Char.flix, main/test/flix/Test.Handler.MultiShot.Enum.flix, main/test/flix/Test.Handler.MultiShot.Float32.flix, main/test/flix/Test.Handler.MultiShot.Float64.flix, main/test/flix/Test.Handler.MultiShot.Int16.flix, main/test/flix/Test.Handler.MultiShot.Int32.flix, main/test/flix/Test.Handler.MultiShot.Int64.flix, main/test/flix/Test.Handler.MultiShot.Int8.flix, main/test/flix/Test.Handler.MultiShot.String.flix, main/test/flix/Test.Handler.MultiShot.Unit.flix
Closes https://github.com/flix/flix/issues/7146
=> test: add `Test.Handler.MultiShot.X.flix`

main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
=> chore: remove unused ImpureDeclaredAsPure error

main/src/ca/uwaterloo/flix/language/ast/Symbol.scala, main/src/ca/uwaterloo/flix/language/ast/Type.scala, main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala
=> refactor: hardcode IO symbol

main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
Closes https://github.com/flix/flix/issues/7036
=> refactor: add `ParsedAst.FormalParamList`

main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
Closes https://github.com/flix/flix/issues/7145
=> test: add negative test cases for `IO` and effects

.github/workflows/rerun-on-demand.yaml
This adds a command so you can rerun failed tests by commenting `!!!rerun`
@jaschdoc
=> ci: add `!!!rerun` command

main/src/ca/uwaterloo/flix/language/phase/MonoTypes.scala
=> fix: MonoTypes enum erasure

examples/larger-examples/FloydWarshall.flix, examples/larger-examples/interpreter.flix, examples/larger-examples/introduction.flix, examples/larger-examples/lambda-calculus.flix, main/src/library/Fixpoint/Interpreter.flix, main/test/ca/uwaterloo/flix/ExampleSuite.scala
Closes https://github.com/flix/flix/issues/7185
=> test: add old examples to test suites

main/src/ca/uwaterloo/flix/language/ast/Purity.scala, main/src/ca/uwaterloo/flix/language/phase/EffectBinder.scala, main/src/ca/uwaterloo/flix/language/phase/Inliner.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
Collect functions related to `Purity` into the `Purity` Object
=> refactor: Purity methods

AUTHORS.md, build.gradle, main/src/ca/uwaterloo/flix/util/ExternalJarLoader.scala
=> fix: do not set custom thread classloader (#7203)

main/src/ca/uwaterloo/flix/language/ast/ReducedAst.scala, main/src/ca/uwaterloo/flix/language/phase/EffectBinder.scala, main/src/ca/uwaterloo/flix/language/phase/Reducer.scala
move pc point counting to reducer in preparation to move tailrec
=> refactor: move pc point counting to Reducer

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/api/Bootstrap.scala, main/src/ca/uwaterloo/flix/runtime/shell/Command.scala, main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala, main/src/ca/uwaterloo/flix/tools/pkg/AvailableUpdates.scala, main/src/ca/uwaterloo/flix/tools/pkg/FlixPackageManager.scala, main/src/ca/uwaterloo/flix/tools/pkg/SemVer.scala, main/src/ca/uwaterloo/flix/util/Formatter.scala, main/test/ca/uwaterloo/flix/TestMain.scala
=> feat: add `outdated` command

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/Coerce.flix, main/src/library/Down.flix, main/src/library/Prelude.flix
=> feat: add `Coerce` type class

main/src/ca/uwaterloo/flix/api/lsp/provider/ShowAstProvider.scala, main/src/ca/uwaterloo/flix/language/dbg/AstPrinter.scala
Fixes https://github.com/flix/vscode-flix/issues/315
* ShowAstProvider now choses the phases with the closest name to the given string
* The compiler now only links strings to phases in one place
=> feat: improve ShowAst

main/src/ca/uwaterloo/flix/util/Validation.scala
The new parser is _so advanced_ that it manages to use a `flatMapN` over __8__ validations! Amazing really.
=> feat: flatMapN over 8 args

main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/MonoType.scala, main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala, main/src/ca/uwaterloo/flix/language/dbg/DocAst.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/MonoTypePrinter.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala, main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala, main/src/ca/uwaterloo/flix/language/phase/Eraser.scala, main/src/ca/uwaterloo/flix/language/phase/MonoDefs.scala, main/src/ca/uwaterloo/flix/language/phase/Reducer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/BackendType.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
fixes #6572
Added after Void and before Unit
=> feat: Introduce AnyType

main/src/library/Fixpoint/Interpreter.flix, main/src/library/Fixpoint/Solver.flix, main/src/library/Map.flix, main/src/library/MutMap.flix, main/src/library/RedBlackTree.flix, main/test/ca/uwaterloo/flix/library/TestMap.flix
=> style: rename `query` to `rangeQuery`

main/src/library/Graph.flix
Related to https://github.com/flix/flix/pull/7208
=> refactor: use `coerce` in `Graph.distancesFrom`

main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/library/Fixpoint/Solver.flix
=> style: update reserved keywords in `Fixpoint.Solver`

main/src/library/Fixpoint/Phase/Compiler.flix
=> style: update reserved keywords in `Fixpoint.Phase.Compiler`

examples/larger-examples/Reachable.flix, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/library/Fixpoint/Phase/IndexSelection.flix
Supersedes https://github.com/flix/flix/pull/7243
=> refactor: rename `project` to `inject`

main/src/ca/uwaterloo/flix/language/errors/Parser2Error.scala
Adds an error type for `Parser2`.
=> feat: Parser2Error

main/test/ca/uwaterloo/flix/library/TestBigInt.flix
=> test: rename `BigInt` tests for `modulo` and `remainder`

main/src/ca/uwaterloo/flix/language/phase/Namer.scala
=> fix: maintain class constraints in laws in Namer

main/src/ca/uwaterloo/flix/language/ast/Type.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala
=> chore: move constantType function to Type.scala

main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
=> chore: relax TypeError requirements in TestTyper

main/src/ca/uwaterloo/flix/language/ast/Type.scala
=> chore: add assocs function to Type.scala

main/src/ca/uwaterloo/flix/language/errors/TypeError.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/UnificationError.scala
We can use this for timeouts or other cases when we want to give up.
=> feat: add `UnificationError.TooComplex`

main/src/ca/uwaterloo/flix/language/ast/Type.scala, main/src/ca/uwaterloo/flix/language/phase/unification/BddFormulaAlg.scala, main/src/ca/uwaterloo/flix/language/phase/unification/BoolFormula.scala, main/src/ca/uwaterloo/flix/language/phase/unification/BoolFormulaAlg.scala, main/src/ca/uwaterloo/flix/language/phase/unification/BoolSubstitution.scala, main/src/ca/uwaterloo/flix/language/phase/unification/QuineMcCluskey.scala, main/src/ca/uwaterloo/flix/language/phase/unification/SimpleBoolFormulaAlgClassic.scala, main/src/ca/uwaterloo/flix/language/phase/unification/TypeMinimization.scala
depends on #7273; extracted from #6499
=> chore: add associated type support to BoolFormula

main/src/ca/uwaterloo/flix/language/ast/Type.scala, main/src/ca/uwaterloo/flix/language/phase/MonoDefs.scala
Makes it clearer whats happening
=> refactor: explicit MonoDefs default

main/src/ca/uwaterloo/flix/language/phase/ConstraintGeneration.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/constraintgeneration/RestrictableChooseConstraintGeneration.scala, main/src/ca/uwaterloo/flix/language/phase/constraintgeneration/SchemaConstraintGeneration.scala, main/src/ca/uwaterloo/flix/language/phase/constraintgeneration/TypeContext.scala
=> feat: introduce constraint generation

main/src/ca/uwaterloo/flix/language/phase/ConstraintGeneration.scala
This probably should not be allowed, but the standard library depends on it. I have added the problem to the followup list.
=> fix: allow effs in guard

main/src/ca/uwaterloo/flix/language/ast/Scheme.scala, main/src/ca/uwaterloo/flix/language/phase/ConstraintGeneration.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/TypeInference.scala, main/src/ca/uwaterloo/flix/language/phase/constraintgeneration/RestrictableChooseConstraintGeneration.scala, main/src/ca/uwaterloo/flix/language/phase/inference/RestrictableChooseInference.scala
=> fix: consider econstrs in scheme instantiation

main/src/library/Adaptor.flix, main/src/library/Debug.flix, main/src/library/Fixpoint/Ast/Shared.flix, main/src/library/Fixpoint/Interpreter.flix, main/src/library/GetOpt.flix
Added parentheses to type ascription.
Closes https://github.com/flix/flix/issues/7304
=> style: update type ascription to new syntax

main/src/library/Fixpoint/Ast/Shared.flix, main/src/library/Fixpoint/Interpreter.flix, main/src/library/GetOpt.flix, main/test/flix/Test.Dec.TypeAlias.flix, main/test/flix/Test.Derives.Eq.flix, main/test/flix/Test.Derives.Hash.flix, main/test/flix/Test.Derives.Order.flix, main/test/flix/Test.Equality.Map.flix, main/test/flix/Test.Equality.Set.flix, main/test/flix/Test.Equality.Tag.flix, main/test/flix/Test.Exp.ForEachYield.flix, main/test/flix/Test.Exp.Force.flix, main/test/flix/Test.Exp.Interpolation.flix, main/test/flix/Test.Exp.Match.List.flix, main/test/flix/Test.Exp.Ref.Assign.flix, main/test/flix/Test.Exp.Ref.Ref.flix, main/test/flix/Test.Predicate.Functional.flix, main/test/flix/Test.Predicate.Guard.flix, main/test/flix/Test.Term.Lit.List.flix, main/test/flix/Test.Term.Lit.Option.flix
Resolves https://github.com/flix/flix/issues/7304
=> style: update ascription syntax

main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/library/Fixpoint/Solver.flix
Closes https://github.com/flix/flix/issues/7308
=> refactor: rename `project` to `projectSym` in `Solver`

examples/larger-examples/restrictable-variants/boolean-formulas.flix, examples/larger-examples/restrictable-variants/colors.flix, examples/larger-examples/restrictable-variants/sequences.flix, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala, main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala, main/test/flix/Test.Dec.RestrictableTag.flix, main/test/flix/Test.Def.ChooseStar.Simple.flix
Closes https://github.com/flix/flix/issues/7303
=> refactor: update restrictable variants tokens

main/src/ca/uwaterloo/flix/language/phase/ConstraintGeneration.scala, main/src/ca/uwaterloo/flix/language/phase/TypeInference.scala, main/test/flix/Test.Exp.Instanceof.flix
=> fix: don't require pure argument to instanceof

main/src/ca/uwaterloo/flix/language/phase/ConstraintGeneration.scala, main/src/ca/uwaterloo/flix/language/phase/TypeInference.scala, main/src/library/Chain.flix, main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
=> fix: require pattern guards to be pure

main/src/library/Array.flix, main/src/library/MutDisjointSets.flix, main/src/library/Ref.flix, main/test/ca/uwaterloo/flix/library/TestRef.flix, main/test/flix/Test.Handler.NewObject.flix
Closes https://github.com/flix/flix/issues/7367
=> refactor: rename `Ref.to` -> `Ref.fresh`

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/MonoAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala, main/src/ca/uwaterloo/flix/language/dbg/AstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala
Fixes https://github.com/flix/flix/issues/7307
=> refactor: `MonoDefs` -> `Monomorpher`

main/src/ca/uwaterloo/flix/language/phase/unification/BddFormulaAlg.scala
extracted from #6499. This will certainly cause a slowdown. But maybe adding it separately lets us quantify that slowdown?
=> chore: synchronize BDDFormulaAlg

main/src/ca/uwaterloo/flix/language/phase/unification/EffUnification.scala
=> feat: resolve associated effects in EffUnification

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/language/phase/unification/TypeMinimization.scala, main/src/ca/uwaterloo/flix/util/Options.scala, main/test/ca/uwaterloo/flix/TestMain.scala
=> chore: remove Xno-bool-table

main/src/ca/uwaterloo/flix/language/phase/unification/TypeMinimization.scala
=> chore: remove implicit flix from type minimization

main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
=> fix: check equality constraints in unifiesWith

main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
=> chore: delete `UndefinedName.03` in `TestResolver`

main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
Cleans up rules in `Lexer` and fixes several bugs to do with subtle differences in separation of keywords, operators and literals that are represented as keywords (`true`, `false` and `null`).
=> feat: cleanup `Lexer` and fix seperation bugs

main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala, main/src/ca/uwaterloo/flix/util/collection/ListOps.scala
=> refactor: introduce findMap

main/src/ca/uwaterloo/flix/language/phase/constraintgeneration/Debug.scala
=> chore: move debugging facilities to Debug.scala

main/test/ca/uwaterloo/flix/util/TestResult.scala
Closes https://github.com/flix/flix/issues/5548
=> test: add tests for `Result.traverse`

main/src/ca/uwaterloo/flix/language/phase/Optimizer.scala, main/src/ca/uwaterloo/flix/language/phase/Verifier.scala
=> feat: Verifier in parallel

main/test/ca/uwaterloo/flix/TestUtils.scala
Before this change source location would be checked on all errors. That leads to boring cases. For example, a `ResolutionError` with no source location would fail a test, even though we were testing for a `WeederError`.
With this change only the error that is expected needs to have a known source-location.
=> feat: Require `SourceLocation` only on expected error in tests

main/src/library/RedBlackTree.flix
=> fix: remove redundant constraint from RedBlackTree Eq

main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> feat: add `Type.Error` to frontend

main/src/ca/uwaterloo/flix/language/errors/NameError.scala, main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala
Related to https://github.com/flix/flix/issues/6817
=> style: update errors for `Namer`

.github/workflows/jar-on-demand.yaml, .github/workflows/rerun-on-demand.yaml
Closes https://github.com/flix/flix/issues/7467
=> chore: bump actions in GitHub Workflows

main/src/ca/uwaterloo/flix/language/phase/ConstraintGeneration.scala, main/src/ca/uwaterloo/flix/language/phase/constraintgeneration/RestrictableChooseConstraintGeneration.scala, main/src/ca/uwaterloo/flix/language/phase/constraintgeneration/SchemaConstraintGeneration.scala, main/src/ca/uwaterloo/flix/language/phase/constraintgeneration/TypeContext.scala
=> chore: remove return value from unifyAllTypes

main/src/ca/uwaterloo/flix/language/phase/ConstraintGeneration.scala, main/test/ca/uwaterloo/flix/language/fmt/TestFormatType.scala
Fixes #7501
Surprisingly little to do.
=> refactor: use mkUnion

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/language/phase/ConstraintResolution.scala, main/src/ca/uwaterloo/flix/language/phase/constraintgeneration/Debug.scala, main/src/ca/uwaterloo/flix/util/Options.scala
=> feat: add Xprint-typer option

main/src/ca/uwaterloo/flix/language/ast/Scheme.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala, main/src/ca/uwaterloo/flix/language/phase/typer/Debug.scala, main/src/ca/uwaterloo/flix/language/phase/typer/RestrictableChooseConstraintGeneration.scala, main/src/ca/uwaterloo/flix/language/phase/typer/SchemaConstraintGeneration.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeConstraint.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeContext.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala
=> refactor: reorganize constraint generation files

main/src/ca/uwaterloo/flix/language/ast/Scheme.scala
=> refactor: make Scheme.lessThanEqual return Boolean

main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala, main/src/ca/uwaterloo/flix/language/phase/typer/RestrictableChooseConstraintGen.scala, main/src/ca/uwaterloo/flix/language/phase/typer/SchemaConstraintGen.scala
=> chore: rename ConstraintGen helpers

main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
=> chore: rename variables in ConstraintGen

main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
=> fix: update location in constraints for unapplied sigs and defs

main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Parser2.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala, main/test/flix/experimental/Test.Dec.AssocType.flix
=> feat: allow default associated type declarations

main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
This PR renames class to trait within HTMLDocumentor. 
There are some field names that continue to use "class" at the moment as the are types defined outside this module.
=> chore: rename class to trait in HTMLDocumentor (issue #6591)

main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala, main/src/resources/doc/styles.css
=> fix: show trait instances in HTML documentation

main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Addresses crash mentioned here: #7529
=> chore: Add missing TreeKind to assert

main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala, main/src/ca/uwaterloo/flix/language/phase/unification/RecordUnification.scala
=> fix: support associated types with records

main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala, main/src/ca/uwaterloo/flix/api/lsp/Request.scala
Related to  flix/vscode-flix#366
=> feat: add disconnect command to LSP

main/src/ca/uwaterloo/flix/language/ast/Scheme.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala
Please double check my work :)
Saves 20MB!
=> feat: reduce memory usage of `Type` by avoiding re-allocations

main/src/ca/uwaterloo/flix/language/phase/unification/BoolFormulaTable.scala
=> feat: canonicalize Boolean formulas in `BoolFormulaTable`

main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
I had to do some cleanup because the code was ugly.
=> feat: reduce memory usage of `Type.Apply` in `Lowering`

main/src/ca/uwaterloo/flix/language/ast/Type.scala
=> feat: reduce memory usage of `Type.Apply` in `Type.map`

main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
=> fix: duplicate modules in HTML documentation

main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala, main/src/library/Concurrent/Channel.flix, main/test/ca/uwaterloo/flix/library/TestChannel.flix
=> fix: add region to `Mpmc`

main/src/ca/uwaterloo/flix/language/errors/TypeError.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala, main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
Note: I took the opportunity to cleanup some code:
- Removed dead code.
- Removed unused parameters.
=> feat: re-enable resilient type inference

main/src/ca/uwaterloo/flix/language/phase/Parser2.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
=> feat: add more `SyntacticContext` to errors

main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
This makes the lexer "official".
=> chore: remove `tryLex`

main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
=> feat: Allow doc-comments above effect handlers

main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala, main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
=> feat: use functions for first and recover sets

main/src/library/Fixpoint/Debugging.flix, main/src/library/Fixpoint/Interpreter.flix, main/src/library/Fixpoint/Solver.flix
I believe (unchecked) effects casts are fundamentally broken, including `masked_cast`.
This does not solve the problem at all, but merely makes it go away.
=> chore: rework Datalog debugging

main/test/ca/uwaterloo/flix/library/TestFloat32.flix, main/test/ca/uwaterloo/flix/library/TestFloat64.flix
closes #1086; these functions no longer exist
=> chore: remove commented tests

main/src/library/UnorderedFoldable.flix
This PR adds an associated effect to `UnorderedFoldable`.
=> refactor: add associated effect to UnorderedFoldable (part of issue #7433)

main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala, main/src/resources/doc/styles.css
=> feat: show instances on enum page in HTML documentation

examples/compiler-puzzle.flix, examples/larger-examples/datalog/delivery-date.flix, examples/larger-examples/datalog/merge_intervals.flix, main/src/ca/uwaterloo/flix/language/phase/Lexer.scala, main/src/ca/uwaterloo/flix/language/phase/Parser2.scala, main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
Closes #7644 
Also adds the example as a test case.
=> fix: Crash on bad fixpoint constraint

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
Closes #7623 
The error we get now is:
```
>> Parse Error: Expected one or more <type parameter>
1 | enum MaxHeap[]
^^
Here
Syntactic Context: OtherType.
```
=> feat: correct sourcelocation on `oneOrMore`

main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
=> fix: use equality constraints in kind inference

main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
=> fix: reconstruct channel effects properly

main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/CodeLensProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/GotoProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/InlayHintProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/ShowAstProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SymbolProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ranker/Differ.scala
The idea is that there will _always be an AST_.
=> refactor: make `root` non-optional in `LanguageServer`

main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Parser.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
=> feat: add `InvokeMethod2` to `Parser`

main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
Work in progress.
Fixes #7761.
=> feat: add type inference for `InvokeMethod2`
