- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
Sometimes, for a reason that is beyond me, the output of `Weeder` is not sorted by source location. This fixes that.
> feat: sort by `SourceLocation` in `Weeder`

- main/src/library/Array.flix
- main/src/library/GetOpt.flix
- main/src/library/Graph.flix
- main/src/library/Iterator.flix
- main/src/library/MutList.flix
- main/src/library/MutSet.flix
- main/src/library/Nec.flix
- main/src/library/Regex.flix
- main/src/library/Result.flix
- main/src/library/Set.flix
- main/src/library/String.flix
- main/src/library/Vector.flix
- main/src/resources/benchmark/BenchmarkSet.flix
- main/test/ca/uwaterloo/flix/library/TestArray.flix
- main/test/ca/uwaterloo/flix/library/TestIterator.flix
- main/test/ca/uwaterloo/flix/library/TestMutList.flix
- main/test/ca/uwaterloo/flix/library/TestNec.flix
- main/test/ca/uwaterloo/flix/library/TestRegex.flix
- main/test/ca/uwaterloo/flix/library/TestResult.flix
- main/test/ca/uwaterloo/flix/library/TestSet.flix
- main/test/ca/uwaterloo/flix/library/TestString.flix
- main/test/ca/uwaterloo/flix/library/TestVector.flix
Some missing renaming in the standard library and its tests.
> style: rename `from` to `src` and `to` to `dst`

- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/ast/ReducedAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/DocAst.scala
- main/src/ca/uwaterloo/flix/language/phase/EffectBinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Eraser.scala
- main/src/ca/uwaterloo/flix/language/phase/Inliner.scala
- main/src/ca/uwaterloo/flix/language/phase/Reducer.scala
- main/src/ca/uwaterloo/flix/language/phase/Tailrec.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
Related to# 7183
Also reames
- `TailCall` -> `Tail`
- `NonTailCall` -> `NonTail`
> refactor: rename `CallType` -> `ExpPosition`

- main/test/ca/uwaterloo/flix/language/phase/TestDeriver.scala
- main/test/ca/uwaterloo/flix/language/phase/TestEntryPoint.scala
- main/test/ca/uwaterloo/flix/language/phase/TestInstances.scala
- main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala
- main/test/ca/uwaterloo/flix/language/phase/TestPatExhaustiveness.scala
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
`class` has been removed in the new parser in favor of `trait`. This PR refactors phase tests to reflect that.
> chore: `class` -> `trait` in language phase tests

- examples/larger-examples/program-analysis/domains/Belnap.flix
Avoids using keyword `not` in `Belnap.flix`. With this the new parser passes `ExampleSuite`.
> style: `not` -> `neg` in Belnap.flix example

- main/src/ca/uwaterloo/flix/language/ast/SyntaxTree.scala
- Cleans up IntelliJ warnings
- removes unused `TreeKind.Type.RecordVariable` in favor of the existing `TreeKind.Type.Variable`.  
- Adds `TreeKind.Pattern.Unary` which is used for negative literals in patters `case -1`
> feat: remove unused treekind

- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
Maybe we should abbreviate parts of the expression to avoid this issue
> fix: add missing source lines to errors

- main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala
- main/src/ca/uwaterloo/flix/language/phase/Verifier.scala
Alternative to #7421
This keeps  `apply` simpler but has n^2 time complexity on the length of records
> feat: Normalize records in monomorpher

- main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
Adds a quickfix for a missing superclass in a derivation.
E.g. 
before
```
enum Direction with Order {case N, E, S, W}
Missing super class instance 'Eq'.(Instance Error)
```
after
```enum Direction with Order, Eq {case N, E, S, W}```
> feat: add missing superclass code action

- main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala
The error below might be improved I think: the highlighting could be better on ##java.lang.String rather than _s
But I didn't find any SourceLocation in the parsed expression for the ## bit.
```
>> Catch type is not a subclass of Throwable.
5 |         case _s: ##java.lang.String => "x"
^^
Type should be java.lang.Throwable or a subclass.
```
> feat: check type of value caught in try-catch (#7414)

- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
Most of the deleted tests are moved to `TestLexer` which live in this PR #7461. 
5 tests have been ignored since the old pipeline does not produce the same error as the new one will. These are:
```
TestWeeder.MalformedFloat64.01
TestWeeder.MalformedFloat64.02
TestParser.IllegalModuleName.01
TestParser.IllegalModuleName.02
TestParser.IllegalModuleName.03
```
They are marked with a TODO and should be reactivated when the new parser is taken into use.
> feat: prepare `TestParser` and `TestWeeder` for new parser

- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Verifier.scala
- fixed typo where accumulated exp was not used
- fixed `l.reverse.foldRight` -> `l.foldLeft`
- fixed calling the continuation in `mkRecordRestrict`
> fix: Simplifier on record patterns

- main/src/ca/uwaterloo/flix/language/phase/ConstraintGeneration.scala
- main/src/ca/uwaterloo/flix/language/phase/constraintgeneration/RestrictableChooseConstraintGeneration.scala
- main/src/ca/uwaterloo/flix/language/phase/constraintgeneration/SchemaConstraintGeneration.scala
- main/src/ca/uwaterloo/flix/language/phase/constraintgeneration/TypeContext.scala
I only changed `TypeContext`.
related to #7286
> refactor: rename `TypeContext` methods

- main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
- main/src/ca/uwaterloo/flix/language/errors/InstanceError.scala
- main/src/ca/uwaterloo/flix/language/errors/KindError.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestInstances.scala
- main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestPatExhaustiveness.scala
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
This PR changes error names that had "Class" in them:
InstanceError.MissingSuperClassInstance 
InstanceError.MissingTypeClassConstraint
KindError.MissingTypeClassConstraint
It also changes class to trait in comments, variable names and test display names.
Is there a way to run `TestAll` outside off IntelliJ? On my PC it goes off into spinner mode after about 1400 of the tests. I've tried both under Linux and Windows and increasing Intellij's memory setting without success. Separately running the test file that it apparently got stuck on is fine - so it doesn't appear to a problem with any particular file.
> refactor: rename Class to Trait (issue #6591)

- main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala
This is dead code, but will be needed once lowering get moved back in the compiler
> feat: normalize schema rows

- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
This PR renames class to trait within Type and Instances. 
Some constructor and field names continue to use "class" at the moment as they are types defined outside these modules.
> chore: rename class to trait in Typer and Instances (issue #6591)

- main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
This PR renames class to trait within Desugar and other modules in `phase` (these modules used "class" enough to have `visitClass` functions). 
Some constructor and field names continue to use "class" at the moment as they are types defined outside these modules. Sometimes the used class in regard to Java classes which have been left unchanged.
> chore: rename class to trait in Desugar and others (issue #6591)

- main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/SchemaConstraintGen.scala
- main/src/ca/uwaterloo/flix/language/phase/util/PredefinedTraits.scala
This PR renames class to trait within `Deriver` and renames the module / object `PredefinedClasses` to `PredefinedTraits`.
`SchemaConstraintGen` is also updated.
> chore: rename class to trait in Deriver and rename PredefinedClasses (issue #6591)

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/LocationLink.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/FindReferencesProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/ImplementationProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SymbolProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/InstanceCompleter.scala
This PR renames class to trait in Indexer and various other LSP modules. I think all the changes are internal and don't involve the LSPs API (I don't really know how it works).
I'm back at work tomorrow, so the rate of PRs will slow down.
> chore: rename class to trait in various LSP modules (issue #6591)

- main/src/ca/uwaterloo/flix/language/ast/Scheme.scala
- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/TreeShaker1.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/Debug.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/TypeConstraint.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/TypeContext.scala
- main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
- main/test/ca/uwaterloo/flix/language/phase/unification/TestAssocTypeUnification.scala
This PR renames the case classes `Symbol.ClassSym` to `Symbol.TraitSym` and `TreeShaker1.ClassSym` to `TreeShaker1.TraitSym`. 
It also changes `TypeContraint.Class` to `TypeConstraint.Trait`.
> chore: rename class to trait (ClassSym => TraitSym) (issue #6591)

- main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Scheme.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/EntryPoint.scala
- main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/TraitEnvironment.scala
This PR renames the case class `Ast.ClassContext` to `Ast.TraitContext`.
It also renames module / object `ca.uwaterloo.flix.language.phase.unification.ClassEnvironment` to `ca.uwaterloo.flix.language.phase.unification.TraitEnvironment`
> chore: rename ClassEnvironment to TraitEnvironment and Ast.ClassContext to Ast.TraitContext (issue #6591)

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala
- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ParsedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/SyntaxTree.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
- main/src/ca/uwaterloo/flix/language/phase/util/PredefinedTraits.scala
This PR renames:
`ParsedAst.Declaration.Class` to `ParsedAst.Declaration.Trait`
`WeededAst.Declaration.Class` to `WeededAst.Declaration.Trait`
`DesugaredAst.Declaration.Class` to `DesugaredAst.Declaration.Trait`
`KindedAst.Class` to `KindedAst.Trait`.
`LoweredAst.Class` to `LoweredAst.Trait`.
`Ast.SyntacticContext.Decl.Class` to `Ast.SyntacticContext.Decl.Trait`
`SyntaxTree.Decl.Class` to `SyntaxTree.Decl.Trait`
`TypeAst` left unchanged for another PR as it appears cascades changes to many files.
> chore: rename Class in ASTs to Trait (issue #6591)

- main/src/ca/uwaterloo/flix/api/lsp/Entity.scala
- main/src/ca/uwaterloo/flix/api/lsp/Index.scala
- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/ImplementationProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SymbolProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/InstanceCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/WithCompleter.scala
- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
- main/src/ca/uwaterloo/flix/language/phase/EntryPoint.scala
- main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/PatMatch.scala
- main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
- main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
- main/src/ca/uwaterloo/flix/tools/Summary.scala
This PR renames `TypedAst.Class` to `TypedAst.Trait` and renames field labels in `TypedAst.Root`.
It also renames field labels in `Completion.InstanceCompletion` and `Ast.Derivations`
> chore: rename TypedAst.Class to TypedAst.Trait (issue #6591)

- main/src/ca/uwaterloo/flix/api/lsp/Entity.scala
- main/src/ca/uwaterloo/flix/api/lsp/Index.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/FindReferencesProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/GotoProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/RenameProvider.scala
This PR Renames `Entity.Class` to `Entity.Trait`.
> chore: rename lsp Entity.Class to Entity.Trait (issue #6591)

- main/src/ca/uwaterloo/flix/language/phase/Verifier.scala
In its current state, this PR doesn't change anything, since the verifier never encounters `Box`/`Unbox`. Before the `TailPos` phase is completed, there are no `MonoType.Box`/`Unbox` occurances within the Ast. However, moving the verifier below `Eraser` introduces test-failures in other cases (with e.g. `IfThenElse` and `Let`).
> feat: add `Box`, `Unbox`, `Cast` to `Verifier`

- main/src/ca/uwaterloo/flix/language/ast/MonoType.scala
- main/src/ca/uwaterloo/flix/language/dbg/DocAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/MonoTypePrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/Eraser.scala
- main/src/ca/uwaterloo/flix/language/phase/Reducer.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
Matches `Type.Void`, used for effect operations primarily.
previously this was represented by `MonoType.Object` which loses information
Fixes #7554
> feat: add `MonoType.Void`

- main/src/ca/uwaterloo/flix/language/phase/Eraser.scala
slight codesize increase but no runtime cost
> feat: undo `Eraser` tail-call unboxing optimization

- .github/workflows/jar-on-demand.yaml
I forgot to update `actions/upload-artifact` in `jar-on-demand`
Related to https://github.com/flix/flix/pull/7474
Related to https://github.com/flix/flix/issues/7467
> chore: bump actions upload artifact

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Fixes crashes found by fuzzing the standard library. 
There are still a couple left to fix, but those are way easier to handle after we have recover sets, so I have just noted them.
> feat: fix crashes found by fuzzing

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
This PR Renames `Class` to `Trait` in the parsers and `NamedAst`.
> chore: rename Class to Trait in the Parsers and NamedAst (issue #6591)

- build.gradle
See diff for rationale.
Yes, this makes CI slower, but it also makes everything more robust.
> test: disable test parallelism

- main/src/ca/uwaterloo/flix/language/phase/Verifier.scala
In the case where the return type of an effects operation is `Void`, `op.tpe` has type `MonoType.Native(java.lang.Object)`. However, this doesn't match with the associated type of `Do.Expr` expressions reffering to such operations. 
Is this expected? Looks like it has something to do with the way void is handled during the TypeInference-phase (now removed...). More details in TODO comment.
> feat: add `TryWith` and `Do` to `Verifier`

- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Verifier.scala
`Region: Unit` is now `Region: Region[IO]` (which also doesn't make much sense, but that is how it is done in desugaring fx).
> fix: better region types in parYield lowering

- main/src/ca/uwaterloo/flix/language/phase/Verifier.scala
Currently fails on `par (...) yield`-expressions.
> feat: add `Spawn` and `Region` to verifier

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
This fixes a bug in the spots where we need to count nesting levels of curly braces.
The issue was that `#{` and `}` pairs were ignored.
> fix: Count HashCurlyL as opener

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
This is a minor tweak which is needed if the program contains both parse errors and other errors (which becomes possible with the new Parser).
> feat: rank syntactic contexts in `CompletionProvider`

- main/src/library/Map.flix
- main/src/library/MutMap.flix
- main/src/library/MutQueue.flix
- main/src/library/Set.flix
- main/test/ca/uwaterloo/flix/library/TestMap.flix
- main/test/ca/uwaterloo/flix/library/TestMutMap.flix
- main/test/ca/uwaterloo/flix/library/TestMutQueue.flix
- main/test/ca/uwaterloo/flix/library/TestSet.flix
This PR `Set.toVector` and other related conversions:
~~~
Map.toVector
Map.toArray
MutMap.toVector
MutMap.toArray
MutQueue.toVector
Set.toVector
Set.toArray
~~~
> feat: add `toVector` to Set and others (issue #7430)

- examples/larger-examples/Reachable.flix
- examples/larger-examples/restrictable-variants/sequences.flix
- main/src/library/Chain.flix
- main/src/library/DelayList.flix
- main/src/library/DelayMap.flix
- main/src/library/Iterable.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/MutDisjointSets.flix
- main/src/library/MutQueue.flix
- main/src/library/Nec.flix
- main/src/library/Nel.flix
- main/src/library/Option.flix
- main/src/library/RedBlackTree.flix
- main/src/library/Set.flix
- main/src/library/Vector.flix
This PR adds an associated type and effect to `Iterable` and makes `Iterable`'s kind `Type` rather than `Type -> Type`.
The collections that already had `Iterable` instances have been updated along with two examples.
> refactor: add assoc type and effect to Iterable (part of issue #7433)

- main/src/library/DelayMap.flix
- main/src/library/Map.flix
- main/src/library/RedBlackTree.flix
- main/test/ca/uwaterloo/flix/library/TestIterable.flix
- main/test/flix/Test.Exp.ForEachYield.flix
This PR changes `Iterable` to iterate over key-value pairs on `Map`, `DelayMap` and `RedBlackTree`.
> refactor: change Iterable to iterate over (k, v) for maps (issue #7617)

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
Closes #7604
This issue was this program:
```scala
mod A {
eff _B {}
///
}
```
Which gave a parser error. The reason was that the doc-comment indicates that a declaration is about to follow, but it does not. The fix is to treat the doc-comment as a regular comment, which will behave nicely in an IDE setting, and be harmless otherwise.
> fix: Parse error when last token of module is a DocComment

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
This PR add a way to get a display string for a `TokenKind`.
This allows `Parser2` to emit more easily read errors like these:
```scala
eff
def main(): Int32 = 123
```
```text
>> Parse Error: Expected <Name> before 'def'
1 | eff
^^^
Here
Syntactic Context: Unknown.
```
or here:
```scala
def foo(): Int32 = 123;
enum Legumes { case BlackBeans }
```
```text
>> Parse Error: Expected <expression> before 'enum'
1 | def foo(): Int32 = 123;
^
Here
Syntactic Context: OtherExpr.
```
This PR also aligns all errors that `Parser2` produces to these principles:
- A concrete TokenKind is displayed with ticks, ie. `'and'`
- A runtime specific TokenKind is displayed with angles, ie. `<name>`
- A large group of token kinds with a sensible name is also displayed with angles, ie. `<expression>` or …
> feat: add `TokenKind.display` for better errors

- main/src/library/Chain.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/Nec.flix
- main/src/library/Nel.flix
- main/src/library/Set.flix
- main/src/library/ToJava.flix
- main/src/library/Vector.flix
This PR adds an associated effect to `ToJava`.
Adding a `FromJava` class will follow in another PR.
> refactor: add assoc effect to ToJava (part of issue #7433)

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Chain.flix
- main/src/library/FromJava.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/Nec.flix
- main/src/library/Nel.flix
- main/src/library/Set.flix
- main/src/library/Vector.flix
- main/test/ca/uwaterloo/flix/library/TestFromJava.flix
- main/test/ca/uwaterloo/flix/library/TestToJava.flix
This PR adds the trait `FromJava` and instances for types that have `ToJava` except `Nec` and `Nel` as we cannot assert the input to them is non-empty.
The tests were derived from `TestToJava.flix` and I spotted some inconsistent names that I corrected.
> feat: add FromJava trait (part of issue #7433)

- main/src/library/Chain.flix
- main/src/library/Collectable.flix
- main/src/library/List.flix
- main/src/library/Set.flix
- main/src/library/Vector.flix
- main/test/ca/uwaterloo/flix/library/TestCollectable.flix
This PR changes the kind of `Collectable` to Type and adds an associated element type and effect. It also removes the `Order` constraint on `collect` that I think was unnecessary (the `Set` instance uses an `Order` constraint but it isn't needed at the trait level).
I've added a handful of instance tests.
> refactor: add associated element type and effect to Collectable (part of issue #7433)

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
Closes #7646 
The example now gives 3 parser errors:
```
>> Parse Error: Expected '=>' before '_'
3 |         case Card.Card(r, s) _ => "${r} of ${s}"
^
Here
Syntactic Context: OtherExpr.
>> Parse Error: Expected '}' before '=>'
3 |         case Card.Card(r, s) _ => "${r} of ${s}"
^
Here
Syntactic Context: OtherExpr.
>> Parse Error: Expected 'type' or 'def' before '=>'
3 |         case Card.Card(r, s) _ => "${r} of ${s}"
^^
Here
Syntactic Context: Instance.
```
**Reasoning**: 
First error is because parser expects '=>' but finds '_'. This stops parsing …
> feat: Fix parser crash on bad match case

- main/src/library/Fixpoint/Phase/Stratifier.flix
Fixes #7658
The initial map is redundant because missing mappings are interpreted as 0 in stratifyHelper and likewise in the functions that use the constructed map
> fix: runtime stratification of join

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
Fixes issue found in #7660 where equality constraints in signatures would loop endlessly.
> fix: Make sure equality contraint loop terminates

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
Closes #7649
Example added as a test case. The error emitted is:
```
>> Parse Error: Expected '[' before '{'
1 | instance Order { }
^^^^^
Here
Syntactic Context: Instance.
```
> fix: Make type parameter required on instances

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
Closes #7645 
Added a test case with the example. Two error messages are produced instead of a crash now: 
```
>> Parse Error: Misplaced comments
4 |>     //case Clubs
5 |>     //case Hearts
6 |>     //case Spades
7 |>     //case Diamonds
Here
Syntactic Context: Unknown.
>> Parse Error: Expected <Name> or 'Pure' before '}'
7 |     //case Diamonds
^^^^^^^^^^^^^^^
Here
Syntactic Context: Enum.
```
**Reasoning**: 
The enum case rule sees `case` and expects a name next. To the parser, comments are invisible, which is achieved by consuming them immediately when opening a new tree node. So when the parser looks for a tag-name it sees the …
> fix: Handle bad enum case crash.

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Closes #7608 
The issue was that `CommentList` was introduced to group sequential comments into a single syntax node, but the weeder was not updated to select into `CommentList`s and capture text. `pickDocumentation` was updated to remedy that.
Another related issue was that the very first doc comment in a file would be placed under the root node rather than the first declaration. That was also fixed.
> fix: capture doc comments again

- main/test/flix/Test.Dec.TypeAlias.flix
closes #5729 (fixed by rework; this just adds a test)
> test: add test for identity type alias

- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
> fix: count unused type parameters in redundancy checks

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
- main/test/flix/Test.Def.ChooseStar.Simple.flix
Closes #7608 
Fixes issue where a doc-comment immediately after the license block-comment would get misplaced into the wrong CommentList.
> fix: Capture doc-comments on top-level traits.

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
Closes #7636 
This PR makes it a parse error to have either a LetMatch or a LetRecDef without a following right-hand side expression. A test for each of these cases has been added. An example would be this program:
```scala
def foo(): Unit \ IO =
def bar(): Int32 = 123
def main(): Int32 = 123
```
Which gives a single parse error:
```
>> Parse Error: Expected ';' before 'def'
2 |     def bar(): Int32 = 123
^^^
Here
Syntactic Context: OtherExpr.
```
> fix: rhs-expression required on LetMatch and LetRecDef

- main/src/library/Array.flix
- main/src/library/Iterable.flix
- main/src/library/MutDeque.flix
- main/src/library/MutList.flix
- main/src/library/MutMap.flix
- main/src/library/MutQueue.flix
- main/src/library/MutSet.flix
- main/test/ca/uwaterloo/flix/library/TestIterable.flix
This PR adds `Iterable` instances for mutable data structures and improves the documentation of `Iterable.Aef`.
See issue #7639
> feat: add Iterable instances for mutable data structures (issue #7639)

- main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
- main/test/flix/fuzzers/FuzzDeleteLines.scala
- main/test/flix/fuzzers/FuzzDuplicateLines.scala
- main/test/flix/fuzzers/FuzzPrefixes.scala
- main/test/flix/fuzzers/FuzzSwapLines.scala
Closes #7640 
Fixes a crash on malformed datalog program and adds the program to parser test suite. 
Also adds a datalog example (`ford-fulkerson.flix`) to the fuzzer suite and fixes 3 more crashes found by doing that.
> fix: fix datalog crash

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
Closes #7679
Closes #7681 
Test cases added to cover both issues
With the example:
```scala
def foo(): Int32 =
forA ( x <- bar(); y <- baz() yield ???
def main(): Unit = ()
```
We now get errors rather than a crash.
```
>> Parse Error: Expected ';' before 'yield'
2 |     forA ( x <- bar(); y <- baz() yield ???
^
Here
Syntactic Context: OtherExpr.
>> Parse Error: Expected ')' before 'yield'
2 |     forA ( x <- bar(); y <- baz() yield ???
^
Here
Syntactic Context: OtherExpr.
```
> fix: handle malformed for-fragments

- main/src/library/FromJava.flix
- main/src/library/ToJava.flix
- main/test/ca/uwaterloo/flix/library/TestFromJava.flix
- main/test/ca/uwaterloo/flix/library/TestToJava.flix
This PR added `ToJava` and `FromJava` instances for the builtin types `String`, `Char` and the number types `Int32` etc.
For Flix types that are primitive types in Java, the conversion is to the respective Java object rather than the primitive type (the Flix type is already the primitive) type. ie. Flix `Char` goes to Java's `java.lang.Character`. `String`, `BigInt` and `BigDecimal` are just identity. Converting to the Java object means they can be stored in Java collections.
The PR also adds `toJavaObject(a: t): ##java.lang.Object with ToJava[t]` to convert safely to the Java representation and upcast to `java.lang.Object`.
> feat: add ToJava and FromJava instances for builtin types String, Char and the number types

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
In recent issues regarding parser crashes the fix has been to use `zeroOrMore`/`oneOrMore` on multiple occasions. 
This prompted me to run through the parser to see if there where more `while`-loops that were replaceable. This is desirable for a couple of reasons:
1. It centralizes a spot for debugging/optimization: `zeroOrMore`.
2. It makes sure looping is done in a resilient manner. 
3. It improves readability at the call-site.
I saw that if we abstract separation just a little, allowing `Required`, `Optional` and `None` we could capture a lot of use-cases.
Going through the parser I also found a number of unnecessary `if`s. This is a remnant from before recover-sets, and is no longer needed!
This should admittedly have been a separate PR.
> feat: add `Separation` enum for better error-handling

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
Closes #7698 
Adds the example as a test-case. 
The fix was to delete some code that handled the case of a trailing doc-comment
```scala
mod Foo {
def bar(): Int32 = 123
/// Like this one
}
def main(): Unit = ()
/// Or this one
```
Turns out, that special handling was no longer needed due to other updates!
> fix: Emit error on faulty program

- main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
Closes #7708 
Example added as a test case, along with two similar examples.
> fix: capture `main` after bad module

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
Closes #7711.
Adds 3 test cases to cover the issues.
> feat: recover in `trait`, `instance` and `eff`

- main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
For instance:
```scala
def new(): Int32 = 123
```
gives 
```
>> Expected <Name>, <greek name>, <name>, <user-defined operator> or <math name> before 'new'.
1 | def new(): Int32 = 123
^^^
Here
Hint: 'new' is a keyword.
```
> feat: nice error when keyword is used as name.

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
This PR fixes a bug where record literals with comments in them would get read as block-expressions. A test case is added to avoid regressions.
> fix: record literal detection

- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala
- main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
> feat: add type constructors for method and static method return types

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
The following example now invokes `PredicateCompleter`:
```scala
﻿def isConnected(s: Set[(Int32, Int32)], src: Int32, dst: Int32): Bool =
let rules = #{
Path(x, y) :- Edge(x, y).
Path(x, z) :- Path(x, y), Edge(y, z).
P // <- Suggests Path/2
};
let edges = inject s into Edge;
let paths = query edges, rules select true from Path(src, dst);
not (paths |> Vector.isEmpty)
```
> fix: PredicateCompleter

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
This example now triggers `UseCompleter`.
```scala
use List.fil // Suggests List.filter
```
> fix: `UseCompleter`

- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Closes #7637 
The example from the issue now has proper highlighting. The issue was a wrong source location on buitin operators.
> fix: source location on built-in binary ops

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Closes #7743 by using `oneOrMore` in parser to emit errors on empty use many or import many.
For instance this example
```scala
import List.{}
def main(): Unit \ IO =
use SemiGroup.{};
println("Hello World!")
```
now outputs:
```
-- Parse Error (Import) -------------------------------------------------- main/foo.flix
>> Expected at least one <name>.
1 | import List.{}
^^
Here
-- Parse Error (Use) -------------------------------------------------- main/foo.flix
>> Expected at least one <name>.
3 |     use SemiGroup.{};
^^
Here
Compilation failed with 2 error(s).
```
> fix: use `oneOrMore` on uses and imports

- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Closes #7642 by fixing the source location on binary expressions where the operator is user-defined.
> fix: `SourceLocation` on user defined operators

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
Triggers `EnumCompleter` when using the new parsing pipeline.
```scala
enum Color {
case Red,
case Green
}
def f(c: Color): Bool = match c {
case Co // <- Suggests 'Color'
}
```
> fix: New parsers triggers `EnumCompleter`

- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
- main/test/ca/uwaterloo/flix/language/phase/TestLexer.scala
Closes #7728 
This example
```scala
def main(): String = "This is a
multi-line string"
```
Gives:
```
-- Lexer Error -------------------------------------------------- main/foo.flix
>> missing '"' in string.
1 | def main(): String = "This is a
^
String starts here.
-- Lexer Error -------------------------------------------------- main/foo.flix
>> missing '"' in string.
2 |  multi-line string"
^
String starts here.
```
Note that there are **two** errors. That's because once we see the new-line in the string, we can't assume there will be a closing `"` later in the file, so we stop consuming characters at that point. Then if there actually is a `"` later, that starts a new string, which is also unterminated.
This is the most conservative behaviour, although we could do better if we checked …
> feat: Emit `LexerError` on multiline strings

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
A simple change that avoids mentioning `TokenKind.Err` in parser errors.
> fix: avoid double reporting lexer errors

- main/src/ca/uwaterloo/flix/language/errors/CodeHint.scala
- main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
Removed for two reasons:
- A compiler debugging feature masquerading as a code hint.
- Brittle and confusing.
> feat: remove `NonTrivialEffect` code hint

- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
Closes #7783 
The issue was that a doc-comment with no text was read as a line-comment. That seems innocent but we have the habit of writing:
```scala
///
/// The comment about gets read as a line-comment.
///
pub type alias Static = IO
```
> fix: `SourceLocation`s on declarations

- examples/larger-examples/datalog/sequence.flix
- main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala
- main/src/ca/uwaterloo/flix/language/errors/LexerError.scala
- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/library/Applicative.flix
- main/src/library/CommutativeMonoid.flix
- main/src/library/CommutativeSemiGroup.flix
- main/src/library/Eq.flix
- main/src/library/Functor.flix
- main/src/library/Group.flix
- main/src/library/JoinLattice.flix
- main/src/library/MeetLattice.flix
- main/src/library/Monad.flix
- main/src/library/Monoid.flix
- main/src/library/Order.flix
- main/src/library/PartialOrder.flix
- main/src/library/SemiGroup.flix
- main/src/library/Traversable.flix
- main/test/ca/uwaterloo/flix/language/phase/TestInstances.scala
- main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/flix/Test.Dec.Trait.flix
- main/test/flix/Test.Def.Generalization.flix
- main/test/flix/Test.Exp.Fixpoint.Compose.flix
- main/test/flix/Test.Kind.Trait.flix
Closes #7727 
With the example from the issue we now get error:
```
-- Lexer Error -------------------------------------------------- main/foo.flix
>> '.' has whitespace on both sides.
18 |     area(Shape    .    Rectangle(2, 4)) |> println
^
here
```
Note that the rule is that no `.` can have whitespace _on both sides_. That's because we need to be able to parse laws and fixpoint constraints:
```scala
law reflexivity: forall(x: a). x == x
//                           ^ Like this
// But this means that this is also fine:
println(area(Shape.    Rectangle(2, 4)))
```
All whitespace information is lost after the lexer, so the check needs to be in this phase. We can't do special handling of laws and fixpoint constraints in the lexer though, because it's context-free. Hence this compromise.
> feat: LexerError for free dots

- main/src/ca/uwaterloo/flix/language/ast/SourcePosition.scala
- main/src/ca/uwaterloo/flix/language/ast/Token.scala
- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
The idea is to store store source positions in Token.
Note: We require that source positions are one-indexed.
> refactor: use `SourcePosition` in `Token`

- build.gradle
We want to enforce that tests are successful with just 3g memory.
> refactor: reduce amount of memory available for tests

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
Closes #7820 
The issue was that `close` calls into `comments` which then does a bunch of calls to `nth` consuming parser fuel.
That's fine in most cases but in the case of a long series of statements, there's a long string of calls to `close` when recursion bottoms out. Many calls to close with no advances makes it look like the parser is stuck, but really everything is fine. We just have deep nesting.
The fix was to allow `comments` to look up the current token without consuming fuel. This is fine, since the behavior is enclosed in `comments` and wont affect fuel elsewhere.
> fix: Don't consume fuel when checking for comments

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
This fixes a bug I caught while fuzzing the parser.
Here's a minimal example the produces the issue:
```scala
mod DelayMap {
@Experimental
pub de
```
This example has been added as a test case. 
3 tests were unignored as well, since they all pass.
> fix: add termination to module recover loop

- main/src/library/Adaptor.flix
- main/src/library/Files.flix
I'm not sure why these are not caught by the redundancy checking
> refactor: remove redundant casts

- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
Fixes one of #7769 tasks.
WIP:
- more tests should be done with an ambiguous method, e.g., with overloading.
- cleaning code
- finish subTyping
`valueOf` method of `String` doesn't work as it is a static method, which gives upon call:
` Exception in thread "main" java.lang.IncompatibleClassChangeError: Expecting non-static method 'java.lang.String java.lang.String.valueOf(int)'`
> feat: extend method resolution with `TypeError.AmbiguousMethod`

- main/src/ca/uwaterloo/flix/language/errors/NameError.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
This is in preparation for removing the use of `Validation` in `Namer`
> refactor: add `SharedContext` to `Namer`

- main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala
- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/flix/Test.Exp.Jvm.InvokeMethod2.Chaining.flix
- main/test/flix/Test.Exp.Jvm.InvokeMethod2.ZeroArg.flix
- main/test/flix/Test.Exp.Jvm.InvokeMethod2.flix
> refactor: switch from `Hash` symbol to `Currency` symbol for `InvokeMethod2`

- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
notice that actually here you would like to have sub-effecting on the structure itself, i.e. `Iterator[a, b, c] <: Iterato[a, d, e]` if `b <: d` and `c <: e`
> refactor: explicit effect up casting

- main/src/ca/uwaterloo/flix/tools/pkg/Dependency.scala
- main/src/ca/uwaterloo/flix/tools/pkg/ManifestError.scala
- main/src/ca/uwaterloo/flix/tools/pkg/ManifestParser.scala
- main/src/ca/uwaterloo/flix/tools/pkg/PackageError.scala
- main/src/ca/uwaterloo/flix/tools/pkg/Permission.scala
- main/src/ca/uwaterloo/flix/tools/pkg/Repository.scala
- main/src/ca/uwaterloo/flix/tools/pkg/RepositoryError.scala
- main/src/ca/uwaterloo/flix/tools/pkg/SemVer.scala
- main/test/ca/uwaterloo/flix/tools/TestManifestParser.scala
- main/test/ca/uwaterloo/flix/tools/TestPermission.scala
- main/test/ca/uwaterloo/flix/tools/ToolsSuite.scala
#7753
Added support for permission to `toml` files.
Is this along the lines of what we want?
> feat: add support for manifest permissions to `flix.toml`

- main/src/library/Adaptor.flix
- main/test/ca/uwaterloo/flix/library/TestAdaptor.flix
- main/test/ca/uwaterloo/flix/library/TestDebug.flix
- main/test/ca/uwaterloo/flix/library/TestObject.flix
- main/test/flix/Test.Exp.Null.flix
- main/test/flix/Test.Kind.Def.flix
Either by
- `checked_cast`
- `???()` instead of `unchecked_cast(??? as _ \ IO)`
Additional could be removed if we
- Checked composite types `Array[String, r]` to `Array[Object, r]`
- Allowed null consistently `Null` to `List[Int32]`
- Char <-> Int32
- `CharSequence` to `String`
- `List[Int32]` to `Object`
> refactor: remove `unchecked_cast`s

- examples/railroad-network.flix
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/KeywordExprCompleter.scala
- main/src/ca/uwaterloo/flix/language/ast/SyntaxTree.scala
- main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
- main/src/library/String.flix
This is a shorthand for an unchecked effect cast to pure. 
We will want it for our OO-refactoring, as shown with one example in String.flix
We can discuss later if it should have richer semantics.
> feat: add `unsafe` expression

- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
```
before:
~~~~ Flix Compiler Performance ~~~~
Throughput (best): 128.377 lines/sec (with 24 threads.)
min: 87.889, max: 128.377, avg: 108.994, median: 111.914
Finished 51 iterations on 66.980 lines of code in 31 seconds.
after:
~~~~ Flix Compiler Performance ~~~~
Throughput (best): 130.169 lines/sec (with 24 threads.)
min: 89.968, max: 130.169, avg: 116.259, median: 117.065
Finished 51 iterations on 66.980 lines of code in 29 seconds.
```
> feat: lex and parse in parallel by size

- main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala
- main/test/flix/Test.Exp.Jvm.InvokeConstructor2.flix
The tests are duplicated from `invokeConstructor`.
Support for array is not yet available.
Also, empty constructor test is not passing until #7918 has been merged in.
> feat: add tests for `invokeConstructor2`

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala
- main/src/ca/uwaterloo/flix/util/Options.scala
We can now choose
```
--Xsubeffecting nothing
--Xsubeffecting lambdas
--Xsubeffecting lambdas-and-instances
--Xsubeffecting lambdas-and-defs
```
with `nothing` being default, thereby not changing anything
> feat: sub-effecting (as an option)

- .github/workflows/community-build.yaml
This project will be archived as the improved Java interop renders it redundant.
> ci: remove fcwg from community build

- main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
- main/test/flix/Test.Exp.Instanceof.flix
This PR requires you to import a Java class or interface before using it in an `instanceof`.
> refactor: require imported name in `instanceof`

- examples/file-information.flix
- examples/polymorphic-record-extension-and-restriction.flix
- examples/polymorphic-record-update.flix
- examples/record-construction-and-use.flix
- examples/working-with-files-and-directories.flix
Updates the examples on the playground. However, once https://github.com/flix/flix/pull/7930 has been merged records will use `#` everywhere, i.e., all examples will be fixed, not just the ones in the playground.
Related to https://github.com/flix/flix/issues/7897
> docs: update playground samples to `#` for `RecordSelect` syntax

- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
This PR adds support for structs to the weeder. It does not include checking for duplicate fields yet - that will come in a little bit(which is why this is a draft for now). This is related to issue #7924
> feat: Add support for structs to the Weeder

- main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala
- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/LiftedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala
- main/src/ca/uwaterloo/flix/language/ast/MonoAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Name.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/OccurrenceAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ReducedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/DocAst.scala
- main/src/ca/uwaterloo/flix/language/phase/EffectBinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Inliner.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/OccurrenceAnalyzer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
This addresses #7934
This is a big pull request of mostly repetitive work. Placeholder values(like `Map.empty`) are used to silence compile errors when necessary.
> feat: Added structs to the various ASTs

- main/src/library/Float64.flix
> refactor: support for `InvokeConstructor2` in `Float64.flix`

- main/src/library/Int32.flix
> refactor: support for `InvokeConstructor2` in `Int32.flix`

- main/src/library/Int64.flix
> refactor: add support for `InvokeConstructor2` in `Int64.flix`

- main/src/library/Concurrent/ReentrantLock.flix
> refactor: support for `InvokeConstructor2` in `ReentrantLock.flix`

- main/src/library/Int16.flix
> refactor: support for `InvokeConstructor2` in `Int16.flix`

- main/src/library/Int8.flix
> refactor: support for `InvokeConstructor2` in `Int8.flix`

- main/src/library/StringBuilder.flix
> refactor: support for `InvokeConstructor2` in `StringBuilder.flix`

- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala
- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
This PR is related to issues #7938 and #7936
It adds support to name resolution but no further steps, hence the runtime exceptions I sometimes throw.
For what it's worth, I manually verify all that the `ignore` tests I add would theoretically pass
As a side question: I have been putting all the struct code after the equivalent enum code. Would it make sense to put it after the restrictableenum code? Logically, it might make sense for all the enum constructs to be together and then have the struct ones
> feat: Add struct support to the `Resolver`

- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala
- main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala
This pull request adds struct support to the kinding phase of the compiler.
Addresses issue #7923 
This PR does not include checking that the last type parameter has kind `Region`.
To keep this PR small, that will come in the next PR as it requires a few changes to the parser and a few other parts too.
> feat: Add struct support to the `Kinder`

- main/src/library/System.flix
> refactor: support for `InvokeConstructor2` in `System.flix`

- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala
- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
The reasoning for this is that the last type parameter of a struct is always its region. Thus, it must have the effect kind
> feat: Add checking that the last type parameter in a `struct` declaration is of kind `Effect`

- main/src/ca/uwaterloo/flix/language/ast/SyntaxTree.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
This PR implements struct put in the parser/weeder and should resolve #7923 
Along the way implementing put, I realized a few mistakes with `get` so this PR also includes simplifications to `get`.
> feat: implement struct put and simplify struct get

- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
The only significant transformation is with expressions of the form
```
new StructName { } @ r
```
I don't think anything can be done to the get and put struct expressions since with those the struct name is not listed
> feat: Add name resolution for struct expressions

- main/test/ca/uwaterloo/flix/language/errors/TestCompilationMessage.scala
This test doesn't pass on windows. There's something wrong with line endings - I really couldn't figure it out, so this is the lazy fix
Ah, the issue is that the file is in LF, so stripMargin produces \n newlines instead of the code that produces \r\n newlines even though the system uses \r\n. I think this supported the fact that we should ignore the newline format when comparing strings here
> fix: TestCompilationMessage on windows

- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
This is one big PR containing all changes to `Namer`. We can either choose to merge it all or just split it out into smaller PRs.
Depends on https://github.com/flix/flix/pull/8056
Closes https://github.com/flix/flix/issues/7875
> refactor: remove `Validation` from `Namer`

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala
- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/errors/NameError.scala
- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
- main/src/ca/uwaterloo/flix/util/Options.scala
- main/src/library/BigInt.flix
- main/test/ca/uwaterloo/flix/TestMain.scala
The idea is to have a flag that, when enables, fails on deprecated features.
(The flag is temporary, but needed for the big interop migration.)
> feat: add `--Xno-deprecated` and enable for old-style Java interop

- main/src/library/Int16.flix
- main/src/library/Int32.flix
- main/src/library/Int64.flix
- main/src/library/Int8.flix
> chore: update syntax for imports in IntX.flix files

- main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/SyntaxTree.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
This removes unused (dead) code related to `InvokeStaticMethod` which does not exist before the `Resolver`.
> chore: remove unused `InvokeStaticMethod2` pre `Resolver`

- main/src/library/Files.flix
Related to #7944,
should be merged in after array support, i.e., #7926.
@magnus-madsen
> chore: update import syntax in `Files`

- main/src/ca/uwaterloo/flix/language/ast/Scheme.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/RestrictableChooseConstraintGen.scala
This PR updates `Scheme.instantiate` to return a type variable mapping from the original generalized variable to the instantiated variable. It also updates all current uses of `Scheme.instantiate` to ignore it.
This is useful for structs.
> feat: return instantiated variable mapping in `Scheme.instantiate`

- main/src/library/Prelude.flix
- main/src/library/Random.flix
- main/src/library/Regex.flix
- main/src/library/String.flix
- main/src/library/StringBuilder.flix
Some of the files in the title had nothing to cleanup, but for completeness/documentation I put them there.
Some of the method invocations, especially related to regex, couldn't be transformed for some reason. I documented them here: https://github.com/flix/flix/issues/8139.
I also didn't update any of the invocations that were expected to have a region effect
This addresses #8096
> chore: clean up old imports in `Prelude`, `Random`, `Regex`(partially), `Set`, `Stringbuilder`, `String`

- main/test/flix/Test.Exp.Jvm.NewObject.flix
I chose not to refactor `checked_cast` expressions since they don't seem to be compatible java style method invocation.
This addresses https://github.com/flix/flix/issues/8096
> chore: new method invocation syntax in `Test.Exp.Jvm.NewObject.flix`

- main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala
@magnus-madsen @mlutze
there was a mistake in subtyping for arrays, as subtyping was made the other way.
Fixed and refactored to be more intuitive. If you can merge it fast for the other tests to be checked.
Thank you.
> refactor: refactor and short fix for arrays in subtyping

- main/src/library/Console.flix
Related to #8096.
The consecutive call seems to be working, probably because thanks to #8168.
> chore: update import syntax completely for  `Console.flix`

- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
- main/src/library/Regex.flix
- main/test/flix/CompilerSuite.scala
#8096 
Unfortunately, `Regex.flix` at one point calls a method entitled `region`. To fix this, temporarily accept `₹region` as a non-keyword "region" token. Should work for any lowercase name.
> chore: Fix regex imports

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/library/Debug.flix
- main/src/library/Prelude.flix
`def name(..)` can be given a tail set that will stop the name parsing, this is lower case name by default, making `Upper.lower.lower` parse as `(Upper.lower).lower`
> feat: parse less names

- main/src/ca/uwaterloo/flix/language/ast/SyntaxTree.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
- main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala
This PR:
- fixes incorrect parsing of struct put expressions
- Makes struct fields `Name.Label`(a change that will also have to be propagated throughout the other phases)
> fix: parse struct expressions correctly

- main/src/ca/uwaterloo/flix/language/phase/PatMatch.scala
- main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Regions.scala
- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
#8154 
These are all straightforward modifications. I didn't split them up so as to avoid the PR spamming I've been doing, but I would be happy to split them up if that's preferable
> feat: add `Throw` support to `PatMatch`, `PredDeps`, `Redundancy`, `Regions`, `Stratifier`, and `CodeHinter`

- main/src/ca/uwaterloo/flix/language/phase/Verifier.scala
struct put has 2 expressions, but I had previously implemented it like it only had one in the verifier. This PR fixes this
> fix: fixed `struct` verifier bug

- main/src/ca/uwaterloo/flix/language/phase/EffectVerifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Regions.scala
Like arrays, the `EffectVerifier` doesn't yet verify the region effects of struct put/get
> feat: add struct support to `EffectVerifier` and `Regions`

- main/test/ca/uwaterloo/flix/language/phase/TestInstances.scala
- main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
- main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
Now that initial struct support is complete, enable tests that were previously ignored
Tests in the form of flix files will come in a different PR
> chore: enable struct related tests

- main/src/ca/uwaterloo/flix/language/phase/Eraser.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
Currently, if we have
`struct.field.field`, the initial `struct.field` gets erased to `Object` and then the JVM complains. This fixes this.
Also, in general it changes the `struct` backend to resemble `Tuple` more.
> fix: `StructGet` and `StructPut` backend type fixes

- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
This is not the prettiest change. The problem is that the work of the `Monomorpher`, `Eraser`, and `Simplifier` must all be done at once.
- `Monomorpher` because we must determine the individual type of each field
- `Eraser` because we cannot infinitely expand types and therefore must erase at the same time
- `Simplifier` because this is all done during generation of `MonoType`
Though this duplicates work and isn't pretty, I don't think it leads to correctness issues, as it is just doing stuff that is done in earlier / later phases
> fix: Handle infinitely recursive struct types with some premature erasure

- main/src/ca/uwaterloo/flix/api/lsp/provider/ShowAstProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/VarCompleter.scala
- main/src/ca/uwaterloo/flix/language/ast/MonoType.scala
- main/src/ca/uwaterloo/flix/language/ast/Purity.scala
- main/src/ca/uwaterloo/flix/language/ast/SyntaxTree.scala
- main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala
- main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
- main/src/ca/uwaterloo/flix/language/phase/Eraser.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/MonoTypes.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Reducer.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenEffectClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenFunAndClosureClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/TypeConstraint.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/CaseSetUnification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/FastBoolUnification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/TraitEnvironment.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/TypeNormalization.scala
- main/src/ca/uwaterloo/flix/tools/CompilerPerf.scala
- main/src/ca/uwaterloo/flix/tools/Summary.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
1. Lists must start their line with whitespace to parse
2. Lists must always use 1. 1. 1. 1. or A. A. A. otherwise it doesn't parse
3. ` is inline code, no matter if there three or one
4. {{{ }}} is code blocks
5. /// doesn't do anything, its not flix
> docs: fix lists and code in doc comments

- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
Previously the whole struct's location was saved instead of the field's location
> fix: struct field location

- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
This fixes the problem for structs but not for enums.
For some reason, if you try to change the equivalent line in the enum class, you get a `unexpected duplicate enum: 'Nil'` error/
> fix: tryLookupName avoid duplicates

- .github/workflows/ide-tests.yaml
This fixes interference between the normal testing suite and the IDE testing suite.
> ci: give IDE tests their own concurrency group

- examples/larger-examples/restrictable-variants/sequences.flix
- main/src/library/Array.flix
- main/src/library/Chain.flix
- main/src/library/DelayList.flix
- main/src/library/File.flix
- main/src/library/Foldable.flix
- main/src/library/List.flix
- main/src/library/Map.flix
- main/src/library/MutMap.flix
- main/src/library/MutSet.flix
- main/src/library/Nec.flix
- main/src/library/Nel.flix
- main/src/library/Set.flix
- main/src/library/String.flix
- main/src/library/StringBuilder.flix
- main/src/library/Vector.flix
The remaining inconsistencies are here because of other per-file consistencies about naming the subject fx.
> docs: consistent `size` and `length` wording

- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/library/Ref.flix
I could potentially do more work to also get rid of `ref` in the compiler if that would be helpful.
> refactor: make `Ref` module use `struct`

- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
I guess I missed this one after all the merges from main.
Related to https://github.com/flix/flix/issues/6270
> refactor: rename variable to `enum0`

- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
They are often swapped or backwards and have less information than their generic default
> feat: remove over/under-applied type errors

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
Because of recent changed to name parsing, this duplicated logic is no longer needed
> refactor: remove duplicated `InvokeMethod` logic

- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
previously the test said method not found because of the simplified logic in `isKnown` but now (#8497) it correctly doesn't touch the JVM constraint (because of the type variable in the array) so its just some mismatched types
> fix: reenable test

- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/util/Grammar.scala
> refactor: use `Grammar.scala` in `MismatchedOpArity`

- main/src/ca/uwaterloo/flix/tools/Tester.scala
If you're unlucky or have slow tests, the reporter might get null before the tester has inserted an element yet
> fix: null match on tester

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
> fix: `try` with missing `with` or `catch`

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/KeywordCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Priority.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/TypeBuiltinCompleter.scala
Introduces better priorities based on occurances in std lib. Before, the priorities were based on the occurances relative to all other items in the set. Now it's only relative to the items that share a first letter with them. For instance, while `def` is more common than `pub`, there's no reason to give one a higher priority than the other, because they would never both occur in list of suggestions anyways.
This PR also introduces `Priority.Default`.
Related to #8419.
> refactor: better completion priorities based on occurances in std lib

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/InvokeMethodCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/InvokeStaticMethodCompleter.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/Loader.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala
They are in logical order now and some functions are moved to `Type` or `JvmOps`
Related to #8574 
Follow up issue to clean up jvm interop logic in phases #8592
> refactor: move functions in TypeReduction

- main/src/ca/uwaterloo/flix/language/phase/unification/OldStarUnification.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
Unification.scala is used in a lot of places. I'm hiding it behind a proxy so that we can transition to the new solver without having to change all the use sites. We can change the interface once the new solver is in place.
> refactor: add unification proxy

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Clock.flix
- main/src/library/Process.flix
The handler should be:
```scala
mod Process {
import java.lang.ProcessBuilder
import java.lang.Runtime
///
/// Runs the `Process` effect of the given function `f`.
///
/// In other words, re-interprets the `Process` effect using the `Exec` effect.
///
pub def run(f: Unit -> a \ ef): a \ (ef - Process) + Exec = {
// Currently try-with typing is broken, so fix it with checked_ecast
checked_ecast(try {
f()
} with Process {
def exec(cmd, args, k) = region rc {
let arr = List.toArray(rc, cmd :: args);
let pb = new ProcessBuilder(arr);
pb.start();
k()
}
})
}
}
```
but this does not work because of #8619
> feat: add `Process` effect

- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
> refactor: remove `Validation` from `visitTypeVar` in `Kinder`

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
This fixes an issue where annotation completions aren't suggested as expect. For instance, typing `@T` would not give us the suggestion `@Test`. Now it does.
If only typing `@` we only get suggestions by invoking the suggestions using ctrl+space. However, when typing for instance `@D` we immediately get the suggestion `@Deprecated`.
For now I've given the priority 1 to the new `getSyntacticContext` case. I believe that what really matters is that it's prioritised above parse error, but I'm unsure. Currently, it seems to have the intended behaviour.
Related to #8638
> fix: broken annotation completions

- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
Removes `Validation` from
https://github.com/flix/flix/issues/8546
> refactor: remove `Validation` from more functions in `Kinder`

- main/src/ca/uwaterloo/flix/language/ast/LiftedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/OccurrenceAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ReducedAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/LiftedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/ReducedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/EffectBinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Eraser.scala
- main/src/ca/uwaterloo/flix/language/phase/Inliner.scala
- main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala
- main/src/ca/uwaterloo/flix/language/phase/OccurrenceAnalyzer.scala
- main/src/ca/uwaterloo/flix/language/phase/Reducer.scala
> chore: drop `Def.purity` from `LiftedAst`, `ReducedAst` and `OccurrenceAst`

- main/src/ca/uwaterloo/flix/language/errors/ParseError.scala
> chore: drop `ParseError.Legacy`

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/TypeBuiltinCompleter.scala
Support for the `Region[r]` type completion was missing, it has now been added.
Related to #8676, specifically item 2
> fix: missing region type completion

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/MatchCompleter.scala
This PR fixed an issue where match completions are suggested at odd times. This was due to a too "forgiving" regex which has now been fixed.
Now match completions are only suggested if you've just typed "match" or if the previous word was "match" and the current word matches an enum.
Related to #8676, specifically item 3
> fix: match completion suggestions at odd times

- main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala
- main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala
- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala
- main/test/flix/Test.Exp.Jvm.InvokeMethod.VarArgs.flix
Example:
```scala
import java.nio.file.Path
@Test
def testInvokeVarArgs01(): Path \ IO =
Path.of("hello", (...{}: Vector[String]))
@Test
def testInvokeVarArgs02(): Path \ IO =
Path.of("hello", ...{"foo.txt"})
@Test
def testInvokeVarArgs03(): Path \ IO =
Path.of("hello", ...{"foo.txt", "bar.txt"})
```
> feat: add support for varargs

- main/test/ca/uwaterloo/flix/BenchmarkSuite.scala
- main/test/ca/uwaterloo/flix/util/FlixSuite.scala
The name parameter is the test name shown when running the test
> feat: add `name` parameter to `mkTestDirCollected`

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SymbolProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/LoweredAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/TypedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
This is redundant (and unused information) because tparams is also kept.
> refactor: remove unused `Enum.tpe` from `TypedAst` and `LoweredAst`

- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
`visitApplyTopLevelFull` will handle padding anyway, so if the the number of parameters matches the number of arguments then `visitApplyTopLevelFull` will not have any effect, i.e., it will just return an `ApplyDef`
> refactor: remove redundant case in `visitApplyDef` in `Resolver`

- main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala
It doesn't use `this` so it felt cluttering to have it inside `StrictSubstitution`
> refactor: move `default` out of `StrictSubstitution`

- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
> refactor: remove `Validation` from `visitExp` in `Kinder`

- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/ast/ReducedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/shared/ExpPosition.scala
- main/src/ca/uwaterloo/flix/language/dbg/DocAst.scala
- main/src/ca/uwaterloo/flix/language/phase/EffectBinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Reducer.scala
- main/src/ca/uwaterloo/flix/language/phase/TailPos.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
> refactor: move `ExpPosition` from `Ast` to `shared`

- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
This is the final step in removing `Validation` from `Kinder`.
Closes https://github.com/flix/flix/issues/8546
> refactor: remove `Validation` from `Kinder`

- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
mkList needs the element type not the list type
> fix: ill-typed fixpoint lambda in `Lowering`

- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/RecordConstraintSolver.scala
This PR introduces a new unification function for records. This is important for the new solver:
- it uses the resilient strategy of giving back constraints instead of creating an error
- it does not call `Unification.xyz`
I've also added some type rule comments to annotate each match rule. Since the Scoped Labels paper does not use separated constraint generation and solving, I had to make up my own syntax.
> feat: RecordConstraintSolver

- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
Instead of converting args up front and the destructing the list. I now destruct the list first and then convert. This achieves:
- More checking of expected list lengths
- allows adding array regions and arrow effects to monotypes in follow up PR
> refactor: `Simplifier.visitType`

- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/SchemaConstraintSolver.scala
- main/src/ca/uwaterloo/flix/util/Options.scala
The same as the last PR. I will follow up to change everywhere it says "record" to "row", but I will leave the type rules as they are.
I've bumped up the solver iteration limit since some schema cases were struggling.
> feat: introduce SchemaConstraintSolver

- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Related to https://github.com/flix/flix/issues/8540
> refactor: remove `HardFailure` for deprecated Java errors in `Weeder2`

- main/src/ca/uwaterloo/flix/language/ast/MonoAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
Also removes `MonoAst.Expr.TypeMatch` since it was only used to throw an ICE but it was never constructed anywhere.
Closes https://github.com/flix/flix/issues/8840
> refactor: remove dead code

- main/src/ca/uwaterloo/flix/language/ast/MonoAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala
Moved `ApplyAtomic` before `ApplyClo` because that's the alphabetical ordering.
> style: reorder `MonoAst`

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SymbolProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/HoleCompletion.scala
- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala
- main/src/ca/uwaterloo/flix/language/ast/MonoAst.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/LoweredAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/ResolvedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/TypedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
- main/src/ca/uwaterloo/flix/language/phase/EntryPoint.scala
- main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala
added source locations for Def, Sig and Op AST nodes where these are missing. These already do exist for some ASTs, but are removed during the Naming phase `Namer.scala`.
Related to the work being done in #8837
> refactor: added source locations for `Def`, `Sig` and `Op`

- main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
Depends on https://github.com/flix/flix/pull/8881
Related to https://github.com/flix/flix/issues/8810
> refactor: remove trivial instances of `Validation` in `Deriver`

- main/src/library/Console.flix
> refactor: rename `Console`'s `printErr` and `printlnErr` to `eprint` and `eprintln`

- main/src/library/Logger.flix
> chore: rename `Logger.debug1` to `Logger.debug`

- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/shared/LabelledPrecedenceGraph.scala
- main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala
- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
> refactor: move `LabelledPrecendenceGraph` from `Ast` to `shared`

- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
Removes all occurrences of `SoftFailure` in `Resolver` (except at the top level)
> refactor: remove `SoftFailure` from `Resolver`

- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/ast/LiftedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala
- main/src/ca/uwaterloo/flix/language/ast/MonoAst.scala
- main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala
- main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala
- main/src/ca/uwaterloo/flix/language/ast/shared/ScalaAnnotations.scala
> refactor: move `IntroducedBy` and `EliminatedBy` from `Ast` to `shared.ScalaAnnotations`

- main/src/ca/uwaterloo/flix/language/ast/Purity.scala
This PR makes i such that non-IO base effects will not trigger full algebraic effect instrumentation
> feat: Make `Purify.fromType` consider base effects

- main/src/ca/uwaterloo/flix/api/lsp/StackConsumer.scala
This PR adds a new consumer for the LSP visitor. This stack consumer adds everything visited to a stack where the head is the last element visited.
Related to #8639
> feat: stack consumer for use with LSP visitor

- main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala
- main/test/ca/uwaterloo/flix/api/lsp/VisitorSuite.scala
This PR fixes an issue where the inside function of the LSP visitor is too strict. This is because it concludes that something cannot be inside of a location if it's synthetic, despite synthetic locations occuring within actual, valid AST nodes. This means that the function concludes, erroneously, that positions that are actually within such AST nodes aren't.
This PR fixes this by simply removing the check and the associated test.
Related to #8639
> fix: include synthetic source locations in visitor

- main/src/library/List.flix
Let's see if this improves performance on the `List.map` benchmark.
> refactor: use accumulator in `List.map`

- main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala
This PR adds a missing visit to type of enum cases.
Related to #8639
> fix: add missing visit to enum case type in LSP visitor

- main/src/ca/uwaterloo/flix/api/lsp/StackConsumer.scala
This PR adds the missing impl of `consumeVarBinder` to `StackConsumer
Related to #8639
> fix: added missing impl of consumeVarBinder to StackConsumer

- main/src/ca/uwaterloo/flix/api/lsp/StackConsumer.scala
- main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala
This PR changes consumeVarBinder to also take the type of the bound value.
Related to https://github.com/flix/flix/issues/8639
> fix: changed consumeVarBinder to also take the type of the bound value

- main/src/ca/uwaterloo/flix/language/ast/Scheme.scala
- main/src/ca/uwaterloo/flix/language/phase/EntryPoint.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver2.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/TraitEnv.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/TraitEnvironment.scala
This will allow us to treat the trait environment more abstractly. Specifically, we need to manipulate it by adding constraints, etc., but the implementation should remain hidden.
> refactor: introduce TraitEnv

- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
Based on #8998, now we can omit some redundant subeffecting on lambdas (can be merged independently)
> feat: Optimize generated lambda subeffecting

- main/src/library/Adaptor.flix
- main/src/library/Chain.flix
- main/src/library/Environment.flix
- main/src/library/Files.flix
- main/src/library/Regex.flix
- main/src/library/StringBuilder.flix
- main/src/library/Vector.flix
- main/test/ca/uwaterloo/flix/library/TestAdaptor.flix
- main/test/ca/uwaterloo/flix/library/TestToJava.flix
- main/test/flix/Test.Exp.UncheckedTypeCast.flix
This pr reduces the use of `unsafe` and uses more precise and sound `unchecked_cast`
Should't `Environment.getEnv()` be impure? can't that change during computation?
> fix: unsafe `unsafe` blocks

- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
if lambda subeffecting is enabled, `x -> checked_ecast(x)` is typed as `x -> x`. The same for defs and instances
Even though this seems minor, I think its pretty important
> feat: ignore redundant `checked_ecast`

- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Very minor change in `visitSpawnExpr` in `Weeder2` that just replace a call to `flatMapN` with a call to `mapN`
> refactor: remove redundant call to `flatMapN`

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/src/ca/uwaterloo/flix/language/phase/PatMatch.scala
- main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Regions.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
Updates phases to consistently return a root and a possibly empty list of errors.
> refactor: always return root and errors from phases

- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/shared/TraitContext.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/unification/TraitEnv.scala
> refactor: move `TraitContext` from `Ast` to `shared`

- main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala
This PR extends the LSP visitor to recursive into types (instead of just consider top-most types).
Related to #9114
> feat: lsp visitor should recurse into types

- AUTHORS.md
- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/MagicMatchCompleter.scala
This pull request implements the magic completion for match first mentioned in #8679.
Here is the effect:
> feat: add magic completion for expr.match

- main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala
This PR fixes an issue where the LSP visitor would fall into endless recursion on `visitType` for assoc types.
Related to #9114
> fix: infinite recursion in visitType

- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Improve errors and avoid pickQName
```
>> Expected <QName>.
1 | def main(): Int32 = 32 instanceof java.lang.Object
^^^^^^^^^
Here
Hint: Use a single unqualified Java type like 'Object' instead of 'java.lang.object'.
```
```
>> Unexpected qualified name. Java names must be imported, e.g., `import java.lang.Object`.
1 | def main(): Int32 = 32 instanceof Java.Lang.Object
^^^^^^^^^^^^^^^^
illegal qualified name
```
> feat: improve `instanceof` parsing

- main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala
This PR removed an accidental double visit to signatures in the LSP visitor. This problem occured because everything in both `root.traits` and `root.sigs` was visited. But since every signature is in a trait, they would then also be visited again after visiting their `trait`. The issue has been fixed by simply removing the line that visits everything in `root.sigs`.
Related to #9114
> fix: removed double visit of sigs in lsp visitor

- main/src/ca/uwaterloo/flix/api/lsp/StackConsumer.scala
This PR makes it such that the StackConsumer also pushes labels onto the stack.
Related to #9114
> feat: add label to StackConsumer

- main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
Currently we can only parse cons lists up to 256 in some cases
```
1 :: 2 :: .. :: Nil; ???
```
The cons list can look infinitely, but going down the call stack drains fuel because of the last failing nth check (correctly special-cased currently) and `if (eat(TokenKind.KeywordWith)) {` line. This means that the statement rule dies when it looks for `;`. If the following rule advances without checking then the fuel is reset so it doesn't always show.
In this PR I just add 2 fuel to account for the stack wind down. The way up is now issue because it is using advance() before calling
> fix: Cons parsing edgecase

- main/src/ca/uwaterloo/flix/api/lsp/StackConsumer.scala
- main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala
This PR removes the visit to labels from the LSP visitor. The inclusion of this visitation was a mistake since labels don't carry any interesting information in and of themselves, but a name and their location. In this sense, they are much like symbols, which we also do not visit. Where labels are of interest, they can be extracted from their parent node. In most cases where a label is of interest, the parent node context is likely needed anyways.
Related to #9114 and undoes #9145 and #9149
> fix: removed label visit and consumer from visitor and consumer interface

- main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala
> fix: add `throw` to parser keywords

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/MagicMatchCompleter.scala
Fix the padding length error when the arity of the tuple is larger than 10.
Remove all the magic numbers used in the MagicMatchCompleter.
> fix: fix the alignment error for magic match completion

- main/test/flix/Test.Exp.TypeMatch.flix
Updated it to match its file name.
> test: rename module `Test.Exp.ReifyType` to `Test.Exp.TypeMatch`

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/MagicMatchCompleter.scala
Resolved all the issues mentioned in #9166.
Note:
- Now we won't return a magic match completion if the enum is empty.
- Now we use `Math.log10` to compute the length of an Int instead of by building a string.
> feat: improve magic match based on #9166

- main/src/ca/uwaterloo/flix/language/phase/Inliner.scala
I checked manually that the Optimizer AST no longer contains any `if (true)` or `if (false)`
Closes https://github.com/flix/flix/issues/8747
> feat: simplify `if (true)` and `if (false)` in Inliner

- examples/larger-examples/datalog/class-hierarchy-analysis.flix
Just fixing some typos: `mulitple` -> `multiple`
> test: fix spelling in `class-hierarchy-analysis`

- main/src/ca/uwaterloo/flix/language/phase/unification/TraitEnvironment.scala
- main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
- main/src/ca/uwaterloo/flix/util/Validation.scala
Related to https://github.com/flix/flix/issues/9196
> refactor: clean up `Validation`

- main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
According to #9125, mkNewStruct is added to automatically introduce a new struct if a undefined type is encountered.
A minor problem: we will not check if the undefined type is followed by a `[r]` even thouth it's necessary for a struct, since this info is not included in `UndefinedType`. But we will add `[r]` manually to the generated struct definition, otherwise the flix compiler will crash.
> feat: add mkNewStruct to CodeActionProvider

- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
This PR fixes issues regarding the `SourceLocation`s associated tag expressions.
The first issue is that the `SourceLocation` for the tuple subexpressions (for 2+ arity cases) of tag expressions overlap with the `SourceLocation` of the `CaseSymUse` of the tag expressions.
The second issue might be up for debate, but I think it's an issue. The issue is that the location for all the AST nodes introduced by `visitTag` like the unit constant and the AST nodes introduced to wrap tags in lambdas for expressions like `let x = Enum.Case` have the `SourceLocation` of the tag expression itself. What location these should have is unclear, but they should at the very least be synthetic. So here I keep them the same but simply make them synthetic.
The first issue is particularly a problem for the work …
> fix: source locations regarding tag expressions are wrong

- main/src/ca/uwaterloo/flix/api/lsp/Position.scala
- main/src/ca/uwaterloo/flix/api/lsp/Range.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
Improve the check in `onSameLine` as suggested on #9125.
Some problems:
- should we change the name since it's not just checking if the ranges are on the same line?
- another conversion function from `SourceLocation` to `Range` is written, which is the same as the one in `MagicMatchCompleter`
> feat: improve onSameLine to check overlap

- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
Tested this manually by hovering in VSCode. It works now (also for decimals which suffered from the same issue).
Closes https://github.com/flix/flix/issues/8798
> fix: produce correct source position for number literals

- main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
fixes #9233
Preview:
There is still one code action that is under the `isRoot` check, which is `mkFixMisspelling`, is this still necessary?
> feat: use AnchorPosition for some codeactions

- main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
> fix: ImportJava CodeAction now displays the right prompt

- main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
further update to #9267
Now if there is an undefined tag, we also propose to use it:
Some left problems:
- Shall we check by prefix, like also providing those for 'Re', 'Gree'
- Shall we propose to use all the cases in the same enum?
> feat: add CodeAction to use UndefinedTag

- main/src/ca/uwaterloo/flix/language/dbg/AstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/MonoAstPrinter.scala
Adds a printer for `MonoAst`. This is quite useful for debugging the inliner
> feat: add `MonoAstPrinter`

- .github/workflows/community-build.yaml
- main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala
Fixes #9264
This is essentially a non-functional refactoring. Some errors have become a little more precise and might not erase user alias in error messages and the order or errors have been made consistent but otherwise nothing has changed.
> refactor: clean up safety

- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
I'm not sure if this is a bug or not, but it seems that if a `HoleError` is impure, then it should also hold for `Throw`?
> fix: make `Throw` impure in `Simplifier`

- main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
Task 3 on #9248
I searched "env" in `ResolutionError` and replace them with `LocalScope`(for `UndefinedNameUnrecoverable` and `UndefinedName`).
Is there any other error that we should change ?
> feat: extend some ResolutionError with LocalScope

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmName.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
Idea: for nullary enum tags like `Option.None`, make a `Option$dotNone$` class with a single tag instance. This means that we only have one `Option.None` object and that pattern match checking for `Option.None` can be done with `instanceOf Option$dotNone$`
Fixes #9259
> feat: singleton nullary enum cases

- main/src/ca/uwaterloo/flix/runtime/shell/Shell.scala
- main/src/library/Prelude.flix
Fixes #8601
This PR correctly checks for algebraic effects, but also disallows any non-primitive effect. I think this is okay, because how would you even use regions in the repl?
@magnus-madsen Env is missing in Prelude - do you have a documentation comment in mind that I can insert?
> fix: Algebraic effects in REPL expressions

- main/src/ca/uwaterloo/flix/language/dbg/AstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/Doc.scala
- main/src/ca/uwaterloo/flix/language/dbg/DocAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/DocAstFormatter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/LiftedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/LoweredAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/MonoAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/ReducedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/ResolvedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/SimplifiedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/SyntaxTreePrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/TypedAstPrinter.scala
Now you can see the syntax tree (also fixed stack blowup for ast printer)
```scala
enum Opt[t] {
case None
case Some(t, Opt[t])
}
```
gives
```scala
/* ..\test.flix */ Root(
UseOrImportList(),
Enum(
Doc(),
AnnotationList(),
ModifierList(),
KeywordEnum["enum"],
Ident(NameUpperCase["Opt"]),
TypeParameterList(
BracketL["["],
Parameter(Ident(NameLowerCase["t"])),
BracketR["]"]
),
CurlyL["{"],
Case(Doc(), KeywordCase["case"], Ident(NameUpperCase["None"])),
Case(
Doc(),
KeywordCase["case"],
Ident(NameUpperCase["Some"]),
Type(
Tuple(
ParenL["("],
Type(Variable(NameLowerCase["t"])),
Comma[","],
Type(
Apply(
Type(QName(Ident(NameUpperCase["Opt"]))),
ArgumentList(
BracketL["["],
Argument(Type(Variable(NameLowerCase["t"]))),
BracketR["]"]
)
)
),
ParenR[")"]
)
)
),
CurlyR["}"]
)
)
```
> feat: add `Parser2` to `Xprint-phases`

- main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
fixes #9271 fixes #9272
Preview:
effect
struct
> feat: support effects and structs in mkUseType

- main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
fixes #9270
Preview:
Shall we keep the trailing ';'?
> feat: support mkUseStruct as a code action

- main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
fixes #9249
now we only filter through the public modifier.
Now the code is verbose and duplicated, since there is no base class for all the symbols where we can access the name and no base class for all the cases where we can access mod. So we have to write code for each type.
Should we use some mechanism to improve that?
> feat: mkUseX only propose when the name is visible

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/AutoUseCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/DefCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ExprCompleter.scala
first step for #9347.
Preview:
Currently we use `AutoUseCompletion` to provide the option, but we can actually make the completion option more informative if we design a specific completion for it.
> feat: Introduce AutoUseCompleter, now support def

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala
second step for #9365
Preview:
Shall we add an extra space between the function name and the parameters? Or anything others?
Another example:
sometimes a long parameter list will obscure the qualified name :( Maybe we should set an upper bound for the parameter list?
> feat: make AutoUseCompletion more readable

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/LocalScopeCompleter.scala
fixes #9374 
I am not familier with all the cases in `Resolution.Declaration`, now I just pick out something like is most likely to be wrong.
The list of all cases:
- Namespace
- Trait
- Instance
- Sig
- Def
- Enum
- Struct
- StructField
- RestrictableEnum
- TypeAlias
- AssocTypeSig
- AssocTypeDef
- Effect
- Op
- Case
- RestrictableCase
> feat: differentiate between expressions and types in LocalScopeCompleter

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
Now simplily move the signature into labelDetails
> feat: improve DefCompletion with labelDetails

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
simply move the signature to the labelDetails.
> feat: improve MethodCompletion with labelDetails

- main/src/ca/uwaterloo/flix/language/phase/typer/PrimitiveEffects.Methods.json
- main/src/library/Http.flix
The only left out method for now is [`CONNECT`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT).
Related to  #9035
> feat: implement different HTTP methods

- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/ast/shared/BoundBy.scala
- main/src/ca/uwaterloo/flix/language/ast/shared/SymUse.scala
- main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala
- main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
- main/src/ca/uwaterloo/flix/language/phase/EffectBinder.scala
- main/src/ca/uwaterloo/flix/language/phase/EntryPoints.scala
- main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
> refactor: move `BoundBy` from `Ast` to `shared`

- main/src/ca/uwaterloo/flix/language/phase/unification/set/SetFormula.scala
~2.3 % frontend throughput increase
(doing just `val` was 0.9 % faster)
> refactor: lazy val `isGround`

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/AutoImportCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala
fixes #9389
We introduce loose match for AutoUseCompletion and AutoImportCompletion.
A loose match for two string only requires their first three chars to be identical.
> feat: introduce fuzzyMatch for some completions

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/AutoUseCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
Another step for #9347
Preview:
A problem is that the former completer will still suggest to complete `A.FooBar` even when `FooBar` is in scope. We'll need to change `EffSymCompleter`, but that would be another PR.
By the way, should we keep `AutoUseEffCompletion` and `EffectCompletion` two different things? We can otherwise use `Option[AnchorPosition]` to indicate if we should auto use and merge them.
> feat: support AutoUse for effects

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
fixes #9437
Now we will not add a redundant semicolon in auto use.
The semicolon is required inside a function body. But the anchor position will not direct the insertion into a function body.
> feat: avoid redundant semicolon in auto use

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
I've found that the sortText of some completion is bare String.
I've changed that of EffectCompletion to `Lower`, same as DefCompletion.
Some completion remains:
- most use completion <img width="580" alt="image" src="https://github.com/user-attachments/assets/e1ea93bd-403c-4fcf-b68d-f61d26dc4c5c">
- hole completion, where priority is a string <img width="455" alt="image" src="https://github.com/user-attachments/assets/ff8df0d9-81d0-4ffb-bd15-396e54072e80">
Shall we change them to use Priority?
> fix: add missing priority for some completions

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/WithHandlerCompleter.scala
> fix: remove the redundant _unit in WithHandlerCompleter

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EffSymCompleter.scala
As suggested in #9434
Preview:
> fix: disable EffSymCompleter when the user is not typing a qualified name

- main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/FindReferencesProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/Ast.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala
- main/src/ca/uwaterloo/flix/language/ast/shared/AliasConstructor.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/test/ca/uwaterloo/flix/language/fmt/TestFormatType.scala
> refactor: move `AliasConstructor` from `Ast` to `shared`

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/KindCompleter.scala
fixes #8582
Preview: 
Note:
- I use the Highest Priority since this is the most useful completion for UndefinedKind.
- There is no CompletionItemKind for Kind so I just use TypeParameter. Or should we use something others?
> feat: introduce KindCompleter

- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
Fixes #9518
Now visits the optional syntactic types instead of the arbitrary expression type
> fix: semantic token of unchecked cast

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/shared/SyntacticContext.scala
fixes #9568
In this PR we cancel the difference between syntactic completion and semantic completion. In stead we provide completions directly for different errors.
It seems that some SyntacticContext is not used anywhere after we cancel syntactic completion, like `SyntacticContext.Expr.InvokeMethod`. Should we remove them? in this PR?
> refactor: provide completions directly for errors

- main/src/ca/uwaterloo/flix/language/ast/Token.scala
- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
`Lexer.retreat` didn't handle lines/columns properly and I couldn't comprehend how `State.end` was tracked.
Now i save the width of the previous line, making the end position computable on the spot when building tokens instead of keeping track of it dynamically. This width of the previous line needs to be recomputed if you retreat across multiple lines. In a follow up PR i think we should remove `retreat` and instead store checkpoints (line/col/offset/prevWidth) and just directly reset instead of going back one by one. So i judge this potential performance cost small and gone in the next PR.
These new positions agree with all locations of the existing lexer, except for some lines ending with an integer literal, in which the existing lexer gives a wrong location.
> fix: lexer positions

- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
retreat has a bug with positions so now there is a simpler checkpoint mechanism. This might be a bit slower but its used rarely. 2/3 places could also avoid using checkpoints with a new version of the isMatch function
This PR changes some source locations a la #9548, but it that PR is merged first, then this will have no location changes
> refactor: get rid of `Lexer.retreat`

- main/src/ca/uwaterloo/flix/language/ast/SourceLocation.scala
- main/src/ca/uwaterloo/flix/language/ast/SourcePosition.scala
- main/test/ca/uwaterloo/flix/language/LanguageSuite.scala
- main/test/ca/uwaterloo/flix/language/ast/AstSuite.scala
- main/test/ca/uwaterloo/flix/language/ast/SourceLocationSuite.scala
- main/test/ca/uwaterloo/flix/language/ast/SourcePositionSuite.scala
This adds a `contains` function to `SourceLocation`s as well as a partial ordering on `SourcePosition`s used by the aforementioned.
This is related to #4276 and will be used by the `HighlightProvider`.
> feat: contains function for SourceLocation

- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/test/flix/Test.Exp.Match.BigInt.flix
fixes https://github.com/flix/flix/issues/9537
We may consider the same for BigDecimal, but that requires more thinking since the definition of equality for them is perhaps unintuitive.
> fix: allow matching on BigInt

- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
- main/src/ca/uwaterloo/flix/util/collection/ArrayOps.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
fixes https://github.com/flix/flix/issues/9583
> fix: don't crash on incomplete unary pattern in Weeder

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/syntactic/KeywordCompleter.scala
> feat: add 'use' to Module keywords

- AUTHORS.md
- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Process.flix
- main/src/library/ProcessHandle.flix
- main/src/library/ProcessWithResult.flix
Related to #9414 .
The process effect has been changed to a more general one. The module's help functions allow you to call exec with fewer arguments. 
Now, the process returns a `ProcessHelper` -- an interface to manipulate with created processes.
> feat: extend `Process` effect (#9414)

- main/src/ca/uwaterloo/flix/Main.scala
We now have just `lsp` and `lsp-vscode` -- as planned.
> chore: rework `lsp` command

- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
Now `Simplifier` does not produce trivial `if`-expressions from guards in pattern matching.
> feat: remove trivial `IfThenElse` in `Simplifier`

- README.md
Currently it looks really bad on mobile...
<table>
<tr>
<th width="50%">Before</th>
<th width="50%">After</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/64aa68f6-cd2e-4e81-9765-ba643ab4a398"></td>
<td><img src="https://github.com/user-attachments/assets/60bb7532-fa08-4dee-b9d6-3a837fc261e1"></td>
</tr>
<tr>
<td>Code is barely readable.</td>
<td>A bit small but still a remarkable improvement. User can tap it for full-size or zoom in with gestures quite easily.</td>
</tr>
</table>
It may be worth considering #3821, but I'm hesitant about that until GitHub supports Flix syntax highlighting.
> fix: remove fixed height from README img

- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/phase/Regions.scala
- main/src/library/Random.flix
- Stop `Random.handleX` from being stateful before the last argument
- Remove unnecessary effects from seeded handler
- Fix region checking for effect with minus, xor, and concrete effects
> fix: correct `Random.handleWithSeed` type and fix region check

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/AutoUseCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/DefCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ExprCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/LocalScopeCompleter.scala
According to #9355, we are now merge different parts of DefCompleter from LocalScopeCompleter, ExprCompleter and AutoUseCompleter into a single DefCompleter.
Preview:
But some problems remain:
- There used to be another guard named `canApplySnippet` that will check if we should use a snippet in situations with `|>` or similar things. But that needs the `previousWord` information from `CompletionContext`. To preserve that guard, we should add this to the error or find the `previousWord` anyway in the completer.
- Some ParseError will carry a `SyntacticContext.Expr.OtherExpr` that will now trigger `ExprCompleter`. If we remove `DefCompleter` and other completers gradually from `ExprCompleter`, how should we handle these `ParseError`? This applies to many other completers too. Something used …
> refactor: merge DefCompleter

- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
Introduce SharedContext for safety and stop returning list of errors.
First two steps for #9554
> feat: introduce `SharedContext` for `Safety` phase

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
fixes #9554
I've made part of this phase incremental. But two problems reamin:
- I don't know how to trigger the test that will output the chart
- Safety will iterate over the internal defs in instances and internal sigs for traits, which makes it hard to reconstruct based on the return value. I can rewrite it to check just stale parts(instances or traits), but I'm not sure if it's easy to employ a finer granularity or reconstruct new instances and traits.
> feat: incremental `Safety`

- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/ResolvedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
> refactor: make symbol naming consistent (`Resolver`)

- main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ImportCompleter.scala
- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
UndefinedJvmImport will be triggered in importing expression:
UndefinedJvmClass will be triggered in instanceof:
UndefinedNew will be triggered in new expression:
The first error will be handled by ImportCompleter. It works fine.
The second error need a completion for all local java classes. To be Done.
The third error need a completion for either local java classes or structs. We can provide a snippet for the struct part.
Later we can introduce a completer for the local java class. Then a new completer for the struct snippet/or adapt the current StructCompleter for this case.
Note:
- the UndefinedNew is very unstable, it stops working when confronting
- qualified name <img width="1043" alt="image" src="https://github.com/user-attachments/assets/3eb135b4-4625-4f68-a179-142e58168337" />
- …
> feat: introduce UndefinedJvmImport and UndefinedNew

- main/src/ca/uwaterloo/flix/language/ast/ChangeSet.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/test/ca/uwaterloo/flix/language/ast/AstSuite.scala
- main/test/ca/uwaterloo/flix/language/ast/TestChangeSet.scala
Introduce partitionOnValues to handle cases like root.Instances.
We will determine if an instance is stale or fresh by looking at the value of the map, instead of the key. I replicate the logic used in `partition` to implement this function.
I think the second filter in 
```
val fresh = oldMap.filter(kv => !dirty.contains(kv._1.src.input)).filter(kv => newMap.contains(kv._1))
```
is redundant, if it's old and not dirty, it should still be in the newMap. Is there any special case for that?
I implement partitionOnValues in another way to make it more efficient. You can help check its correctness.
If the assertion above, "an item is old and not dirty will also be in the new map", is correct, I think this way works.
The incremental ratio is still 0.5
Note:
- `mergeMappedList` could be placed …
> feat: introduce partitionOnValues

- main/src/library/Fixpoint/Solver.flix
This is an example of a limitation that results from the correctness of the new solver. We cannot infer the type of `compiler` because the constraints that would infer it cross region boundaries.
> fix: add annotation to runWithStratification

- .github/workflows/community-build.yaml
> ci: remove flix-files from community build

- main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
This test is no longer well-typed since we cannot infer the region type.
> test: remove broken test

- main/src/ca/uwaterloo/flix/Main.scala
- main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala
Change the architect a little bit.
`didOpen` will try to add the opened file to the flix instance if it's a flix source file.
> feat: load main for the standalone lsp when initializing

- main/src/ca/uwaterloo/flix/api/lsp/Diagnostic.scala
- main/src/ca/uwaterloo/flix/api/lsp/DiagnosticSeverity.scala
- main/src/ca/uwaterloo/flix/api/lsp/DiagnosticTag.scala
- main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala
- main/src/ca/uwaterloo/flix/api/lsp/Position.scala
- main/src/ca/uwaterloo/flix/api/lsp/PublishDiagnosticsParams.scala
- main/src/ca/uwaterloo/flix/api/lsp/Range.scala
Now the standlone lsp will compile flix on open and on change. And diagnostics are properly returned. I also handle the crash situation but I have no immediate example to make it crash.
> feat: compile flix for stand alone lsp

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EffectCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ExprCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/LocalScopeCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/OpCompleter.scala
- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
OpCompleter will work for two cases:
- UndefinedName:
- UndefinedOp
Due to the syntax of effect handling, we will never auto use UndefinedOp, neither will we provide completions for qualified name.
Note:
- I add EffectCompleter to UndefinedName so that we can first complete `DivByZero` then its op.
- The completer will not work in this case:
And the reason is that the completer that should work here is OpCompleter, which should find this is a qualified name and check if there is a qualified op that matches. But it will only check for `A.DivByZero.divByZero` which doesn't match with `DivByZero.divBy`. The problem is that every time we meet a dot, we are not looking into that thing. But calling different completers to check if they have matched qualified name. Here `DivByZero` is in scope, …
> refactor: introduce OpCompleter

- build.gradle
intelliJ warned my about coursier `2.1.14` so just bumping to latest release
> chore: update vulnerable dependency

- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/EntryPoints.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
The `Option` wrapper was redundant since it only every constructed `Some`
> refactor: remove `Option` from `TypedAst.entryPoints`

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ExprCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/LocalScopeCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/SignatureCompleter.scala
Preview:
Note:
- Since there is no traitCompleter(#9675 is blocked), we do not provide completions for `A.Tr`.
- `Trait.si` still doesn't work, the same as what we mentioned in OpCompleter. I think we need to figure out a way to process that case together efficiently.
> refactor: introduce sig completer

- main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EnumCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EnumTagCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ExprCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/LocalScopeCompleter.scala
- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
Preview:
Also works for UndefinedTag
The previous EnumTagCompleter is also used for `SyntacticContext.Pat`, I write a case to repeat this context, and we can see that `UndefinedTag` is also raised here, so it's safe to remove EnumTagCompleter from this `SyntacticContext.Pat` in this case. But I am not sure if there is another case of `SyntacticContext.Pat`.
Note:
- I add EnumCompleter to UndefinedTag so that we can first complete "A.Clr" then "A.Clr.Green"
- Unlike other completers, we don't check if the tag is public since that syntax is not valid. But maybe we should check if the enum is public? The same issue may also apply to other internal constructs like sigs or ops.
> refactor: introduce tag completer

- main/src/ca/uwaterloo/flix/language/ast/ChangeSet.scala
fixes #9693
Add two apis to first partition, then process the stale part and finally merge it.
If we want to improve the efficiency of merging for ListMap, we should update ListMap.++
An example usage for safety would look like:
```scala
val defs = changeSet.updateStaleValues(root.defs, oldRoot.defs, ParOps.parMapValues2[Symbol.DefnSym, Def, Def](visitDef))
val traits = changeSet.updateStaleValues(root.traits, oldRoot.traits, ParOps.parMapValues2[Symbol.TraitSym, Trait, Trait](visitTrait))
val instances = changeSet.updateStaleValueLists(root.instances, oldRoot.instances, ParOps.parMapValueList2[Symbol.TraitSym, TypedAst.Instance, TypedAst.Instance](visitInstance))
(root.copy(defs = defs, traits = traits, instances = instances), sctx.errors.asScala.toList)
```
I've done several things to …
> feat: add partition and merge api to ChangeSet

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ExprCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/LocalScopeCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ModuleCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/TypeCompleter.scala
Preview:
Note:
- we do not check visibility for modules, since they can not be annotated.
- I remove SyntacticContext.Pat and add ModuleCompleter to UndefinedTag to work for this case:
> refactor: introduce module completer

- main/src/ca/uwaterloo/flix/language/ast/ChangeSet.scala
My bad. I forgot to push this change to the previous PR.
Now the signature is updated.
> refactor: change the signature of updateStaleValues

- main/src/ca/uwaterloo/flix/language/ast/ChangeSet.scala
- main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
Use the new changeSet api for existing incremental compilations.
The perf result:
The incremental compilation for `Weeder2` `Parser2` and `Lexer` is left untouched since they do not fit very well.
> refactor: use new changeset api for existing incremental compilation

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/phase/Regions.scala
fixes #9658
perf figure:
I just use cachedTyperAst as the oldRoot, as it's used both before and after Regions. What is the rule to choose the oldRoot?
> feat: make Regions incremental

- main/src/ca/uwaterloo/flix/language/ast/Scheme.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolverInterface.scala
This moves some common functionality from ConstraintSolver to ConstraintSolverInterface. The intention is to make it easier to swap ConstraintSolver -> ConstraintSolver2 under the hood.
> refactor: introduce ConstraintSolverInterface

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/language/phase/PatMatch.scala
fixes #9656
perf figure:
I remembered that Matt said root.sig is redundant, so I only visit all the traits, same as what we did in safety.
> feat: make PatMatch incremental

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
Does it make any sense to provide ExprSnippetCompletion there?
> fix: remove ExprSnippetCompleter from UndefinedAnnotation

- AUTHORS.md
- main/src/library/Regex.flix
- main/src/library/String.flix
- main/test/ca/uwaterloo/flix/library/TestRegex.flix
Hey,
First of all, sorry for the bigger change.
Nevertheless, this should address all the points from the issue #9471.
> 1. The first one would be such with only two parameters, one a regex and a string.
> 2. The second one would be such that have more than two parameters, however have different types.
> 3. The third one would be functions that still have to use named parameters, however not all of them need to be named parameters.
Additionally, I've changed one minor thing in the `Regex.flix` even though it was not directly discussed in the issue itself. This would be the renaming of the `split` parameter from `regex` to `rgx` as all the other functions used `rgx` and not `regex`. In the case this should not be wanted, I'll remove the change immediately.
Feel free to ping me at anytime …
> refactor: remove unnecessary named parameters in Regex

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala
- main/src/ca/uwaterloo/flix/language/ast/Name.scala
- main/src/ca/uwaterloo/flix/language/ast/SyntaxTree.scala
- main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Add a new field `trailingDot` to QName to indicate if there is a trailing dot.
Note:
- I add a new TreeKind named TrailingDot and tryPick that to check
- I add `trailingDot` as the last field so that we can set a default value for it
I'll start using this field in the following PR. But some preliminary tests show that it works fine.
I am not sure if it's possible to process this in another way. When detecting the existence of a trailing dot. we just use all the idents as the namespace and use an empty string as ident.
The benefit is:
- Currently `use AMod.BMod.` will not trigger a resolution error since the QName is AMod as namespace and BMod as ident, which is a valid use. We have to manually check if there is a trailing dot when resolving. However, if we have [AMod, BMod] as namespace …
> feat: identify trailing dot in QName

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EnumTagCompleter.scala
The first PR try to support partially qualified name(`Clr.Green` below, if we call it this way)
Preview:
The general procedure would be:
- find if the namespace(`Clr`) is resolved in the local scope
- If yes, find the fully qualified name(`AMod.BMod.Clr`) of the namespace 
- Then use the fully qualified name to find the parent construct from root
- provide partially qualified completions
Actually we can find the construct in the LocalScope directly. But the construct stored there is from former phases(like NamedAst, ResolvedAst), so we will use the map to get the newest version and use it to provide completions.
The parent construct here is Enum, other possible construct could be Sig, Effect and Module.
> feat: support partially qualified name for EnumTagCompleter

- main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala
- main/src/ca/uwaterloo/flix/api/lsp/VSCodeLspServer.scala
Preview:
Note that variables are also highlighted, but their color scheme here is blank:
> feat: support semantic tokens for standalone lsp

- main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
fixes #9685
Now the parser will not accept qualified name in try catch:
But the error message is helpless, how could we improve this?
> fix: disallow qualified name in try-catch

- main/src/ca/uwaterloo/flix/api/lsp/VSCodeLspServer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/ShowAstProvider.scala
The mechanism to open the desired ast file is kind of broken(Not due to the change in this PR).
But the ast is correctly printed.
Will fix the problem in the following PR.
> refactor: make show ast provider return path

- main/src/ca/uwaterloo/flix/util/CofiniteSet.scala
Here's another attempt at generifying CofiniteSet.
The problem before was that `empty` and `universe` were inefficient because we couldn't reuse _the_ empty set and _the_ universal set -- we had to construct a new one each `empty`/`universe` was called.
The normal Scala solution for that is to make a default `empty` case and make that `X[Nothing]`, where the type parameter is covariant. But SortedSet doesn't allow covariance.
In this PR: I introduce an implicit parameter to `empty` and `universe`, called `Cached`. The `empty` and `universe` function then reuse the single object provided by the `Cached` implementation.
> feat: add generic CofiniteSet

- main/test/ca/uwaterloo/flix/TestUtils.scala
This change allows a test writer to specify where an error is expected.
For example, I can do this:
```
test("TestLeq02") {
val input =
"""
|def foo(): List[a] = 21 :: Nil // ERROR
|
|enum List[t] {
|    case Nil,
|    case Cons(t, List[t])
|}
""".stripMargin
val result = compile(input, Options.TestWithLibNix)
expectError[TypeError](result)
}
```
Which will ensure the error is on the second line, and fail the test if it is not.
> test: allow specifying error locations in tests

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala
- main/src/ca/uwaterloo/flix/language/ast/Name.scala
- main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Move the last ident to namespace when constructing the QName
Prev:
`A.B.` will be QName(["A"], "B", trailingDot = true)
Now:
`A.B.` will be QName(["A", "B"], "")
And the completer works fine after the change:
Note:
- I find the code duplicate in visitQNameExpr and visitQName, and call the latter form the former.
- Next step would be remove `getNamespaceAndIdentFromQName` from all call site. And just pass the qname for completers to use. That will change a lot of code so I left it for the following PR.
> feat: move ident to namespace for QName when there is a trailing dot

- main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala
- main/src/ca/uwaterloo/flix/api/lsp/SemanticTokenModifier.scala
- main/src/ca/uwaterloo/flix/api/lsp/SemanticTokenType.scala
for your reference:
We use to order them alphabetically. Now I just list them the way spec lists them.
> feat: use the full SemanticToken legend

- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
Now in nvim, constants are colored:
We should also remove the syntax highlight for vscode and adjust the SemanticTokenTypes used by the client.
Note:
- maybe we can just use the full list of SemanticTokenTypes and Modifiers so that we dont need to change it every time we add something new:
- I assign Char and Str the String type
- I assign Regex the Regexp type
- I assign number to Int* Float* BigInt BigDecimal
- The rest falls back to Type
> feat: provide semantic tokens to constants

- main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala
will jump to the implementation
> feat: add support for `ImplementationProvider` for standalone lsp

- main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala
The capability is the same as the vscode client:
It's ok to return an empty workspaceEdit when there is no edit:
> feat: support rename for standalone lsp

- main/src/ca/uwaterloo/flix/api/lsp/WorkspaceSymbol.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SymbolProvider.scala
I think the go to symbol in workspace relies on the `processWorkspaceSymbols`? Or is there other way to test that it works fine?
> refactor: make processWorkspaceSymbols return WorkspaceSymbols

- main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala
- main/src/ca/uwaterloo/flix/api/lsp/WorkspaceSymbol.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SymbolProvider.scala
now the content is the same as document symbols
Note that I filtered out all the symbols whose uri doesn't starts with "file://", which usually refers to flix standard lib files. nvim will panic over such uris. And these usis do not actaully work on vscode:
> feat: support workspace symbol for stand alone lsp

- main/src/ca/uwaterloo/flix/api/lsp/CodeLens.scala
- main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala
Preview:
Note:
- for nvim, we need to first call `vim.lsp.codelens.refresh()` to get the codelens and then use the shortcut `<leader>cl`(which will call `vim.lsp.codelens.run()` to run the codelens. Usually, it's recommended to add this config to refresh automatically:
```lua
vim.api.nvim_create_autocmd({ "BufEnter", "CursorHold", "InsertLeave" }, {
pattern = "<buffer>",
callback = function()
vim.lsp.codelens.refresh({ bufnr = bufnr })
end,
})
```
Should we add this to the minimal config? It makes no sense to just gives a shortcut that doesn't work on its own.
- The commands in the received code lens still need to be implemented. In VSCode, these commands are implemented on the client side, which is not available for nvim. Currently I just add some mock method to handle that on the server …
> feat: support code lens for stand alone lsp

- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
Note:
- Modifier stored in the AST has no loc, so we can not use it to provide semantic tokens. I use the tokens instead.
- Some Modifier is also a keyword(like pub). I didn't find from the lsp spec what will happen in this case. But in nvim, the first token will shadow the following ones. So I put modifierTokens before keywordTokens.
> feat: provide semantic tokens for modifiers

- main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/TypedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/Dependencies.scala
- main/src/ca/uwaterloo/flix/language/phase/EffectVerifier.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/PatMatch.scala
- main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala
- main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction2.scala
- main/src/ca/uwaterloo/flix/tools/Summary.scala
fixes #9931
Fix the problem in Ascribe, now we can highlight most of the cases for types:
> feat: provide semantic tokens for types

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/DefCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EffectCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EnumCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EnumTagCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ModuleCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/OpCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/SignatureCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/StructCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/TypeAliasCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/UseCompleter.scala
- main/src/ca/uwaterloo/flix/language/ast/Name.scala
- main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala
Now we can pass qn where we need it instead of namespace + ident.
Not every completer is tested, but they should all work fine since the change is trivial:
> feat: use qname directly in completers

- main/src/ca/uwaterloo/flix/api/lsp/provider/GotoProvider.scala
As discussed in #9935
We now filter out standard lib files in the GotoProvider.
I am not not sure if we should do this filtering. Currently if you try to command+click to go to something in the lib, it will say:
After filtering, it just keeps silent. (But of course, we can say something, in the plain lsp, we can send something back, in vscode, we can print to the console)
> fix: filter out lib files in GotoProvider

- main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/UseCompleter.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
As discussed in #9775
We first introduce available on constructs, so that we can always all it to get the bool instead of writing a function for each.
Next step will be introducing some thing like IsQName(?) to Symbols with namespace and name, so that we can reuse a `match(sym: IsQName, qn: Name.QName, qualified: Boolean`  to handle all matches.
After that we can get rids of all the matchesEnum matchesStruct things.
> feat: introduce Decl for TypedAst constructs

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
fixes #9953
The error message:
> fix: require operation decl to be annotated with return type

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/SignatureCompleter.scala
- main/src/ca/uwaterloo/flix/language/ast/shared/LocalScope.scala
Preview:
Note:
- The algorithm:
- get the first item of the namespace (we've checked its non-empty beforehand)
- search for it in the local scope, we only accept Namespace(BMod above) or Trait(Addable above)
- if found, concatenate its fully qualified form with the rest of the namespace
- now use the concatenated name to search for trait
- provide sig completions from the trait
- the resolution conflict problem:
- If the user uses two different BMod, then there will be two resolution for BMod in the local scope. In this case BMod is ambiguous and we should not provide the completion starts with BMod. But we cannot just check for duplication. For example, in the case above, `Addable` is also resolved to two traits, but it's totally fine. Currently, I am just use headOpt to get one …
> feat: support partially qualified name for SigCompleter

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EnumCompleter.scala
First mentioned in #9652
Now we will consider type parameters (when triggered from undefined type)
> feat: take account type parameters in enum completion

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ModuleCompleter.scala
fixes #9957
Now it can see the existence of the Trait in LocalScope, thus will not longer auto-use it again.
> fix: module completer will not suggest duplicated auto-use

- main/src/ca/uwaterloo/flix/language/ast/ChangeSet.scala
- main/src/ca/uwaterloo/flix/language/phase/Dependencies.scala
- main/src/ca/uwaterloo/flix/language/phase/Instances.scala
- main/src/ca/uwaterloo/flix/language/phase/PatMatch.scala
- main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/test/ca/uwaterloo/flix/language/ast/TestChangeSet.scala
solves  #9966 
Now we use instance.tpe.typeConstructor to compare two instances.
> fix: avoid using `contains` in partitionOnValues

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EnumCompleter.scala
Only UndefinedType will bring the type parameter.
> fix: EnumCompleter should not complete with typeparameters in expr

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EnumTagCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/SignatureCompleter.scala
Use the same algorithm used in SignatureCompleter. Now we support the namspace head to be either module or enum:
Although the algorithm is the same, the pattern matching and field accessing makes it hard to reuse to code:
> fix: EnumTagCompleter now supports all partially-qualified name

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
> feat: add signature detail to Op Completion

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
- main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
Currently, we can only see a parse error with withHandler context, and WithHandlerCompleter, which is an evil ctx-dependent completer, will provide completions.
So I first change the parser to recover from a handler with only the name(maybe incomplete name).
Then the resolver will find out that it's a undefined effect.
And if the name is resolved, there is still an error indicating the missing handler:
So the next step:
- add env to UndefinedEff (#9997)
- call EffectCompleter over UndefinedEfffect(yes, currently it's not called) and provide completion with the op snippet. Then we can remove WithHandlerCompleter.
> feat: emit undefined effect in handler

- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/ast/shared/ModuleKind.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
As discussed in #9994
We introduce ModuleKind to tell which modules are companion ones.
We will only use it in the completer and the completer will only access the module syms built in Typer.
So the module kind for syms built elsewhere does not matter. I just assume they are all stand alone ones.
It could be complicated to determine the real kind of modules in those places. Or we can introduce a new case Unknown if you prefer
> feat: introduce module kind

- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
refer to #8759 for the context
Now the master branch will only emit a parse error:
And the reason is that pickRawArguments will fails if there is nothing.
We have to recover from that case and build a invokeConstructor with an empty list of args.
Then it works
> fix: let compiler emit undefined new

- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
I think the code is more readable now with the stringcursor methods
```scala
private def acceptName(isUpper: Boolean)(implicit s: State): TokenKind = {
s.sc.advanceWhile(c => c.isLetter || c.isDigit || c == '_' || c == '!' || c == '$')
if (s.sc.advanceIfMatch('?')) {
TokenKind.HoleVariable
} else {
if (isUpper) {
TokenKind.NameUpperCase
} else {
TokenKind.NameLowerCase
}
}
}
```
> refactor: simplify `Lexer.acceptName`

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/shared/SyntacticContext.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
fixes #10015
Only SyntacticContext used in `CompletionProvider` is reserved:
```scala
case err: ParseError => err.sctx match {
// Expressions.
case SyntacticContext.Expr.Constraint => PredicateCompleter.getCompletions(uri) ++ KeywordCompleter.getConstraintKeywords
case SyntacticContext.Expr.OtherExpr => ExprCompleter.getCompletions(ctx)
// Declarations.
case SyntacticContext.Decl.Enum => KeywordCompleter.getEnumKeywords
case SyntacticContext.Decl.Effect => KeywordCompleter.getEffectKeywords
case SyntacticContext.Decl.Module => KeywordCompleter.getModKeywords ++ ExprSnippetCompleter.getCompletions()
case SyntacticContext.Decl.Struct => KeywordCompleter.getStructKeywords
case SyntacticContext.Decl.Trait => KeywordCompleter.getTraitKeywords
case SyntacticContext.Decl.Type => …
```
> chore: remove unused syntactic context

- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
This also allows slightly more laziness
> refactor: simplify `Lexer.isSeparatedX`

- main/src/ca/uwaterloo/flix/language/errors/ParseError.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
fixes #10015
Add default param to expect, expectAny, zeroOrMore, oneOrMore, nameUnqualified, nameAllowQualified, aliasedName
Now all the "free" Unknown in parser2 is eliminated.
> chore: use Unknown as the default SyntacticContext param

- main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala
Sometimes our code may make the compiler emit some errors for the lib files.
And the uri used there is invalid, which will produce tons of errors in nvim.
So we filter them out.
> fix: filter out lib files when publishing diagnostics

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
These completions are unused since the corresponding completer has been removed.
> chore: remove unused completion

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionContext.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/HoleCompletion.scala
Now completionContext only has one field: range.
Since we also remove previousWord, we can no longer tell if a def completion comes after |> etc. Relative code is removed too.
> chore: remove unused CompletionContext fields

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/HoleCompleter.scala
fixes #9998
Now we will trigger HoleCompleter if there are no errors.
But actually it still doesn't work:
> fix: make holeCompleter work when there are no errors

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/KindCompleter.scala
Now only change KindCompletion to avoid using CompletionContext.range, as a preview.
This way, we'll need to add range to every Completion, build it from loc(if available), and test if the range from loc is exactly what we want.
Also sometimes we'll meet problems like in KeywordCompletion loc is not available.
Do you think it's okay to impl this way?
> refactor: remove `CompletionContext` from `KindCompleter`

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/shared/SyntacticContext.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
fixes #10056
Now the three completions can be triggered in instance:
> feat: introduce SyntacticContext.Instance

- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
The first wrong loc we meet when trying to get rid of CompletionContext.
After this PR it becomes:
We want to use this range in Completion. So it should not include the import.
Actually the wrong loc of the jname is also fixed in this PR.
> fix: UndefinedJvmImport should not include import in the range

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/LocalScopeCompleter.scala
Now the completion has detail:
We could also further merge the completion for local java class and the AutoImport completion. Like what we do for AutoUseDef and Def.,
> feat: add detail to local scope java completion

- main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala
- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/ResolvedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/TypedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
- main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
- main/src/ca/uwaterloo/flix/tools/Summary.scala
third part for #10046
A little problem in the Desugar part. Some of the contextes use loc1.asSynthetic, while others do not. Is it okay if I just adhere to the context?
> feat: introduce SourceLocation for MatchRule

- main/src/ca/uwaterloo/flix/language/phase/typer/PrimitiveEffects.Packages.json
Functionality for working with the garbage collector. Does not seem dangerous per se, but `Sys` does cover "interacting with the jvm"
https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/ref/package-summary.html
> feat: annotate `java.lang.ref` with primitive effects

- main/src/ca/uwaterloo/flix/language/phase/typer/PrimitiveEffects.Packages.json
> fix: update `java.net` package name for primitive effect annotations

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/PredicateCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/syntactic/ExprSnippetCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/syntactic/KeywordCompleter.scala
- main/src/ca/uwaterloo/flix/language/errors/ParseError.scala
In the first commit, I just extract the loc from ParseError but not use it.
But that change is too small, so I also use the loc in the second commit. If you prefer, we can use another PR.
Note:
- I use implicit to pass the range in CompletionProvider, since it's convenient and we also do this for root, flix etc.
- It would also be convenient to make range implicit for KeywordCompletion etc. But we dont do that for any completion. So I pass them manually.
- I also check that the range must not be empty. In the following case, we have an empty range and since "" is the prefix of any string, we get all the completions:
> feat: use loc from parse error

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/AutoImportCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- change the signature to get the information it needs directly.
- accept range from the error
> refactor: unwrap AutoImportCompleter

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ImportCompleter.scala
change the signature to get the information it needs directly.
accept range from the error
> refactor: unwrap ImportCompleter

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/semantic/GetStaticFieldCompleter.scala
change the signature to get the information it needs directly.
accept range from the error
> refactor: unwrap GetStaticFieldCompleter

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/UseCompleter.scala
change the signature to get the information it needs directly.
accept range from the error
> refactor: unwrap UseCompleter

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/semantic/InvokeStaticMethodCompleter.scala
change the signature to get the information it needs directly.
accept range from the error
> refactor: unwrap InvokeStaticMethodCompleter

- main/src/ca/uwaterloo/flix/api/lsp/Range.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/syntactic/KeywordCompleter.scala
In the enum case, we have two errors, so the completion is now duplicated.
The first is from the failure of parsing a decl when meeting enu.
After that the parser leave the enu as is and the module will try to parse it again and emit another other.
> refactor: let KeywordCompleter use its own range

- main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
> fix: mark mkLambdaMatch components' locs with asSynthetic

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/OpCompleter.scala
Besides the normal refactor, also something specific to OpCompleter:
- If isHandler, we can get the fully qualified name of the effect, as a result, we can just lookup the map instead of iterate through it.
- Wee've seen similar code in a lot of places, where we define a sym and use it to lookup the table, should we add a helper function somewhere?
- Although unwrapped, I still keep two entry point for OpCompleter, since they are not completely doing the same thing. 
- Should we add another completer? if isHandler, the completion is a snippet defining the handler, if not isHandler, it's a function call.
> refactor: unwrap OpCompleter

- main/src/ca/uwaterloo/flix/language/ast/SourceLocation.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
fixes #10092
Also fixes a an issue around people calling their handler continuation `_unit`, e.g. `def op(_unit) = 42`
> fix: handler unit padding location

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala
Preview:
But there is a problem in displaying the type parameter:
Ideally they should be replace by a or String. But how could we achieve that?
> feat: EnumTagCompleter now supports snippet

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala
follows #10148
Now the displayed and pre-filled type is more user-friendly:
> fix: better type display in EnumTagCompletion

- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
according to #10085
I choose the replace env with scp.
In the arg, to avoid shadowing, I use scp0 consistently.
taenv is left as it is, since it's not of type LocalScope.
Many shadow problem is also solved since we are using the new warning config. To solve them, I rename names in arg with a trailing 0, names inside with a trailing 1, 2 etc.
Somewhere 1, 2 is used for the first and second exp. I use e1_, e2_ to avoid shadowing there.
Resolver is the first place where we use LocalScope a lot. Another place is in the completers, that would be another PR.
> refactor: rename env to scp in resolver

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/LocalScopeCompleter.scala
I also remove the support of localscope completion for structfield, assoctype, assoceff.
Relative discussion in #9773. But it's been hanging there for quite a while. 
I think it's safe to remove these either impossible or uncommon cases.
I preserve two entry points: Expr one and Type one
> refactor: unwrap LocalScopeCompleter

- main/test/flix/fuzzers/FuzzDeleteLines.scala
- main/test/flix/fuzzers/FuzzDuplicateLines.scala
- main/test/flix/fuzzers/FuzzPrefixes.scala
- main/test/flix/fuzzers/FuzzSwapLines.scala
This should allow https://github.com/flix/flix/pull/10117 to go through.
Depends on
- https://github.com/flix/flix/pull/10199
I've created a ticket to track the discovered resiliency issue: https://github.com/flix/flix/issues/10181
> test: remove fuzzing sources after each test

- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
- main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
- main/test/flix/Test.Exp.Interpolation.flix
```
flix> "${10+2}"
12                                                                              
flix> "\${10+2}"
${10+2}                                                                         
flix> "\\${10+2}"
\12                                                                             
flix> "\\\%{10+2}"
\%{10+2}                                                                        
flix> "\\\\%{10+2}"
\\12                                                                            
```
Fixes #10215
> fix: string interpolation after double backslash

- main/test/ca/uwaterloo/flix/language/ast/SourcePositionSuite.scala
only used 0 in cases where they will be unused, but 1 is more correct
> fix: 1-indexed pos in SourcePositionSuite

- main/src/library/Foldable.flix
- main/test/ca/uwaterloo/flix/library/TestFoldable.flix
closes #9490 
I added tests directly on Foldable.filter as there were none. Though I guess List.filter, etc are tested so perhaps not super useful?
> feat: allow effectful f in Foldable.filter

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/TypeAliasCompleter.scala
fixes #10194
We filter out non-star types in type alias completer, so that static is filtered out:
Is this a sound filtering? Are we filtering out some types that are actually needed in some UndefinedType errors?
> fix: filter out non-star type in TypeAliasCompleter

- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
fixes #10190
Preview:
Method:
I filter out tokens for binder whose type has a synthetic location.
Also, I stop providing semantic token for all types with a synthetic location. If Synthetic location is not abused, I think that is safe?
I also change the token type for the op name (displayByRepo above) to Function
Known issue:
resume is not colored, the reason is that its location is synthetic and is not precise:
> fix: fix broken semantic Token for handler

- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/test/ca/uwaterloo/flix/api/lsp/TestCompletionProvider.scala
name definition invariant in #10138
We collect names from the root and filter out those whose src does not start with "<test>", which means that they are not defined in the tested program, but in the library.
Then I add Sourceable and Locatable to all the Symbols used, so that I can concatenate them together, do the filtering, and map to loc.
Then we just call completion and test its emptiness.
Possible improvements:
- We can modify the name a little bit, the invariant should still hold. But I will wait to reuse the helper functions from other PR to modify the code.
- We can include more name definitions, like parameters, local variable defs, and other bindings.
> feat: new completion invariant: no completions on name definition

- main/src/ca/uwaterloo/flix/language/ast/Token.scala
- main/test/ca/uwaterloo/flix/api/lsp/TestCompletionProvider.scala
Comment invariant in #10138
Add some comment to the tested programs and test the invariant the same way we test the former ones.
There is one thing that we can do differently:
we can delete some characters in the original program, the invariant should still hold.
For example, we can randomly delete some characters in the comment, craft the new program and test the invariant again.
I think we can add that as another test?
> feat: new completion invariant: no completion inside comment

- main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala
Once `exp1` was a lambda and then it was not changed when `exp1` just became the function body
> fix: `TypeReconstruction` of `LocalDef`

- main/src/ca/uwaterloo/flix/language/verifier/EffectVerifier.scala
> fix: `EffectVerifier` of throw

- main/src/ca/uwaterloo/flix/language/verifier/EffectVerifier.scala
The verifier does not account for the intrinsic region effect, so I've put it as todo like the above region things
> fix: `EffectVerifier` of `StructNew`

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/DefCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ExprContext.scala
Now we can handle pipeline and () as the def context:
Note that if there is both pipeline and (), () will dominate since it's closer to the error.
As a result, the completion in this mixed context is just what we want:
So there is no need to consider the state machine(it's only needed if we want the exact arg count in mixed context)
> feat: handle pipeline in expr context

- main/src/ca/uwaterloo/flix/api/lsp/SignatureInformation.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SignatureHelpProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
Preview:
Also, when moving back, the active parameter will follow correctly.
Also works for snippet!
> feat: support Signature Help for signature

- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
> fix: pass RunWith down the compiler when there is only run

- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala
Fixes https://github.com/flix/flix/issues/10366
> fix: don't crash in Kinder for empty structs

- main/src/ca/uwaterloo/flix/api/lsp/LspUtil.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/DefCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ExprContext.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/SignatureCompleter.scala
Preview:
Each call to `getExprContext` will rebuild its own stack, related to #10344
`getExprContext` is placed in ExprContext.scala for reuse.
`mkSpecSnippet` is placed in LspUtil.scala for reuse.
> feat: use ExprContext in SigCompleter

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EnumTagCompleter.scala
We've already applied ExprContext to EnumTagCompleter. Similarly, we can use that for EnumTag.
Preview:
Now several problems arise during the impl:
- It is possible that the ectx for EnumTagCompleter is `InsideRunWith`, which is actually an invalid context to complete to a EnumTag. What we should do in this case is to stop returning completion for enum tag. But in `toCompletionItem`, we have no choice but have to return one CompletionItem. This problem implies that:
- Not only can we use this context to determine the content of a completion, but also whether we should offer a completion.
- We may need a method to suppress the completion in `toCompletionItem`
- EnumTagCompleter is also used for `UndefinedTag`, which mean the current ExprContext, which is detecting `UndefinedName` in the …
> feat: use ExprContext for EnumTagCompleter

- main/test/ca/uwaterloo/flix/api/lsp/TestCompletionProvider.scala
I think we just call autoComplete in every possible position?
> feat: add completion invariant that autoComplete is free of crashes

- main/src/ca/uwaterloo/flix/language/ast/MonoAst.scala
- main/src/ca/uwaterloo/flix/language/ast/OccurrenceAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/MonoAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala
- main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala
- main/src/ca/uwaterloo/flix/language/phase/optimizer/Inliner.scala
- main/src/ca/uwaterloo/flix/language/phase/optimizer/LambdaDrop.scala
- main/src/ca/uwaterloo/flix/language/phase/optimizer/OccurrenceAnalyzer.scala
- main/src/ca/uwaterloo/flix/language/phase/optimizer/Optimizer.scala
These two values are alwasy `None` and also unused.
> refactor: remove unused AST cast info

- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala
This doesn't belong here and makes internal Asts nonwelltyped
> refactor: remove null casting logic from `TypeReconstruction`

- main/test/ca/uwaterloo/flix/api/lsp/TestCompletionProvider.scala
Just a duplicate of the former impl for vars.
One thing for the naming: I don't know why,but what inside Expr.Var is not `VarSymUse`, but `VarSym`. `VarSymUse` doesn't even exist and we call it `varOccurs`. But for `Expr.ApplyDef`, we have `DefSymUse`, so we just call it `defSymUse`. Shall we unify the naming? to `xxxSymUse`?
The invariant is violated.
Not sure if we should place the analysis here, but for program
```
...
def test(): Unit \ {Sys, IO} = Environment.handle(() -> {
let rec = safeConnects("bis", exampleGraph());
println("Safe:");
rec#safe |> Vector.sort |> Vector.map(Chalk.green) |> Vector.forEach(println);
println("Unsafe:");
rec#unsafe1 |> Vector.sort |> Vector.map(Chalk.red) |> Vector.forEach(println)
})()
```
When we try to delete "|>" to "|".
First, "|>" is treated as a …
> feat: add no-duplication completion invariant for defs

- examples/larger-examples/datalog/single-source-shortest-path-arbitrary.flix
- examples/larger-examples/datalog/single-source-shortest-paths.flix
The previous order defined paths to be equal if they had the same length. This was changed to a real total order.
Should not affect performance.
> fix: correct Order instance for shortest-path examples

- main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala
- main/src/ca/uwaterloo/flix/api/lsp/VSCodeLspServer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/test/ca/uwaterloo/flix/api/lsp/TestCompletionProvider.scala
related to #10477
We just cancel `autoComplete` and distribute `toCompletionItem` to all call sites.
> feat: postpone calling toCompletionItem

- main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala
- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/SyntaxTree.scala
- main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala
- main/src/ca/uwaterloo/flix/language/ast/Type.scala
- main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/ResolvedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
- main/src/ca/uwaterloo/flix/language/phase/Namer.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
- main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
```
def main(): Unit =
let b = foo("bac");
xmatch b with Foo {
case x => x + 1
case y => 2
};
()
def foo(n: Int32): XVar[#(Foo(Int32))] = xvar Foo(n)
```
> feat: add support for `ExtensibleMatch` to frontend

- main/src/ca/uwaterloo/flix/language/phase/optimizer/Inliner.scala
This change makes it so that the inliner accounts for the fact that local defs are lifted at a later stage. Thus, it is okay to inline a function that simply defines a local def and immediately invokes it.
> feat: consider local def as direct call in `Inliner`

- main/src/ca/uwaterloo/flix/language/phase/optimizer/Inliner.scala
Now just returns a let-binding that the caller may visit
> refactor: simplify `bindArgs`

- main/src/ca/uwaterloo/flix/language/ast/MonoAst.scala
- main/src/ca/uwaterloo/flix/language/phase/optimizer/OccurrenceAnalyzer.scala
I left `LocalContext` because I think you will soon use it.
> chore: remove unused code in `MonoAst`

- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/KeywordCompleter.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Priority.scala
- Merge `KeywordCompletion` and `KeywordLiteralCompletion`
- Update documentation slightly
- Group annotations (will help for next PR)
- Rename `Medium` priorities (will be used in the next PR in `KeywordCompleter`)
> refactor: cleanup `KeywordCompleter`

- main/src/ca/uwaterloo/flix/util/Graph.scala
- main/test/ca/uwaterloo/flix/util/TestGraph.scala
The documentation says the opposite of the tests. This PR fixes that.
```scala
/**
* A topologically sorted result.
*
* Fewest incoming edges on the left.
* The node at the head of the list has no incoming edges.
*/
case class Sorted[N](sorted: List[N]) extends TopologicalSort[N]
```
However, the tests all have nonzero incoming edges on the left but zero outgoing:
```scala
test("topSort.Sorted.01") {
val graph = Map(
1 -> List(),
2 -> List(1)
)
val result = Graph.topologicalSort(graph.keys, graph.apply)
val expected = Graph.TopologicalSort.Sorted(List(1, 2))
assert(result == expected)
}
test("topSort.Sorted.02") {
val graph = Map(
1 -> List(),
2 -> List(1),
3 -> List(2)
)
val result = Graph.topologicalSort(graph.keys, graph.apply)
val expected = Graph.TopologicalSort.Sorted(List(1, 2, 3)) …
```
> docs: fix `Graph` documentation

- main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/completion/KeywordCompleter.scala
If the user has typed "le" we suggest "let" but not "match". 
The fix for expressions is easy, but the general fix in other cases is hard and will have to wait.
> fix: avoid spurious expression keyword suggestions

- main/src/ca/uwaterloo/flix/language/phase/optimizer/Inliner.scala
- main/src/ca/uwaterloo/flix/language/phase/optimizer/Optimizer.scala
This PR drops usage of the delta set in the inliner.
This makes it simpler to understand the inliner.
In theory this could increase work because inlining is repeated. 
In practice this seems not to be the case:
```
Master
~~~~ Flix Compiler Performance ~~~~
Throughput (best): 72.277 lines/sec (with 24 threads.)
min:  9.088, max: 72.277, avg: 60.475, median: 62.102
Finished 100 iterations on 69.994 lines of code in 123 seconds.
PR
~~~~ Flix Compiler Performance ~~~~
Throughput (best): 72.698 lines/sec (with 24 threads.)
min:  8.575, max: 72.698, avg: 67.482, median: 70.518
Finished 100 iterations on 69.994 lines of code in 111 seconds.
```
> feat: drop usage of delta set in `Inliner`

- main/src/ca/uwaterloo/flix/language/phase/VarOffsets.scala
The `setStackOffset` function computes *the next offset* not how much the offset should grow. Thus, in `visitDef` the mutable variable `offset` should just be reassigned, not added to
> fix: do not increment offset counter in `VarOffsets`

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendType.scala
if you have
```
let x = {q = 42}
```
then currently it is ... kind of typed like
```
let x: RecordExtend$Int = {q = 42}
```
but this PR fixes it such that it is
```
let x: Record = {q = 42}
```
This bug is currently not observable, but was revealed because im doing another fix
> fix: Backend types of records

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenAnonymousClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenFunAndClosureClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
This removes ad hoc erasure of a few things, but notably arrays. This PR should fix our long standing issue around array types in the backend.
As a bonus, this PR conceptually eliminates JvmType - but follow up PRs will actually weed it out
> fix: remove ad hoc erasure in the backend

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/ClassMaker.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
This PR splits code generations (public, final, implementation) from the method/constructor/etc references that are used for name lookup
This leads the way for
- `F` -> classFile API
- `BackendObjType` -> `ClassDesc`
> refactor: Split `F` from `BackendObjType`

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenEffectClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenNamespaceClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
This function is the same as `toBackendType` but with an assert that the type is an erased type. This was merely a stepping stone since `toBackendType` is newer.
This is a step towards the backend to be erasure oblivious
> refactor: remove `BackendType.asErasedBackendType`

- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
Removes the unneeded type errors mention in #10722 .
`TestTyper.scala`, however, contains test cases with the titles indicating that they are for `RegionVarEscapes`. However, they expect any type error and not the specific one. I ran some of them and they throw other errors such as `UnexpectedArg`. Should I rename/repurpose these tests or delete them entirely since there already test cases for these other type errors?
> refactor: remove unused type errors

- main/src/ca/uwaterloo/flix/language/phase/jvm/GenAnonymousClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenEffectClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/GenFunAndClosureClasses.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala
Now names reflect which types are actually erased
> refactor: update JvmOps names

- AUTHORS.md
- main/src/library/BigInt.flix
- main/src/library/Float32.flix
- main/src/library/Float64.flix
- main/test/ca/uwaterloo/flix/library/TestBigInt.flix
- main/test/ca/uwaterloo/flix/library/TestFloat32.flix
- main/test/ca/uwaterloo/flix/library/TestFloat64.flix
For the various `clampToX` functions in `BigInt`, `Float32`, and `Float64`:
* makes the function subject-last
* uses record arguments
* renames `minimum`/`maximum` to `min`/`max`
These changes are consistent with (and were already made in) `Int16`, `Int32`, and `Int64`.
(fixes #6123)
@mlutze
> refactor: make clampToX functions subject-last

- main/src/library/Fixpoint3/BoxingType.flix
> refactor: rename types in `BoxingType` to avoid use of reserved names

- main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/ClassMaker.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
- main/src/ca/uwaterloo/flix/language/phase/jvm/JvmName.scala
@magnus-madsen I don't know if you agree with that approach
this `FlixError` object basically corresponds to the old `GenFlixError` class. These objects have no reason to be a part of BOT so i will extract them to be their own ClassMaker thing, makes both simpler in the process. 
This means that most of `BOT` gets extracted into `ClassMaker` which is maybe fine but i could also add `ClassConstants` to cut in in two, or have `FlixError` be its own file.
> refactor: remove BOT FlixError

- main/src/library/BPlusTree.flix
- main/test/ca/uwaterloo/flix/library/TestBPlusTree.flix
`putWith` could be treated like `put` under concurrent execution.
> fix: bug in putWith

- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
Avoids unnecessary calls into unification
Fixes #10878
> feat: lazy `Stratifier.labelEq` checking

- main/src/library/BPlusTree.flix
- main/test/ca/uwaterloo/flix/library/TestBPlusTree.flix
We have added a parallel foreach method to the BPlusTree. It is meant for internal usage by the Datalog engine, though e.g. merge could also use it.
> feat: add parallel foreach to BPlusTree

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/Fixpoint/Ast/Datalog.flix
- main/src/library/Fixpoint/Solver.flix
- main/src/library/Fixpoint3/Phase/RenamePredSyms.flix
This phase simply transforms PredSym as Flix understands them into PredSyms with unique integer parts as our solver uses this.
To keep ensure the old Datalog engine and ours can work on `Datalog.flix` at the same time we have modified the old engine's `Solver.flix`.
> feat: transformer from Flix PredSym to Fixpoint PredSym

- main/src/library/Reader.flix
fixes a small mistake i overlooked in https://github.com/flix/flix/issues/6402
> fix: InputStream Reader implementation returns 0 instead of -1

- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
Pure refactor. Removes unused parameters and makes use of some existing helpers to make everything more DRY.
> chore: clean up Typer.scala

- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/library/IpAddr.flix
- main/src/library/Ipv4Addr.flix
- main/src/library/Ipv6Addr.flix
Addresses #10855.
First push separates `IpAddr` into two enums for v6 and v4. Next step is adding functionality.
> feat: add functionality to and refactor `IpAddr`

- main/src/ca/uwaterloo/flix/language/phase/typer/PrimitiveEffects.scala
- main/src/library/Time/Instant.flix
Before, it returned `Map(null -> effset)`, just choosing the last occuring effect set in the `json` file.
> fix: correctly load primitive package effects

- main/src/library/Ipv4Addr.flix
partially addresses #10961. using `bitwiseAnd` to get u8 -> i8. I don't think it will work for the parse function because going the otherway requires really complicated bit operations.
> refactor: Ipv4Addr to use `bitwiseAnd`

- main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
This property is already checked more robustly in the Typer.
> feat: remove redundant SafetyError.IllegalSpawnEffect

- main/src/ca/uwaterloo/flix/language/fmt/DisplayType.scala
- main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala
- main/src/ca/uwaterloo/flix/language/fmt/TypeView.scala
- main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala
I decided against `FormattedType` because it's confusing with our typical terminology, where `formatX` means turn it into a string. Plus then we would need a `formatFormattedType` function which seemed silly to me.
related to #11005
> chore: rename SimpleType to DisplayType

- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/library/Fixpoint/Solver.flix
- main/src/library/Fixpoint3/Ast/Datalog.flix
- main/src/library/Fixpoint3/Solver.flix
This allows `Lowering` to handle the `solveMode` in the pattern-match in `visitExp` for when https://github.com/flix/flix/pull/11035 is merged.
See https://github.com/flix/flix/issues/11022.
> feat: add unimplemented `runSolverWithProvenance` to Datalog solver and match `SolveMode` in `Lowering`

- main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolverInterface.scala
- main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
Adds undefined label and extra label errors as discussed in #10722. 
A couple of comments:
i) Currently, it produces the same old error in the case of open records. 
ii) It seems difficult to fit the code into the design of the `toTypeErrors` function creating a list from a `TypeError` since there can now be multiple error messages generated from the same constraint. So `mkErrorsFromRecords` returns the list.
> refactor: improve type errors for record types

- main/src/library/MutDisjointSets.flix
- main/test/ca/uwaterloo/flix/library/TestMutDisjointSets.flix
The following function would loop forever.
```
def func(): Bool = region rc {
let s = MutDisjointSets.empty(rc);
MutDisjointSets.makeSet(0, s);
MutDisjointSets.union(1, 0, s);
Assert.eq(true, MutDisjointSets.equivalent(1, 0, s))
}
```
> fix: bug in MutDisjointSet

- main/src/ca/uwaterloo/flix/language/ast/SyntaxTree.scala
- main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala
- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Related to https://github.com/flix/flix/issues/11023.
I tested `pquery` in a program by adding it to the lexer, and it mostly works fine but causes a lot of crashing when it's not written out fully.  There is also an issue with the predicate symbols in the `with { ... }` part; it will accept anything but an `Ident` and I can't figure out why.
> feat: add support for `pquery` in `Parser2` and `Weeder2`

- main/src/library/Fixpoint3/Ast/ExecutableRam.flix
- main/src/library/Fixpoint3/Ast/Ram.flix
- main/src/library/Fixpoint3/Boxing.flix
- main/src/library/Fixpoint3/Interpreter.flix
- main/src/library/Fixpoint3/Phase/Hoisting.flix
- main/src/library/Fixpoint3/Phase/IndexSelection.flix
- main/src/library/Fixpoint3/Phase/Lowering.flix
- main/src/library/Fixpoint3/Phase/Simplifier.flix
- main/src/library/Fixpoint3/Util.flix
Primarily remove `RamStmt.EstimateJoinSize`.
> chore: remove join-profiler leftover

- main/src/library/Vector.flix
- main/test/ca/uwaterloo/flix/library/TestVector.flix
Simple proposal for a binary search for vector. See #6508
Could be changed to have a range, e.g. `binarySearch(x: a, from: {from = Int32}, to: {to = Int32}, v: Vector[a])`
> feat: implement binarySearch for `Vector`

- main/src/library/Order.flix
Removed `lazy` and `thenCompare` from tuple comparison.
The following very unscientific program was used to evaluate the performance (it prints every 5000000 comparison):
```
mod TupleOrder {
pub def compare(t1: (a1, a2), t2: (a1, a2)): Comparison with Order[a1], Order[a2] =
let (x1, x2) = t1;
let (y1, y2) = t2;
match x1 <=> y1 {
case Comparison.EqualTo => x2 <=> y2
case res => res
}
pub def compare2(t1: (a1, a2), t2: (a1, a2)): Comparison with Order[a1], Order[a2] =
let (x1, x2) = t1;
let (y1, y2) = t2;
let cmp1 = x1 <=> y1;
if (cmp1 != Comparison.EqualTo) cmp1
else x2 <=> y2
}
def mainBTreeExperiment(): Unit \ IO = region rc {
let t1 = (1, 2);
let t2 = (1, 2);
// let t1 = (1, 2);
// let t2 = (3, 2);
spawn runForeverOld(0i64, t1, t2) @ rc;
spawn runForeverNew(0i64, t1, t2) @ rc;
spawn …
```
> chore: improve performance of tuple comparison

- main/src/library/Fixpoint3/Phase/Hoisting.flix
- main/src/library/MutDisjointSets.flix
- main/test/ca/uwaterloo/flix/library/TestMutDisjointSets.flix
Replace the enums of records with structs and make `findSet.findRoot` tail recursive.
The following program went from 120 s to 80 s.
```
def testtt(): Bool = region rc {
let set = MutDisjointSets.empty(rc);
MutDisjointSets.union(1, 2, set);
MutDisjointSets.union(2, 3, set);
MutDisjointSets.union(3, 4, set);
MutDisjointSets.union(4, 5, set);
MutDisjointSets.union(5, 6, set);
MutDisjointSets.union(11, 12, set);
MutDisjointSets.union(12, 13, set);
MutDisjointSets.union(13, 14, set);
MutDisjointSets.union(14, 15, set);
MutDisjointSets.union(15, 16, set);
MutDisjointSets.union(21, 22, set);
MutDisjointSets.union(22, 23, set);
MutDisjointSets.union(23, 24, set);
MutDisjointSets.union(24, 25, set);
MutDisjointSets.union(25, 26, set);
MutDisjointSets.union(31, 32, set);
MutDisjointSets.union(32, …
```
> refactor: improve performance of `MutDisjointSets`

- main/src/ca/uwaterloo/flix/api/lsp/Consumer.scala
- main/src/ca/uwaterloo/flix/api/lsp/LocationLink.scala
- main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala
- main/src/ca/uwaterloo/flix/api/lsp/consumers/StackConsumer.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/FindReferencesProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala
- main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
- main/src/ca/uwaterloo/flix/language/ast/LiftedAst.scala
- main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala
- main/src/ca/uwaterloo/flix/language/ast/MonoAst.scala
- main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/LiftedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/LoweredAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/MonoAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/dbg/printer/TypedAstPrinter.scala
- main/src/ca/uwaterloo/flix/language/phase/Dependencies.scala
- main/src/ca/uwaterloo/flix/language/phase/EffectBinder.scala
- main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala
- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala
- main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
- main/src/ca/uwaterloo/flix/language/phase/Safety.scala
- main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
- main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala
- main/src/ca/uwaterloo/flix/language/phase/optimizer/Inliner.scala
- main/src/ca/uwaterloo/flix/language/phase/optimizer/OccurrenceAnalyzer.scala
- main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
- main/test/ca/uwaterloo/flix/verifier/EffectVerifier.scala
Fixes #9650
I searched for the regexes:
```regex
sym:\s*\S*SymUse                      # sym: XyzSymUse
[Ss]ym\.sym                           # sym.sym or Sym.sym
(?<!Use):\s*(SymUse\.)?\w*SymUse\b    # x: XyzSymUse where x is not "Use"
```
> chore: rename sym: XSymUse to symUse: XSymUse

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
Related to #11130.
This doesn't actually change any behavior since the return value of `oneOrMore` was ignored before.
> fix: use zeroOrMore for parsing NewObject body

- main/test/flix/Test.Exp.Fixpoint.Permutations.flix
> feat: add tests with different body atom orderings in Datalog

- main/src/library/Fixpoint3/Interpreter.flix
- main/src/library/Fixpoint3/Phase/RenamePredSyms.flix
- main/src/library/Fixpoint3/Solver.flix
Related to https://github.com/flix/flix/issues/11023.
It does currently not filter the facts according to the `with` part. This will be fixed in a separate PR.
> feat: add support for `pquery` in Datalog3 engine

- main/src/library/Fixpoint3/Boxing.flix
Replace most `X.forEach` with the new foreach loops.
There are 2 kinds of exceptions to the replacement in this draft. The first is partial application:
```
Vector.forEach(computeMappingTermRec, terms)
```
The second is small one liners:
```
Vector.forEach(i -> insert(RamId.RelPos(predSym, i)), Vector.range(0, arity))
```
Style choice: I have always used the brackets, even for one-liners. Argument: Readability
> chore: replace `X.forEach(...)` with `foreach(...) {...}` in Boxing

- main/src/library/Fixpoint3/Ast/Datalog.flix
- main/src/library/Fixpoint3/Boxing.flix
- main/src/library/Fixpoint3/Interpreter.flix
- main/src/library/Fixpoint3/Phase/Compiler.flix
- main/src/library/Fixpoint3/Provenance.flix
- main/src/library/Fixpoint3/Solver.flix
See #11066.
There are 3 cases where the new `foreach` keyword is not used.
1. Partial application. Example: `Vector.forEach(unifyRamIdsTerm(set), terms)`
2. One liner. Example: `Vector.forEach(i -> insert(RamId.RelPos(predSym, i)), Vector.range(0, arity))`
3. Performance critical `BPlusTree.forEach`. This is mainly in the interpreter, as the implementation of `foreach` for `BPlusTree` allocates a new tuple per entry.
If any of the cases should be converted to `foreach` loops please say so, otherwise I will consider this more or less done.
> chore: use `foreach` keyword

- main/src/library/Fixpoint3/Ast/Ram.flix
- main/src/library/Fixpoint3/Boxing.flix
- main/src/library/Fixpoint3/Predicate.flix
This started as a simple transformation of `Predicates` from `(Int64, Set[RelSym])` to `(List[RelSym], List[RelSym], Int64)`.
It ended up also removing a few `@Internal pub` from functions and in minor refactoring of the module `Predicate`.
> refactor: only transform predicates to list once

- main/src/library/Fixpoint3/Provenance.flix
Fixes #11305.
Problem: Rebinding of variables in nested body atoms not updated correctly when revisited.
I'll beautify the file/function later.
> fix: provenance failing to rebind variables

- main/test/flix/Test.Exp.Fixpoint.PQuery.flix
Related to https://github.com/flix/flix/issues/11245.
> chore: test that `mkExtVar` in `pquery` orders terms correctly

- main/src/library/Fixpoint3/Boxing.flix
- main/test/flix/Test.Exp.Fixpoint.Functional.flix
When this has been merged I will make a PR for #11304.
> fix: allow unused variables in functional predicates

- main/test/flix/Test.Exp.Fixpoint.PQuery.flix
Follow up from #11351 integrating #11345
> chore: add tests for functional predicates in `pquery`

- main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
Its name is now like the other desugaring functions. Also updated the wording in the doc.
> refactor: rename `mkLambdaMatch` to `desugarLambdaMatch`

- main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
- main/test/flix/Test.Exp.Fixpoint.PQuery.flix
> fix: allow nullary predicates in `pquery`

- main/src/library/List.flix
Fixes the simple right-to-left CPS functions from #11399
Simple here means that the loop is (mostly) of the form: `loop(restOfList, accumulatedResultToBeReversed) = ???`
> refactor: remove CPS from simple left-to-right List folds

- main/src/library/List.flix
Fixes the misc. right-to-left CPS functions from #11399
> refactor: remove CPS from misc. left-to-right List folds

- main/src/library/List.flix
I forgot this function in the previous PRs.
I believe only `sequence`, `traverse` and `zipWithA` are CPS style. Everything from #11399 should now be added.
I do not have experience with Flix's `Applicative` so I would prefer if someone else would fix `sequence` and `traverse`.
> refactor: replace CPS in last non-applicable List function

- main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala
- main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
- main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
- main/src/ca/uwaterloo/flix/language/phase/Typer.scala
Closes #8720.
Removes `tpe: Type` from `KindedAst.Enum` and instead reconstruct it as needed in `Deriver`.
Also as a side note: What is `ResolvedAst.TypeParam.Implicit` and why can it occur in `Enum`?
> refactor: remove type from `KindedAst.Enum`

- main/src/ca/uwaterloo/flix/language/errors/LexerError.scala
- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
- main/test/ca/uwaterloo/flix/language/phase/TestLexer.scala
- main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
- [Fix] Treats e.g. `42i32x` as a single wrong number (previously int `42i32` and variable `x`)
- [Fix] Allows `12e+12`.
- [Feat] Errors are better
- `32i31` says that `i31` is an invalid suffix (previously "Undefined name 'i31'")
- `12e12e` says that a digit was expected instead of `e` (second occurrence) (previously "malformed float")
- `12.4i32` says that decimals cannot have integer suffixes (previously "malformed float")
- [Test] More tests
- [Docs] Documented a regex describing valid numbers.
- [Refactor] The regex based function makes it easier to read
- [Performance] `--Xbenchmark-phases`
- `    PR: 164,5 ms (07,2%)` 
- `Master: 165,6 ms (07,2%)`
Follow up work: sort `LexerError` and `TestLexer`
> feat: better number parsing

- main/src/ca/uwaterloo/flix/language/ast/Symbol.scala
- main/src/ca/uwaterloo/flix/language/phase/EntryPoints.scala
- main/src/ca/uwaterloo/flix/util/collection/CofiniteSet.scala
- [Fix] made `hasAssert` sound.
- [Refactor] reduced subset code duplication.
- [Refactor] removed "always Nil" return value from `WrapMain`
- [Style] fixed formatting inconsistencies.
> refactor: clean up `EntryPoints`

- main/src/ca/uwaterloo/flix/language/errors/LexerError.scala
- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
- main/test/ca/uwaterloo/flix/language/phase/TestLexer.scala
- No reason to arbitrarily limit it
- other places in the lexer don't have this recursion counter (block comments, numbers, keywords, ..)
> feat: remove Interpolation nesting threshold

- main/test/ca/uwaterloo/flix/util/FlixSuite.scala
- main/test/ca/uwaterloo/flix/verifier/TokenVerifier.scala
Ensures that ranges are not empty, like `[1, 1[`
Enabling it for full `FlixSuite` also goes through
> feat: non-empty tokens lexer verification

- main/test/ca/uwaterloo/flix/util/FlixSuite.scala
- main/test/ca/uwaterloo/flix/verifier/TokenVerifier.scala
For a program like
```
123
42
```
This verifies that `123` has range `[1:1, 1:4[` instead of `[1:1, 2:1[`. The lexer does this to make ranges touch as few lines as possible.
This is accepted with full FlixSuite enabled
> feat: end col lexer verification

- main/src/ca/uwaterloo/flix/api/Bootstrap.scala
`Bootstrap` uses `'` quoted strings in all printed messages except here.
> fix: replace backticks with single quotes in prints

- main/src/ca/uwaterloo/flix/api/Bootstrap.scala
The function `getAlFilesWithExt` could easily be misunderstood, so I added a check to ensure it is used correctly. This can also be done via a `Validation` type. What do you think is best?
> feat: check file extension input in `Bootstrap`

- main/src/ca/uwaterloo/flix/api/Bootstrap.scala
- main/src/ca/uwaterloo/flix/api/Flix.scala
- main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala
- main/src/ca/uwaterloo/flix/util/FileOps.scala
- main/test/ca/uwaterloo/flix/util/FlixSuite.scala
This PR removes file operations from `Bootstrap` and merges them into `FileOps`. The reason is threefold:
1. `Bootstrap` had many functions related to file operations. Removing them from the class allows it to focus more cleanly on what it must achieve, i.e., less clutter more meaningful code.
2. `Bootstrap` and `FileOps` had code duplication, so this PR improves code reuse.
3. `isZipArchive` was used in both `Bootstrap` and `Flix` but defined twice. As it seems to be a predicate that relies solely on a file and its first four bytes, it seems natural to move it to `FileOps`. This improves code reuse again.
> refactor: merge file operations in `Bootstrap` with `FileOps`

- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
There is a peek function that returns the previous char in case of EOF which is really dangerous.
This PR uses the `s.sc.peek` function with returns `EOF` for eof. Additionally, it guards peeks to avoid calling `EOF.isLetter` fx
> refactor: remove Lexer.peek

- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
- main/src/library/BigInt.flix
- main/test/flix/Test.Exp.Jvm.InvokeMethod2.flix
current keywords are interpreted as names if prefixed by `.`. This means that `something.and` does not see `and` as a keyword. I propose that we remove this edge case since we have `$and` to allow keywords as names.
| Input | Before | PR | Fix |
| --- | --- | --- | --- |
| `x.not(y)` |  accepted | `expected <name> instead of 'not'` | `x.$not(y)` |
> feat: harden keywords in lexer

- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
The lexer doesn't partially consume operators, so if an operator is being lexer then there will never be a operator symbol immediately before it.
Profiler suggests this is a hot spot so performance might actually be noticeably better
> refactor: remove operator lexing look-behind

- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
The advance that returns the char is somewhat unsafe because it returns a null char.
- peekAndAdvance is unsafer and is only used 2 places
- advance is safe and is used 20 places
I think its good to isolate the unsafer uses.
> refactor: split StringCursor.advance

- main/test/ca/uwaterloo/flix/library/TestBPlusTree.flix
Changes:
1. The number of inserted elements in some tests has been decreased.
2. `put05` does no longer re-compute of the same thing for each round.
3. Deleted some redundant `concurrencyXX` tests.
> chore: improve performance of `BPlusTree` tests

- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
The tree uses longest match, so `#` can also be added
> refactor: add `#` as simple token

- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
- main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala
An empty case set now requires a space, e.g. `Formula[< >]`
> refactor: remove `<>` special lexing

- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
Treats operators as uniformly as possible. Additionally it avoids a bunch of options
> refactor: simplify operators

- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
Eagerly eat all irrelevant chars instead of spending so much time on each.
> refactor: faster block comments in Lexer

- main/src/ca/uwaterloo/flix/language/errors/LexerError.scala
With this PR, you get a usable message no matter the input.
```
>> Unexpected character '\uD808'.
1 | 𒌒
^
Unexpected character.
```
> feat: better Lexer unicode errors

- main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
Instead of reusing token kinds as operators, introduce its own custom type.
`--Xbenchmark-phases`
- `    PR 137,2 ms (06,8%)`
- `Master 161,8 ms (08,0%)`
This has the extra benefit that the Lexer Tokens are separated from parser operators, i.e. lexing of infix operators can be made sensible.
> refactor: explicit parser operators

- main/src/library/Reflect.flix
- main/test/ca/uwaterloo/flix/library/TestReflect.flix
The doc says `The value returned should not be depended on` so we should use null for all object types
> feat: simplify `Reflect.default`

- main/src/ca/uwaterloo/flix/language/errors/WeederError.scala
- main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
- main/test/ca/uwaterloo/flix/language/phase/TestPatMatch.scala
Disallow constants in destructuring patterns.
Overall change: For destructuring assignments, except `match`, constants will be reported as an error and replaced by `Pattern.Error` to prevent further errors (concretely `Non-exhaustive match`).
What will users experience?
1. Better error messages
2. Expressions of the form `let A.A = ???` are now illegal independent of how the enum `A` looks.
Reasoning:
1. The current error reporting is bad. See #11590.
2. Destructuring with constants is useless. It can be replaced by destructuring to `_`. The only exception would be to show what the value is, but I think that is a niche concern.
Not handled: Destructuring with `x :: xs`. It will always be reported as non-exhaustive, but we do not throw an error. It can be caught by the following, but the …
> feat: prohibit constants in destructuring

- main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
Somewhere `<=>` got lost as an operator, but because `Weeder` does string matching, it only resulted in inproper precedence
> fix: lex `<=>` distinctly

- main/src/library/Char.flix
> fix: `Char.isAscii`

- main/test/ca/uwaterloo/flix/tools/TestFlixPackageManager.scala
Moves url to the flix organization, just to safe guard against a very unlikely accident.
> test: do not depend on 3rd party library
