flix/flix

main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
This example now triggers the `HoleCompletor`
```scala
def foo(): Bool = 
let l = List.range(1, 1000);
l? // <- Completions triggers here
```
=> fix: `HoleCompleter`

build.gradle
=> refactor: remove `scalactic` dependency

main/src/ca/uwaterloo/flix/language/phase/Parser2.scala, main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
Adds a regression test for #7820
=> test: Add regression test for issue 7820

main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala, main/src/ca/uwaterloo/flix/api/lsp/LocationLink.scala, main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/Symbol.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/errors/TypeError.scala, main/src/ca/uwaterloo/flix/language/phase/Deriver.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala, main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala, main/src/ca/uwaterloo/flix/language/phase/util/PredefinedTraits.scala
=> chore: rename clazz to trt

main/src/ca/uwaterloo/flix/language/errors/TypeError.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala, main/test/flix/Test.Exp.Jvm.InvokeMethod2.Chaining.flix, main/test/flix/Test.Exp.Jvm.InvokeMethod2.ZeroArg.flix, main/test/flix/Test.Exp.Jvm.InvokeMethod2.flix
=> feat: add type inference for `InvokeMethod2` with parametered methods

main/src/library/Adaptor.flix, main/src/library/Comparison.flix
=> fix: rename Comparison.toInt to Comparison.toInt32

main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala, main/test/flix/Test.Exp.Jvm.InvokeMethod2.Chaining.flix, main/test/flix/Test.Exp.Jvm.InvokeMethod2.ZeroArg.flix, main/test/flix/Test.Exp.Jvm.InvokeMethod2.flix
Part of #7833 and #7769.
Note that there are still some issues, see #7841.
=> feat: add `BigInteger` support for `InvokeMethod2`

main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/dbg/DocAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
=> feat: add support for `InvokeConstructor2` and `InvokeStaticMethod2` to front-end

main/src/ca/uwaterloo/flix/tools/SocketServer.scala
This will enable us to restart the server every night and still have decent performance.
=> refactor: enable warmup of `SocketServer`

main/src/ca/uwaterloo/flix/language/phase/Namer.scala
I also ran IntelliJ's `optimize imports` but it looks like it's already fine so feel free to just close this pr.
=> style: reformat file

main/src/ca/uwaterloo/flix/language/phase/Namer.scala
Also checked that functions are private when possible.
=> style: remove unused variables in `Namer`

main/src/ca/uwaterloo/flix/language/phase/Namer.scala
=> refactor: remove `visitType` inner function

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/api/lsp/Diagnostic.scala, main/src/ca/uwaterloo/flix/language/CompilationMessage.scala, main/src/ca/uwaterloo/flix/language/errors/DerivationError.scala, main/src/ca/uwaterloo/flix/language/errors/EntryPointError.scala, main/src/ca/uwaterloo/flix/language/errors/InstanceError.scala, main/src/ca/uwaterloo/flix/language/errors/KindError.scala, main/src/ca/uwaterloo/flix/language/errors/LexerError.scala, main/src/ca/uwaterloo/flix/language/errors/NameError.scala, main/src/ca/uwaterloo/flix/language/errors/NonExhaustiveMatchError.scala, main/src/ca/uwaterloo/flix/language/errors/ParseError.scala, main/src/ca/uwaterloo/flix/language/errors/RedundancyError.scala, main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala, main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala, main/src/ca/uwaterloo/flix/language/errors/StratificationError.scala, main/src/ca/uwaterloo/flix/language/errors/TypeError.scala, main/src/ca/uwaterloo/flix/language/errors/WeederError.scala, main/src/ca/uwaterloo/flix/tools/SocketServer.scala, main/test/ca/uwaterloo/flix/TestUtils.scala, main/test/ca/uwaterloo/flix/language/LanguageSuite.scala, main/test/ca/uwaterloo/flix/language/errors/TestCompilationMessage.scala, main/test/ca/uwaterloo/flix/util/FlixSuite.scala
Closes https://github.com/flix/flix/issues/6735
=> refactor: add `CompilationMessage.messageWithLoc`

main/src/ca/uwaterloo/flix/language/phase/Namer.scala
=> refactor: remove `toSoftFailure` in `Namer`

main/src/library/Char.flix
=> refactor: update java imports in `Char.flix`

main/src/library/Environment.flix
=> refactor: update java imports in `Environment.flix`

build.gradle
We need them for benchmarking.
=> refactor: undo exclusion of tests

main/src/library/Files.flix, main/test/ca/uwaterloo/flix/library/TestFile.flix
=> refactor: update java imports in `File.flix`

main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/errors/TypeError.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeConstraint.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeContext.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala
=> feat: add `InvokeConstructor2` support

main/src/ca/uwaterloo/flix/language/dbg/DocAst.scala, main/src/ca/uwaterloo/flix/language/dbg/DocAstFormatter.scala
Related to https://github.com/flix/flix/issues/7897
=> feat: update `DocAst` with `#` for `RecordSelect`

main/src/ca/uwaterloo/flix/language/phase/Namer.scala
=> refactor: remove `Validation` from `visitType` in `Namer`

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/phase/Reader.scala
=> feat: add support for auto-complete of classes in JARs

main/test/flix/Test.Exp.Apply.Named.flix, main/test/flix/Test.Exp.Force.flix, main/test/flix/Test.Exp.Match.Record.flix, main/test/flix/Test.Exp.Record.Extend.flix, main/test/flix/Test.Exp.Record.Restrict.flix
Related to https://github.com/flix/flix/pull/7930
Related to https://github.com/flix/flix/issues/7897
=> feat: update `CompilerSuite` to `#` `RecordSelect` syntax

main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/SyntaxTree.scala, main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
Add the ability to parse struct declarations of the form specified in this issue: #7924
=> feat: Add support to parser for struct declarations

main/src/library/BigInt.flix
=> refactor: support for `InvokeConstructor2` in `BigInt.flix`

main/src/library/Files.flix
=> refactor: partial refactor for `InvokeConstructor2` in `Files.flix`

main/src/ca/uwaterloo/flix/language/phase/Namer.scala
=> refactor: remove `Validation` from `tableDecl` in `Namer`

main/src/library/Files.flix
=> refactor: update java imports in `Files.flix`

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/KeywordExprCompleter.scala
=> feat: added struct to KeywordExprCompleter

main/src/ca/uwaterloo/flix/language/ast/Name.scala, main/src/ca/uwaterloo/flix/language/errors/WeederError.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala, main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
This is the first of the well-formedness checks listed in #7938.
Would welcome any suggestions for error messages(or approval if you think they are ok) - I tried to copy similar error messages.
=> feat: Added checking of duplicate struct fields and associated tests to weeder

main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala
=> feat: Add the completed struct desugar pass

main/test/ca/uwaterloo/flix/library/TestFile.flix
=> refactor: import java types in `TestFile.flix`

main/src/library/Random.flix
=> refactor: support for `InvokeConstructor2` in `Random.flix`

main/src/ca/uwaterloo/flix/language/phase/Namer.scala
=> refactor: remove `Validation` from `tableUnit` in `Namer`

main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
=> fix: parsing of chains of application and record select

main/src/library/System.flix
=> refactor: update java imports in `System.flix`

main/src/library/Adaptor.flix
=> refactor: update java imports in `Adaptor.flix`

main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/Symbol.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala
Addresses part of #7936 and #7938.
=> feat: add struct support to the namer phase

main/src/library/Float32.flix, main/src/library/Float64.flix
=> refactor: update java imports in `Float32.flix` and `Float64.flix`

main/src/library/Concurrent/CyclicBarrier.flix, main/src/library/StringBuilder.flix
=> refactor: support for `InvokeConstructor2` in `CyclicBarrier.flix`

main/src/library/BigDecimal.flix
=> refactor: support for `InvokeConstructor2` in `BigDecimal.flix`

main/src/library/List.flix
=> refactor: update java imports in `List.flix`

build.gradle
=> fix: downgrade antlr to 4.11.1

main/src/ca/uwaterloo/flix/tools/SocketServer.scala
=> feat: log programs sent to playground

main/src/library/Vector.flix
=> refactor: update java imports in `Vector.flix`

main/src/library/FromJava.flix
=> refactor: update java imports in `FromJava.flix`

main/src/ca/uwaterloo/flix/language/phase/Namer.scala
=> refactor: remove `Validation` from functions in `Namer`

main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/Type.scala, main/src/ca/uwaterloo/flix/language/ast/TypeConstructor.scala, main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala, main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/PatMatch.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala, main/src/ca/uwaterloo/flix/language/phase/unification/BoolAlg.scala, main/src/ca/uwaterloo/flix/language/phase/unification/BoolUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/EffUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/RecordUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/SchemaUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
=> feat: add IDs to error types

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/tools/Summary.scala
split summary into logical components for easier maintenance and modification
=> feat: structured summary

main/test/flix/Test.Exp.Jvm.GetField.flix
=> refactor: update java imports in `Test.Exp.Jvm.GetField.flix`

main/src/library/Int8.flix
=> refactor: update java imports in `Int8.flix`

main/src/library/Int16.flix
=> refactor: update java imports in `Int16.flix`

main/src/library/Int32.flix
=> refactor: update java imports in `Int32.flix`

main/src/library/Int64.flix
=> refactor: update java imports in `Int64.flix`

main/src/library/Chain.flix
=> refactor: update java imports in `Chain.flix`

main/src/library/Nel.flix
=> refactor: update java imports in `Nel.flix`

main/src/library/Map.flix
=> refactor: update java imports in `Map.flix`

main/src/library/Nec.flix
=> refactor: update java imports in `Nec.flix`

main/src/library/Set.flix
=> refactor: update java imports in `Set.flix`

main/test/flix/Test.Exp.CheckedTypeCast.flix
=> refactor: update java imports in `Test.Exp.CheckedTypeCast.flix`

main/test/flix/Test.Exp.Jvm.GetFieldDoubleNestedClass.flix
=> refactor: update java imports in `Test.Exp.Jvm.GetFieldDoubleNestedClass.flix`

main/test/flix/Test.Exp.Jvm.InvokeMethod.flix
=> refactor: update java imports in `Test.Exp.Jvm.InvokeMethod.flix`

main/test/flix/Test.Exp.Jvm.InvokeStaticMethod2.flix
=> refactor: update java imports in `Test.Exp.Jvm.InvokeStaticMethod2.flix`

main/test/flix/Test.Exp.Jvm.GetFieldStaticInnerClass.flix
=> refactor: update java imports in `Test.Exp.Jvm.GetFieldStaticInnerClass.flix`

main/test/flix/Test.Exp.Jvm.GetStaticFieldStaticInnerClass.flix
=> refactor: update java imports in `Test.Exp.Jvm.GetStaticFieldStaticInnerClass.flix`

main/test/flix/Test.Exp.UncheckedTypeCast.flix
=> refactor: update java imports in `Test.Exp.UncheckedTypeCast.flix`

main/test/flix/Test.Exp.Jvm.InvokeStaticMethod.flix
=> refactor: update java imports in `Test.Exp.Jvm.InvokeStaticMethod.flix`

main/test/flix/Test.Exp.Jvm.GetStaticField.flix
=> refactor: update java imports in `Test.Exp.Jvm.GetStaticField.flix`

main/src/library/ToJava.flix
=> refactor: update java imports in `ToJava.flix`

main/test/flix/Test.Exp.Jvm.InvokeConstructor.flix
=> refactor: update java imports in `Test.Exp.Jvm.InvokeConstructor.flix`

main/test/flix/Test.Import.flix
=> refactor: update java imports in `Test.Import.flix`

main/test/flix/Test.Exp.Jvm.NewObject.flix
=> refactor: update java imports in `Test.Exp.Jvm.NewObject.flix`

main/test/flix/Test.Exp.Jvm.InvokeConstructor2.flix
Related to https://github.com/flix/flix/pull/8075/files
=> refactor: update java imports in `Test.Exp.Jvm.InvokeConstructor2.flix`

main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala
=> fix: only highlight occurrences in relevant document

main/src/library/Add.flix
=> chore: update syntax for imports in Add.flix

main/src/library/Concurrent/Channel.flix, main/src/library/Concurrent/Condition.flix, main/src/library/Concurrent/CyclicBarrier.flix, main/src/library/Concurrent/ReentrantLock.flix
=> chore: update import syntax in Concurrent modules

main/src/library/BigDecimal.flix, main/src/library/BigInt.flix
=> chore: update imports in `BigX`

main/src/library/Object.flix
=> chore: update import syntax in Object.flix

main/src/library/Time/Epoch.flix
=> chore: update import syntax for Epoch.flix

main/src/library/Time/Instant.flix
=> chore: update import syntax for Instant.flix

main/src/library/Float32.flix, main/src/library/Float64.flix
=> chore: update syntax for imports in FloatX.flix files

main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala
=> feat: check for illegal nested try catch blocks

examples/using-laziness-for-logging.flix
=> chore: update import syntax in using-laziness-for-logging.flix

main/test/flix/Test.Import.flix
=> chore: update import syntax in Test.Import.flix

main/test/flix/Test.Exp.Instanceof.flix
=> chore: update import syntax in Test.Exp.Instanceof.flix

main/test/flix/Test.Handler.Gen.AtomicInteger.flix
=> chore: update import syntax in Test.Handler.Gen.AtomicInteger.flix

main/test/flix/Test.Handler.NewObject.flix
=> chore: update import syntax in Test.Handler.NewObject.flix

main/test/flix/Test.Handler.OneShot.AtomicInteger.flix
=> chore: update import syntax in Test.Handler.OneShot.AtomicInteger.flix

main/test/flix/Test.Handler.Ask.AtomicInteger.flix
=> chore: update import syntax in Test.Handler.Ask.AtomicInteger.flix

main/test/flix/Test.Handler.ZeroShot.AtomicInteger.flix
=> chore: update import syntax in Test.Handler.ZeroShot.AtomicInteger.flix

main/test/flix/Test.Exp.Jvm.TryCatch.flix, main/test/flix/Test.Java.Function.flix
Note that I also assigned myself to PutField.flix, PutStaticField.flix, UncheckedTypeCast.flix but these don't really need any work done to them.
#8096
=> chore: fixed import syntax for TryCatch and Function

main/src/library/Environment.flix
=> chore: environment remove unnecessary imports

main/test/ca/uwaterloo/flix/library/TestAdaptor.flix, main/test/ca/uwaterloo/flix/library/TestChar.flix, main/test/ca/uwaterloo/flix/library/TestFile.flix, main/test/ca/uwaterloo/flix/library/TestFloat32.flix, main/test/ca/uwaterloo/flix/library/TestFloat64.flix, main/test/ca/uwaterloo/flix/library/TestInt16.flix, main/test/ca/uwaterloo/flix/library/TestInt32.flix, main/test/ca/uwaterloo/flix/library/TestInt64.flix, main/test/ca/uwaterloo/flix/library/TestToJava.flix
=> chore: add new method syntax to `test/ca/waterloo/flix/library/Test*` files

main/test/flix/Test.Exp.CheckedTypeCast.flix
=> chore: update import syntax in Test.Exp.CheckedTypeCast.flix

main/src/library/Adaptor.flix
=> chore: update imports in `Adaptor.flix`

main/src/library/File.flix, main/src/library/Files.flix
=> chore: update imports in File(s)

main/test/flix/Test.Exp.Jvm.InvokeStaticMethod2.flix
=> chore: update import syntax in `Test.Exp.Jvm.InvokeStaticMethod2.flix`

main/src/library/CodePoint.flix
=> chore: update import syntax in `CodePoint.flix`

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/InvokeMethodCompleter.scala, main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/errors/TypeError.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala
This implementation is deliberately barebones.
=> feat: add InvokeMethodCompleter

main/src/library/Environment.flix, main/src/library/Regex.flix, main/src/library/String.flix, main/test/ca/uwaterloo/flix/library/TestAdaptor.flix, main/test/ca/uwaterloo/flix/library/TestFile.flix
#8096 
A few small touchups from the parts I missed earlier since I was waiting on a different PR.
=> chore: touch up `Environment.flix`, `Regex.flix`, `String.flix`, `TestAdaptor.flix`, and `TestFile.flix`

main/src/library/Array.flix
part of #8096 
sorry for breaking my vow, but I've removed the redundant Unit/BigX/String cases
=> chore: update imports in Array.flix

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/Box.flix, main/test/ca/uwaterloo/flix/library/TestBox.flix, main/test/flix/CompilerSuite.scala
See `#8155`
Now you can, for example, call `Box.box(30)` or `Box.unbox(Box.box('c'))`
=> feat: add `Box` trait

main/src/ca/uwaterloo/flix/language/ast/SyntaxTree.scala, main/src/ca/uwaterloo/flix/language/phase/Parser2.scala, main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
=> feat: add `throw` to the parser

main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala, main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala
=> refactor: remove TypeParams type

main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
=> refactor: TestResolver

main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala
We will be finding more of these for decades...
=> chore: rename class -> trait

main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
=> feat: Add `throw` to the weeder

main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> feat: Add `throw` to `Namer`, `Desugar`, and `Resolver`

main/src/ca/uwaterloo/flix/language/ast/AtomicOp.scala, main/src/ca/uwaterloo/flix/language/phase/Eraser.scala, main/src/ca/uwaterloo/flix/language/phase/Verifier.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
=> feat: add `throw` to `AtomicOp`

main/src/ca/uwaterloo/flix/language/phase/Verifier.scala
=> fix: verifier array bug

main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
=> feat: add kinding to throw

main/src/ca/uwaterloo/flix/language/phase/Eraser.scala
=> feat: add eraser support to `Throw`

main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
=> feat: add `Throw` support to `GenExpression`

main/src/ca/uwaterloo/flix/language/phase/Verifier.scala
=> feat: add `Throw` to verifier

main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala
=> feat: add `Throw` support to the indexer

main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
=> feat: add `Throw` to `SemanticTokensProvider`

main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala
=> feat: add `throw` support to `TypedAstOps`

AUTHORS.md
Added my name for confirming open source contributions.
=> docs: update AUTHORS.md

main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala
=> feat: add `Throw` to `Safety`

main/src/ca/uwaterloo/flix/language/phase/EffectVerifier.scala
=> feat: add `Throw` support to `EffectVerifier`

main/src/ca/uwaterloo/flix/language/dbg/DocAst.scala, main/src/ca/uwaterloo/flix/language/dbg/DocAstFormatter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/TypedAstPrinter.scala
=> feat: add `throw` to `DocAst`

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala, main/src/ca/uwaterloo/flix/util/Options.scala
=> feat: configurable max iterations

main/src/ca/uwaterloo/flix/language/ast/LiftedAst.scala, main/src/ca/uwaterloo/flix/language/ast/OccurrenceAst.scala, main/src/ca/uwaterloo/flix/language/ast/ReducedAst.scala, main/src/ca/uwaterloo/flix/language/phase/EffectBinder.scala, main/src/ca/uwaterloo/flix/language/phase/Inliner.scala, main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala, main/src/ca/uwaterloo/flix/language/phase/OccurrenceAnalyzer.scala
All the additions to the phases are similar in nature
=> feat: add struct support to `EffectBinder`, `Inliner`, `LambdaLift`, `OccurrenceAnalyzer` and `Monomorpher`

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> chore: remove Resolver.Params

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
=> fix: missing undefined variable error

build.gradle
=> feat: enable Scala optimizer in `build.gradle`

main/src/ca/uwaterloo/flix/language/phase/jvm/BackendType.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
Once this PR gets merged, the struct tests can be enabled and added
=> feat: add struct support to `GenExpression` and `BackendType`

main/src/ca/uwaterloo/flix/api/Bootstrap.scala, main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/ast/shared/Input.scala, main/src/ca/uwaterloo/flix/language/ast/shared/Source.scala, main/src/ca/uwaterloo/flix/language/phase/Reader.scala, main/src/ca/uwaterloo/flix/runtime/shell/Category.scala, main/src/ca/uwaterloo/flix/tools/SimpleRunner.scala, main/src/ca/uwaterloo/flix/tools/Summary.scala, main/test/ca/uwaterloo/flix/util/FlixSuite.scala
This PR propagates the SecurityContext from Flix add input methods into Input
=> feat: propagate `SecurityContext`

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/StructFieldCompleter.scala, main/src/ca/uwaterloo/flix/language/ast/Ast.scala
=> feat: add struct field autocompletion

main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
=> feat: add semantic tokens for struct decls

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> chore: remove Resolver.Constraints

main/src/ca/uwaterloo/flix/api/Bootstrap.scala
=> feat: add crash reports to generated .gitignore

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/StructFieldCompleter.scala
=> feat: show type when completing struct fields

main/src/ca/uwaterloo/flix/language/phase/Safety.scala
=> feat: add security permission check to Safety phase

main/src/library/Adaptor.flix
=> style: update imports in `Adaptor.flix` to new import style

main/src/library/Float32.flix, main/src/library/Float64.flix
=> style: update imports in `Float32.flix` and `Float64.flix` to new import style

main/src/library/Environment.flix
=> style: update imports in `Environment.flix` to new import style

main/src/library/Files.flix
=> style: update imports in `Files.flix` to new import style

main/src/library/File.flix
=> style: update imports in `File.flix` to new import style

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> chore: remove Resolver.Expressions

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> chore: remove Resolver.Patterns

main/src/ca/uwaterloo/flix/language/ast/SyntaxTree.scala, main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Lexer.scala, main/src/ca/uwaterloo/flix/language/phase/Parser2.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala, main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala, main/test/flix/Test.Dec.Trait.flix
Related to https://github.com/flix/flix/issues/8268
=> feat: add `redef` keyword

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> chore: remove Resolver.Predicates

main/src/library/Environment.flix, main/src/library/Prelude.flix
=> fix: remove redundant `(System.err).something` parens

main/src/library/BigDecimal.flix, main/src/library/BigInt.flix, main/src/library/Boxable.flix, main/src/library/Boxed.flix, main/src/library/Concurrent/Condition.flix, main/src/library/Concurrent/ReentrantLock.flix, main/src/library/Console.flix, main/src/library/Debug.flix, main/src/library/File.flix, main/src/library/Float32.flix, main/src/library/Float64.flix, main/src/library/Map.flix, main/src/library/Random.flix, main/src/library/Regex.flix, main/src/library/Set.flix, main/src/library/String.flix, main/src/library/Time/Instant.flix
=> refactor: remove usage of `##` in library

main/test/ca/uwaterloo/flix/library/TestToJava.flix, main/test/flix/Test.Exp.Concurrency.Spawn.flix, main/test/flix/Test.Exp.Jvm.GetField.flix, main/test/flix/Test.Exp.Jvm.GetFieldDoubleNestedClass.flix, main/test/flix/Test.Exp.Jvm.GetFieldStaticInnerClass.flix, main/test/flix/Test.Exp.Jvm.NewObject.flix, main/test/flix/Test.Exp.Jvm.TryCatch.flix, main/test/flix/Test.Java.Function.flix
=> refactor: remove usage of `##` in tests

main/src/ca/uwaterloo/flix/language/ast/Name.scala, main/src/ca/uwaterloo/flix/language/ast/Symbol.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
=> refactor: switch from `/` to `.` module syntax internally

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> chore: make Resolver functions private

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> refactor: extract local functions in Resolver

main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Just a minor warning / style issue
=> style: remove parenthesis in lambda

main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Related to https://github.com/flix/flix/issues/8268
=> feat: deprecate `override` keyword

main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala
=> feat: run `Indexer` asynchronously in `LanguageServer`

main/test/ca/uwaterloo/flix/language/phase/TestInstances.scala
Related to https://github.com/flix/flix/issues/8268
=> test: add instance test for `redef`

main/src/ca/uwaterloo/flix/api/lsp/provider/HoleCompletion.scala, main/src/ca/uwaterloo/flix/language/ast/Scheme.scala, main/src/ca/uwaterloo/flix/language/ast/Symbol.scala, main/src/ca/uwaterloo/flix/language/ast/Type.scala, main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala, main/src/ca/uwaterloo/flix/language/ast/shared/Scope.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala, main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala, main/src/ca/uwaterloo/flix/language/phase/Deriver.scala, main/src/ca/uwaterloo/flix/language/phase/EffectBinder.scala, main/src/ca/uwaterloo/flix/language/phase/EntryPoint.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala, main/src/ca/uwaterloo/flix/language/phase/typer/RestrictableChooseConstraintGen.scala, main/src/ca/uwaterloo/flix/language/phase/typer/SchemaConstraintGen.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeContext.scala, main/src/ca/uwaterloo/flix/language/phase/unification/EffUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/RecordUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/SchemaUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala, main/test/ca/uwaterloo/flix/language/fmt/TestFormatType.scala, main/test/ca/uwaterloo/flix/language/phase/unification/TestCaseSetUnification.scala
This introduces levels to the appropriate phases, but does not use them for unification/constraint solving, so I'm calling it a refactor.
=> refactor: introduce levels

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/Array.flix, main/src/library/IndexMut.flix, main/src/library/Indexable.flix, main/src/library/IndexableMut.flix, main/src/library/MutMap.flix, main/src/library/Vector.flix
Fixes https://github.com/flix/flix/issues/8402
=> refactor: rename `Index` and `IndexMut` to `Indexable` and `IndexableMut`

examples/using-laziness-for-logging.flix, main/src/library/CodePoint.flix, main/src/library/Concurrent/Channel.flix, main/src/library/Concurrent/ReentrantLock.flix, main/src/library/Console.flix, main/src/library/Debug.flix, main/src/library/FromJava.flix, main/src/library/Int16.flix, main/src/library/Int32.flix, main/src/library/Int64.flix, main/src/library/Int8.flix, main/src/library/Object.flix, main/src/library/ToJava.flix, main/test/ca/uwaterloo/flix/library/TestFromJava.flix, main/test/ca/uwaterloo/flix/library/TestToJava.flix, main/test/flix/Test.Exp.CheckedTypeCast.flix, main/test/flix/Test.Exp.Instanceof.flix, main/test/flix/Test.Exp.Jvm.GetField.flix, main/test/flix/Test.Exp.Jvm.GetFieldDoubleNestedClass.flix, main/test/flix/Test.Exp.Jvm.GetFieldStaticInnerClass.flix, main/test/flix/Test.Exp.Jvm.InvokeMethod.flix, main/test/flix/Test.Exp.Jvm.InvokeMethod2.Overload.Null.flix, main/test/flix/Test.Exp.Jvm.InvokeMethod2.Overload.Subtypes.flix, main/test/flix/Test.Exp.Jvm.InvokeStaticMethod.flix, main/test/flix/Test.Exp.Jvm.InvokeStaticMethod2.flix, main/test/flix/Test.Exp.Jvm.PutField.flix, main/test/flix/Test.Exp.Jvm.PutStaticField.flix, main/test/flix/Test.Exp.UncheckedTypeCast.flix, main/test/flix/Test.Import.flix
Search regex: `import .* [\{,;]`
Closes https://github.com/flix/flix/issues/7999
=> style: update import style in library and tests

main/src/ca/uwaterloo/flix/language/phase/PatMatch.scala
=> refactor: use Symbol.CaseSym in PatMatch

main/src/ca/uwaterloo/flix/api/lsp/provider/HoleCompletion.scala, main/src/ca/uwaterloo/flix/language/ast/RigidityEnv.scala, main/src/ca/uwaterloo/flix/language/ast/Scheme.scala, main/src/ca/uwaterloo/flix/language/ast/shared/Scope.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala, main/src/ca/uwaterloo/flix/language/phase/EffectVerifier.scala, main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala, main/src/ca/uwaterloo/flix/language/phase/unification/CaseSetUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/EffUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/EffUnification2.scala, main/src/ca/uwaterloo/flix/language/phase/unification/EqualityEnvironment.scala, main/src/ca/uwaterloo/flix/language/phase/unification/TraitEnvironment.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala, main/test/ca/uwaterloo/flix/language/phase/unification/TestAssocTypeUnification.scala
=> refactor: further plumbing of levels

main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala, main/src/library/Array.flix, main/src/library/Indexable.flix, main/src/library/IndexableMut.flix, main/src/library/MutMap.flix, main/src/library/Vector.flix
=> feat: remove `Indexable.getSwapped` and `IndexableMut.putSwapped`

main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala
Dont merge this before #8444 !
move known type checking into the solver instead of being external
=> refactor: change java solver interface

main/src/ca/uwaterloo/flix/language/phase/Parser2.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
=> fix: `Parser2` and `Weeder2` editor problems

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionPriority.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionPriority.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EffSymCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/TypeBuiltinCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/TypeCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/WithCompleter.scala
Related to #8417.
Refactorings
- Priority extracted to own file CompletionPriority
- Priority levels renamed
=> refactor: completion priority refactoring (related to #8417)

main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala
=> feat: Revert "refactor: change java solver interface"

main/src/library/MutList.flix
Related to https://github.com/flix/flix/issues/7983
=> feat: add `Indexable` and `IndexableMut` instance for `MutList`

main/src/library/MultiMap.flix
Related to https://github.com/flix/flix/issues/7983
=> feat: add `Indexable` instance on `MultiMap`

main/src/library/MutQueue.flix
=> refactor: implement `MutQueue` via struct

main/src/ca/uwaterloo/flix/language/ast/Symbol.scala, main/src/library/Prelude.flix
Additional scaffolding for @AStenbaek
=> feat: add additional base effects

main/src/ca/uwaterloo/flix/util/collection/Bimap.scala
Needed in the new effect solver
=> feat: `Bimap.from`

main/src/ca/uwaterloo/flix/language/phase/typer/BaseEffects.scala, main/src/library/Prelude.flix
=> chore: scaffolding for base effects

main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
=> feat: allow empty try-with handler blocks

main/src/ca/uwaterloo/flix/language/phase/Namer.scala
=> chore: reorder implicits in Namer

main/src/ca/uwaterloo/flix/language/ast/Type.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala, main/test/flix/Test.Exp.Jvm.GetField2.flix
=> feat: Java field resolution

main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Closes https://github.com/flix/flix/issues/8533
=> feat: add syntactic context to `pick` in `Weeder2`

main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
=> feat: add `SharedContext` to `Kinder`

main/src/ca/uwaterloo/flix/language/errors/WeederError.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Related to https://github.com/flix/flix/issues/8540
=> feat: use `SoftFailure` in `Weeder2` at `visitParameter`

main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
Closes https://github.com/flix/flix/issues/8394
=> refactor: eliminate plural functions in `Namer` and `Stratifier`

main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/MonoAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/ast/shared/Denotation.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala, main/src/ca/uwaterloo/flix/language/phase/typer/SchemaConstraintGen.scala
=> refactor: move `Denotation` from `Ast` to `shared`

main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
Closes https://github.com/flix/flix/issues/8571
=> style: reorder implicit params in `Kinder`

main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala
Related to #8574 
Reformat in intellij, `_` unused vars, make defs private, etc
=> refactor: reformat TypeReduction

main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala, main/src/ca/uwaterloo/flix/util/InternalCompilerException.scala
=> refactor: polish `TypeReduction`

main/src/library/Console.flix
=> fix: `Console.run`

main/src/ca/uwaterloo/flix/language/phase/Lexer.scala, main/test/ca/uwaterloo/flix/library/TestDebug.flix
Fixed lexing of debug! and debug!! and added some regression tests
Fixes #8596
=> fix: debug! and debug!!

main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala
=> fix: bug in `HighlightProvider.scala`

main/src/ca/uwaterloo/flix/language/dbg/AstPrinter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/ResolvedAstPrinter.scala
some parts missing, but better than nothing
=> feat: resolved ast printer

main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
Closes https://github.com/flix/flix/issues/8645
=> refactor: inline `visitExps` in `Lowering`

main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
=> refactor: remove `Validation` from `visitRestrictableChoose*` in `Kinder`

main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
=> refactor: remove `Validation` from `Kinder` for several helper functions

main/src/ca/uwaterloo/flix/language/phase/PatMatch.scala, main/test/flix/Test.Exp.Match.Struct.flix
=> fix: handle structs in pattern matches

main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
=> refactor: remove `Validation` from more functions in `Kinder`

build.gradle, main/src/ca/uwaterloo/flix/language/errors/TypeError.scala, main/src/ca/uwaterloo/flix/language/phase/Verifier.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala, main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala, main/test/ca/uwaterloo/flix/library/TestAdaptor.flix, main/test/flix/Test.Exp.Jvm.Complex.flix
=> refactor: rework method resolution

main/src/ca/uwaterloo/flix/language/errors/TypeError.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala
=> refactor: clean up `TypeReduction` errors

main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
=> refactor: remove `Validation` from `KindEnv` in `Kinder`

main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/TypedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/EffectVerifier.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/PatMatch.scala, main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Regions.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala, main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
=> feat: allow effectful holes

main/src/ca/uwaterloo/flix/language/phase/Kinder.scala
=> refactor: remove `Validation` from functions in `Kinder`

main/src/resources/benchmark/Benchmarks.flix
Closes https://github.com/flix/flix/issues/8715
=> test: do not print in benchmarks

main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/BytecodeInstructions.scala
Making this before I have to copy it again for n-ary tags
=> refactor: backend `mkString`

main/src/ca/uwaterloo/flix/api/lsp/LanguageServer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ExprCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/HoleCompletion.scala
=> refactor: cleanup `CompletionProvider`

main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Also reduces number of cases in the function
Related to https://github.com/flix/flix/issues/8540
=> feat: add `SoftFailure` for singleton enum with cases in `Weeder2`

main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/MonoAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/ast/shared/Doc.scala, main/src/ca/uwaterloo/flix/language/phase/Deriver.scala, main/src/ca/uwaterloo/flix/language/phase/EntryPoint.scala, main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
=> refactor: move `Doc` from `Ast` to `shared`

main/src/ca/uwaterloo/flix/language/phase/Regions.scala
=> fix: Check regions inside instances and sigs

main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LiftedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/MonoAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/OccurrenceAst.scala, main/src/ca/uwaterloo/flix/language/ast/ReducedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/SimplifiedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/ast/shared/Modifiers.scala, main/src/ca/uwaterloo/flix/language/dbg/DocAst.scala, main/src/ca/uwaterloo/flix/language/phase/ClosureConv.scala, main/src/ca/uwaterloo/flix/language/phase/Deriver.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/EntryPoint.scala, main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
=> refactor: move `Modifiers` from `Ast` to `shared`

main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala
Closes https://github.com/flix/flix/issues/8783
=> refactor: remove `Expr.Let` from `WeededAst`

main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala
Closes https://github.com/flix/flix/issues/8819
=> refactor: rename `ctx` to `sctx` in `LambdaLift`

main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/MonoAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/LoweredAstPrinter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/ResolvedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/TypedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/Deriver.scala, main/src/ca/uwaterloo/flix/language/phase/EffectVerifier.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala, main/src/ca/uwaterloo/flix/language/phase/PatMatch.scala, main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Regions.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/TreeShaker1.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala, main/src/ca/uwaterloo/flix/language/phase/extra/CodeHinter.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
Closes https://github.com/flix/flix/issues/8842
=> feat: remove `Expr.Sig` from `Resolver` and later

main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/src/library/Adaptor.flix, main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala
Related to #8853 but does not fully solve it
=> fix: disallow control-effects in spawn and new expressions

main/src/ca/uwaterloo/flix/language/errors/EntryPointError.scala, main/src/ca/uwaterloo/flix/language/phase/EntryPoint.scala, main/test/ca/uwaterloo/flix/language/phase/TestEntryPoint.scala
Closes https://github.com/flix/flix/issues/8811
=> refactor: remove `Validation` from `EntryPoint`

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/phase/Reader.scala
=> refactor: remove `Validation` from `Reader`

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/phase/PatMatch.scala
=> refactor: remove `Validation` from `PatMatch`

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala
=> refactor: remove `Validation` from `Safety`

main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
Related to https://github.com/flix/flix/issues/8810
=> refactor: fix warnings in `Deriver`

main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
=> refactor: remove `Validation` internally from `Parser2`

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala
=> refactor: remove `Validation` from `Stratifier`

main/src/ca/uwaterloo/flix/language/phase/Lexer.scala, main/src/ca/uwaterloo/flix/runtime/shell/Category.scala
=> refactor: remove `Validation` internally from `Lexer`

main/src/ca/uwaterloo/flix/language/errors/DerivationError.scala, main/src/ca/uwaterloo/flix/language/phase/Deriver.scala
Depends on https://github.com/flix/flix/pull/8882
Closes https://github.com/flix/flix/issues/8810
=> refactor: remove `Validation` internally from `Deriver`

main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
Also removes one `SoftFailure` to ensure that `sctx` is correctly hooked up
=> refactor: add `SharedContext` to `Resolver`

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala
=> refactor: remove `Validation` from `Redundancy`

main/src/ca/uwaterloo/flix/language/phase/Lexer.scala, main/src/library/Debug.flix, main/test/ca/uwaterloo/flix/library/TestDebug.flix
=> chore: rename `debug` to `dbg`

main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/shared/Modifier.scala, main/src/ca/uwaterloo/flix/language/ast/shared/Modifiers.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/LambdaLift.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
=> refactor: move `Modifier` from `Ast` to `shared`

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> refactor: remove `SoftFailure`s from `resolveExp` in `Resolver`

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> refactor: remove `Validation` from `resolvePatternInConstraint` in `Resolver`

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> refactor: remove `Validation` from `lookupQName` in `Resolver`

main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/shared/Stratification.scala, main/src/ca/uwaterloo/flix/language/phase/UllmansAlgorithm.scala
=> refactor: move `Stratification` from `Ast` to `shared`

main/src/ca/uwaterloo/flix/language/phase/EntryPoint.scala, main/test/ca/uwaterloo/flix/language/phase/TestEntryPoint.scala
=> feat: allow entry point to have any base effect

main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
Discussed in https://github.com/flix/flix/pull/8911
=> refactor: make `InaccessibleRestrictableEnum` recoverable

main/src/ca/uwaterloo/flix/language/phase/unification/Zhegalkin.scala
=> chore: use unicode in Zhegalkin.scala

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/test/flix/Test.Use.Op.flix
=> fix: allow importing ops to shadow definitions

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/errors/ParseError.scala, main/src/ca/uwaterloo/flix/language/errors/WeederError.scala, main/src/ca/uwaterloo/flix/language/phase/Lexer.scala, main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
=> refactor: remove `Validation` from `Lexer` and `Parser2`

main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Removes some more uses of `SoftFailure`
=> refactor: use `SharedContext` in `Weeder2`

main/src/ca/uwaterloo/flix/language/phase/unification/set/SetSubstitution.scala, main/src/ca/uwaterloo/flix/language/phase/unification/set/SetUnification.scala, main/test/ca/uwaterloo/flix/language/phase/unification/UnificationSuite.scala, main/test/ca/uwaterloo/flix/language/phase/unification/set/EquationGenerator.scala, main/test/ca/uwaterloo/flix/language/phase/unification/set/SetFormulaGenerator.scala, main/test/ca/uwaterloo/flix/language/phase/unification/set/TestSetUnification.scala
This doesn't have full coverage and mostly hits SVE, but that's also the most complex part
=> test: property testing of `SetUnification`

main/test/flix/Test.Assoc.Eff.Covariance.flix, main/test/flix/Test.Exp.Effect.flix
=> refactor: remove `checked_ecast(???)`

main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala, main/src/ca/uwaterloo/flix/api/lsp/StackConsumer.scala, main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/TypedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala
=> refactor: introduced `TypedAst.Binder`

main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Depends on https://github.com/flix/flix/pull/8961
=> refactor: remove `Validation` from functions in `Weeder2`

main/src/ca/uwaterloo/flix/tools/Summary.scala
The couting itself will be ugly, so it always counts `-1` eff vars
=> feat: Eff var numbers (just formatting)

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
Most lambdas created in `Resolver` must be pure, so know the type will also know that. This should gain some (perhaps not much) typer performance and will allow better subeffecting for lambdas.
Fixes #8653
=> feat: Annotate `Resolver` lambdas pure

main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction2.scala, main/src/ca/uwaterloo/flix/language/phase/typer/SubstitutionTree.scala
Depends on:
- #9007 
Identical to TypeReconstruction except that it uses a SubstitutionTree instead of a Substitution
=> feat: introduce TypeReconstruction2

main/src/ca/uwaterloo/flix/language/phase/unification/set/SetFormula.scala, main/test/ca/uwaterloo/flix/language/phase/unification/set/TestSetFormula.scala
=> feat: `SetFormula.tableForm`

main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Closes https://github.com/flix/flix/issues/8960
=> fix: return error pattern for illegal pattern in `Weeder2`

main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/MonoAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/LoweredAstPrinter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/TypedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala, main/src/ca/uwaterloo/flix/language/phase/PatMatch.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction2.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
Closes https://github.com/flix/flix/issues/8965
=> refactor: swap `pat` and `tpe` fields in `RecordLabelPattern`

main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala, main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala, main/test/ca/uwaterloo/flix/library/TestBox.flix
=> fix: reinstate `RedundantUncheckedEffectCast` for constants

main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver2.scala, main/src/ca/uwaterloo/flix/language/phase/typer/SubstitutionTree.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction2.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala
What Magnus' giveth Matt taketh
=> feat: reduce memory allocation of new type inference solver

main/src/ca/uwaterloo/flix/Main.scala
=> feat: `--Xsubeffecting` hint

main/src/ca/uwaterloo/flix/language/phase/unification/set/SetUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/zhegalkin/Zhegalkin.scala, main/src/ca/uwaterloo/flix/util/CofiniteIntSet.scala
now without superexponential blowup
=> feat: Zhegalkin to SetFormula

main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala, main/src/ca/uwaterloo/flix/api/lsp/StackConsumer.scala, main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/shared/EqualityConstraint.scala, main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala, main/src/ca/uwaterloo/flix/language/phase/unification/AssocTypeSubstitution.scala, main/src/ca/uwaterloo/flix/language/phase/unification/EqualityEnvironment.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala, main/test/ca/uwaterloo/flix/language/phase/unification/TestAssocTypeUnification.scala
=> refactor: move `EqualityContraint` from `Ast` to `shared`

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/errors/KindError.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala
Related to https://github.com/flix/flix/pull/8944
=> refactor: remove `Validation` from `Typer`

main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/Scheme.scala, main/src/ca/uwaterloo/flix/language/ast/shared/BroadEqualityConstraint.scala, main/src/ca/uwaterloo/flix/language/errors/TypeError.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatEqualityConstraint.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver2.scala, main/src/ca/uwaterloo/flix/language/phase/unification/AssocTypeSubstitution.scala, main/src/ca/uwaterloo/flix/language/phase/unification/BoolUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/EqualityEnvironment.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala
=> refactor: move `BroadEqualityConstraint` from `Ast` to `shared`

main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/shared/Instance.scala, main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver2.scala, main/src/ca/uwaterloo/flix/language/phase/unification/TraitEnv.scala, main/src/ca/uwaterloo/flix/language/phase/unification/TraitEnvironment.scala
=> refactor: move `Instance` from `Ast` to `shared`

main/src/library/FilePathWithError.flix
=> feat: introduce `FilePathWithError`

main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/Scheme.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/shared/AssocTypeDef.scala, main/src/ca/uwaterloo/flix/language/phase/EffectVerifier.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver2.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction2.scala, main/src/ca/uwaterloo/flix/language/phase/unification/EqualityEnvironment.scala, main/src/ca/uwaterloo/flix/language/phase/unification/TraitEnvironment.scala, main/src/ca/uwaterloo/flix/language/phase/unification/Unification.scala, main/test/ca/uwaterloo/flix/language/phase/unification/TestAssocTypeUnification.scala
=> refactor: move `AssocTypeDef` from `Ast` to `shared`

docs/DIDYOUKNOW.md, main/src/library/Array.flix, main/src/library/Chain.flix, main/src/library/List.flix, main/src/library/MutDeque.flix, main/src/library/MutList.flix, main/src/library/Nec.flix, main/src/library/Nel.flix, main/src/library/Vector.flix, main/test/ca/uwaterloo/flix/library/TestArray.flix
=> refactor: remove `!` from function names in `Array`

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
Setting up for https://github.com/flix/flix/issues/7148
=> refactor: extract visitHandler method in Resolver

main/src/ca/uwaterloo/flix/language/phase/unification/EffUnification3.scala, main/src/ca/uwaterloo/flix/util/collection/SortedBimap.scala
=> feat: `SortedBimap` (in `EffUnification3`)

main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction2.scala, main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
This removes boxing/unboxing from method resolution
Fixes  #9130
=> fix: avoid boxing in JVM resolution

main/src/ca/uwaterloo/flix/language/ast/Type.scala, main/src/ca/uwaterloo/flix/language/errors/TypeError.scala, main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction2.scala, main/src/ca/uwaterloo/flix/language/phase/unification/EqualityEnvironment.scala
=> feat: add base source location to `FieldNotFound`

examples/larger-examples/Reachable.flix, main/src/library/Array.flix, main/src/library/Concurrent/Channel.flix, main/src/library/Fixpoint/Phase/Compiler.flix, main/src/library/Fixpoint/Solver.flix, main/src/library/Foldable.flix, main/src/library/Graph.flix, main/src/library/Iterator.flix, main/src/library/MutList.flix, main/src/library/RedBlackTree.flix, main/src/library/Reducible.flix, main/src/library/Vector.flix, main/test/ca/uwaterloo/flix/library/TestArray.flix, main/test/ca/uwaterloo/flix/library/TestDelayMap.flix, main/test/ca/uwaterloo/flix/library/TestMap.flix, main/test/ca/uwaterloo/flix/library/TestMutList.flix, main/test/ca/uwaterloo/flix/library/TestPrelude.flix, main/test/ca/uwaterloo/flix/library/TestRedBlackTree.flix, main/test/ca/uwaterloo/flix/library/TestSet.flix, main/test/ca/uwaterloo/flix/library/TestVector.flix, main/test/flix/Test.Exp.ForEach.flix, main/test/flix/Test.Exp.NewRegion.flix, main/test/flix/Test.Exp.Regions.flix, main/test/flix/experimental/Test.Dec.AssocEff.flix
=> refactor: remove `!` from function names in `MutList`

main/src/library/FilePath.flix, main/src/library/FilePathWithError.flix, main/src/library/IOError.flix
=> feat: introduce new `IoError`

examples/effects/Rewind.flix, examples/larger-examples/Reachable.flix, main/src/library/Fixpoint/Interpreter.flix, main/src/library/Fixpoint/Solver.flix, main/src/library/Foldable.flix, main/src/library/MutDisjointSets.flix, main/src/library/MutMap.flix, main/test/ca/uwaterloo/flix/library/TestMutMap.flix, main/test/flix/Test.Exp.NewRegion.flix, main/test/flix/Test.Exp.Regions.flix
=> refactor: remove `!` from function names in `MutMap`

main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
=> fix: revert "refactor: throw ICE in `pickIdent`"

examples/internal-mutability-with-regions.flix, examples/larger-examples/Reachable.flix, main/src/library/Foldable.flix, main/src/library/MutSet.flix, main/test/ca/uwaterloo/flix/library/TestMutSet.flix
=> refactor: remove `!` from functions in `MutSet`

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/MagicMatchCompleter.scala, main/src/ca/uwaterloo/flix/language/ast/Ast.scala
Fulfilled the two improvement suggestions in #9118.
=> feat: improve magic match

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/Http.flix
Fixes #9035
What do we think of this design of having `Http.Response`?
Do we want to add handler in this PR or another?
=> feat: add `Http` effect

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
Related to https://github.com/flix/flix/pull/9173
Related to https://github.com/flix/flix/issues/8813
=> refactor: use `phaseNew` in `Weeder2`

main/src/ca/uwaterloo/flix/language/dbg/DocAst.scala, main/src/ca/uwaterloo/flix/language/dbg/DocAstFormatter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/LoweredAstPrinter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/ResolvedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/SimplifiedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/TypedAstPrinter.scala
What should the keyword be?
- `def`?
- `local def`?
- `localdef`?
Closes https://github.com/flix/flix/issues/8782
=> refactor: rename `LetRec` to `LocalDef`

main/src/library/Vector.flix
=> refactor: remove `!` from function names in `Vector`

main/src/library/Regex.flix
=> refactor: remove `!` from function names in `Regex`

examples/larger-examples/restrictable-variants/sequences.flix, main/src/library/Array.flix, main/src/library/Foldable.flix, main/src/library/Graph.flix, main/src/library/Iterator.flix, main/src/library/MutDeque.flix, main/src/library/MutList.flix, main/src/library/MutMap.flix, main/src/library/MutQueue.flix, main/src/library/MutSet.flix, main/src/library/RedBlackTree.flix, main/src/library/String.flix, main/src/library/StringBuilder.flix, main/src/library/Vector.flix, main/test/ca/uwaterloo/flix/library/TestArray.flix, main/test/ca/uwaterloo/flix/library/TestDelayList.flix, main/test/ca/uwaterloo/flix/library/TestMutList.flix, main/test/ca/uwaterloo/flix/library/TestStringBuilder.flix, main/test/ca/uwaterloo/flix/library/TestVector.flix
=> refactor: remove `!` from function names in `StringBuilder`

main/src/ca/uwaterloo/flix/language/ast/Scheme.scala, main/src/ca/uwaterloo/flix/language/phase/unification/BoolUnification.scala, main/src/ca/uwaterloo/flix/tools/pkg/ManifestParser.scala, main/src/ca/uwaterloo/flix/tools/pkg/MavenPackageManager.scala, main/src/ca/uwaterloo/flix/util/Result.scala, main/test/ca/uwaterloo/flix/language/phase/unification/TestFastBoolUnification.scala, main/test/ca/uwaterloo/flix/util/TestResult.scala
Closes https://github.com/flix/flix/issues/9195
=> refactor: clean up `Result`

main/src/ca/uwaterloo/flix/api/Bootstrap.scala, main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/phase/Inliner.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala, main/src/ca/uwaterloo/flix/language/phase/unification/TraitEnvironment.scala, main/src/ca/uwaterloo/flix/util/Result.scala, main/src/ca/uwaterloo/flix/util/Validation.scala, main/test/ca/uwaterloo/flix/TestUtils.scala, main/test/ca/uwaterloo/flix/util/TestValidation.scala
Closes https://github.com/flix/flix/issues/9196
=> refactor: remove `Validation.success` and `Validation.toFailure`

main/src/library/MutDeque.flix
=> refactor: remove `!` from function names in `MutDeque`

main/src/library/Http.flix
=> feat: introduce HTTP handler

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/MagicMatchCompleter.scala
According to #9202, we now support magic match for tuple!
Here is how it looks like:
Note:
- I introduce a new enum `Member` to represent either a enum or other type in the tuple.
- Maybe we could consider using the same marker for all the `_member2` placeholder so that user can edit them simultaneously.
=> feat: support magic match completion for tuple

main/src/library/Http.flix
=> feat: add the `Net` effect to `Http.handle`

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/syntactic/KeywordCompleter.scala
Closes https://github.com/flix/flix/issues/8909
=> fix: add `with` in `KeywordCompleter`

main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
=> feat: add mkImportJava to UndefinedType

main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
=> feat: Add CodeAction for UndefinedTag

main/src/ca/uwaterloo/flix/language/phase/OccurrenceAnalyzer.scala
=> fix: OccuranceAnalyzer

main/src/ca/uwaterloo/flix/language/ast/shared/LocalScope.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> feat: introduce LocalScope

main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction2.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
=> fix: Revert "refactor: remove ArrayLit evar"

main/src/ca/uwaterloo/flix/api/lsp/Indexer.scala, main/src/ca/uwaterloo/flix/api/lsp/StackConsumer.scala, main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/shared/Derivation.scala, main/src/ca/uwaterloo/flix/language/phase/Deriver.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> refactor: move `Derivation` from `Ast` to `shared`

main/src/ca/uwaterloo/flix/api/lsp/StackConsumer.scala, main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala, main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/shared/Derivations.scala, main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> refactor: move `Derivations` from `Ast` to `shared`

main/src/ca/uwaterloo/flix/language/ast/Type.scala, main/src/ca/uwaterloo/flix/language/phase/unification/EffUnification3.scala, main/src/ca/uwaterloo/flix/language/phase/unification/set/SetFormula.scala, main/src/ca/uwaterloo/flix/language/phase/unification/set/SetSubstitution.scala, main/src/ca/uwaterloo/flix/language/phase/unification/zhegalkin/Zhegalkin.scala
Added without "deep" integration
This code is currently unused
=> feat: `SetFormula.Xor`

main/src/ca/uwaterloo/flix/language/phase/Namer.scala
Closes https://github.com/flix/flix/issues/9315
=> fix: check for empty `name` in `Namer.mkDuplicateNamePair`

main/src/ca/uwaterloo/flix/language/phase/unification/set/SetFormula.scala, main/src/ca/uwaterloo/flix/language/phase/unification/zhegalkin/Zhegalkin.scala
fix `SetFormula.mkXorDirectAll` and improve zhegalking conversion
=> fix: `SetFormula.Xor`

main/src/ca/uwaterloo/flix/language/phase/unification/set/SetFormula.scala, main/src/ca/uwaterloo/flix/language/phase/unification/zhegalkin/Zhegalkin.scala
=> refactor: revert "fix: `SetFormula.Xor`"

main/src/ca/uwaterloo/flix/api/lsp/CompletionItem.scala, main/src/ca/uwaterloo/flix/api/lsp/CompletionItemLabelDetails.scala
=> feat: introduce CompletionItemLabelDetails

main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/library/Debug.flix
=> feat: remove unchecked_cast from debugWithPrefix

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/AutoImportCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
fixes #9358
Also renamed `path` with namespace and qualifiedName
=> feat: rerank the packages in auto import

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/AutoImportCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/AutoUseCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala
=> feat: inhibit AutoUseCompletion and AutoImportCompletion

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/AutoImportCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
=> feat: make AutoImportCompletion more readable

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/AutoUseCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/DefCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/LocalScopeCompleter.scala
=> fix: stop AutoUseCompleter from using functions in root module

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
Not sure about how to trigger that.
But it should work fine.
=> feat: improve SigCompletion with labelDetails

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala
Similar update for three completions.
Is it okay to put them in the same pr, or separate them?
=> feat: improve OpCompl EnumTagCompl and HoleCompl with labelDetails

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/api/lsp/VSCodeLspServer.scala
=> refactor: introduce `lsp-vscode` command

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/InstanceCompleter.scala, main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/Scheme.scala, main/src/ca/uwaterloo/flix/language/ast/Symbol.scala, main/src/ca/uwaterloo/flix/language/ast/Type.scala, main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala, main/src/ca/uwaterloo/flix/language/ast/shared/VarText.scala, main/src/ca/uwaterloo/flix/language/dbg/DocAstFormatter.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala, main/src/ca/uwaterloo/flix/language/fmt/SimpleType.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala, main/test/ca/uwaterloo/flix/language/fmt/TestFormatType.scala, main/test/ca/uwaterloo/flix/language/phase/unification/TestCaseSetUnification.scala
=> refactor: move `VarText` from `Ast` to `shared`

main/src/library/Array.flix, main/src/library/Graph.flix, main/src/library/MutDeque.flix, main/src/library/MutList.flix, main/src/library/MutMap.flix, main/src/library/MutQueue.flix, main/src/library/MutSet.flix, main/src/library/RedBlackTree.flix, main/src/library/Vector.flix
=> refactor: reduce usage of `StringBuilder` in library

main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala, main/src/ca/uwaterloo/flix/util/JvmUtils.scala
=> fix: #9417

main/src/ca/uwaterloo/flix/api/lsp/provider/SymbolProvider.scala
fixes #9250
Actually I am not sure how to test the code. Any hint?
I implement it the same way enum is implemented here.
=> feat: extend SymbolProvider with structs

main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/MonoAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/shared/TypeSource.scala, main/src/ca/uwaterloo/flix/language/phase/Deriver.scala, main/src/ca/uwaterloo/flix/language/phase/EntryPoints.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
=> refactor: move `TypeSource` from `Ast` to `shared`

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/MagicMatchCompleter.scala
fixes #9439
Preview:
To fix the bug, we need to change the index used in line 88 to newIndex.
Also I renamed Z to index to make things more clear.
=> fix: fix the indexing in magic matching

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/AutoUseCompleter.scala
=> feat: use fuzzy match in auto use for effects

main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
Closes https://github.com/flix/flix/issues/9418
=> refactor: simplify `mkParYield` in `Lowering`

examples/interoperability/swing/swing-dial.flix
Closes https://github.com/flix/flix/issues/9278
=> docs: add Swing number dial example

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
Related to https://github.com/flix/flix/issues/9256
=> refactor: fix warnings in `Resolver`

main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction2.scala
#6982 introduced a wrong type reconstruction for some reason
=> fix: Try-With reconstruction

main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala, main/src/ca/uwaterloo/flix/language/phase/Parser2.scala, main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
=> fix: parser stuck in effect declaration

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/Chain.flix, main/src/library/FileRead.flix, main/src/library/FileReadWithResult.flix, main/src/library/Http.flix, main/src/library/List.flix, main/src/library/Map.flix, main/src/library/Set.flix, main/src/library/ToFlix.flix, main/src/library/Vector.flix, main/test/ca/uwaterloo/flix/library/TestFromJava.flix
=> feat: rename `FromJava` to `ToFlix`

main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/shared/UseOrImport.scala, main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
=> refactor: move `UseOrImport` from `Ast` to `shared`

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionContext.scala, main/src/ca/uwaterloo/flix/language/ast/Ast.scala, main/src/ca/uwaterloo/flix/language/ast/shared/SyntacticContext.scala, main/src/ca/uwaterloo/flix/language/errors/ParseError.scala, main/src/ca/uwaterloo/flix/language/phase/Parser2.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
=> refactor: move `CompletionContext` from `Ast` to `shared`

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/FindReferencesProvider.scala, main/src/ca/uwaterloo/flix/language/ast/shared/Input.scala, main/src/ca/uwaterloo/flix/language/ast/shared/Source.scala, main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/src/ca/uwaterloo/flix/language/phase/Reader.scala, main/src/ca/uwaterloo/flix/runtime/shell/Category.scala, main/src/ca/uwaterloo/flix/tools/Summary.scala, main/test/ca/uwaterloo/flix/api/lsp/VisitorSuite.scala
=> chore: remove `isStable`

main/src/ca/uwaterloo/flix/tools/CompilerPerf.scala
=> feat: rework incremental plot

main/src/library/IoError.flix
Fixes https://github.com/flix/flix/issues/9451
=> feat: add ToString to IoError

main/src/library/Environment.flix, main/src/library/FileRead.flix, main/src/library/FileReadWithResult.flix, main/src/library/FileWrite.flix, main/src/library/FileWriteWithResult.flix, main/src/library/Http.flix, main/src/library/HttpWithResult.flix
=> feat: add missing `runWithIO`

main/src/ca/uwaterloo/flix/language/phase/PatMatch.scala, main/test/flix/Test.Exp.Match.Bool.flix
related to https://github.com/flix/flix/issues/1554
=> fix: exhaustiveness bug in matching on tuple of Booleans

main/src/ca/uwaterloo/flix/language/phase/typer/PrimitiveEffects.Constructors.json, main/src/ca/uwaterloo/flix/language/phase/typer/PrimitiveEffects.Methods.json
Closes https://github.com/flix/flix/issues/9514
=> feat: annotate `java.math.BigInteger` with effects

examples/effects-and-handlers/advanced/backtracking.flix, main/src/ca/uwaterloo/flix/language/phase/typer/PrimitiveEffects.Classes.json, main/src/ca/uwaterloo/flix/language/phase/typer/PrimitiveEffects.Packages.json, main/src/library/Eff/BiasedCoin.flix, main/src/library/Eff/RandomCoin.flix, main/src/library/Random.flix, main/test/ca/uwaterloo/flix/library/TestRedBlackTree.flix
Also adds `NonDet` to the entire `java.util.random` package.
=> feat: add primitive effects to `java.util.Random`

main/src/ca/uwaterloo/flix/language/phase/Regions.scala
For the order, I choose (scope, sctx, flix)
=> feat: introduce SharedContext for Regions

main/src/ca/uwaterloo/flix/language/errors/WeederError.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala, main/test/ca/uwaterloo/flix/language/phase/TestNamer.scala, main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
fixes https://github.com/flix/flix/issues/6174
=> refactor: move DuplicateTag from Weeder to Namer

main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala
Use a ConcurrentLinkedQueue to store the edges.
=> feat: introduce SharedContext for PredDeps phase

main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala, main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala
fixes #9682
For UndefinedType, I add kindOpt between qualified name and anchor position.
=> feat: extend `UndefinedType` with `Kind`

main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/SyntaxTree.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
=> refactor: remove syntex tree.native

main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/ImplementationProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/UseDefCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/UseEffCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/UseEnumCompleter.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala, main/src/ca/uwaterloo/flix/language/ast/shared/LocalScope.scala, main/src/ca/uwaterloo/flix/language/phase/Dependencies.scala, main/src/ca/uwaterloo/flix/language/phase/Deriver.scala, main/src/ca/uwaterloo/flix/language/phase/EffectVerifier.scala, main/src/ca/uwaterloo/flix/language/phase/HtmlDocumentor.scala, main/src/ca/uwaterloo/flix/language/phase/Instances.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala, main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Regions.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/tools/Summary.scala, main/src/ca/uwaterloo/flix/util/ParOps.scala, main/src/ca/uwaterloo/flix/util/collection/ListMap.scala
fixes #9694
I use ListMap in all the Ast that I can find, is there any other place that we should also replace?
=> refactor: use list map everywhere

main/src/ca/uwaterloo/flix/api/lsp/Hover.scala, main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala, main/src/ca/uwaterloo/flix/api/lsp/MarkupContent.scala, main/src/ca/uwaterloo/flix/api/lsp/MarkupKind.scala
Preview:
We will return a null when nothing is found and you can see that null is properly processed as the bottom says: "no information available"
=> feat: support hover for the standalone lsp

main/src/ca/uwaterloo/flix/language/ast/ChangeSet.scala, main/src/ca/uwaterloo/flix/util/collection/ListMap.scala, main/test/ca/uwaterloo/flix/language/ast/TestChangeSet.scala, main/test/ca/uwaterloo/flix/util/TestListMap.scala, main/test/ca/uwaterloo/flix/util/UtilSuite.scala
use ListMap instead of List[k, List[V]]
=> refactor: use ListMap for ChangeSet

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/syntactic/KeywordCompleter.scala, main/src/ca/uwaterloo/flix/language/ast/shared/SyntacticContext.scala, main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
The only keyword here is "def"
"eff" is provided by module keyword completer.
=> feat: introduce effect keyword completer

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EnumTagCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/OpCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/SignatureCompleter.scala
Check the parent trait, effect and enum for visibility
=> fix: check the visibility for completion for sigs, ops and tags

main/src/ca/uwaterloo/flix/language/ast/ChangeSet.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala
Use ChangeSet.partitionOnValues to make Safety totally incremental.
=> feat: make Safety totally incremental

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala
=> feat: make PredDeps incremental

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/ast/Symbol.scala, main/src/ca/uwaterloo/flix/language/phase/Dependencies.scala
fixes #9628
I have no idea why the ratio is not 1.0, but it's almost totally incremental.
=> feat: make dependencies incremental

main/src/ca/uwaterloo/flix/language/phase/Instances.scala
Use SharedContext to store errors.
Will apply the new api to make it incremental in the next PR.
=> feat: introduce SharedContext to Instances

main/src/ca/uwaterloo/flix/language/phase/unification/EqualityEnvironment.scala
=> chore: remove dead code from EqualityEnvironment

main/src/ca/uwaterloo/flix/api/lsp/VSCodeLspServer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala
A simple refactor for following stand alone lsp support
=> refactor: make processHighLight return Set[DocumentHighlight]

main/src/ca/uwaterloo/flix/api/lsp/DocumentHighlight.scala, main/src/ca/uwaterloo/flix/api/lsp/DocumentHighlightKind.scala, main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala, main/src/ca/uwaterloo/flix/api/lsp/MarkupContent.scala
=> feat: support document highlight for stand alone lsp

main/src/ca/uwaterloo/flix/api/lsp/VSCodeLspServer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/CodeLensProvider.scala
=> refactor: make CodeLensProvider return CodeLens

main/src/ca/uwaterloo/flix/api/lsp/VSCodeLspServer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/GotoProvider.scala
=> refactor: make GotoProvider return LocationLink

main/src/ca/uwaterloo/flix/api/lsp/VSCodeLspServer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/RenameProvider.scala
=> refactor: make RenameProvider return WorkspaceEdit

main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/SyntaxTree.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/Parser2.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Typer.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
=> feat: add tokens to all frontend asts

main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala
Not sure where we want to store the implicit objects.
=> refactor: use new CofiniteSet in Monomorpher

main/src/ca/uwaterloo/flix/api/lsp/CodeAction.scala, main/src/ca/uwaterloo/flix/api/lsp/CodeActionKind.scala, main/src/ca/uwaterloo/flix/api/lsp/Command.scala, main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala, main/src/ca/uwaterloo/flix/api/lsp/Range.scala, main/src/ca/uwaterloo/flix/api/lsp/TextEdit.scala, main/src/ca/uwaterloo/flix/api/lsp/WorkspaceEdit.scala
It works fine (if we ignore the broken code action)
=> feat: support code action for stand alone lsp

main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver2.scala, main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
fixes https://github.com/flix/flix/issues/9750
=> fix: propogate error locations in contextReduction

main/src/ca/uwaterloo/flix/api/lsp/CompletionItem.scala, main/src/ca/uwaterloo/flix/api/lsp/CompletionItemKind.scala, main/src/ca/uwaterloo/flix/api/lsp/CompletionList.scala, main/src/ca/uwaterloo/flix/api/lsp/InsertTextFormat.scala, main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala
=> feat: support auto completion for stand alone lsp

main/src/ca/uwaterloo/flix/api/lsp/Location.scala, main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala, main/src/ca/uwaterloo/flix/api/lsp/VSCodeLspServer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/FindReferencesProvider.scala
=> feat: support find references for standalone lsp

main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
I think this makes the code easier to read and splits the levels of concerns.
I don't think it should be slower - if scala has as good inlining as @jaschdoc it will be identical code
=> refactor: `StringCursor.advanceWhile`

main/src/library/Random.flix
Hey,
This small PR updates the documentation in Random to include the ranges. 
It is related to #7034.
=> docs: extend function description in Random

main/src/ca/uwaterloo/flix/api/lsp/LocationLink.scala, main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala
=> feat: support goto definition for standalone lsp

main/src/ca/uwaterloo/flix/api/lsp/InlayHint.scala, main/src/ca/uwaterloo/flix/api/lsp/InlayHintKind.scala, main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala
InlayHint has not been implemented yet.
=> feat: support InlayHint for standalone lsp

main/src/ca/uwaterloo/flix/api/lsp/DocumentSymbol.scala, main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala, main/src/ca/uwaterloo/flix/api/lsp/SymbolKind.scala, main/src/ca/uwaterloo/flix/api/lsp/SymbolTag.scala
=> feat: support document symbols for standalone lsp

main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
=> feat: add semantic tokens for keywords

main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala
=> feat: provide semantic tokens for comments

main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/shared/Annotations.scala
These is no Type for annotation, so I borrow Modifier
=> feat: provide semantic tokens for annotations

main/src/ca/uwaterloo/flix/language/phase/EntryPoints.scala, main/src/ca/uwaterloo/flix/language/phase/unification/TraitEnvironment.scala
=> refactor: eliminate EntryPoints dependency on TraitEnvironment 

main/src/ca/uwaterloo/flix/language/phase/unification/set/SetFormula.scala, main/src/ca/uwaterloo/flix/language/phase/unification/set/SetUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/zhegalkin/ZheglakinPerf.scala, main/test/ca/uwaterloo/flix/language/phase/unification/set/TestSetUnification.scala
A lot of refactoring + a few tweaks here and there + dead code elimination (as determined by profiling)
=> refactor: simplify and cleanup SetUnification

main/src/library/Char.flix, main/src/library/CodePoint.flix, main/src/library/String.flix, main/test/ca/uwaterloo/flix/library/TestChar.flix, main/test/ca/uwaterloo/flix/library/TestCodePoint.flix, main/test/ca/uwaterloo/flix/library/TestString.flix
Hey, 
This small PR fixes #9541.
=> refactor: rename Char.isWhiteSpace to Char.isWhitespace

main/src/ca/uwaterloo/flix/language/phase/typer/TypeConstraint.scala
fixes https://github.com/flix/flix/issues/9943
=> chore: remove TypeConstraint.index

main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala
=> perf: tweak performance of `Substitution.@@`

main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver2.scala
related to https://github.com/flix/flix/issues/9938
=> feat: eliminate resolved constraints after block effect unification

main/src/ca/uwaterloo/flix/language/ast/Symbol.scala, main/src/ca/uwaterloo/flix/language/ast/shared/QualifiedSym.scala
As discussed in #9775
With IsQualified, we can now check name matching for every IsQualified Symbol, instead of writing a function for each symbol.
We'll do that refactor in next PR.
=> feat: introduce QualifiedSym

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/DefCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EffectCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EnumCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/EnumTagCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/OpCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/SignatureCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/StructCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/TypeAliasCompleter.scala
=> feat: introduce matchesName to CompletionUtils

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/UseCompleter.scala
The only difference between these Completions is the kind, so we just need to pass it as an arg.
=> refactor: introduce UseCompletion

main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala
fixes #10005
Avoid raising NPE if WorkspaceFolders is not specified.
=> fix: check workspacefolders before accessing

main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
=> refactor: simplify `Lexer.scanToken`

main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
Master: 188,0 ms (06,3%)
PR: 157,1 ms (05,3%)
=> refactor: make StringCursor final

main/src/ca/uwaterloo/flix/language/phase/Lexer.scala, main/test/ca/uwaterloo/flix/language/phase/TestLexer.scala
=> feat: remove max comment nesting

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/Iterator.flix, main/src/library/MutCollectable.flix, main/src/library/MutList.flix
related to https://github.com/flix/flix/issues/10018
=> feat: introduce MutCollectable

main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
- Comments are start with capital letter
- Comments end with period
- Single line comments are on one line
- Single expression defs are without `{..}`
- Fix grammar (i.e. used as e.g.)
- Column width 100 (unless impractical)
- Named boolean conditions
=> refactor: uniform style in Lexer

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/OpCompleter.scala
=> feat: OpCompleter now supports partially qualified name

main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/FindReferencesProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/GotoProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/RenameProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala, main/src/ca/uwaterloo/flix/tools/Summary.scala
=> feat: introduce source location to SelectChannelRule

main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/FindReferencesProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/GotoProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/RenameProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/ResolvedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/TypedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala, main/src/ca/uwaterloo/flix/tools/Summary.scala
=> feat: introduce source location to HandlerRule

main/src/ca/uwaterloo/flix/language/phase/unification/set/SetUnification.scala, main/src/ca/uwaterloo/flix/language/phase/unification/zhegalkin/ZhegalkinPerf.scala
```
--------------------------------------------------------------------------------
Trivial | ConstProp |  VarProp |  VarAssign |  ReflDupl |    SVE
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6,367 &    18,123 &      295 &        150 &       172 &  1,200 \\
0 &    43,159 &      633 &        407 &         1 &    284 \\
--------------------------------------------------------------------------------
```
=> feat: extend `ZhegalkinPerf` with eliminated variables

main/src/ca/uwaterloo/flix/language/phase/typer/PrimitiveEffects.Classes.json, main/src/ca/uwaterloo/flix/language/phase/typer/PrimitiveEffects.Methods.json, main/src/library/Box.flix, main/src/library/Debug.flix, main/src/library/Hash.flix, main/src/library/Int8.flix, main/src/library/ToString.flix, main/test/ca/uwaterloo/flix/library/TestBox.flix, main/test/ca/uwaterloo/flix/library/TestInt8.flix, main/test/flix/Test.Exp.Jvm.InvokeConstructor.flix, main/test/flix/Test.Exp.Jvm.InvokeConstructor2.flix
Related to https://github.com/flix/flix/issues/9511
=> feat: annotate `java.lang.Byte` with primitive effects

main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/FindReferencesProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/GotoProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/RenameProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/ResolvedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala, main/src/ca/uwaterloo/flix/tools/Summary.scala
=> feat: introduce SourceLocation for TypeMatchRule

main/src/ca/uwaterloo/flix/language/phase/typer/PrimitiveEffects.Classes.json, main/src/ca/uwaterloo/flix/language/phase/typer/PrimitiveEffects.Methods.json, main/src/library/Box.flix, main/src/library/Debug.flix, main/src/library/Hash.flix, main/src/library/Int16.flix, main/src/library/ToString.flix, main/test/ca/uwaterloo/flix/library/TestBox.flix, main/test/ca/uwaterloo/flix/library/TestInt16.flix, main/test/flix/Test.Exp.Jvm.InvokeConstructor.flix, main/test/flix/Test.Exp.Jvm.InvokeConstructor2.flix
Related to https://github.com/flix/flix/issues/9511
=> feat: annotate `java.lang.Short` with primitive effects

main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/FindReferencesProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/GotoProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/RenameProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/language/ast/DesugaredAst.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/ResolvedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/TypedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Namer.scala, main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala, main/src/ca/uwaterloo/flix/tools/Summary.scala
=> feat: introduce SourceLocation for CatchRule

main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/HoleCompleter.scala, main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ResolvedAst.scala, main/src/ca/uwaterloo/flix/language/ast/TypedAst.scala, main/src/ca/uwaterloo/flix/language/ast/ops/TypedAstOps.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/ResolvedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/TypedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/phase/Dependencies.scala, main/src/ca/uwaterloo/flix/language/phase/EffectVerifier.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/PatMatch.scala, main/src/ca/uwaterloo/flix/language/phase/PredDeps.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/src/ca/uwaterloo/flix/language/phase/Safety.scala, main/src/ca/uwaterloo/flix/language/phase/Stratifier.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala, main/src/ca/uwaterloo/flix/tools/Summary.scala
fixes #10074
The name convention is env
=> feat: add LocalScope to Hole

main/src/ca/uwaterloo/flix/language/phase/typer/PrimitiveEffects.Classes.json, main/src/ca/uwaterloo/flix/language/phase/typer/PrimitiveEffects.Methods.json, main/src/library/Box.flix, main/src/library/Debug.flix, main/src/library/Hash.flix, main/src/library/Int32.flix, main/src/library/ToString.flix, main/test/ca/uwaterloo/flix/library/TestBox.flix, main/test/ca/uwaterloo/flix/library/TestInt32.flix, main/test/flix/Test.Exp.Jvm.InvokeConstructor.flix, main/test/flix/Test.Exp.Jvm.InvokeConstructor2.flix
Related to https://github.com/flix/flix/issues/9511
=> feat: annotate `java.lang.Integer` with primitive effects

main/src/ca/uwaterloo/flix/language/phase/typer/PrimitiveEffects.Classes.json
=> feat: annotate `java.lang.Character$Subset` with primitive effects

main/src/ca/uwaterloo/flix/language/phase/typer/PrimitiveEffects.Packages.json
=> feat: annotate `java.lang.reflect` with primitive effects

main/src/ca/uwaterloo/flix/api/lsp/Visitor.scala
Related to https://github.com/flix/flix/issues/10108
=> fix: visit LocalDef binder in LSP visitor

main/src/ca/uwaterloo/flix/language/phase/Resolver.scala, main/test/ca/uwaterloo/flix/TestUtils.scala, main/test/ca/uwaterloo/flix/language/phase/TestResolver.scala
Fixes https://github.com/flix/flix/issues/10047
Depends on https://github.com/flix/flix/pull/10062
=> fix: visit arguments in case function cannot be resolved

main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
Mostly docs, but hints strings have been made consistent
=> refactor: Docs and hints in Parser

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/HandlerCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/OpCompleter.scala
fixes #10153
Both completers work fine:
=> feat: introduce HandlerCompleter

main/src/ca/uwaterloo/flix/api/lsp/LspServer.scala, main/src/ca/uwaterloo/flix/api/lsp/VSCodeLspServer.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/CompletionUtils.scala
fixes #9900
Finally we could remove CompletionContext and the relative helper functions.
=> refactor: remove CompletionContext

main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver2.scala, main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
Fixes https://github.com/flix/flix/issues/10176
=> fix: ensure Type.Error is not in final constraints

main/src/ca/uwaterloo/flix/api/lsp/Position.scala, main/test/ca/uwaterloo/flix/api/lsp/TestCompletionProvider.scala
Programs is lifted to the top, otherwise there will be a warning.
=> refactor: break down completion invariant tests

main/test/ca/uwaterloo/flix/TestAll.scala, main/test/flix/resiliency/ResiliencySuite.scala, main/test/flix/resiliency/ford-fulkerson-prefix.flix
Depends on
- https://github.com/flix/flix/pull/10199
=> test: introduce ResiliencySuite

main/src/library/MutPriorityQueue.flix
=> feat: add minCapacity() to MutPriorityQueue

main/src/ca/uwaterloo/flix/tools/Summary.scala
only used for unknown positions, so doesn't influence anything
=> fix: 1-indexed pos in Summary

main/src/ca/uwaterloo/flix/language/phase/Verifier.scala
=> fix: Verify Stmt properly

main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala
=> refactor: `reduceAssoc` in `Monomorpher`

AUTHORS.md, main/src/ca/uwaterloo/flix/tools/SocketServer.scala
=> fix: show all error messages on play.flix.dev

main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala
=> fix: strict substitution on typematch effect

main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala
=> fix: fix the location of error in LetMatchExpr

main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
Remove a few features that have a very low power-to-weight ratio
=> chore: simplify `CodeActionProvider`

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/ca/uwaterloo/flix/language/verifier/ClassVerifier.scala, main/src/ca/uwaterloo/flix/language/verifier/EffectVerifier.scala
=> refactor: add `verifier` folder

main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala, main/test/flix/Test.Exp.Regions.flix
Pretty obvious solution now that I look at it again...
Fixes #9661 and fixes #10201 and allows us to support nested try-catch
=> fix: Make nested try-catch / region work

main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/util/Options.scala
=> chore: remove unused `Options.test`

main/src/ca/uwaterloo/flix/language/phase/Safety.scala
=> docs: update `Safety`

main/src/ca/uwaterloo/flix/api/lsp/provider/CodeActionProvider.scala
Remove support for derivation quickfix because the implementation is half broken and the feature is obscure.
=> refactor: remove derivation quickfix

main/test/ca/uwaterloo/flix/api/lsp/TestCompletionProvider.scala
fixes #10326
All files, except ones from large-example, and package-manager are included.
The whole test takes 3 min 3 s on my computer.
Do you think we should first read and compile all the programs for further usage, that would be a huge acceleration.
=> feat: include most file programs in examples for TestCompletionProvider

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/KeywordCompleter.scala
=> feat: provide keyword completion for run

main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
If we first advance, the location from `currentSourceLocation` will point to the next token, so we can see:
which is not ideal.
After this PR, we'll see:
=> fix: fix off-by-one error in exprDelimited location

main/src/ca/uwaterloo/flix/language/phase/OccurrenceAnalyzer.scala, main/src/ca/uwaterloo/flix/language/phase/optimizer/Optimizer.scala
=> refactor: tweak performance of `OccurrenceAnalyzer`

main/src/ca/uwaterloo/flix/language/phase/OccurrenceAnalyzer.scala
Closes https://github.com/flix/flix/issues/10381
=> refactor: add `visitFormalParam` and update doc in `OccurrenceAnalyzer`

main/test/ca/uwaterloo/flix/api/lsp/TestCompletionProvider.scala
The error message now looks like this:
Do we think we should still provide a link to the file of the example?
=> feat: update TestCompletionProvider error message for assertEmpty

main/src/ca/uwaterloo/flix/language/phase/optimizer/Inliner.scala, main/src/ca/uwaterloo/flix/language/phase/optimizer/OccurrenceAnalyzer.scala, main/src/ca/uwaterloo/flix/language/phase/optimizer/Optimizer.scala
Closes https://github.com/flix/flix/issues/10371
Closes https://github.com/flix/flix/issues/10377
=> feat: use delta sets in `Optimizer`

main/src/ca/uwaterloo/flix/language/phase/optimizer/Inliner.scala
This mirrors the case for unconditionally inlined `Var`
=> fix: correctly beta-reduce LocalDef in `Inliner`

main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/library/Debug.flix, main/test/ca/uwaterloo/flix/library/TestDebug.flix
=> fix: `dbg` effect

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/test/ca/uwaterloo/flix/api/lsp/TestCompletionProvider.scala
An attempt to eliminate duplicate keyword completions.
=> fix: ignore completion duplication check for vars

main/src/ca/uwaterloo/flix/language/dbg/DocAst.scala, main/src/ca/uwaterloo/flix/language/dbg/DocAstFormatter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/LiftedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/LoweredAstPrinter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/MonoAstPrinter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/OpPrinter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/ReducedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/SimplifiedAstPrinter.scala
MonoAst printing should be complete now and closer to surface syntax
=> feat: polish `MonoAst` Printing

main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/library/Fixpoint/Ast/Datalog.flix, main/src/library/Fixpoint/Ast/Ram.flix, main/src/library/Fixpoint/Ast/Shared.flix, main/src/library/Fixpoint/Debugging.flix, main/src/library/Fixpoint/Interpreter.flix, main/src/library/Fixpoint/Phase/Compiler.flix, main/src/library/Fixpoint/Phase/IndexSelection.flix, main/src/library/Fixpoint/Phase/Simplifier.flix, main/src/library/Fixpoint/Phase/Stratifier.flix, main/src/library/Fixpoint/Phase/VarsToIndices.flix, main/src/library/Fixpoint/Solver.flix
Dropped [v] from Datalog-related enums (except Denotation) and adjusted Lowering.flix acordingly.
=> refactor: Drop [v] from Datalog type

main/src/ca/uwaterloo/flix/language/phase/optimizer/Inliner.scala
Closes https://github.com/flix/flix/issues/10522
=> refactor: rework `isTrivial`

main/src/ca/uwaterloo/flix/language/phase/optimizer/Inliner.scala
Closes https://github.com/flix/flix/issues/10540
=> feat: only copy live defs in `Inliner`

main/src/resources/benchmark/Benchmark.Enum.flix, main/src/resources/benchmark/Benchmarks.flix
Just to make them a bit more varied
=> feat: Set and Enum benchmark

main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/library/FileRead.flix, main/src/library/FileReadWithResult.flix, main/src/library/FileWrite.flix, main/src/library/FileWriteWithResult.flix, main/src/library/Http.flix, main/src/library/HttpWithResult.flix, main/src/library/Process.flix, main/src/library/ProcessWithResult.flix, main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
=> fix: report shadowing in formal parameters of handlers

main/src/ca/uwaterloo/flix/language/phase/Parser2.scala
fixes https://github.com/flix/flix/issues/7731
=> fix: do not parse types as type parameters

main/src/ca/uwaterloo/flix/language/ast/shared/Annotation.scala, main/src/ca/uwaterloo/flix/language/ast/shared/Annotations.scala, main/src/ca/uwaterloo/flix/language/errors/WeederError.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala, main/src/ca/uwaterloo/flix/language/phase/optimizer/Inliner.scala, main/src/ca/uwaterloo/flix/language/phase/optimizer/Optimizer.scala, main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
Maybe the `inlined` variable should be copied over to `sctx` at the beginning of `Inliner.run`.
Closes https://github.com/flix/flix/issues/10373
=> feat: add `@Inline` and `@DontInline` annotations

main/src/ca/uwaterloo/flix/language/ast/AtomicOp.scala, main/src/ca/uwaterloo/flix/language/phase/Eraser.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/BackendType.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala, main/test/ca/uwaterloo/flix/verifier/TypeVerifier.scala
=> feat: extensible variants backend

main/src/ca/uwaterloo/flix/language/ast/MonoType.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
inliner and occurrenceAnalyzer left
There is also that todo in redundancy that I don't know what refers to
=> feat: ext var simpl

main/test/ca/uwaterloo/flix/library/TestBPlusTree.flix
Fixed toList03 (renamed to toList05) and introduced 2 more tests. See #10603
=> fix: BPlusTree test

main/src/ca/uwaterloo/flix/language/phase/Parser2.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
Makes the code a lot easier to read and reduces chance of bugs (and fixes a few)
+400 -300 but if you count chars then this removes code
=> refactor: implicit parser context

main/test/ca/uwaterloo/flix/library/TestList.flix
=> refactor: fix ListTest.flix indentation and convert @test to @Test

AUTHORS.md, main/src/ca/uwaterloo/flix/Main.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolver2.scala, main/src/ca/uwaterloo/flix/language/phase/unification/EffUnification3.scala, main/src/ca/uwaterloo/flix/util/ChaosMonkey.scala, main/src/ca/uwaterloo/flix/util/Options.scala, main/test/ca/uwaterloo/flix/TestMain.scala
=> feat: adding chaos monkey object to shuffle constraints when user requests

main/test/ca/uwaterloo/flix/library/TestOption.flix
=> refactor: reformat `TestOption.flix`

main/test/ca/uwaterloo/flix/library/TestMap.flix
=> refactor: cleanup `TestMap`

main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/BytecodeInstructions.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
=> refactor: CodeGen BigDecimal

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ExprSnippetCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/ImportCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/KindCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/LocalScopeCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/MagicMatchCompleter.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/PredicateCompleter.scala
=> feat: add `Priority`s to some `Completion`s

main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
=> feat: simplify error code

main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala
Pure reformatting. I will be changing this file and not being auto-formatted is burdensome.
=> chore: reformat `Completion.scala`

main/src/ca/uwaterloo/flix/language/phase/jvm/BackendObjType.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmBackend.scala
Reducing some of the OOP complexity in BackendObjType
=> refactor: Remove Generatable

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/Fixpoint3/Ast/ExecutableRam.flix
This adds what should be the last Datalog-v3 before adding basic functionalities
=> feat: add last major Datalog v3 type

main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintSolverInterface.scala, main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala
Reintroduces one reported type error from #10722
=> refactor: reintroduce MissingInstanceArrow

main/src/ca/uwaterloo/flix/language/phase/jvm/JvmLoader.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmWriter.scala
=> fix: `JvmLoader` and `JvmWriter` should not be phases

main/src/ca/uwaterloo/flix/language/ast/ReducedAst.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmLoader.scala
This removes the mutable method field in `ReducedAst.Def`
=> refactor: remove `ReducedAst.method`

main/src/ca/uwaterloo/flix/language/phase/jvm/AsmOps.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmOps.scala, main/src/ca/uwaterloo/flix/language/phase/jvm/JvmType.scala
=> refactor: remove JvmType constants

main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
also nice since pushArgs shows as a type error in IDE
=> refactor: remove pushArgs

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/IoError.flix, main/src/library/Ping.flix, main/src/library/TimeUnit.flix
addresses #10798.
next push will contain PingWithResult.
=> feat: add `Ping` effect

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/Dns.flix, main/src/library/DnsWithResult.flix, main/src/library/IpAddr.flix
=> feat: Add `DnsWithResult` effect

main/src/library/Process.flix, main/src/library/ProcessHandle.flix, main/src/library/ProcessWithResult.flix
=> refactor: use `java.lang.Process` as `JProcess`

main/src/ca/uwaterloo/flix/language/phase/jvm/GenFunAndClosureClasses.scala
The local variables are stored and read to local fields to enable effect resumption. These fields are not a part of any interface and are truly local, so it does't make any sense to erase them - pure downside (runtime casts and compiletime complexity)
=> feat: remove local variable field erasure on def/closure objects

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/IpAddr.flix, main/src/library/Tcp.flix, main/src/library/TcpServer.flix
Part 1 of https://github.com/flix/flix/issues/10794 (I will add `TcpWithResult` in a new PR).
=> feat: add Tcp effect

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/TcpWithResult.flix
fixes https://github.com/flix/flix/issues/10794
=> feat: add TcpWithResult effect

main/src/library/Reader.flix
fixes https://github.com/flix/flix/issues/6402
=> feat: make InputStream instance of Reader

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/Reader.flix, main/src/library/Tcp.flix, main/src/library/TcpAcceptWithResult.flix, main/src/library/TcpWithResult.flix
fixes https://github.com/flix/flix/issues/10869
=> feat: add `TcpAcceptWithResult` effect

main/src/library/Process.flix, main/src/library/ProcessWithResult.flix
Addresses #10894
first commit message
> add `pid` and `waitForTimeout` maybe we hardcode to milliseconds
=> feat: add functionality to `Process` and `ProcessWithResult` (pid, in/out streams)

examples/fixpoints/railroad-network.flix, examples/larger-examples/datalog/class-hierarchy-analysis.flix, examples/larger-examples/datalog/connect-graph.flix, examples/larger-examples/datalog/drivable-speed.flix, examples/larger-examples/datalog/drivable.flix, examples/larger-examples/datalog/ford-fulkerson.flix, examples/larger-examples/datalog/friend-suggestions.flix, examples/larger-examples/datalog/half-siblings.flix, examples/larger-examples/datalog/heirs-and-usurpers.flix, examples/larger-examples/datalog/pairwise-acyclic-graphs.flix, examples/larger-examples/datalog/palindrome.flix, examples/larger-examples/datalog/single-source-shortest-distance.flix, examples/larger-examples/datalog/single-source-shortest-path-arbitrary.flix, examples/larger-examples/datalog/single-source-shortest-paths.flix, examples/larger-examples/datalog/stratifier.flix, examples/larger-examples/datalog/travelling-with-preference.flix, examples/larger-examples/datalog/unconnected-roads.flix, examples/larger-examples/program-analysis/IDE.flix, examples/larger-examples/program-analysis/IFDS.flix, main/src/ca/uwaterloo/flix/language/ast/SyntaxTree.scala, main/src/ca/uwaterloo/flix/language/ast/WeededAst.scala, main/src/ca/uwaterloo/flix/language/errors/WeederError.scala, main/src/ca/uwaterloo/flix/language/phase/Desugar.scala, main/src/ca/uwaterloo/flix/language/phase/Parser2.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala, main/src/library/Graph.flix, main/test/flix/Test.Integ.Fixpoint.TypeAlias.flix
depends on 
- https://github.com/flix/flix/pull/10812
=> feat: require arity for `inject` expressions

main/src/library/RedBlackTree.flix
Related to https://github.com/flix/flix/issues/10519
=> refactor: remove CPS in `RedBlackTree.size`

main/src/library/TcpAccept.flix, main/src/library/TcpAcceptWithResult.flix, main/src/library/TcpSocket.flix
fixes https://github.com/flix/flix/issues/10923
=> feat: make `TcpSocket` an instance of `Reader` and `Writer`

main/src/ca/uwaterloo/flix/api/lsp/provider/CodeLensProvider.scala
=> fix: fixes #10936

build.gradle
related to https://github.com/flix/flix/issues/8680
=> chore: clean up build.gradle

build.gradle, main/src/ca/uwaterloo/flix/language/phase/typer/TypeReduction2.scala
=> refactor: replace old array type idiom with Class.arrayType

main/src/ca/uwaterloo/flix/language/phase/typer/TypeConstraint.scala, main/src/ca/uwaterloo/flix/language/phase/typer/TypeContext.scala
Adds the new `Source` provenance type as discussed in #10912.
=> feat: add-source-provenance

main/test/ca/uwaterloo/flix/library/TestMonad.flix
=> refactor: @test -> @Test and newline and EOF

main/test/ca/uwaterloo/flix/library/TestChain.flix
=> refactor: @test -> @Test and newline at EOF

main/test/ca/uwaterloo/flix/library/TestInt32.flix
=> refactor: @test -> @Test, fix newlines in comments

main/test/ca/uwaterloo/flix/library/TestMutMap.flix
=> refactor: @test -> @Test and correcting linebreaks

main/test/ca/uwaterloo/flix/library/TestMutSet.flix
=> refactor: @test -> @Test and linebreak corrections

main/test/ca/uwaterloo/flix/library/TestRef.flix
=> refactor: @test -> @Test and linebreak formatting

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/BufReader.flix, main/test/ca/uwaterloo/flix/library/TestBufReader.flix
fixes https://github.com/flix/flix/issues/10796
=> feat: add `BufReader`

main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala
=> fix: check for unused type alias parameters

main/src/library/Fixpoint3/Phase/Stratifier.flix
=> refactor: clean `mkStratificationMap` in Fixpoint3 stratifier

main/src/library/IpAddr.flix, main/src/library/Ping.flix, main/src/library/PingWithResult.flix, main/src/library/TcpBind.flix, main/src/library/TcpBindWithResult.flix, main/src/library/TcpConnect.flix, main/src/library/TcpConnectWithResult.flix
=> refactor: make `toBytes` return a Vector instead of an Array

main/src/ca/uwaterloo/flix/language/ast/shared/QualifiedSym.scala, main/src/ca/uwaterloo/flix/language/ast/shared/SymbolSet.scala
As per [this request](https://github.com/flix/flix/pull/10947#issuecomment-3021882005), split into a new pull request
=> refactor: extend `SymbolSet` 

main/src/ca/uwaterloo/flix/language/phase/Typer.scala
Extract some helper methods that will be needed for a new function called `checkInstAssocTypes` (see https://github.com/flix/flix/pull/11021/files#r2194130365).
=> chore: extract helper methods for working with associated types

main/src/library/Array.flix, main/test/ca/uwaterloo/flix/library/TestArray.flix
Note that the tests are simply copy-pasted from `copyOfRange`.
=> feat: add `copy` to Array

main/src/library/BufReader.flix, main/src/library/Process.flix, main/src/library/Reader.flix, main/src/library/TcpSocket.flix, main/test/ca/uwaterloo/flix/library/TestBufReader.flix
fixes https://github.com/flix/flix/issues/10976
=> feat: rename `Reader` to `Readable` and add an associated type

main/src/ca/uwaterloo/flix/language/ast/KindedAst.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/TypeReconstruction.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala, main/src/ca/uwaterloo/flix/language/phase/typer/SchemaConstraintGen.scala
Related to https://github.com/flix/flix/issues/11023.
=> feat: type and generate constraints for `FixpointQueryWithProvenance`

examples/larger-examples/datalog/pairwise-acyclic-graphs.flix, main/src/library/List.flix, main/test/ca/uwaterloo/flix/library/TestList.flix
=> chore: List.groupBy should return List[Nel[a]]

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/BufReader.flix, main/src/library/Peekable.flix, main/test/ca/uwaterloo/flix/library/TestBufReader.flix
fixes https://github.com/flix/flix/issues/11101
As I mention in the ticket, i'm open to suggestions on the naming of things
=> feat: add Peekable trait and instance for BufReader

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/CharacterSet.flix, main/src/library/DecodingReader.flix, main/test/ca/uwaterloo/flix/library/TestDecodingReader.flix
fixes https://github.com/flix/flix/issues/10977
=> feat: add DecodingReader

examples/larger-examples/datalog/single-source-shortest-path-arbitrary.flix
The shortest path from 1 to 6 was not unique.
=> fix: bug in test

.github/workflows/first-interaction.yaml
Related to https://github.com/flix/flix/issues/7537
=> ci: add an auto-greeter to tell first-time PRs about AUTHORS.md

main/src/ca/uwaterloo/flix/language/phase/Parser2.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala, main/test/ca/uwaterloo/flix/language/phase/TestWeeder.scala
=> refactor: move 'atLeastOne' checking to Weeder for type parameters

main/test/ca/uwaterloo/flix/library/Fixpoint/TestFixpoint.Functional.flix, main/test/flix/Test.Exp.Fixpoint.Functional.flix
=> feat: add tests for functionals in Datalog

main/src/library/Process.flix, main/src/library/TcpSocket.flix, main/src/library/Writable.flix
The file name was correct already
=> chore: rename `Writeable` to `Writable`

examples/larger-examples/restrictable-variants/sequences.flix, examples/traits/trait-with-higher-kinded-type.flix, main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/Array.flix, main/src/library/Chain.flix, main/src/library/DelayList.flix, main/src/library/DelayMap.flix, main/src/library/ForEach.flix, main/src/library/List.flix, main/src/library/Map.flix, main/src/library/MutDeque.flix, main/src/library/MutList.flix, main/src/library/MutMap.flix, main/src/library/MutPriorityQueue.flix, main/src/library/MutSet.flix, main/src/library/Nec.flix, main/src/library/Nel.flix, main/src/library/Option.flix, main/src/library/RedBlackTree.flix, main/src/library/Set.flix, main/src/library/Vector.flix
progress towards https://github.com/flix/flix/issues/11016
=> feat: add ForEach trait and instances for collections

main/src/library/Range.flix
Forgot one - follow up to https://github.com/flix/flix/pull/11195
https://github.com/flix/flix/issues/11016
=> feat: add ForEach instance for Range

main/src/library/ForEach.flix, main/test/ca/uwaterloo/flix/library/TestForEach.flix
https://github.com/flix/flix/issues/11016
=> feat: add withFilter view to ForEach

main/src/library/ForEach.flix, main/test/ca/uwaterloo/flix/library/TestForEach.flix
https://github.com/flix/flix/issues/11016
=> feat: add withMap view to ForEach

main/src/library/Fixpoint3/Ast/Datalog.flix, main/src/library/Fixpoint3/Phase/Compiler.flix, main/src/library/Fixpoint3/Provenance.flix
=> chore: remove `App0` from `Datalog` enum

examples/larger-examples/datalog/single-source-shortest-paths.flix
Hopefully last error in these examples.
=> fix: bug in example `ShortestPath`

main/test/flix/Test.Exp.Fixpoint.Application.flix, main/test/flix/Test.Exp.Fixpoint.Functional.flix, main/test/flix/Test.Exp.Fixpoint.If.flix
Simple tests verifying that lattice elements can be used in guards, functionals and applications.
=> chore: add lattice tests for guard, application and functional.

main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
Fixes https://github.com/flix/flix/issues/11245.
=> fix: `termTypesOfRelation` in Lowering

main/test/flix/Test.Exp.Fixpoint.Stratification.flix
=> chore: add tests for Fixpoint stratification

main/test/flix/Test.Exp.Fixpoint.KeywordSolve.flix
=> chore: add tests for `solve` in Datalog

main/src/library/ForEach.flix, main/test/ca/uwaterloo/flix/library/TestForEach.flix
https://github.com/flix/flix/issues/11016
=> feat: add withZip view to ForEach

main/test/flix/Test.Exp.Fixpoint.KeywordSolve.flix, main/test/flix/Test.Exp.Fixpoint.Stratification.flix
Fixes https://github.com/flix/flix/pull/11238#discussion_r2262021387.
=> chore: reformat Fixpoint tests

main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala, main/test/flix/Test.Exp.ExtMatch.flix
Closes https://github.com/flix/flix/issues/11172
=> feat: add support for nullary extensible variant constructors

main/test/flix/Test.Exp.Fixpoint.Solve.Lattice.flix
=> chore: add more fixpoint lattice tests

main/src/resources/benchmark/Benchmarks.flix
Hopefully brings iterator, map and set benchmarks closer to the rest.
Related to https://github.com/flix/flix/issues/11015
=> chore: rescale benchmarks

main/test/flix/Test.Exp.ExtTag.flix
Removed redundant test, added a new test for unit constructor
=> test: update tests for `ExtTag`

main/test/flix/Test.Exp.Fixpoint.Application.flix
Related to https://github.com/flix/flix/issues/11275.
=> chore: reformat `Test.Exp.Fixpoint.Application`

main/src/ca/uwaterloo/flix/api/lsp/provider/HoverProvider.scala
fixes https://github.com/flix/flix/issues/11281
=> fix: enable hover information on wildcards

main/src/library/Fixpoint3/Phase/IndexSelection.flix
Mostly removal of mutation and prevention of a relatively expensive algorithm in the common (simple) case.
=> chore: simplify `Fixpoint/Phase/IndexSelection.flix`

main/src/ca/uwaterloo/flix/language/fmt/DisplayType.scala, main/src/ca/uwaterloo/flix/language/fmt/FormatType.scala
Closes https://github.com/flix/flix/issues/11075
=> refactor: remove unused extensible types in DisplayType

docs/DIDYOUKNOW.md, docs/STYLE.md, main/src/ca/uwaterloo/flix/language/errors/DerivationError.scala, main/src/ca/uwaterloo/flix/language/errors/ResolutionError.scala, main/src/ca/uwaterloo/flix/language/errors/TypeError.scala
Hopefully this is all occurrences :)
Closes https://github.com/flix/flix/issues/11378
=> fix: rename occurrences of type classes to traits

main/src/ca/uwaterloo/flix/language/ast/LoweredAst.scala, main/src/ca/uwaterloo/flix/language/ast/MonoAst.scala, main/src/ca/uwaterloo/flix/language/dbg/DocAst.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/LoweredAstPrinter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/MonoAstPrinter.scala, main/src/ca/uwaterloo/flix/language/dbg/printer/TypedAstPrinter.scala, main/src/ca/uwaterloo/flix/language/errors/RedundancyError.scala, main/src/ca/uwaterloo/flix/language/errors/WeederError.scala, main/src/ca/uwaterloo/flix/language/phase/Kinder.scala, main/src/ca/uwaterloo/flix/language/phase/Lowering.scala, main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala, main/src/ca/uwaterloo/flix/language/phase/Redundancy.scala, main/src/ca/uwaterloo/flix/language/phase/Simplifier.scala, main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala, main/src/ca/uwaterloo/flix/language/phase/optimizer/Inliner.scala, main/src/ca/uwaterloo/flix/language/phase/optimizer/OccurrenceAnalyzer.scala, main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala, main/test/ca/uwaterloo/flix/language/phase/TestRedundancy.scala, main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala, main/test/flix/Test.Exp.ExtMatch.flix
Closes https://github.com/flix/flix/issues/11173
=> feat: add default case to `ematch`

main/src/ca/uwaterloo/flix/language/phase/typer/ConstraintGen.scala
Closes https://github.com/flix/flix/issues/11406
=> docs: add type rules to `ExtMatch` case in `ConstraintGen`

main/src/library/BPlusTree.flix
First part of #11395
See the performance note before accepting.
=> chore: update `BPlusTree.put` guarantees

main/src/library/BPlusTree.flix, main/test/ca/uwaterloo/flix/library/TestBPlusTree.flix
This should complete the `BPlusTree` part of #11395.
=> feat: add `getKeyAndValue` and `putIf` to `BPlusTree`

main/src/library/Fixpoint3/Ast/ExecutableRam.flix, main/src/library/Fixpoint3/Interpreter.flix, main/src/library/Fixpoint3/Phase/Lowering.flix, main/src/library/Fixpoint3/Phase/Provenance.flix, main/test/flix/Test.Exp.Fixpoint.PQuery.flix
Last part of #11395 closing #11362 (±bugs)
=> feat: provenance should always compute a shortest proof

main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
pulling out the weird special case
=> refactor: separate user op lexing special case

main/src/ca/uwaterloo/flix/api/Flix.scala, main/src/library/Fixpoint3/Predicate.flix, main/src/library/Fixpoint3/TypeInfo.flix
=> feat: add `TypeInfo` to fixpoint solver

main/src/library/Fixpoint3/Ast/ExecutableRam.flix, main/src/library/Fixpoint3/Ast/Ram.flix, main/src/library/Fixpoint3/Boxing.flix, main/src/library/Fixpoint3/Debugging.flix, main/src/library/Fixpoint3/Interpreter.flix, main/src/library/Fixpoint3/Phase/Compiler.flix, main/src/library/Fixpoint3/Phase/Hoisting.flix, main/src/library/Fixpoint3/Phase/IndexSelection.flix, main/src/library/Fixpoint3/Phase/Lowering.flix, main/src/library/Fixpoint3/Phase/Provenance.flix, main/src/library/Fixpoint3/Phase/Simplifier.flix, main/src/library/Fixpoint3/Predicate.flix, main/src/library/Fixpoint3/Solver.flix
Part of #11381
Adds and tracks the type through the phases, but does not use it yet.
=> feat: type the `Datalog.Ram` ast

main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
used once and just reverse nth
=> refactor: remove helper method

main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
on master, `_2` is seen as a lowercase name.
=> feat: improve `_` lexing

main/src/ca/uwaterloo/flix/language/ast/SourceLocation.scala, main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
Shorter and simpler functions.
This is required for my PR that improves lexer error source locations.
=> refactor: locations in lexer

main/src/ca/uwaterloo/flix/language/phase/Lexer.scala
=> refactor: prefer advanceIfMatch to peekIs

main/src/library/Fixpoint3/Ast/Ram.flix, main/src/library/Fixpoint3/BoxingType.flix, main/src/library/Fixpoint3/Phase/Compiler.flix, main/src/library/Fixpoint3/Phase/Hoisting.flix, main/src/library/Fixpoint3/Phase/IndexSelection.flix, main/src/library/Fixpoint3/Phase/Lowering.flix, main/src/library/Fixpoint3/Phase/Provenance.flix, main/src/library/Fixpoint3/TypeInfo.flix
Final part of #11381.
Removes `RamId`
=> chore: remove `RamId` from Fixpoint

main/src/ca/uwaterloo/flix/language/phase/Lexer.scala, main/test/flix/Test.Unused.Def.flix, main/test/flix/Test.Unused.Var.flix
=> feat: constrain chars to ascii

main/src/ca/uwaterloo/flix/language/ast/Type.scala
Closes https://github.com/flix/flix/issues/11542
=> fix: do not assume kind `Star` in `Type.mkEnum`

main/src/library/Prelude.flix, main/src/library/Reflect.flix
=> feat: add `Reflect.reflectEffect`

main/src/ca/uwaterloo/flix/language/phase/Parser2.scala, main/test/ca/uwaterloo/flix/language/phase/TestParser.scala
=> fix: type alias must have body

main/src/ca/uwaterloo/flix/language/phase/Lowering.scala
Mostly a follow up to #11221
Instead of generating and visiting a `TypedAst` just generate a `LoweredAst`.
Also fixes 2 unused things Intellij was mad about.
=> refactor: make `LoweredAst` directly in `Lowering.mkExtVar`

main/src/ca/uwaterloo/flix/api/lsp/provider/CompletionProvider.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/Completion.scala, main/src/ca/uwaterloo/flix/api/lsp/provider/completion/MagicDefCompleter.scala
=> feat: add `MagicDefCompleter`

main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala, main/test/flix/Test.Exp.Instanceof.flix
fixes https://github.com/flix/flix/issues/11767
=> fix: support instanceof for primitive types

main/src/ca/uwaterloo/flix/tools/pkg/Dependency.scala, main/src/ca/uwaterloo/flix/tools/pkg/ManifestError.scala, main/src/ca/uwaterloo/flix/tools/pkg/ManifestParser.scala, main/src/ca/uwaterloo/flix/tools/pkg/Trust.scala, main/test/ca/uwaterloo/flix/tools/TestManifestParser.scala, main/test/ca/uwaterloo/flix/tools/TestTrust.scala, main/test/ca/uwaterloo/flix/tools/ToolsSuite.scala
Related to https://github.com/flix/flix/issues/11436
Related to https://github.com/flix/flix/issues/9522
=> feat: rework manifest `permissions` to `trust`

main/src/ca/uwaterloo/flix/util/collection/ListOps.scala
Code written by JLS.
First step of resurrecting https://github.com/flix/flix/pull/10874
=> feat: add ListOps.zip and ListOps.zipOption
